### ISSUE TITLE
Shows hh:26: tt instead of Time on the secondary display

### ISSUE THREAD

**Issue by Sumitdhiman** [martinet101/ElevenClock#1]
![image](https://user-images.githubusercontent.com/10372750/135822548-84a71f6f-76e1-497e-8a8f-216bd7b954d2.png)

Restarting from the Task Manager fixed it.

**Comment by Sumitdhiman** [comment]
After restarting, in a while same problem again.
![image](https://user-images.githubusercontent.com/10372750/135823010-c4e69716-53f8-4391-9978-bea748760dd3.png)

**Comment by martinet101** [comment]
huh, that's weird... could you tell me please your locale?

**Comment by Sumitdhiman** [comment]
My locale is India.

**Comment by martinet101** [comment]
Just if you know about python and how does it work, could you try running the source code (i've added a commit right now)? (If not just don't mind). It's because for me it works, but just to make sure it works for you also before closing the issue.

**Comment by Sumitdhiman** [comment]
Is there a guide for that? I am not so much into developer things to be honest.

**Comment by martinet101** [comment]
Oh, just don't mind. I'll test it myself. If it works i'll publish a repease ASAP and i'll let you know :).

**Comment by Sumitdhiman** [comment]
Thank you. Btw, I had to write an article for the Microsoft Community (I am sure a lot of people would want this after tomorrow) which is why I found the bug during testing. Had to use Image from your Readme file, hope that is not a problem :)


https://answers.microsoft.com/en-us/windows/forum/all/add-clock-to-the-second-display-in-windows-11/14ed24f5-b203-4bd7-a4e7-c4eb3539b042

**Comment by martinet101** [comment]
Oh, that's cool @Sumitdhiman :) (I bet microsoft won't like that😂). Don't worry about using the screenshot, is just a simple photo. Thank you a lot ;)

P.D. If you don't mind, i'll link the article on the readme file

**Comment by Sumitdhiman** [comment]
That's a community generated article, so there are no issues on the Microsoft forum for sure 👍

Feel free to link!

**Comment by martinet101** [comment]
I've just released version 1.2 fixing this issue. You'll find the installer in the releases section. Thanks for submitting the issue, and also for the article on MS forum ;)

**Comment by martinet101** [comment]
The thing is that it the visible text actually changed to /releases, but the link is still pointing to release 1.2

**Comment by Sumitdhiman** [comment]
I get it now. That is a bug in the editor. Fixing it now. Thank you for the heads up.

**Comment by martinet101** [comment]
No, Thank you for writing the article and reediting-it ;)

**Comment by Sumitdhiman** [comment]
Done. Can you confirm?  I just noticed that I just pressed backspace, which deleted text, but did not modify the URL. Been busy with Windows 11 launch :)

**Comment by martinet101** [comment]
Yes, it works.

Thanks :)
