### ISSUE TITLE
[BUG] Seconds appear after AM/PM in clock

### ISSUE THREAD

**Issue by Kirito-SF** [martinet101/ElevenClock#100]
**Describe the bug**
When seconds are enabled for the taskbar clock, they are appearing after the AM/PM. So the 'ElevenClock' clock shows as '3:11 PM:45' as an example.

**To Reproduce**
1. Enable seconds for the taskbar clock.
2. Seconds will now appear in the incorrect location (single digit numbers will also appear without the 0 in front).
3. Seconds appear like this in the clock, whether 'Show seconds on the clock' in ElevenClock settings is enabled or not.

**Expected behavior**
The seconds should appear before the AM/PM, so it should look like '3:11:45 PM'.

**Screenshots**
![ElevenClock-seconds-bug](https://user-images.githubusercontent.com/31504222/137206041-410f6f72-0dab-44bf-a9a2-386581a8a7f3.png)

**Comment by martinet101** [comment]
Duplicate
