### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by Draskic** [martinet101/ElevenClock#1001]
Hi
Overlaying the 11clock over the original Windows 11 clock on the taskbar works fine until a notification comes through the Notification Center in Windows when the blue circle "pushes" the original Windows clock to the left, but that doesn't happen with 11clock either! That's the problem! That's why 11clock cannot, unfortunately, replace the original Windows 11 clock, which, by the way, is worthless because the letters are too small, and its functionality is questionable!
It is necessary to think about this shift at 11 o'clock!
Greeting!
Drasko

**Comment by martinet101** [comment]
Hi @Draskic, I am seeing that you are facing issues that existed some time ago but that wiring fixes for them have been rolled out, so I am scared that you might be using an old/obsolete/corrupted ElevenClock installation, or your ElevenClock data directory has gone completely invalid.

For this, I'll need to ask you to:
- check on the log (settings - > debugging info-> open log) for errors. They will be marked as red. If any error is present, please post them here.
- check you are running version 3.9.1
- full reset ElevenClock doing the following:
1. Uninstall ElevenClock
2. Remove the .elevenclock directory placed in your user folder
3. Install ElevenClock from github.

**Comment by Draskic** [comment]
Hi
It seems that there are no errors!
I'm using version 3.9.1 and I have no intention of doing a complete reset or uninstalling 11clock!
The described problems with the shift of the clock to the appearance of notifications in Windows 11 (last Build!) are a rough reality and should be thoroughly reviewed and adjusted!
I'm sending a log!
Greeting!
[11clocklog.txt](https://github.com/martinet101/ElevenClock/files/9845000/11clocklog.txt)

**Comment by martinet101** [comment]
Hi, as you can see in the screenshot above, you have notifications disabled. You can enable them from the settings window or by resetting ElevenClock (and that was the main point of resetting ElevenClock) 

![Screenshot_20221022-201149-127.png](https://user-images.githubusercontent.com/53119851/197356276-46f32ad9-7188-4960-b5f4-30ce23301402.png)


Hope this helps!

**Comment by Draskic** [comment]
O.K.
I wouldn't do a reset.
How to turn on notifications in the settings from 11 o'clock?

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/197357170-6bf48c2c-f9dd-45a5-adf1-a0d3d71e094c.png)

**Comment by Draskic** [comment]
I get it!
I deliberately disabled that badge because it was of no use. Every time I clicked on it, the Task Manager opened, which is set for one click at 11 o'clock.

**Comment by martinet101** [comment]
Now you can set double-click or middle-click actions if you wish

**Comment by Draskic** [comment]
O.K.
I'll try that!
As far as I remember, 2x click didn't work, and I didn't try the middle one (wheel?).
But this one in the notification badge is important,
I just have to wait for a notification in Windows and set 11clock to be around the time of Windows!
Thank you for Saturday's effort (Zagreb, Croatia)

**Comment by martinet101** [comment]
Second click was fixed in the latest update, and middle click is indeed the wheel click

**Comment by Draskic** [comment]
Hi Marti
I tried! It works quite well.
Clicking with the first button, I first set the function to "Disabled", so that didn't work. Fortunately, I realized that I completely disabled the click with the first button, so that the first notification was still activated on the badge!
I already forgot what functions Windows 11 had on the clock, but I put "Task selection" on the wheel, and nothing on double-click, because it still doesn't work for me (last Build)!
Microsoft dared to remove the Task Manager from "Hidden icons" (right mouse button), and with the "Winaero" tweaker on the desktop, MS again "moved" it to "Other options", so there is not much use from Microsoft!

A summary of the settings is this:
 FIRST: One clicks nothing and opens notifications and calendar, if I want.
 SECOND: Double click again nothing and opens notifications and ev. calendar (however, that double click doesn't work on my last build and cumul. update!)
 THIRD: Click on the Wheel "Change Task" (works well)

I found that the right click from 11clock, in addition to Settings, also has Task Manager, so I use that!

Greeting!
Drasko

**Comment by martinet101** [comment]
So, knowing that your double-click action does not work, could you please share your log again, with this settings set to what does not work?

**Comment by Draskic** [comment]
[Last log for 11Clock.txt](https://github.com/martinet101/ElevenClock/files/9846401/Last.log.for.11Clock.txt)
👍

**Comment by martinet101** [comment]
I suppose that ctrl+shift+esc triggers the task manager on your machine, right?

Also, is your keyboard based on the Latin alphabet?

**Comment by Draskic** [comment]
Yes, that combination is possible!
But it is quite unpleasant!
The one on "Hidden Icons" with the right button was better, but Microsoft dropped it to 11!
Now I googled a bit: it is also on the Start button with a right click.
This is similar to the Hidden Icons menu.
I have a Latin keyboard.
Greeting!

**Comment by martinet101** [comment]
> Yes, that combination is possible!
> But it is quite unpleasant!

So the shortcut is not the issue (it was for some people).

Could you please try the shortcut with version 3.9.2?

**Comment by Draskic** [comment]
Short cut? How?
And I have version 3.9.1

**Comment by martinet101** [comment]
Restarting ElevenClock should update. If not, download the latest version from [here](https://github.com/martinet101/ElevenClock/releases/tag/3.9.2)

**Comment by Draskic** [comment]
Hi
I updated to version 3.9.2 (downloaded)!
Now all three functions work!
I need to see when a notification comes and if clicking on the badge works to open the notification.
Now I put Task Manager on the first of the "Change action".
Likewise on the second (double click), and on the third (wheel) Change Task.
I still don't understand your question: "Could you please try the shortcut with version 3.9.2?"

**Comment by martinet101** [comment]
No, clocking the notification will still do the same action as the one done when clicking the clock. This won't change (when I was doing it I tried forcing the counter to open the calendar, but it wouldn't work in any way :/)

**Comment by martinet101** [comment]
On the question I meant trying the double click shortcut with v3.9.2

**Comment by Draskic** [comment]
O.K.
Then I will disable the first function so that it opens a notification (I did it the first time).
"trying the double click shortcut with v3.9.2"?
How to make a shortcut to 11clock?
I know how to make shortcuts to programs, but on 11clock, which is already working?

**Comment by martinet101** [comment]
No, there are no shortcuts, my wording was wrong.

What I meant was the clicked action, that can be understood as a _shortcut_ to the task manager

**Comment by Draskic** [comment]
O.K. I undersand!
Now I turned off the first two "Change the action done" and put Task Manager on the third (wheel) and it works.
I have to say that the second function (double click) works unreliably and it is very difficult to get Task Manager because constantly
opens the notification!
