### ISSUE TITLE
Cannot change the custom date and time format

### ISSUE THREAD

**Issue by rusegithub** [martinet101/ElevenClock#1002]
When I go to "Date & Time Settings:" and check the box for "Set a custom date and time format", I cannot change the text in the box that has %H:%M:S etc in it.

There is a blinking 'text placement cursor' at the start before the %H, but I can't move that or click in the box or change any text.

Am I doing something wrong?

I wanted to try changing %m/%d/%y to %m.%d.%y but it doesn't seem to be letting me.

I'm on the latest version that updated just now. 

## To Reproduce
Steps to reproduce the behaviour:
1. Go to "Date & Time Settings:"
2. Try to click on the box that has %H:%M:S etc in it
3. Cannot.

## Expected behaviour
I can change the text in the box from %m/%d/%y to %m.%d.%y

## Screenshots
This is the box I can't click in or change: (https://i.imgur.com/j3ZXhuB.png)

Thanks, by the way. I absolutely love ElevenClock. You're very kind.

**Comment by martinet101** [comment]
The text shown there is a placeholder, and it should disappear when typing something. If it does not work, please try resetting ElevenClock

**Comment by rusegithub** [comment]
> The text shown there is a placeholder, and it should disappear when typing something. If it does not work, please try resetting ElevenClock

Thank you. I feel stupid. Should've tried that.

But can I just add that maybe a "restore default" button or something might be useful. Because when you start typing, the text disappears, as you say, but I couldn't remember what was there before! Luckily I had the above screenshot, so it didn't matter (or I could've worked it out at https://strftime.org). 

But a button would be nice. I had actually right-clicked and tried to copy the text first, but that didn't copy anything. I could see that it wouldn't let me click on the "Copy" bit here: https://i.imgur.com/ZWyX57K.png so I tried using Ctrl+C but that did nothing either.

Thanks again, though.

(I'm just about to send another bit of feedback about full screen mode. Sorry to pester you!)

**Comment by rusegithub** [comment]
Actually it's not working.

I changed it to

%H:%M
%A
%D.%M.%Y

but it displayed like this: https://i.imgur.com/RHzDpTB.png

Then I changed it back to

%H:%M
%A
%D/%M/%Y

and it looks like this: https://i.imgur.com/X28tbzr.png

Here's the full part of that section in settings which includes the preview: https://i.imgur.com/QP56hpo.png

Resetting to default settings fixed the problem but I can't change the format to 

%H:%M
%A
%D.%M.%Y


It really doesn't bother me but there you go. :)

**Comment by martinet101** [comment]
Hi, There's a link with a cheatsheet regarding the date and time formats, which are case sensitive. 
day of the month is lowercase d, so it might be bugging because of this
![image](https://user-images.githubusercontent.com/53119851/197407025-6d38d276-8b46-4c70-be56-86b84900a4de.png)

**Comment by rusegithub** [comment]
Bingo.

%H:%M
%A
%#d.%#m.%Y

Thank you.
