### ISSUE TITLE
Hide the clock in fullscreen mode stopped working in 3.9.3

### ISSUE THREAD

**Issue by matthewkogan** [martinet101/ElevenClock#1004]
## To Reproduce
With (or without) "Hide the clock in fullscreen mode" ticked, it is always on top, even when a YouTube video is playing full screen.

## The Log
🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.002996206283569336 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.9.3 (v3.93) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(1336, 914, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M:%S 
%d/%m/%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 1536, 960)
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 0.5470004081726074
🔵 Restart loop: 1
🟣 Expected AttributeError on checkAndUpdateBackground
{'System language': 'default', 'Arabic - عربي\u200e (62%)': 'ar', 'Bosnian - Bosanski (6%)': 'bs', 'Bulgarian - български (18%)': 'bg', 'Catalan - Català': 'ca', 'Czech - Čeština (99%)': 'cs', 'Danish - Dansk (98%)': 'da', 'German - Deutsch (99%)': 'de', 'Greek - Ελληνικά (18%)': 'el', 'English - English': 'en', 'Spanish - Español (99%)': 'es', 'Estonian - eesti (92%)': 'et', 'Persian - فارسی\u200e (5%)': 'fa', 'Finnish - Suomi (63%)': 'fi', 'French - Français (99%)': 'fr', 'Hebrew - עִבְרִית\u200e (92%)': 'he', 'Croatian - Hrvatski (11%)': 'hr', 'Hungarian - Magyar (91%)': 'hu', 'Indonesian - Bahasa Indonesia (92%)': 'id', 'Italian - Italiano (65%)': 'it', 'Japanese - 日本語 (93%)': 'ja', 'Korean - 한국어 (99%)': 'ko', 'Lithuanian - Lietuvių (22%)': 'lt', 'Latvian - Latviski (61%)': 'lv', 'Norwegian (bokmål) (92%)': 'nb', 'Dutch - Nederlands (80%)': 'nl', 'Norwegian (nynorsk) (67%)': 'nn', 'Polish - Polski (96%)': 'pl', 'Portuguese (Brazil) (99%)': 'pt_BR', 'Portuguese (Portugal) (99%)': 'pt_PT', 'Romanian - Română (92%)': 'ro', 'Russian - Русский (92%)': 'ru', 'Sinhala - සිංහල': 'si', 'Slovak - Slovenčina (30%)': 'sk', 'Serbian - Srpski (22%)': 'sr', 'Swedish - Svenska (78%)': 'sv', 'Thai - ภาษาไทย (82%)': 'th', 'Turkish - Türkçe (99%)': 'tr', 'Ukranian - Yкраї́нська (93%)': 'ua', 'Vietnamese - Tiếng Việt (38%)': 'vi', 'Simplified Chinese (China) (99%)': 'zh_CN', 'Traditional Chinese (Taiwan) (99%)': 'zh_TW'}
🟣 Expected AttributeError on checkAndUpdateBackground
🔵 Language file up-to-date
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🟣 Expected AttributeError on checkAndUpdateBackground
🔵 System tray icon enabled
🟣 Expected AttributeError on checkAndUpdateBackground
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 3.710329294204712
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 396, in loadAtomicClockOffset

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 519, in open

🔴   File "urllib\request.py", line 536, in _open

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 1377, in http_open

🔴   File "urllib\request.py", line 1352, in do_open

🔴   File "http\client.py", line 1374, in getresponse

🔴   File "http\client.py", line 318, in begin

🔴   File "http\client.py", line 279, in _read_status

🔴   File "socket.py", line 705, in readinto

🔴 ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 10054] An existing connection was forcibly closed by the remote host)
🔵 Showing tooltip
🔵 Long date string: dd MMMM yyyy
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟢 Cached text input host hwnd: 66716
🔵 Showing tooltip
🔵 Long date string: dd MMMM yyyy
🔵 Announcement URL: https://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://upload.wikimedia.org/wikipedia/commons/d/db/Google_Translate_Icon.png
🟢 Cached text input host hwnd: 66718
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

**Comment by martinet101** [comment]
Please note that it might take up to 10 seconds to start detecting full-screen windows.

**Comment by matthewkogan** [comment]
I just watched a 9 minute video and the clock was on top throughout.

**Comment by martinet101** [comment]
Hi, taking a look at your log, it seems like you have disabled hiding on full-screen.

**Comment by matthewkogan** [comment]
I disabled it to see if it made any difference, but it didn't. I have re-enabled it now and it's still on top of my full-screen videos.

**Comment by martinet101** [comment]
Could you please send your log with this function enabled?

**Comment by martinet101** [comment]
Might this be the same issue as #1017?

**Comment by Kenryy** [comment]
Different
When "Hide the clock in fullscreen mode" option is closed, ElevenClock can work normally. Although the program "Windows 输入体验" still fulling screen.
log [3.9.3close.txt](https://github.com/martinet101/ElevenClock/files/9941246/3.9.3close.txt)
