### ISSUE TITLE
Eleven clock only shows on monitor 2 monitor 1 shows windows clock before repair used to be on both monitors

### ISSUE THREAD

**Issue by keitht1958** [martinet101/ElevenClock#1009]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Hi,

when sating repair, what do you mean?

Also, have you tried resetting ElevenClock?

**Comment by keitht1958** [comment]
Yes reset and reinstall clock on 2cnd monitor but not 1st cant see any option in settings

**Comment by martinet101** [comment]
Could you please send me your ElevenClock log?

**Comment by keitht1958** [comment]
log file attached

[eleven_log_27_10_2022.txt](https://github.com/martinet101/ElevenClock/files/9876416/eleven_log_27_10_2022.txt)

**Comment by martinet101** [comment]
Hi, you have clock on first monitor disabled. Please uninstall elevenclock, delete a folder called .elevenclock placed in your user directory and reinstall ElevenClock.

**Comment by BlackburnUTG** [comment]
> Hi, you have clock on first monitor disabled. Please uninstall elevenclock, delete a folder called .elevenclock placed in your user directory and reinstall ElevenClock.

I just updated from win10 and win11. and installed ElevenClock for the first time. And I have this issue too.
I did what you said, but it didn't fix the issue for me

**Comment by BlackburnUTG** [comment]
> @BlackburnUTG, can you please share your logs?

[log_eleven.txt](https://github.com/marticliment/ElevenClock/files/14050911/log_eleven.txt)

**Comment by marticliment** [comment]
From where did you install ElevenClock?

**Comment by BlackburnUTG** [comment]
> From where did you install ElevenClock?

from releases page on github

**Comment by keitht1958** [comment]
Win 11 downloads folder played up but then I Had to reinstall  win11 for another reason  then it worked fine

**Comment by BlackburnUTG** [comment]
@keitht1958 kek, man. ElevenClock developer is talking to me, not to you)))

**Comment by BlackburnUTG** [comment]
@marticliment I fixed the issue. Nvidea Gefore Expierence overlay caused this. I disabled the overlay - then I saw part of elevenclock's UI, but it didn't hide the windows clock. Then I reinstalled elevenclock - and everything is fine - windows clock is hiden
