### ISSUE TITLE
[FEATURE REQUEST] Inverted-Color 

### ISSUE THREAD

**Issue by WildcatMidnight** [martinet101/ElevenClock#1014]
Hi! 
 
( Describe the solution I'd like ) 
 
I like an Option - 
  { may be in: [ Settings ] Clock Appearance: _ 
    Use a custom font color ( Select custom color ) } - 
 
  that makes ( my ) Clock ( is always still appear over topmost ) - 
    could always be: **INVERTED**-color ( real-time ) - 
     to whatever background's under ( of any others applications windows ) 
  ( It seems work as: Windows control panel mouse properties pointers scheme - 
    " Windows Inverted . . " - for mouse pointer cursor ) 
 
( Then my Clock's surely always be seenable real-time at every circumstances - 
  instead of usually selecting and changing " custom color " time to time to make it's visible ) 
 
Thanks!

**Comment by martinet101** [comment]
Done!

https://user-images.githubusercontent.com/53119851/202849102-45acedb4-4158-421c-a268-60a3c76dcc17.mp4
