### ISSUE TITLE
Winget package is out of date

### ISSUE THREAD

**Issue by ppvnf** [martinet101/ElevenClock#1015]
Winget pkg is still at version 3.9.1. By the way, I got a Python error when downloading it from WingetUI (the error was from ElevenClock, but it worked and updated itself afterwards). I forgot to save the log though

**Comment by martinet101** [comment]
That's an issue with the publish action.
![image](https://user-images.githubusercontent.com/53119851/200047925-a92b3964-e418-44f4-8c93-4a90864479e8.png)
@vedantmgoyal2009 (sorry to ping you)
is this behaviour normal? Am I doing something wrong?

**Comment by vedantmgoyal2009** [comment]
That's because the installer is uploaded sometime later after the release is created. In the meantime, no installers are avaible, hence the action fails.

**Comment by martinet101** [comment]
Oh, I see.


On the next release I'll add the binaries before publishing.
