### ISSUE TITLE
Make `%z` and `%Z` work in custom date/time formats

### ISSUE THREAD

**Issue by myfairsyer** [martinet101/ElevenClock#1018]
Replace `%z` and `%Z` inside the custom date/time format string by the timezone offset or name, not by empty strings.

(To make this description easier, I'll directly address the maintainer @martinet101 as _you_, here.)

In the settings dialogue for custom date/time formats, you refer to https://strftime.org/ for the codes that can be used inside the custom date/time format that will be interpreted/replaced by their respective data.

https://strftime.org/ lists `%z` and `%Z` as codes for timezone offset and name:
![image](https://user-images.githubusercontent.com/13559472/200015573-ecb535a3-bf59-4b18-8202-3e39b58136b9.png)

However, when I use these codes in ElevenClock, they just get replaced by empty strings:
![image](https://user-images.githubusercontent.com/13559472/200015750-ee5990e0-9b47-412a-93c3-4c40234c502b.png)

You added this behavior to the _known issues_ of your main wiki page in fb1a3f5 from June 4th: https://github.com/martinet101/ElevenClock/wiki/Home/_compare/65f6fa2d9fd1e78bf15b98b380c0e3fae0610d1c...fb1a3f5ebe049fd23a6f2aaa7eaab71cfa0cbf2b, where you describe it as a misexplanation of Python's datetime documentation and refer to https://github.com/robotframework/robotframework/issues/3766#issuecomment-732951221, where this is also being discussed..
The Python datetime documentation page you provided a link to, says the following in its note 6 about `%z` and `%Z`:

> For a naive object, the %z and %Z format codes are replaced by empty strings.

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes:~:text=For%20a%20naive%20object%2C%20the%20%25z%20and%20%25Z%20format%20codes%20are%20replaced%20by%20empty%20strings.

However, this April in #5, you seemed to manage to work around the issue that "windows registry clocks ...  use a timezone method not compatible with python's" in your tooltips, after @SmartManoj gave you a link to https://github.com/regebro/tzlocal/blob/master/tzlocal/windows_tz.py:
![image](https://user-images.githubusercontent.com/13559472/200023717-e9226a33-7d1a-4815-ace7-e571899a5173.png)

You answered my (implicit) question if this workaround would also enable you to make `%z` and `%Z` in custom date/time format strings work "properly" in ElevenClock with the suggestion to either refer to an existing issue about `%z` and `%Z` or to open a new one.

So here you are the new issue, I really hope, that although you added this to known issues as feature codes that are not even meant to work _**after**_ our discussion in April, using the workaround from #5 might also be a feasible solution here.

Thank you very much for your great work!

**Comment by martinet101** [comment]
As far as I understand in your explanation, i suppose that yes, the zurrent timezone can be read from the registry and then converted by the same alghorithm used in the tooltip, and then shown with %z and %Z.

I suppose that this can be done

**Comment by TheAlienDrew** [comment]
This was basically my request in https://github.com/martinet101/ElevenClock/issues/989/.

Looking forward to the feature.

**Comment by martinet101** [comment]
Hi,

I couldn't find a way to get timezone names to get displayed, since the libraries behaviour is weird and not properly documented.

I'm sorry, but this will not be worked on, at least until Python decides to clarify how strftime works

**Comment by TheAlienDrew** [comment]
I have a solution for this.

**Comment by TheAlienDrew** [comment]
Your usage of `datetime.datetime.now()` should be changed to `datetime.datetime.now(datetime.timezone.utc).astimezone()`

**Comment by TheAlienDrew** [comment]
Here's some test code for you:

```python3
import datetime
import dateutil.tz as tz

dateTimeFormat = "%I:%M %p %Z (%z)"

# timezones
egyptTZ = tz.gettz('Egypt Standard Time')

# allows showing of TZ info via `%z` and `%Z`
nowUTC = datetime.datetime.now(datetime.timezone.utc)
nowLocal = nowUTC.astimezone()
nowEgypt = nowUTC.astimezone(tz=egyptTZ)

timeUTC = nowUTC.strftime(dateTimeFormat)
timeLocal = nowLocal.strftime(dateTimeFormat)
timeEgypt = nowEgypt.strftime(dateTimeFormat)

print("Results formated as: \"{}\"".format(dateTimeFormat))
print(timeUTC)
print(timeLocal)
print(timeEgypt)
```
