### ISSUE TITLE
[FEATURE REQUEST] Since this may not be for Windows 10, It works. BUT!

### ISSUE THREAD

**Issue by Rellawing** [martinet101/ElevenClock#1021]
**Is your feature request related to a problem? Please describe.**
I'd like you to add a calendar widget like Windows 11's. Your app works as a great clock replacement for Windows 10 for us unlucky people whose all 3 computers were deemed incompatible. >.>

And related, there is an issue: Upon clicking the clock, even after setting to open calendar after x clicks, it does not do anything. Looks great, though, if a bit slow as far as clocks go.

**Describe the solution you'd like**
Simple! A built in Calendar so it will call up a calendar and link to standard event/appointment settings in the OS.  And/or working call to the Calendar for Windows 10.

Additional note: The Quick Settings option calls The Action Center in Windows 10, which is good! There's already support for calling that! 
If you added a widget for calling a Windows 11-like Action Center, that'd be uber awesome!

**Comment by martinet101** [comment]
Hi, this should work by default, but if you are using a non-latin eyboard, this feature might be broken, and the bug is #923

**Comment by Rellawing** [comment]
My keyboard is standard American. Razer Cynosa Chroma. The mouse is Razer Naga Epic Chroma. It's a matter of clicking the clock with the mouse pointer, so I'm not sure how the keyboard influences the software's functioning. 🤔

**Comment by Rellawing** [comment]
The solution for this problem is to go to Run using Win+R.
Type in: %userprofile%/.elevenclock
This will open C:\Users\USER\.elevenclock in File Explorer.
open CustomClockClickAction and replace what's there with:
Win+Alt+d --- Save it.
Restart the clock by right clicking and selecting RestartElevenClock.

This method **requires Windows 10 Anniversary Update or later**.

**But there are still errors.** 😦 

Neither double-click nor middle click actions work. The first action overrides all other actions.

**Comment by martinet101** [comment]
You need to enable the double click / middle click first before being able to change the actions.

Also, please note that while it works, some features do not work on w10 because it is not supported, and support is not planned, since other apps like T-clock reduc work as expected there.

**Comment by Rellawing** [comment]
😭
