### ISSUE TITLE
[FEATURE REQUEST] on-mouse-click popup show time with running seconds

### ISSUE THREAD

**Issue by cotesystems** [martinet101/ElevenClock#1022]
I often need to see the seconds of the current time, but I don't want it distracting me in the system tray time display.   It was a nice feature in Win 10 that on-mouse click, the calendar would show up and the current time with live running seconds would display.   So we would only display live seconds when we needed it.   Can we add this feature to ElevenClock for Win 11?
![Win_10_ clock-pop-up](https://user-images.githubusercontent.com/44899422/200393608-7a942da3-565b-48f8-bf79-a8441337d47d.png)
![Win_11_ clock-pop-up](https://user-images.githubusercontent.com/44899422/200393609-21da5bd6-e90a-4b69-816c-ce1076b99ee4.png)

**Comment by martinet101** [comment]
Hi,

Seconds to the calendar flyout can be added with an easy tweak, without requiring additional software. You can find how to here: https://www.youtube.com/watch?v=01t_40FdJNU

**Comment by cotesystems** [comment]
Thanks Marti, that tweak almost achieves what I need.   It only
adds the seconds as a static value, where the old Win 10 feature
displayed it as a running updating clock value.    I often need it
to show as a running updated value so that I can watch for a specific
time to arrive so that I can manually trigger something else I am
testing or configuring that has to occur at a specific time including
seconds. Or I am watching/monitoring another app and I want to confirm
exactly what time including seconds that it finishes or changes state.

Any tweak for making the seconds display a live updating value?

Thanks

Michel Cote
780-666-2555
 

--- Original message follows ---
Subject: Re: [martinet101/ElevenClock] [FEATURE REQUEST]
on-mouse-click popup show time with running seconds (Issue #1022)
From: "Martí Climent" 
To: "martinet101/ElevenClock" 
CC: "cotesystems" , "Author" 
Date: 07-11-2022 12:32 pm








Hi,



Seconds to the calendar flyout can be added with an easy tweak,
without requiring additional software. You can find how to here:
https://www.youtube.com/watch?v=01t_40FdJNU



—
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].
You are receiving this because you authored the thread.Message ID: 



Links:
------
[1]
https://github.com/martinet101/ElevenClock/issues/1022#issuecomment-1306090068
[2]

**Comment by cotesystems** [comment]
Forgot to mention that I can't use the tweak because only 2
additional calendars are allowed to display in Win 11 and I am already
using them to monitor work I am in progress with customers in those
regions.

Michel Cote
780-666-2555
 

--- Original message follows ---
Subject: Re: [martinet101/ElevenClock] [FEATURE REQUEST]
on-mouse-click popup show time with running seconds (Issue #1022)
From: "Martí Climent" 
To: "martinet101/ElevenClock" 
CC: "cotesystems" , "Author" 
Date: 07-11-2022 12:32 pm








Hi,



Seconds to the calendar flyout can be added with an easy tweak,
without requiring additional software. You can find how to here:
https://www.youtube.com/watch?v=01t_40FdJNU



—
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].
You are receiving this because you authored the thread.Message ID: 



Links:
------
[1]
https://github.com/martinet101/ElevenClock/issues/1022#issuecomment-1306090068
[2]

**Comment by martinet101** [comment]
Hi,

I think live seconds are not possible, and modifying the calendar flyout is not possible in W11. The best thing I can recommend you is ElevenClock, but you won't be able to get rid of the distraction of the seconds (though honestly, after two or three days you don't notice it anymore)
