### ISSUE TITLE
Timezones displayed as local time

### ISSUE THREAD

**Issue by robknapman** [martinet101/ElevenClock#1023]
Hi,

I am having an issue where Elevenclock is showing timezones as local time, searching through the forum, i see others have also had this issue and the last post said it was resolved.

![image](https://user-images.githubusercontent.com/117725833/200537516-3f99a453-ef16-4d76-92f5-06c5c74de6b6.png)

The log file is really big 147000kb so I have zipped it up

[elevenclock.zip](https://github.com/martinet101/ElevenClock/files/9960072/elevenclock.zip)

Hopefully you know what the issue is

Rob

**Comment by martinet101** [comment]
Might this be related to #989.?

**Comment by robknapman** [comment]
I can confirm 3.9.1 is working correctly

**Comment by elenapoot** [comment]
3.9.3 has this bug. When I reinstalled from the microsoft store, it worked properly for a moment, but then updated to 3.9.3, which does not.

**Comment by martinet101** [comment]
All I'm going to close this and mark it as duplicate, please post on #989 so you get updates about the issue
