### ISSUE TITLE
[FEATURE REQUEST] Show notification about change of season 

### ISSUE THREAD

**Issue by ppvnf** [martinet101/ElevenClock#1027]
**Is your feature request related to a problem? Please describe.**

It's not really important, but I think it would be nice if ElevenClock would show a notification in equinox and solstice

**Describe the solution you'd like**

Have an option that enables a notification in case of change of season.
It would have to detect the user location, at least approximately, since the seasons are the opposite in north and south hemispheres

**Comment by martinet101** [comment]
Hi @ppvnf,

I really appreciate your feature request, but I don't see how this could be in ElevenClock's scope. I mean, the goal is to have a customizable clock, but not to provide hour chime/custom calendars/etc.

**Comment by ppvnf** [comment]
> Hi @ppvnf,
> 
> I really appreciate your feature request, but I don't see how this could be in ElevenClock's scope. I mean, the goal is to have a customizable clock, but not to provide hour chime/custom calendars/etc.

That's okay. I am learning some programming and maybe a weather app would be something nice to create when I have enough skill...
