### ISSUE TITLE
can't exit full screen youtube videos as the icon is in the Same location

### ISSUE THREAD

**Issue by SWEATSHOPKING** [martinet101/ElevenClock#103]
watching a youtube video full screen, try to click on the exit full screen button but it's in the same location as elevenclock so it just overrides the exit full screen button and instead it opens the notification panel.

**Comment by martinet101** [comment]
I'm investigating this. 

Meanwhile, you can: 
 - Exit fullscreen pressing esc
 - Right click on the clock and select "Hide". To show the clocks again, just click on the taskbar icon
