### ISSUE TITLE
[ISSUE] High usage CPU

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#1030]
"High" usage cpu in idle.

Actually: 2-5% usage

Expected: 0-1% usage

HW (laptop):
* CPU: AMD Ryzen 5650U (6C/12T))
* RAM: 32GB DDR4
* 3 displays:
  * fHD monitor
  * 2k monitor (master)
  * fHD laptop screen

OS:
* Windows 11 x64 22623.891
* ElevenClock 3.9.3

![b](https://user-images.githubusercontent.com/3808250/201725603-5d823e7f-4eda-4dd1-bb7b-dc8bcca39dd0.gif)

**Comment by martinet101** [comment]
Hi @panther7,

Does this happen only during the first 30 seconds after launch or is this high cpu usage perpetual?

Also, could you please check with [processexplorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) if the percentage shown in task mabager is accurate?

Thanks!

**Comment by martinet101** [comment]
Hi,

could you please try this release?

**Comment by panther7** [comment]
Is much better :) ...but in future, maybe it could be lower, like (0-0,5%) ;-)

![b](https://user-images.githubusercontent.com/3808250/201923519-958ba121-f246-464c-a1fc-8ef51740d19e.gif)

@martinet101

**Comment by martinet101** [comment]
Could you please check the cpu usage with process explorer?

**Comment by panther7** [comment]
3.9.3
![b](https://user-images.githubusercontent.com/3808250/201934267-04ea81b9-d5f0-414c-a963-032c35a1f480.gif)

3.9.4b2
![c](https://user-images.githubusercontent.com/3808250/201934292-c76efa3d-bf75-4578-a130-624611c75da6.gif)

**Comment by martinet101** [comment]
Then it is taask manager misreporting... You can see cpu usage is between 0.5 and 0%. 

There have been other reports of task manager misreporting, so i'll close this as fixed with the beta version
