### ISSUE TITLE
[BUG/ISSUE] Display seconds on the clock

### ISSUE THREAD

**Issue by ngc7743** [martinet101/ElevenClock#1037]
Spacing occurs every 1, 11, 21, 31, 41, 51 seconds.
![ASDFADSFASFD](https://user-images.githubusercontent.com/67748893/202644978-179dd3f8-ce14-41f9-85c0-ef665682a015.png)

**Comment by martinet101** [comment]
This has been done on purpose to prevent the time string from side to side and distracting the user.

This can be disabled by specifying a custom font
