### ISSUE TITLE
[FEATURE REQUEST] Add Calendar popup like Windows 10 had

### ISSUE THREAD

**Issue by KyferEz** [martinet101/ElevenClock#1038]
I want a clock to present a calendar like we had in Windows 10 that displays when left-clicked. I used that ALL the time to simply determine what day of the week a future date was for scheduling purposes. Not having that is a real PITA and I would LOVE if someone would code up one for this clock!

**Comment by martinet101** [comment]
Hi @KyferEz, 

You can still do that with the current calendar, don't you?

**Comment by KyferEz** [comment]
In windows 11 there is no longer a calendar on the clock, and there's no
replacement I've been able to find.

**Comment by martinet101** [comment]
Yeah there is
![image](https://user-images.githubusercontent.com/53119851/202855047-4b5060f9-b844-4d50-b362-4aa662dabc00.png)

**Comment by KyferEz** [comment]
Well guess something is broke in my W11 because I get nothing when I click
the clock. It literally just acts like it wasn't clicked. Did some research
and might be related to Action center; I don't like the constant
notifications so disabled it.

Thanks for responding!

**Comment by martinet101** [comment]
Note that ElevenClock was reported to not peoperly open the clock. Please check if the Win+N shortcut opens this calendar. Also, try updating ElevenClock, some fixes to the calendar opener were done

**Comment by KyferEz** [comment]
It ended up being caused by this:
https://www.elevenforum.com/t/when-i-click-on-clock-volume-network-etc-on-taskbar-nothing-happens.979/post-33472

Thanks for the reply though!
