### ISSUE TITLE
This relates to the ability to see one's Notifications Center pane. When clicking on the Notifications badge to the right of the ElevenClock taskbar clock it just does nothing. However, the badge is indeed indicating that there are 11 notification messages ― but cannot view them as the Notifications Center pane is not being responsive and not popping up.

### ISSUE THREAD

**Issue by EdDCosta-US** [martinet101/ElevenClock#1045]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Does the Win+N shortcut work on your pc?

Which keyboard layout are you using?

**Comment by EdDCosta-US** [comment]
The Win+N keyboard shortcut is not working on my this laptop. And my laptop has the (modern) US ANSI/ASCII QWERTY keyboard layout.

**Comment by martinet101** [comment]
Ok. ElevenClock emulates the win+N keyboard shortcut to work, so if it does not work from your keyboard I'm afraid I can't help you, since is not an ElevenClock fault.

I'm sorry :(
