### ISSUE TITLE
ElevenClock-Updater.exe is blocked by Norton 360

### ISSUE THREAD

**Issue by pewyss1** [martinet101/ElevenClock#1046]
Hello

I recently install Windows 11 on my brand new HP Notebook.
While installing ElevenClock from the Microsoft Store, ElevenClock is installed and running but only for a short moment.
Then elevenclock-updater.exe is executed and my Norton 360 Security-Programm is blocking it.

Now I even can’t deinstall ElevenClock at all and it’s not running.

Do you have a solution?

Thank you in advance for your Help
Peter

**Comment by martinet101** [comment]
Hi Peter,

You'll need to whitelist ElevenClock, since it often gets identified as a false positive.

If you look at virus total, you'll see that only some MI or vendors flag that as virus.
