### ISSUE TITLE
[BUG/ISSUE] Clock looks wrong since 3.9.4 (font rendering?)

### ISSUE THREAD

**Issue by BooBerry** [martinet101/ElevenClock#1047]
Ever since updating to [3.9.4](https://github.com/martinet101/ElevenClock/releases/tag/3.9.4) the Windows 11 22H2 clock font (and/or font rendering) looks completely wrong. Happens in 3.9.5 and 3.9.6 as well.

## To Reproduce
Steps to reproduce the behaviour:
1. Update to 3.9.4 or newer on Windows 11 22H2 with a 1440p or larger screen.

## Expected behaviour
Pre-3.9.4 it looks like this, which looked absolutely perfect, especially when compared to the system clock and how it appears (appears to be 1:1, with seconds added)...

![Correct](https://user-images.githubusercontent.com/5448916/203568264-2bc6bec5-0ff7-4c18-ba24-e0e8c8beb20c.png)

After updating to 3.9.4 or newer, it looks like this which the font rendering appears to be wrong and looks bad, IMO.

![Incorrect](https://user-images.githubusercontent.com/5448916/203568504-9b9b483a-f1d5-4c57-aed7-82326fceb6f4.png)

Overall if looks squished, almost kinda like the font rendering changed. Also it doesn't fully cover the system clock (you can see it on the edge) which yes I know I can manually override and fix, but pre-3.9.4 it just worked perfectly as-is.

I'm using Windows 11 22H2 64-bit with a 1440p screen and an AMD GPU. I also tested this on a secondary device which it happens there too.

Things I've tried:

1. I tried resetting ElevenClock's settings to the default and it still appears this way.
2. I've messed with the custom font settings and other appearance settings, which don't even come close to restoring how it looks pre-3.9.4.

My only workaround right now is downgrading to 3.9.3 and disabling updates.

Thoughts? Is there any way to restore the pre-3.9.4 appearance?

**Comment by martinet101** [comment]
Qt6.4 introduces changes in the font render engine, so it might be that

**Comment by martinet101** [comment]
I have found the issue now

**Comment by martinet101** [comment]
It has been fixed, and the fix will roll out with the next update

**Comment by martinet101** [comment]
Could you please test this release?

https://github.com/martinet101/ElevenClock/releases/tag/3.9.7-beta1

**Comment by BooBerry** [comment]
Yup, works perfectly again! Thanks! :D
