### ISSUE TITLE
ElevenClock covers start button

### ISSUE THREAD

**Issue by wfarrell1** [martinet101/ElevenClock#1048]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Hi, 

In order to get your clock to the left you need to have your taskbar centered.

Is this the issue you were facing?

**Comment by wfarrell1** [comment]
Thank you for your reply.
I had the Taskbar to the left. I'll use the feature "Hide the clock during
10 seconds when clicked."
 I would use the grammar  "Hide the clock *for *10 seconds when clicked."

**Comment by martinet101** [comment]
You could also change  the click action so it does open the start menu instead of opening the calendar, and set the double-click to the notifications pane
