### ISSUE TITLE
Enabling Internet Time Sync will display my remote timezone as default

### ISSUE THREAD

**Issue by iamaluckyguy** [martinet101/ElevenClock#1057]
Enabling Internet Time Sync will display my remote timezone as default.  I have a China Time as main and a Pacific Time (US Los Angeles) as a secondary time. I am in China and I am using the China Time. Things are normal if I did not enable Internet Time Sync. If I do, then the Pacific Time will be displayed as default.

**Comment by martinet101** [comment]
yes, this is expected to happen since your time is taken from your ip.

you can do two things in this situatiin:
 - disable internet time
- enable internet time but specify a custom date and time URL. theres more info on the ElevenClock wiki about this

**Comment by martinet101** [comment]
for more help make sure to reply
