### ISSUE TITLE
[FEATURE REQUEST] Add the feature of adding taskbar icons alongside the clock

### ISSUE THREAD

**Issue by argente69** [martinet101/ElevenClock#106]
I have and dual monitor setup and I use my PC to play a lot of games. When I was on windows 10, I used to have the temperature and % of utilization and my obs icon on my second monitor taskbar and the game on fullscreen on my principal display. Now in windows 11, this isn't possible anymore because we cant move the principal monitor taskbar to the second like I used to do on Win10. Is there a way you adding the taskbar icons alongside the clock on a future update?
here's a example:
![image](https://user-images.githubusercontent.com/29031093/137335474-b6162436-18cd-4587-a65a-e6249726c7e0.png)

**Comment by martinet101** [comment]
Nope, since this is windows built-in feature, i can't access other program's trays and move them to other taskbars. I mean, if i coukd do that I would, and I already thought of that, but it isn't possible.

I'm sorry i can't :(
