### ISSUE TITLE
ElevenClock is hidden when interacting with the Windows Start Menu

### ISSUE THREAD

**Issue by ninbura** [martinet101/ElevenClock#1060]
When interacting with the Windows Start Menu ElevenClock is hidden until the Taskbar is no longer in focus. When interacting with any other element on the Taskbar there's only a flicker. 

Is this intended / already known?

https://user-images.githubusercontent.com/58058942/206331835-312aa1e8-cfb1-427d-abd3-a9dc87a53563.mp4

**Comment by martinet101** [comment]
it is a known issue, due to the Taskbar having the user focus.

the same thing happens with the action center

**Comment by ninbura** [comment]
Would it then be possible to add an option that changes the position of ElevenClock when the Start menu or Action Center is focused? 

For example, to a different corner of the screen?

**Comment by martinet101** [comment]
no, since there's no way to detect whether the start menu is opened or not.

**Comment by micheldiemer** [comment]
I am using translucenttb 
translucenttb.github.io
With TranslucenTb and ElevenClock both enabled, ElevenClock is not hidden when clicking on the start menu.
Windows 11 22H2 BUILD 22621, 1992

**Comment by ninbura** [comment]
While ElevenClock adds more functionality than simply displaying seconds on your Taskbar/system clock; it should be noted that Microsoft added the ability to display seconds in your Taskbar/system clock natively in the latest build of Windows 11:
![image](https://github.com/marticliment/ElevenClock/assets/58058942/2deba165-a789-49c2-a674-f872ab93368f)

While I appreciate the stopgap that Eleven Clock provided; for me, and I assume many others, it is no longer necessary.
