### ISSUE TITLE
%V is not working in workweek

### ISSUE THREAD

**Issue by sundara-vignesh** [martinet101/ElevenClock#1068]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Hi @sundara-vignesh,

`%V` is not a valid parameter for python's strftime. You can check the full list here: https://strftime.org/

**Comment by sundara-vignesh** [comment]
WW starts from 0.. can we make it to start from 1? for that %V should be the one. can u upgrade the tool?

**Comment by martinet101** [comment]
Hi @sundara-vignesh, ElevenClock's datetime system is based on Python's datetime library, so perhaps this suggestion should be made to the python language itself.

Here you can find information on how to create a feature request, though i'd jump directly to the python-dev mailing list:
https://stackoverflow.com/a/2386470/11632591
