### ISSUE TITLE
[ISSUE] CPU still high

### ISSUE THREAD

**Issue by alaskino** [martinet101/ElevenClock#110]
Check your code because the CPU usage is still very high at the moment. Sometimes it goes +10,0%

**Comment by alaskino** [comment]
Already disabled. As you se
![a](https://user-images.githubusercontent.com/64799057/137376289-2578c89c-ec40-4c7a-8ae6-5498397134c6.png)
e

**Comment by martinet101** [comment]
You are running 2.1, update to 2.1.1
