### ISSUE TITLE
[FEATURE REQUEST] Languages addition

### ISSUE THREAD

**Issue by alaskino** [martinet101/ElevenClock#111]
I suggest to add at least english, french, spanish, german, italian and russian languages.

**Comment by martinet101** [comment]
Welp, i was thinking about this, i'll study that

**Comment by alaskino** [comment]
💖

**Comment by Seeloewen** [comment]
If you need any help translating, I can fluently speak german. If you could make some kind of language file or something I could totally contribute.

**Comment by Ranzo** [comment]
Hi, If you need any help translating, I can fluently speak russian language.

**Comment by martinet101** [comment]
Nice, I'll let you know
