### ISSUE TITLE
[BUG] Clicking the clock shows the notifications and calendar panel on the first screen

### ISSUE THREAD

**Issue by Nickfrm** [martinet101/ElevenClock#113]
Clicking the clock shows the notifications and calendar panel on the first screen but should be shown on the second one.

**Comment by Nickfrm** [comment]
Here's the preview:
![clock_issue](https://user-images.githubusercontent.com/35500726/137382724-0cd4b5eb-bf75-4e60-a2ec-7d0136c6e838.gif)

Let me know if you need any additional info

**Comment by Nickfrm** [comment]
But most of the time nothing happens when I click the clock

**Comment by martinet101** [comment]
Hi @Nickfrm , the calendar not showing sometimes is a Windows 11 bug, and it will happen if you use Win+N keyboard shortcut. (Actually ElevenClock emulates Win+N) key press.

About showing the clock on the secondary screen, i have already tried implementing this, but it is not possible. Im sorry :(

**Comment by proimage** [comment]
> About showing the clock on the secondary screen, i have already tried implementing this, but it is not possible. Im sorry :(

That's rather odd; when I first installed ElevenClock a week ago or so, that's exactly how it was working... clicking on secondary monitor clocks was showing the calendar on those screens.

**Comment by martinet101** [comment]
Oh, that's weird, it never worked for me. I guess this feature is broken
