### ISSUE TITLE
[BUG] Overlapping clocks on main screen

### ISSUE THREAD

**Issue by wrufeger** [martinet101/ElevenClock#114]
**Describe the bug**
overlapping clocks on one screen, all others without clock after monitor wake up.

**To Reproduce**

1. wait, till monitors go to sleep
2. move mouse

**Screenshots**

![image](https://user-images.githubusercontent.com/524191/137382320-e2a0f897-51eb-4a50-a512-72156d1aa582.png)

**Additional context**
currently using 3x 4K monitors

**Comment by martinet101** [comment]
Before going to sleep, the clock does overlap or not?

**Comment by martinet101** [comment]
Then  should i close that?

**Comment by dbeachy1** [comment]
BTW this is happening on my system as well. I suspect the reason (on my system, at least) is that my second monitor completely powers off when Windows 11 turns the displays off, and it takes a few seconds (maybe 5?) for the monitor to "wake up" when Windows wakes up the screens, and by that time, the ElevenClock is already rendered (and then stuck) on my primary display's taskbar.

![ElevenClock bug_Screenshot 2021-10-15 132545](https://user-images.githubusercontent.com/2531742/137528877-d9b052de-6a4b-499e-b4bf-43300bd398be.png)

Thanks for looking at this, BTW! I love ElevenClock!

**Comment by martinet101** [comment]
Fixed, coming in 2.2

**Comment by ktremain** [comment]
please see my new bug #142 - i think the issue may not be sleep, but the second screen being "removed" by windows during sleep or wake up as i can re-create this by changing screen layouts.
