### ISSUE TITLE
[BUG] Hide the clock when RDP client is active crashes software

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#115]
**Describe the bug**
Hide the clock when RDP client is active crashes software

**To Reproduce**
1. Download latest version 2.11
2. Check off Hide the clock when RDP client is active
3. Crash

**Expected behavior**
No crash

**Screenshots**
![image](https://user-images.githubusercontent.com/22828430/137385173-eba14b40-4305-4a89-ae32-4ff8320e3746.png)
![image](https://user-images.githubusercontent.com/22828430/137385192-5fc0c504-01a0-4796-a45d-96aa313245a7.png)

**Comment by martinet101** [comment]
Fixed, fix coming in v2.2. 

(Note that cpu stills around 0.2% when RDP check is enabled)
