### ISSUE TITLE
[BUG] Seconds displayed as s and not ss

### ISSUE THREAD

**Issue by prg011** [martinet101/ElevenClock#116]
Hi,

The clock displays seconds as s, not ss. So I get:  4:00:1 PM instead of 4:00:01 PM.

Not a big thing, but it would look better.

(FYI, My Regional settings are set to (long date): `h:mm:ss tt` ).

**Comment by martinet101** [comment]
Yep, let me check this

**Comment by martinet101** [comment]
Ok, i'll change that and i'll force :ss mode

**Comment by martinet101** [comment]
Ficed, coming in 2.2
