### ISSUE TITLE
[BUG/ISSUE] Non-padded hour parameters don't work

### ISSUE THREAD

**Issue by Ander3232** [martinet101/ElevenClock#1164]
Hey guys,

EC doesn't accept these formats in the Python time/date chart:

%-H  Hour (24-hour clock) as a decimal number
%-I  Hour (12-hour clock) as a decimal number

It says "Invalid format". Thanks!

![EC_screenshot](https://user-images.githubusercontent.com/25757204/229123857-3baf0444-68e7-4af7-9ed6-6e8a10eb017b.jpg)

**Comment by marticliment** [comment]
It requires a #, not a -
