### ISSUE TITLE
[FEATURE REQUEST] Option to get clock to manually switch between light and dark modes.

### ISSUE THREAD

**Issue by TECHSPERT50** [martinet101/ElevenClock#119]
I customise my taskbar with OpenShell, etc. This means that sometimes the clock shows the incorrect colour, as it is detecting what the taskbar should look like, by windows default, and shows in an unreadable colour. had to hover over the clock for it to be visible in this screenshot: 
![image](https://user-images.githubusercontent.com/92092170/137401812-7a142f11-4ce2-421a-9900-a17139fc78e4.png)

It would be great if there was an option to switch the clocks colour in the settings menu.

**Comment by martinet101** [comment]
I'll anyway add this function

**Comment by martinet101** [comment]
Coming in version 2.2
