### ISSUE TITLE
Shows %H:01 instead of Time on the secondary display

### ISSUE THREAD

**Issue by kurzpc** [martinet101/ElevenClock#12]
Hello,

#1 
I have a similar problem.

Primary monitor 21:01 Displayed on the second monitor %H:01

![Screenshot 2021-10-05 220157](https://user-images.githubusercontent.com/72160647/136094920-f9ffc07c-3a8d-46b4-984a-e1288593ea62.jpg)

![Screenshot 2021-10-05 220143](https://user-images.githubusercontent.com/72160647/136094927-dba09f93-d55d-4552-be2c-48ad8eb801bd.jpg)

My region is Germany
Time short => HH:mm
Time long => HH:mm:ss

![Screenshot 2021-10-05 220302](https://user-images.githubusercontent.com/72160647/136094943-c9cfe336-9daf-4686-80f1-4dbb96ee7293.jpg)
![Screenshot 2021-10-05 220348](https://user-images.githubusercontent.com/72160647/136094947-032f0e28-c4b9-4c4b-ae91-cb77c9cc694f.jpg)

It would be great if you could fix the problem as well.

**Comment by StephanBruh** [comment]
Same issue here.

**Comment by yannhodiesne** [comment]
Got the same issue here, with default French settings

**Comment by Ashe-Sterling** [comment]
If you have your system set to 24-hour time, I believe I've fixed this issue in my fork of the project.

Release here: https://github.com/Ashe-Sterling/ElevenClock/releases/tag/1.5

**Comment by kurzpc** [comment]
> 
> 
> If you have your system set to 24-hour time (as OP does), I believe I've fixed this issue in my fork of the project.
> 
> Release here: https://github.com/Ashe-Sterling/ElevenClock/releases/tag/1.5

Thank you works perfectly.

**Comment by martinet101** [comment]
@Ashe-Sterling , thanks for the PR, it will be shipped with version 1.6

**Comment by Ashe-Sterling** [comment]
@martinet101 Sure thing!

**Comment by martinet101** [comment]
Version 1.6 released. Relaunch ElevenClock and it will update
