### ISSUE TITLE
[BUG] Clock shows over Vmware

### ISSUE THREAD

**Issue by prg011** [martinet101/ElevenClock#120]
When using a virtual machine (VMare Workstation Pro) in full screen mode, the clock displays on top of the virtual machine screen. See attached.

![2021-10-14_22-08-12](https://user-images.githubusercontent.com/15201313/137421095-f32ccead-949d-42d0-8402-05870d499897.gif)

**Comment by TECHSPERT50** [comment]
You can either right click and select hide, or go into the settings and select "Automatically hide in Fullscreen mode".

**Comment by martinet101** [comment]
Are you running thr lastest version? (2.1.1)
