### ISSUE TITLE
[BUG] Refreshing when seconds are already displayed duplicates seconds

### ISSUE THREAD

**Issue by prg011** [martinet101/ElevenClock#126]
![2021-10-15_17-57-19](https://user-images.githubusercontent.com/15201313/137557992-62399369-d699-4e14-b551-b0727540d4d7.gif)

And interestingly enough, it does duplicate seconds but formatted with leading zero... 

![2021-10-15_18-00-11](https://user-images.githubusercontent.com/15201313/137558105-bf892787-ba3f-47e4-9343-813a27291b69.gif)

**Comment by TECHSPERT50** [comment]
Ive seen a slightly different variation of this, it is easy to resolve. I had it enabled in the registry, and had changed the short date in the classic control panel menu to yyyy-mm-dd-s. I just disabled it in the registry, that fixed it for me. Although, this might not be the same thing.

**Comment by martinet101** [comment]
I've been able to recreate the issue, i'll try to fix it asap

**Comment by martinet101** [comment]
Fixed, will be released in v2.2
