### ISSUE TITLE
[ISSUE] fatal error

### ISSUE THREAD

**Issue by panaris** [martinet101/ElevenClock#134]
https://bit.ly/3pgkAj7 fatal error with the latest build

**Comment by martinet101** [comment]
Try running this one and send me the output:

https://1drv.ms/u/s!ApcYxgwZ8nkcgb9UIgweh3VbJRcG_A?e=9dUxtI

**Comment by martinet101** [comment]
This is the only output?

**Comment by martinet101** [comment]
This is the only output?

**Comment by panaris** [comment]
after that it forcecloses. I can't see further

**Comment by martinet101** [comment]
OK, I'll fix it asap

**Comment by martinet101** [comment]
For the moment, install 2.11, it won't auto-update

**Comment by fabieu** [comment]
> https://bit.ly/3pgkAj7 fatal error with the latest build

Same here

**Comment by moeilijk** [comment]
Running the default windows theme so I think so

**Comment by martinet101** [comment]
Ok, nice then :)
