### ISSUE TITLE
[FEATURE REQUEST] Adjust position

### ISSUE THREAD

**Issue by hellzalien** [martinet101/ElevenClock#135]
With Win11 busting up the task bar using a round-a-bout way to make the taskbar small (like win10) makes the date/time shifted too far down and is cut off. 

Being able to set a X/Y position with your program would allow a round-a-bout for a round-a-bout way to fix this issue. 

Thanks!

**Comment by TECHSPERT50** [comment]
@martinet101 I know what they mean to say. They set the taskbar to the small size in the registry editor, and Elevenclock appears to high, and large. They want an option to move the clock, using X/Y coordinates.
