### ISSUE TITLE
[BUG] Seconds showing on clock even when setting is disabled

### ISSUE THREAD

**Issue by hJdTzv7G** [martinet101/ElevenClock#137]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened
## Describe the bug
No matter whether or not the "Show seconds on the clock" setting is enabled, the seconds continue to show.

This happened for me on both versions 2.2 and 2.1.1. I haven't tried other versions.

## To Reproduce
1. Disable "Show seconds on the clock"
2. Observe that seconds still show
3. Repeatedly toggle this setting and seeing no change. (The Show date on the clock and Show time on the clock settings work for me though.)

## Expected behavior
The seconds should not show when "Show seconds on the clock" is disabled.

## Screenshots

![Screenshot 2021-10-17 201740](https://user-images.githubusercontent.com/40006136/137664141-47a644b7-5a33-43f8-a361-bf0a362be4d9.png)
![Screenshot 2021-10-17 201715](https://user-images.githubusercontent.com/40006136/137664142-e2eab769-e64d-4098-882f-1a6548ec40f3.png)
![Screenshot 2021-10-17 202345](https://user-images.githubusercontent.com/40006136/137664626-73789da4-f85e-4342-8dac-e7bb401e8827.png)
![Screenshot 2021-10-17 202327](https://user-images.githubusercontent.com/40006136/137664629-b45b7ae1-1bcd-4e50-8fb5-cf971825b910.png)

**Comment by martinet101** [comment]
The settings checkbox is ignored when seconds are enabled on system registry (see enable seconds in windows 10 Taskbar) or when seconds are present in the short date.

Please check both parameters and tell me it it has been fixed

**Comment by hJdTzv7G** [comment]
I checked for the ShowSecondsInSystemClock setting but it's not there. I checked my short date and don't see seconds. Attached is a screenshot of what I was requested to check, maybe I missed something?

![Screenshot 2021-10-18 210655](https://user-images.githubusercontent.com/40006136/137842240-7ea92276-30d6-4938-9419-bbab465f9399.png)

**Comment by martinet101** [comment]
Well, as far as I see, this tutorial has not the right registry path.

Try this one and make sure the DWORD does not exist:

https://www.google.com/amp/s/www.howtogeek.com/325096/how-to-make-windows-10s-taskbar-clock-display-seconds/amp/
