### ISSUE TITLE
Clock does not autohide with the taskbar like it should

### ISSUE THREAD

**Issue by mja00** [martinet101/ElevenClock#14]
I have my taskbar set to autohide because I prefer as much screen as possible. Sadly it looks like the clock remains onscreen even when the taskbar hides. 

Taskbar hidden
![image](https://user-images.githubusercontent.com/11252574/136152205-54679a57-7be6-4b85-b846-9461c0566fb2.png)
Taskbar shown
![image](https://user-images.githubusercontent.com/11252574/136152228-63d96b32-d5dc-4127-8f96-e93c1881763e.png)

Currently running version 1.5

**Comment by martinet101** [comment]
Coming in release 1.9
