### ISSUE TITLE
[BUG] Taking a screenshot with certain applications does not work as intended...

### ISSUE THREAD

**Issue by NorthernLawOfficial** [martinet101/ElevenClock#141]
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened

Unsure if this is an issue with other screenshot applications, however I use one called Lightshot, what is supposed to happen will be shown down below, when the screenshot application is currently being used, you cannot click anywhere on the screen that actually affects what is on the screen. Everything NOT selected in the screenshot box which you can change whenever, also will be shown in the video, is dimmed, except the ElevenClock on both monitors is not dimmed as it should be where as the Windows default clock is, other than it being annoying that ElevenClock doesn't get dimmed, that isn't the big issue, the big issue is it still allows you to interact with it, but it shouldn't when taking a screenshot, this not only prevents you from taking a screenshot or doing other options using this but also might make you accidentally click on the ElevenClock settings or something.

1. Download Lightshot, screenshotting software
2. Take a screenshot anywhere on the screen
3. See that ElevenClock does not dim like everything else on the monitors, and is also still interactable, unlike everything else on the monitors.

What should happen is like how it worked in Windows 10, and with the Windows 11 default clock. Upon taking a screenshot, everything OUTSIDE of your selected box is dimmed, EVERYTHING, regardless of if it is inside the box or not, is NOT interactable. So with Windows 10, the clocks on the side monitors would not be able to be pressed, and would dim, just like the main clock, and the rest of the screen

As you can see in the screenshot provided below, I have put in red boxes, all 3 clocks on all 3 monitors, the default Windows 11 one is dimmed,  and non interactable, however the ElevenClock ones are NOT dimmed out, AND are also interactable, which prevents you from taking a screenshot that includes any part of that corner of the screen on both side monitors. Unfortunately I was unable to record a video as that would have been easier to show it, more so than a screenshot, but I think I got the point across pretty accurately, and it is very easily to reproduce so it shouldn't be a problem, please let me know if it is. 

![elevenclock bug thing](https://user-images.githubusercontent.com/92351169/137784722-5894456b-7309-44da-8e25-356273bf270b.png)

**Comment by martinet101** [comment]
I'm sorry, i can't really fix that, this has to be with z-indexes. You'll need to quit or hide ElevenClock while capturing (right-click ->Hide elevenclock), or use "Snip and Sketch" (which works for me).

I'm sorry though :(
