### ISSUE TITLE
[FEATURE REQUEST] Add weekday option

### ISSUE THREAD

**Issue by MiDniGG** [martinet101/ElevenClock#150]
**Is your feature request related to a problem? Please describe.**
In Windows 10 the weekday was visible when you increased the size of the taskbar.
Since I, at least 5 times a day, want to know, what weekday we have, I definitely need this feature back.

**Describe the solution you'd like**
If possible (remaining space and stuff) give the option to add the weekday (system language) to the clock.
I would prefer to see it between time and date. Other options would be before the date.
Maybe you can give different options like short (Mo) and long (Monday) or smth. like this...
Or you simply could take the "date (long)" option from region settings:
![image](https://user-images.githubusercontent.com/6615476/138086511-464b7e96-5d14-4ab0-8791-71f1b24b2b22.png)

**Comment by martinet101** [comment]
I'll take a look
