### ISSUE TITLE
Clock is missing an hour

### ISSUE THREAD

**Issue by artgru** [martinet101/ElevenClock#16]
![obraz](https://user-images.githubusercontent.com/37419387/136166397-412fd370-6de7-4e35-997d-010d37e3f5c7.png)
First installation.

**Comment by flabbert** [comment]
this was probably because you did same as me, you clicked on the link in the microsoft thread, which links to the 1.2 release, go to all releases and use 1.5, and it is fixed.

**Comment by artgru** [comment]
yes! I didn't see any version reference during the installation, so probably that was the cause! 
Thanks!
