### ISSUE TITLE
Clock shows on top of full screen applications

### ISSUE THREAD

**Issue by alanman87** [martinet101/ElevenClock#163]
The clock overlays on top of everything when a fullscreen app is in use on a secondary monitor.

Here's an example of a video playing in discord full screen.
![image](https://user-images.githubusercontent.com/28031959/138309015-d9f232aa-ed22-4b6f-b957-d1d6fca6ea88.png)

**Comment by moeilijk** [comment]
I agree with OP. I was about to submit a bug report for the clock being on top of the YouTube exit full screen button bottom right. Full screen applications should be exclusively full screen as default behavior. The clock overlaying a full screen application is a feature and should be a conscious setting in the application, not the other way around.
