### ISSUE TITLE
Clock shows %H:25 instead of 11:25

### ISSUE THREAD

**Issue by cmdrsamu** [martinet101/ElevenClock#17]
Having German default local settings the clock does show %H:25 instead of 11:25. Maybe there is an issue with not having AM/PM and 24 hour clock mode.
![image](https://user-images.githubusercontent.com/8345827/136176500-b476e813-3118-4b56-85a0-9a08854df2b2.png)

**Comment by flabbert** [comment]
check issue #16 this is a duplicate, until url has been updated in the microsoft thread

**Comment by cmdrsamu** [comment]
Yep that is exactly where I cam from and it is fixed with 1.5. Thank you for fast response!
