### ISSUE TITLE
[FEATURE REQUEST] Hide system clock on main display

### ISSUE THREAD

**Issue by dallinmoak** [martinet101/ElevenClock#194]
**Is your feature request related to a problem? Please describe.**
I found your (awesome) repo while looking into how to display seconds in the taskbar clock on windows 11. It would be cool to use this clock in place of the system clock, so that i can see seconds on my secondary display _and_ main display.  

**Describe the solution you'd like**
It would be super nice if, in addition to the feature you added in issue[#175](https://github.com/martinet101/ElevenClock/issues/175), i could use your clock in place of the system clock on the right side of the toolbar. 

![image](https://user-images.githubusercontent.com/32078384/139079147-f8f01972-7bb0-4c59-b847-420144de2a75.png)

**Comment by micachi** [comment]
Is it also difficult to specify a background color to obscure the original clock?

**Comment by martinet101** [comment]
Well' i'll try to implement solid backgrounds...
