### ISSUE TITLE
[BUG] Overflow not working

### ISSUE THREAD

**Issue by xasz** [martinet101/ElevenClock#196]
## Describe the bug
The clock does get above the icons when they reach the edge of the monitor.
![image](https://user-images.githubusercontent.com/1305196/139202092-cdb251fc-50e9-4336-b66c-13f9c20edd3e.png)
I am using a Pivot screen and the taskbar i quite short.
When i have alot of stuff open i cannot read the clock anymore and cannot click the apps, because icons get in the background.

## To Reproduce
1. Open alot of stuff :)

## Expected behavior
I think this is an edge case and i can think of 2 possible solutions:
1. The clock should disapear, when there is no space left to show it
2. The icons should stop before the clock

## Screenshots
![image](https://user-images.githubusercontent.com/1305196/139202516-19da948a-5ca1-496c-940d-ce6dacfc45dd.png)

## Additional context
Btw: the overflow of the icons in W11 does s**k anyway. I think there will be a change on this at some point by microsoft.
On my Pivot if i open more stuff than the taskbar can display it just stops showing them, there is (at least i have not found a way) no way to show all open apps like in a dropdown

**Comment by Moonwink** [comment]
![ElevenClock](https://user-images.githubusercontent.com/96207744/147495153-30c3dfcb-35b5-4a31-ba75-957292b29169.jpg)
I'd love to be able to click on the icons under ElevenClock.

**Comment by martinet101** [comment]
That would be difficult... I guess I'd need to make ElevenClock clicable through, but that would need to be an optional feature...

Il'' take a look

**Comment by martinet101** [comment]
Cehck out #417

**Comment by Moonwink** [comment]
I’m no programmer so I can’t help there.  Would it be possible to allow raising it up instead if sitting in the lower right hand corner?

 

Thanks for this utility.  I can’t believe MS screws up so much with every update.

Don

**Comment by martinet101** [comment]
It was a feature request (#379 i think)

**Comment by Moonwink** [comment]
What if?  What if when I clicked on the time/date and it opens the calendar it would blank the time/date and let me click on the icons underneath?  Is something like that possible?

**Comment by martinet101** [comment]
Yes, it could be someting like this: after clicking it hides during 10 seconds? (obviously an optional feature)

**Comment by Moonwink** [comment]
That would work!

**Comment by martinet101** [comment]
An option is going to be added to hide the clock during 10s after being clicked. It might help with the overflow issues
![image](https://user-images.githubusercontent.com/53119851/147821562-f44ab86c-d709-419e-b822-cc91510ed30e.png)
Coming with the next version!
