### ISSUE TITLE
Taskbar at top, clock at bottom

### ISSUE THREAD

**Issue by Kaev** [martinet101/ElevenClock#2]
When you configure your OS to show the taskbar at the top of your desktop (currently only doable via regedit changes in Win11... why?!), the clock still gets shown at the bottom right corner.

**Comment by martinet101** [comment]
I am aware of  this problem and I am imprementing a fix, but thanks for letting me know ;)

**Comment by martinet101** [comment]
The fix will be shipped with the next version on Elevenclock
