### ISSUE TITLE
Clicking on the clock and then on the taskbar flashes the clock

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#20]
**Describe the bug**
Clicking on the clock and then on the taskbar flashes the clock

**To Reproduce**
1. Click on the clock
2. Click on the taskbar

**Expected behavior**
For the clock to not flash

**Screenshots**
Video: https://i.imgur.com/qc2dkjr.gifv

**Comment by MaxJW** [comment]
No worries at all, thank you so much for the explanation, I appreciate it!
