### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by BWar81** [martinet101/ElevenClock#200]
Whenever I try and install this (either via winget or downloaded EXE) I get an access denied error. Have tried with command prompt run as administrator and the same with the exe, any ideas?

![image](https://user-images.githubusercontent.com/42467373/139333163-4f458cea-e523-47b7-bd13-8e363b7f911b.png)

**Comment by martinet101** [comment]
Try disabling your anti-virus or Anti-Malware and whitelisting ElevenClock

**Comment by martinet101** [comment]
Did that help?
