### ISSUE TITLE
[ISSUE] ElevenClock getting flagged as virus by McAfee

### ISSUE THREAD

**Issue by Seeloewen** [martinet101/ElevenClock#201]
For some reason every now and then my McAfee decides to just uninstall the software because it's getting flagged as a virus. Is there any way to fix this? It's really ennoying to reinstall the software every 5 minutes.

**Comment by martinet101** [comment]
You will need to whitelist ElevenClock

**Comment by martinet101** [comment]
See #140, this is a duplicate
