### ISSUE TITLE
[FEATURE REQUEST] Ability to center the clock above the date

### ISSUE THREAD

**Issue by ZomeDash** [martinet101/ElevenClock#203]
In Windows 10, the time was centered above the date, however this has been removed in Windows 11, I was wondering if it'd be possible to have the time centered above the date on both the main clock thats there by default, and the ones the program adds.

**Comment by martinet101** [comment]
Yes, i could do that. I'll take a look

**Comment by martinet101** [comment]
This will go more long-term, because it will be more difficult than what I thought

**Comment by martinet101** [comment]
Done, coming with next version
