### ISSUE TITLE
[FEATURE REQUEST] Only update when inactive

### ISSUE THREAD

**Issue by panaris** [martinet101/ElevenClock#206]
**Is your feature request related to a problem? Please describe.**
Elevenclock minimized my fullscreen game to update itself.

**Describe the solution you'd like**
Just add a task to the sheduler to run the updater only when inactivity is detected.

**Comment by martinet101** [comment]
Do you have silent updates enabled?

**Comment by panaris** [comment]
yes

**Comment by martinet101** [comment]
Then I'll try to reproduce the issue

**Comment by panaris** [comment]
https://bit.ly/3jW5kUS
Also greek letter Τ always overlaps the next letter.

**Comment by martinet101** [comment]
> https://bit.ly/3jW5kUS Also greek letter Τ always overlaps the next letter.

Hi @panaris , this happens due to a  qt bug with variable font kernings.

**Comment by martinet101** [comment]
I'll add a mechanism to detect move mouse if updates are set to silent, to prevent Elevenclock from updating if user is moving the mouse

**Comment by panaris** [comment]
or you can separate the updater from the main program (like settings) and use the windows task scheduler which already has this feature.
