### ISSUE TITLE
[BUG] Debugging information reports system is Win 10

### ISSUE THREAD

**Issue by Senectus** [martinet101/ElevenClock#209]
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
## Describe the bug
Debugging information reports system is Win 10

## To Reproduce
right click ElevenClock and choose settings
scroll to bottom.

## Expected behavior
should say "Windows 11" ;-) 

## Screenshots

![image](https://user-images.githubusercontent.com/15642668/139563175-52b040b4-8dfe-4f7f-b060-62890b8aa70d.png)

**Comment by brucetony** [comment]
This is an issue with the `platform` library. There are currently working on it: https://bugs.python.org/issue45382

**Comment by martinet101** [comment]
Anyway, I'll add a check if build number is greater or equal to 22000

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/139593489-5fb1f2d1-89de-4ccc-8c58-dd1b1c1c14f0.png)
