### ISSUE TITLE
[FEATURE REQUEST] Hide clock on only the screen citrix is fullscreened on

### ISSUE THREAD

**Issue by TheInvoker** [martinet101/ElevenClock#212]
**Is your feature request related to a problem? Please describe.**
I'm on windows 11, and the task bar icons are centered aligned, and I prefer to show the clock on the left side. However in my citrix, it is windows 10 where the icons are left aligned. The clock then overlaps on the start menu icon as a result in the citrix. 

**Describe the solution you'd like**
An option to hide the clock on only the monitors that the citrix is running on in full screen. Right now, all the clocks go away when I go into citrix, but citrix only runs on 1 of my 3 monitors and I want to still see the clock on the other 2.

**Comment by martinet101** [comment]
Will be difficult, but I'll try it

**Comment by martinet101** [comment]
Because this issue is related with #228 and other ones, i'll move that to Issue #229
