### ISSUE TITLE
[BUG] Text cut off in debbugging information when language is zh_TW

### ISSUE THREAD

**Issue by mmis1000** [martinet101/ElevenClock#214]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
## Describe the bug
The last line in debugging information has been cut off from bottom.

## To Reproduce
1. Set the language to `Chinese Traditional (taiwan)`
2. Open setting page

## Expected behavior
The text displays properly

## Screenshots
![圖片](https://user-images.githubusercontent.com/2993977/139586543-c82379f9-e456-438d-9147-d900429e9051.png)

**Comment by martinet101** [comment]
Done!
