### ISSUE TITLE
[FEATURE REQUEST] Font

### ISSUE THREAD

**Issue by szalmaarpad56** [martinet101/ElevenClock#215]
It would be nice if we can change font in the application.

**Comment by martinet101** [comment]
Are you having issues with the current font or it is just for customization?

**Comment by szalmaarpad56** [comment]
It's just for the customization,beacuse its make the app better if we can change font on the clock,and it will look much better with some fonts.Sorry if my english is a bit bad.

**Comment by Tommasov** [comment]
> Are you having issues with the current font or it is just for customization?

Hi! Actually in my system the font looks different from the OS default (Screenshot attached)
![Main monitor](https://user-images.githubusercontent.com/9279914/140564754-3642e063-598a-4d6c-a961-73ef389f6c8a.png)
![Secondary monitor](https://user-images.githubusercontent.com/9279914/140564758-bca697d5-8222-44b5-a219-3d4b1318ff1f.png)
d)

**Comment by martinet101** [comment]
Hi @Tommasov, i'm fixing this on version 2.6

Old:
![image](https://user-images.githubusercontent.com/53119851/140566482-dfc99477-e6fa-45f7-92f9-6802ad6f6b4c.png)
New:
![image](https://user-images.githubusercontent.com/53119851/140566574-4928c3b3-2724-4b09-8c1c-af8c8289533c.png)
Windows 11's:
![image](https://user-images.githubusercontent.com/53119851/140566638-d116a324-dbc7-471c-8ff4-4a96c571320f.png)

**Comment by Tommasov** [comment]
> Hi @Tommasov, i'm fixing this on version 2.6
> 
> Old: ![image](https://user-images.githubusercontent.com/53119851/140566482-dfc99477-e6fa-45f7-92f9-6802ad6f6b4c.png) New: ![image](https://user-images.githubusercontent.com/53119851/140566574-4928c3b3-2724-4b09-8c1c-af8c8289533c.png) Windows 11's: ![image](https://user-images.githubusercontent.com/53119851/140566638-d116a324-dbc7-471c-8ff4-4a96c571320f.png)

Thank you for the awesome work you're doing

**Comment by jonnyka** [comment]
Hey, first of all, huge thanks man!
Second, can we have a font size change function? My primary monitor is an ultrawide, secondary is fullHD, and the font size is too small there.

thanks!

**Comment by martinet101** [comment]
There you go, coming with the next version:

![image](https://user-images.githubusercontent.com/53119851/141690805-a14d3c80-57fe-4121-b91e-99b1c13f6d72.png)
