### ISSUE TITLE
[FEATURE REQUEST] Default Hide the clock in fullscreen mode to "on"

### ISSUE THREAD

**Issue by moeilijk** [martinet101/ElevenClock#216]
**Is your feature request related to a problem? Please describe.**
Or probably better to reverse the functionality and make it "Force the clock in fullscreen mode" and default it to "off" 
As responded on issue #163 and referenced in  #155 #197 
https://github.com/martinet101/ElevenClock/issues/163#issuecomment-955680304
With multiple issues reported it seems people find it unexpected behavior.

**Describe the solution you'd like**
You could keep telling everybody to read the FAQ or documentation but expected behavior from applications is to not overlay on full screen applications by default. The idea of full screen is that no other applications interfere. If I want an application to overlay on another full screen application I'd take the time to look at the settings.

**Comment by martinet101** [comment]
OK, you are actually right.

I'll do that

**Comment by Bhaalspawn** [comment]
what i don't like is that after exit the fullscreen mode there is a short time that the clock is not there and appears just a bit later. sometimes it's very fast sometimes around 1s later.
I hope that reversing this feature (default hidden and option to make it visibile in fullscreen) can change this behavior

**Comment by martinet101** [comment]
Done!
