### ISSUE TITLE
[FEATURE REQUEST] Set clock position for every individual clock

### ISSUE THREAD

**Issue by Reaver01** [martinet101/ElevenClock#217]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Option to move the position of the clock on individual monitors. having 3 monitors it would be nice to have the clock on the right on the left one and on the left on the right one.

**Comment by martinet101** [comment]
This is a difficult one, but anyway it could be done

It is a long term feature though

**Comment by martinet101** [comment]
I'm sorry, but its really complicated to implement that
