### ISSUE TITLE
[FEATURE REQUEST] Brief description

### ISSUE THREAD

**Issue by erivlis** [martinet101/ElevenClock#218]
**Is your feature request related to a problem? Please describe.**
I'm using _[VMware Horizon Client](https://customerconnect.vmware.com/en/downloads/info/slug/desktop_end_user_computing/vmware_horizon_clients/horizon_8)_  to connect to a remote computer. Essentially a type of full-screen remote client.

**Describe the solution you'd like**
Hide the clock. Similar to the functionality you give for hiding the clock when using _RDP_ or _Citrix Clients_.
Perhaps even open this to user configuration somehow. A user could maintain a "blacklist" of applications that when running in full-screen cause the clock to be hidden.

**Comment by martinet101** [comment]
Yes, I was planning something like that. Could you please tell me the process name of VMWare Horizon Client?

**Comment by JamesBulman** [comment]
I am having this issue as well.

The process name is vmware-view.exe.

Screenshot of it happening https://imgur.com/a/E2Y7gHh

**Comment by martinet101** [comment]
Fixed, coming in 2.6

**Comment by erivlis** [comment]
Thanks!
