### ISSUE TITLE
Cuts into other screen

### ISSUE THREAD

**Issue by terran5151** [martinet101/ElevenClock#22]
With this installed on the other monitor the date cuts off onto my main screen. 

![image](https://user-images.githubusercontent.com/88588091/136465702-e4d1f3f5-fd4e-481a-b2fa-d7994ec394c4.png)

![image](https://user-images.githubusercontent.com/88588091/136465727-00276509-fb96-4d5a-bfc2-9585cb6e9573.png)

![image](https://user-images.githubusercontent.com/88588091/136465746-e46b5410-44bb-442d-a11d-4c4e836c9d1e.png)

Is it because I have the day of the week next to the my date? Any fix?

**Comment by terran5151** [comment]
Ok I fiddled around with the date / time and it's not overlapping now but it is showing this 

![image](https://user-images.githubusercontent.com/88588091/136466782-11a649a6-89b3-4e9d-98df-f191d3307006.png)

This is my main screens config 

![image](https://user-images.githubusercontent.com/88588091/136466796-fd28a37e-9f25-458c-896b-bd5cb4ad17c8.png)

**Comment by martinet101** [comment]
This is a spacing problem. I'll fix it asap

**Comment by martinet101** [comment]
Coming in release 1.8
