### ISSUE TITLE
[BUG] Clock incorrect placement on display disconnect

### ISSUE THREAD

**Issue by kwiksilver3441** [martinet101/ElevenClock#220]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
## To Reproduce
Disconnect a monitor. I use 3.
Elevenclock will display over the default clock on main screen
Plugging in a new monitor will not solve the issue. 
Plugging in a new display will not cause elevenclock to reset, therefore it will not contain a copy of the clock

## Expected behavior
On monitor disconnect/reconnect, have it update and display to correct position.

## Screenshots
![image](https://user-images.githubusercontent.com/31498096/139710250-e96ca312-e1df-490d-9fd2-5cf34a9ae869.png)
![image](https://user-images.githubusercontent.com/31498096/139710291-74beac2e-0ba2-448f-866c-c6dad0c28013.png)

## Additional context
Opening elevenclock application will reset all clocks to correct position

**Comment by martinet101** [comment]
Could you please send me the log? (go to settings, scroll to the bottom and click on open log)

**Comment by wrufeger** [comment]
still have the same problem, answered already on closed ticket, but no answer:

---------------------------------------------------------------------------------------------------

   ElevenClock's v2.5 log: Select all the text and hit Ctrl+C to copy it

---------------------------------------------------------------------------------------------------




de
NullColor
['238,215,183', '215,182,152', '179,123,92', '160,102,75', '134,80,59', '102,51,38', '65,18,14', '136,23,152']
Starting update check
62.19921875
<PySide2.QtGui.QScreen(0x1eb9b014170, name="\\\\.\\DISPLAY9") at 0x000001EB9B9F5CC0> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x1eb9b014530, name="\\\\.\\DISPLAY11") at 0x000001EBA2A85F80> PySide2.QtCore.QRect(-3840, 0, 3840, 2160) (3840, 2160, -3840, 0, 144.0, 144.0)
[WinError 259] Es sind keine Daten mehr verfügbar
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-237, 2088, 225, 72)
Full screen rect:  (-3840, 0, 0, 2160)
<PySide2.QtGui.QScreen(0x1eb9b014610, name="\\\\.\\DISPLAY10") at 0x000001EBA2A85E00> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(7443, 2088, 225, 72)
Full screen rect:  (3840, 0, 7680, 2160)
screenCheckThread
Restart loop: 1
updates not found
480
NullColor
['238,215,183', '215,182,152', '179,123,92', '160,102,75', '134,80,59', '102,51,38', '65,18,14', '136,23,152']

**Comment by karth06** [comment]
Even i have the same issue, please refer the below screenshot,
![eleven-clock-issue](https://user-images.githubusercontent.com/11913452/140006857-c9d88527-9183-49e8-8dd8-7fbdac450a10.jpg)

**Comment by Bhaalspawn** [comment]
i have a similar problem, i don't know if i have to open a new issue

I use 2 monitors. When i turn one off and then on again, the clock doesn't appear, it's gone and i have to restart the app manually
no overlapping or bad position, just no clock

**Comment by wrufeger** [comment]
another log, after this happened:

de
NullColor
['238,215,183', '215,182,152', '179,123,92', '160,102,75', '134,80,59', '102,51,38', '65,18,14', '136,23,152']
Starting update check
[WinError 259] Es sind keine Daten mehr verfügbar
62.8828125
<PySide2.QtGui.QScreen(0x1c142e8a700, name="\\\\.\\DISPLAY9") at 0x000001C143845CC0> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x1c142e8a7a0, name="\\\\.\\DISPLAY10") at 0x000001C1438A6480> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(7443, 2088, 225, 72)
Full screen rect:  (3840, 0, 7680, 2160)
<PySide2.QtGui.QScreen(0x1c142e8a100, name="\\\\.\\DISPLAY11") at 0x000001C1438A9940> PySide2.QtCore.QRect(-3840, 0, 3840, 2160) (3840, 2160, -3840, 0, 144.0, 144.0)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-237, 2088, 225, 72)
Full screen rect:  (-3840, 0, 0, 2160)
screenCheckThread
Restart loop: 1
updates not found
Starting update check
updates not found
Starting update check
updates not found
[<PySide2.QtGui.QScreen(0x1c142e8a700, name="\\\\.\\DISPLAY9") at 0x000001C143845CC0>, <PySide2.QtGui.QScreen(0x1c142e8a100, name="\\\\.\\DISPLAY11") at 0x000001C1438A9940>] [(3840, 2160, 0, 0, 144.0, 144.0), (3840, 2160, 3840, 0, 144.0, 144.0), (3840, 2160, -3840, 0, 144.0, 144.0)]
checkLoop
close
close
49.33203125
<PySide2.QtGui.QScreen(0x1c142e8a700, name="\\\\.\\DISPLAY9") at 0x000001C143845CC0> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x1c142e8a100, name="\\\\.\\DISPLAY11") at 0x000001C1438A9940> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(3603, 2088, 225, 72)
Restart loop: 1
Full screen rect:  (0, 0, 3840, 2160)
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)
screenCheckThread
[WinError 259] Es sind keine Daten mehr verfügbar
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)

...

131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)
Starting update check
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)
updates not found
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)

...

131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)
NullColor
['238,215,183', '215,182,152', '179,123,92', '160,102,75', '134,80,59', '102,51,38', '65,18,14', '136,23,152']
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)
131308 Windows-Eingabeerfahrung (0, 0, 3840, 2160) (0, 0, 3840, 2160)

**Comment by martinet101** [comment]
ok, this should be fixed now, since i updated to Qt6, which (At least for me) did the trick. Please make syer to repoen the issue if this does not get solved in v2.6
