### ISSUE TITLE
[FEATURE REQUEST] Hide tray icon

### ISSUE THREAD

**Issue by Bhaalspawn** [martinet101/ElevenClock#225]
Just give the chance to hide the tray icon tha appears on the primary monitor
I would hide it in any case but that icon at the moment is useless..right click does nothing (no menu)

**Comment by martinet101** [comment]
Mhmm... right clocking the icon tray should open a menu, and clicking the tray should reload the clocks. Anyway, there's a setting in the settings window to hide the icon

**Comment by martinet101** [comment]
Did that help?

**Comment by Bhaalspawn** [comment]
i confirm that right clicking the icon does nothing to me, only right clicking the clock shows the menu (and it's not accurate because even clicking more than 1cm on the left of che clock show the menu)

i can't find the option the settings i have. where should it be? Appearance? General?

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/139925174-0a7ee428-0a46-466f-9580-02e48ecdaaf5.png)

**Comment by Bhaalspawn** [comment]
but i thought that was to show the clock, there is no mention to ElevenClock ICON...... ok

**Comment by martinet101** [comment]
Well, i thought it made sense... Anyway, i'll modify the text to make it more clear
