### ISSUE TITLE
[FEATURE REQUEST] Hide the clock when RDP Client window is currently active (not just running)

### ISSUE THREAD

**Issue by hybrid2102** [martinet101/ElevenClock#228]
Would be very useful to hide the clock only when the RDP Client window is currently active.
The current setting just checks if the client is running, causing the clock to be invisible even when the RDP Client window is minimized.

BTW, awesome project, keep up the good work!

**Comment by martinet101** [comment]
Because this issue is related with #212 and other ones, i'll move that to Issue https://github.com/martinet101/ElevenClock/issues/229
