### ISSUE TITLE
[FEATURE REQUEST] Hide clock if a window is over it

### ISSUE THREAD

**Issue by martinet101** [martinet101/ElevenClock#229]
**Is your feature request related to a problem? Please describe.**
RDP, Citrix Workspace and VMWare Horizon: Hide only if window is over clock
**Describe the solution you'd like**
Detech whether a window is over the clock instead of detecting if a process name is running.

This feature request has to be with #212 and #228

**Comment by martinet101** [comment]
@TheInvoker, @hybrid2102, the issue you were facing is going to be maintained here

**Comment by Fachep** [comment]
just now i capture a screenshot, the clock displayed upon my capture software
![image](https://user-images.githubusercontent.com/31302548/140299226-8620dab3-0bb1-4be5-a32d-85f0dc67158a.png)
and it's clickable

**Comment by martinet101** [comment]
This has been fixed and will be released with 2.6
