### ISSUE TITLE
[FEATURE REQUEST] Publish this app on the Microsoft Store

### ISSUE THREAD

**Issue by zchilds** [martinet101/ElevenClock#230]
**Is your feature request related to a problem? Please describe.**
N/a

**Describe the solution you'd like**
Submit this app to the Microsoft Store for easy installation.
- https://docs.microsoft.com/en-us/windows/uwp/publish/
- https://aka.ms/storepreviewwaitlist

Thanks!

**Comment by martinet101** [comment]
Sent the request, now we only have to wait!!!

![image](https://user-images.githubusercontent.com/53119851/140162627-43843d4a-d463-4d57-ab0b-772c38ea9521.png)

**Comment by martinet101** [comment]
Just have to wait, can't do more about it

**Comment by martinet101** [comment]
Just to let you know, they have answered:

![image](https://user-images.githubusercontent.com/53119851/140941330-442bfa74-ccb3-4dde-8bc8-116a94d8b3db.png)

Just have to wait!

**Comment by martinet101** [comment]
I have been accepted. I only have to regiester myself as a dev and i'll be able to publish it!!!

![image](https://user-images.githubusercontent.com/53119851/141829617-42c4b42f-da98-4bfc-aaae-5e5298acc90b.png)

**Comment by JohnLGalt** [comment]
Great news!  'Gratz!

**Comment by martinet101** [comment]
Almost there!!!
![image](https://user-images.githubusercontent.com/53119851/142004782-022247e0-df54-4ad9-9977-e5e98b533eb1.png)

**Comment by martinet101** [comment]
https://somepythonthings.tk/redirect/?elevenclockstore

Install from ms store

**Comment by zchilds** [comment]
Nice work! Thank you. Gave you 5 stars on the store.
