### ISSUE TITLE
[BUG] Font error when using Chinese Character languages

### ISSUE THREAD

**Issue by Fachep** [martinet101/ElevenClock#231]
The clock text seems to change with application language:
when using alphabet languages like english:
![image](https://user-images.githubusercontent.com/31302548/140297903-a4cf08e6-ba8f-42d8-99ad-ad70393de38c.png)
but when chinese(tw):
![image](https://user-images.githubusercontent.com/31302548/140298020-4f44e022-8c5e-4b19-8cc0-78287b91e6de.png)

**Comment by martinet101** [comment]
yes, because chinese windows uses different fonts. check https://github.com/martinet101/ElevenClock/pull/199
