### ISSUE TITLE
[FEATURE REQUEST] Show desktop button

### ISSUE THREAD

**Issue by u4human** [martinet101/ElevenClock#233]
I want show desktop button to sub monitor 

What do you think?

**Comment by martinet101** [comment]
Yes, this cloud be perfectly a feature

**Comment by martinet101** [comment]
Gonna take a look at it and try to imlpement it

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/140579813-46d3d0ff-1dd3-4f59-9a68-8ece1781b6da.png)

**Comment by martinet101** [comment]
Coming in v2.6

**Comment by u4human** [comment]
thank you bro,
