### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by radische** [martinet101/ElevenClock#234]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 mintues, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by radische** [comment]
I have added the .dll file from Explorer Patcher to enable the Windows 10 taskbar in Windows 11. I found that the new taskbar has no clock, so I installed your ElevenClock to get a clock on the only taskbar I have. ElevenClock installs, but I still have no clock on the taskbar.

**Comment by martinet101** [comment]
Try Enabling "Show clock on first taskbar"
![image](https://user-images.githubusercontent.com/53119851/140412722-c8757879-8841-4f6e-85b8-94691018f7ad.png)
Did it help?

**Comment by radische** [comment]
It worked! Thanks. 

 
 

Sent: Thursday, November 04, 2021 at 1:12 PM
