### ISSUE TITLE
[BUG] ElevenClock not updating (SSL: Certificate_verify_failed)

### ISSUE THREAD

**Issue by Thorandor** [martinet101/ElevenClock#235]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening

## Describe the bug
I am currently on 2.4 and have only just realised that 2.5 has been released (I was off for a week). My machine however did not update, despite the following options being ticked:

- Automatically check for updates
- Automatically install available updates

## To Reproduce
1. Try to update, you will see the following in the log:
`Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>`

## Expected behavior
ElevenClock should update / the SSL cert should be verifyable

## The Log
`en
NullColor
NullColor
['215,226,228', '160,174,183', '101,116,134', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']
Starting update check
start RDP thread
60.80859375
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x17c43dc9040, name="\\\\.\\DISPLAY2") at 0x0000017C497EC100> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
[WinError 259] No more data is available
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(7443, 2088, 225, 72)
Full screen rect:  (3840, 0, 7680, 2160)
screenCheckThread
Restart loop: 1
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
NullColor
NullColor
['215,226,228', '160,174,183', '101,116,134', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
[<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80>] [(3840, 2160, 0, 0, 144.0, 144.0), (3840, 2160, 3840, 0, 144.0, 144.0)]
checkLoop
close
89.16015625
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80>, <PySide2.QtGui.QScreen(0x17c443a5580, name="\\\\.\\DISPLAY2") at 0x0000017C49815E00>] [(3840, 2160, 0, 0, 144.0, 144.0)]
checkLoop
89.17578125
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x17c443a5580, name="\\\\.\\DISPLAY2") at 0x0000017C4470CB00> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(7443, 2088, 225, 72)
Restart loop: 1
Full screen rect:  (3840, 0, 7680, 2160)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
[<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80>] [(3840, 2160, 0, 0, 144.0, 144.0), (3840, 2160, 3840, 0, 144.0, 144.0)]
checkLoop
close
91.57421875
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80>, <PySide2.QtGui.QScreen(0x17c443cd730, name="\\\\.\\DISPLAY2") at 0x0000017C44771780>] [(3840, 2160, 0, 0, 144.0, 144.0)]
checkLoop
91.546875
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x17c443cd730, name="\\\\.\\DISPLAY2") at 0x0000017C44776500> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(7443, 2088, 225, 72)
Restart loop: 1
Full screen rect:  (3840, 0, 7680, 2160)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
[<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80>] [(3840, 2160, 0, 0, 144.0, 144.0), (3840, 2160, 3840, 0, 144.0, 144.0)]
checkLoop
close
91.4140625
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80>, <PySide2.QtGui.QScreen(0x17c44373930, name="\\\\.\\DISPLAY2") at 0x0000017C44785100>] [(3840, 2160, 0, 0, 144.0, 144.0)]
checkLoop
91.41015625
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x17c44373930, name="\\\\.\\DISPLAY2") at 0x0000017C49815600> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(7443, 2088, 225, 72)
Full screen rect:  (3840, 0, 7680, 2160)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
[<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80>] [(3840, 2160, 0, 0, 144.0, 144.0), (3840, 2160, 3840, 0, 144.0, 144.0)]
checkLoop
close
91.62890625
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
[<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80>, <PySide2.QtGui.QScreen(0x17c4415bb10, name="\\\\.\\DISPLAY2") at 0x0000017C497E7B00>] [(3840, 2160, 0, 0, 144.0, 144.0)]
checkLoop
91.5859375
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x17c4415bb10, name="\\\\.\\DISPLAY2") at 0x0000017C497E7B00> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(7443, 2088, 225, 72)
Restart loop: 1
Full screen rect:  (3840, 0, 7680, 2160)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Starting update check
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

close
61.37890625
<PySide2.QtGui.QScreen(0x17c43dc9580, name="\\\\.\\DISPLAY1") at 0x0000017C44704A80> PySide2.QtCore.QRect(0, 0, 3840, 2160) (3840, 2160, 0, 0, 144.0, 144.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x17c4415bb10, name="\\\\.\\DISPLAY2") at 0x0000017C497E7B00> PySide2.QtCore.QRect(3840, 0, 3840, 2160) (3840, 2160, 3840, 0, 144.0, 144.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(7443, 2088, 225, 72)
Full screen rect:  (3840, 0, 7680, 2160)
screenCheckThread
[WinError 259] No more data is available
start RDP thread
Restart loop: 1
NullColor
NullColor
['215,226,228', '160,174,183', '101,116,134', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']
`

**Comment by martinet101** [comment]
For me it seems to work, anyway, how did you get the log? In theory there's no log option in version 2.4...

Could you try it again? There might have been some certificate issue with cloudflare.

**Comment by Thorandor** [comment]
Interestingly, I did provide you a log from my laptop, which my wife already manually updated to 2.5, I can only apologise for that. However, my main PC is still on 2.4, and I am not seeinf any update notifications or otherwise.

Can I somehow get a lot from that over to you?

**Comment by martinet101** [comment]
Could you try accessing those webs from your browser?. Also, in which country are you? (Bc they may be issues with the certificates on that zone)
  - https://versions.somepythonthings.tk/versions/elevenclock.ver
  - https://www.somepythonthings.tk/versions/elevenclock.ver
  - https://github.com/martinet101/ElevenClock/releases/download/2.5/ElevenClock.Installer.exe

**Comment by Thorandor** [comment]
Link1 :
`2.5
///
NO URL
///
D8AACB34FC1581B18A6369D7A1F7056A7D032A738880FACBF9375581FD83469A`

Link 2:
`2.5
///
https://github.com/martinet101/ElevenClock/releases/download/2.5/ElevenClock.Installer.exe
///
D8AACB34FC1581B18A6369D7A1F7056A7D032A738880FACBF9375581FD83469A`

Link 3: download starts

I am in the UK

**Comment by martinet101** [comment]
Before this update, ElevenClock updated automatically everytime?

**Comment by Thorandor** [comment]
No, not once.

**Comment by martinet101** [comment]
Ok, i can't really figure out why is this happening, but i'll add a switch to enable http-only downloads on next version. I'll let you know when i launch it.

**Comment by Thorandor** [comment]
Cheers buddy, please let me know if you need me to help test anything.

**Comment by martinet101** [comment]
Could you try installing version 1.8 and see if it does update?

**Comment by martinet101** [comment]
It is because i introduced a server change in 1.9, which could potentially cause this error.

Here the link: https://github.com/martinet101/ElevenClock/releases/download/1.8/ElevenClock.Installer.exe

**Comment by Thorandor** [comment]
Yes, 1.8 worked for me: 

1. Uninstalled 2.4
2. Installed 1.8
3. Confirmed ElvenClock was running
4. I noted two EC clocks in the systray, clicked on one
5. ElevenClock installer window opened and it updated
6. I'm now on 2.5

**Comment by martinet101** [comment]
Ok, then the fix i impkemented will work. I'll nlet you know when i release 2.6, but it will include an option to use old update server.
![image](https://user-images.githubusercontent.com/53119851/140640629-d2c34268-0e4c-4415-983f-df3dceb2bc71.png)

**Comment by martinet101** [comment]
2.6 has been released. Update manually and check "Alternative update server" in the settings

**Comment by Thorandor** [comment]
Downloaded and installed. Let's see what happens when 2.7 is out to then test :)
