### ISSUE TITLE
[BUG] Clock Position

### ISSUE THREAD

**Issue by Arclight25** [martinet101/ElevenClock#237]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
Position of the clock on the 2nd screen is off.

## To Reproduce
This happens every time the program runs

## Expected behavior
**positioning of clock on 2nd screen has been shift down and to the right with the latest update.....**

## Screenshots
If applicable, add screenshots to help explain
![Untitled](https://user-images.githubusercontent.com/91793198/140644510-6e3386cf-fb93-4cea-8602-9277f050c90b.jpg)
 your problem.

## The Log

---------------------------------------------------------------------------------------------------

   ElevenClock's v2.6 log: Select all the text and hit Ctrl+C to copy it

---------------------------------------------------------------------------------------------------

en
NullColor
['237,217,196', '212,184,164', '171,126,105', '153,105,86', '128,82,67', '96,53,43', '60,19,15', '136,23,152']
Starting update check
67.171875
<PySide6.QtGui.QScreen(0x22018bf8dc0, name="\\\\.\\DISPLAY1") at 0x00000220194DE740> PySide6.QtCore.QRect(0, 0, 2560, 1440) (2560, 1440, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide6.QtGui.QScreen(0x22018bf9100, name="\\\\.\\DISPLAY8") at 0x000002201C254480> PySide6.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide6.QtCore.QRect(-150, 1032, 150, 48)
[WinError 259] No more data is available
Restart loop: 1
Full screen rect:  (-1920, 0, 0, 1080)
[WinError 259] No more data is available
screenCheckThread
Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
updates not found

close
75.94140625
<PySide6.QtGui.QScreen(0x22018bf8dc0, name="\\\\.\\DISPLAY1") at 0x00000220194DE740> PySide6.QtCore.QRect(0, 0, 2560, 1440) (2560, 1440, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide6.QtGui.QScreen(0x22018bf9100, name="\\\\.\\DISPLAY8") at 0x000002201C254480> PySide6.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide6.QtCore.QRect(-150, 1032, 150, 48)
[WinError 259] No more data is available
Full screen rect:  (-1920, 0, 0, 1080)
[WinError 259] No more data is available
screenCheckThread
[WinError 259] No more data is available
Restart loop: 1
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
['153,235,255', '76,194,255', '101,116,134', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']
[WinError 259] No more data is available
[WinError 259] No more data is available
[WinError 259] No more data is available

close
94.31640625
<PySide6.QtGui.QScreen(0x22018bf8dc0, name="\\\\.\\DISPLAY1") at 0x00000220194DE740> PySide6.QtCore.QRect(0, 0, 2560, 1440) (2560, 1440, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide6.QtGui.QScreen(0x22018bf9100, name="\\\\.\\DISPLAY8") at 0x000002201C254480> PySide6.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide6.QtCore.QRect(-150, 1032, 150, 48)
[WinError 259] No more data is available
Full screen rect:  (-1920, 0, 0, 1080)
[WinError 259] No more data is available
screenCheckThread
[WinError 259] No more data is available
Restart loop: 1
[WinError 259] No more data is available

close
94.4765625
<PySide6.QtGui.QScreen(0x22018bf8dc0, name="\\\\.\\DISPLAY1") at 0x00000220194DE740> PySide6.QtCore.QRect(0, 0, 2560, 1440) (2560, 1440, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide6.QtGui.QScreen(0x22018bf9100, name="\\\\.\\DISPLAY8") at 0x000002201C254480> PySide6.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide6.QtCore.QRect(-150, 1032, 150, 48)
[WinError 259] No more data is available
Full screen rect:  (-1920, 0, 0, 1080)
[WinError 259] No more data is available
screenCheckThread
[WinError 259] No more data is available
Restart loop: 1
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
['153,235,255', '76,194,255', '101,116,134', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']

**Comment by martinet101** [comment]
I'll investigate that, by the time, disable updates and install 2.5

**Comment by martinet101** [comment]
On the settings, under Experimental Features, toggling "Use alternative alignment" does something?

**Comment by Arclight25** [comment]
![Untitled2](https://user-images.githubusercontent.com/91793198/140647143-dbd5a4a5-7b03-48a2-88f1-111cdd5806eb.jpg)
yea...moves it from the second display (where it should be) to the desktop of the main display.  It also renders the taskbar icons unusable, as it is over the top of them.  Will install 2.5

**Comment by Arclight25** [comment]
![Untitled3](https://user-images.githubusercontent.com/91793198/140647589-f052c638-4239-40af-810d-346ae108d017.jpg)
2.5 restores positioning back to normal.

**Comment by martinet101** [comment]
Hi @Arclight25, which is the scaling of your display?

**Comment by martinet101** [comment]
Try running this one:
https://github.com/martinet101/ElevenClock/blob/main/ElevenClock-test2.exe?raw=true

**Comment by martinet101** [comment]
Please see https://github.com/martinet101/ElevenClock/releases/tag/2.6.1.

Download and install. If the issue has not been fixed there, please reopen this

**Comment by Arclight25** [comment]
look like that worked!  Thanks!
