### ISSUE TITLE
[BUG] Cant see clock on second monitor

### ISSUE THREAD

**Issue by mikusekdan** [martinet101/ElevenClock#242]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
with last update i was able to set clock on my second monitor, now there is not such a option. This is the main reason that i have instaled it into my PC..
Thank you

**Comment by martinet101** [comment]
Check issue #238

You'll need to disable updates and install version 2.5

**Comment by martinet101** [comment]
It is a duplicate
