### ISSUE TITLE
[BUG] clock shows up in the middle of my screen

### ISSUE THREAD

**Issue by TipsterTrickster** [martinet101/ElevenClock#243]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 mintues, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by TipsterTrickster** [comment]
The clock is showing in the middle of the screen on my right monitor, I tried using the alternative alignment, but then it just disappears, It works fine if I'm only using one display and I have the show on primary monitor selected, but as soon as I have the extend display option selected it goes right back to the middle.
![Screenshot (1)](https://user-images.githubusercontent.com/45155553/140657827-8b9b66fe-5ea4-4017-8b6c-4d40e9239569.png)

**Comment by IAmCrazyyy** [comment]
![PE4c](https://user-images.githubusercontent.com/34993338/140703438-79bbdfdc-0a8a-48cc-9a00-d6c88832b1be.png)
I have similar issue, using a laptop and second screen. One screen is 15"(left) and second one is 24"(right) I have offset set in windows for these 2 screens.

**Comment by martinet101** [comment]
@IAmCrazyyy , could you please send your log?

**Comment by sts950** [comment]
I'm also having this problem - seems to have stopped working over the weekend.  Prior to this update i had to use the "Alternate clock alignment" to have the time go to the correct location.  Now when i use this option the clock isn't visible.  When unchecked the click is in the middle of the primary monitor (exactly same position as the screen shot above.  I have attached me log file
[elevenclocklog.txt](https://github.com/martinet101/ElevenClock/files/7497826/elevenclocklog.txt)
.

**Comment by chrisowens517** [comment]
I'm having the same issue after running windows updates this morning
OS Name	Microsoft Windows 11 Pro for Workstations
Version	10.0.22000 Build 22000


![2021-11-08 12_04_50-Greenshot](https://user-images.githubusercontent.com/51752410/140786374-03bcd22b-59e2-4c1d-a271-a83482e2d8c5.png)


[ElevenClockLog.txt](https://github.com/martinet101/ElevenClock/files/7498740/ElevenClockLog.txt)

**Comment by IAmCrazyyy** [comment]
@martinet101 
---------------------------------------------------------------------------------------------------

   ElevenClock's v2.6 log: Select all the text and hit Ctrl+C to copy it

---------------------------------------------------------------------------------------------------




en
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
['255,147,112', '255,101,77', '255,18,17', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']
Starting update check
[WinError 259] No more data is available
63.609375
<PySide6.QtGui.QScreen(0x123426aadd0, name="\\\\.\\DISPLAY1") at 0x0000012342F1F6C0> PySide6.QtCore.QRect(0, 0, 1536, 864) (1536, 864, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide6.QtGui.QScreen(0x123426aa990, name="\\\\.\\DISPLAY4") at 0x00000123458A4440> PySide6.QtCore.QRect(1920, -332, 1920, 1080) (1920, 1080, 1920, -332, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide6.QtCore.QRect(3690, 700, 150, 48)
[WinError 259] No more data is available
Restart loop: 1
Full screen rect:  (1920, -332, 3840, 748)
[WinError 259] No more data is available
screenCheckThread
Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
updates not found
480
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
['255,147,112', '255,101,77', '255,18,17', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']

**Comment by martinet101** [comment]
Try running this one:
https://github.com/martinet101/ElevenClock/blob/main/ElevenClock-test2.exe?raw=true

**Comment by martinet101** [comment]
With version 2.5 does this happen?

**Comment by martinet101** [comment]
Please see https://github.com/martinet101/ElevenClock/releases/tag/2.6.1.

Download and install. If the issue has not been fixed there, please reopen this

**Comment by chrisowens517** [comment]
> Please see https://github.com/martinet101/ElevenClock/releases/tag/2.6.1.
>Download and install. If the issue has not been fixed there, please reopen this

@martinet101 
I am still having this issue in 2.6.1. Using alternative clock alignment does work as a workaround, but without it the clock remains in the center of the main screen.

**Comment by martinet101** [comment]
With the workaround, does it work at 100% or it just works at half?

**Comment by qazomardok** [comment]
> Please see https://github.com/martinet101/ElevenClock/releases/tag/2.6.1.
> 
> Download and install. If the issue has not been fixed there, please reopen this

nope -(
screenshot: https://ibb.co/PzP3gLb

**Comment by chrisowens517** [comment]
> With the workaround, does it work at 100% or it just works at half?

With the workaround it is 100% working for me.

**Comment by qazomardok** [comment]
> > With the workaround, does it work at 100% or it just works at half?
> 
> ‎С обходным путем это на 100% работает для меня.‎

maintain it. with alternative server sync option it works. thanks

**Comment by martinet101** [comment]
Hi @TipsterTrickster @IAmCrazyyy @sts950 @chrisowens517 @qazomardok,

I don't know if you are still using ElevenClock, but I have upgraded the library that caused this issue again and now it shouldn't fail, but I wanted to ask you if you could test this build here https://drive.google.com/file/d/1-BzA2vP9ssd2yZ729VjtlBw8nzOkQpvq/view?usp=sharing and confirm that the clock works just fine.

Thank you all!

**Comment by qazomardok** [comment]
> Hi @TipsterTrickster @IAmCrazyyy @sts950 @chrisowens517 @qazomardok,
> 
> I don't know if you are still using ElevenClock, but I have upgraded the library that caused this issue again and now it shouldn't fail, but I wanted to ask you if you could test this build here https://drive.google.com/file/d/1-BzA2vP9ssd2yZ729VjtlBw8nzOkQpvq/view?usp=sharing and confirm that the clock works just fine.
> 
> Thank you all!

Я проверил. Ошибка пропала. Но с текущим билдом дл меня надобность в программе отпала - microsoft встроила эту функцию. Кастомизация мне не нужна.

**Comment by martinet101** [comment]
Yes, i understand, but it was just to know if it worked now.

Lots of thanks!
