### ISSUE TITLE
[BUG] Clock still shows while watching a full screen YouTube video even though "Hide the clock in fullscreen mode" is on.

### ISSUE THREAD

**Issue by TechStudent11** [martinet101/ElevenClock#245]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
I was watching a YouTube video and the clock still shows. Even though I have "Hide the clock in fullscreen mode" on. See screenshots below.

## To Reproduce
1. Open any full-screen video

## Expected behavior
The clock is supported to disappear after entering full-screen mode.

## Screenshots
_Eleven Clock Settings_
![image](https://user-images.githubusercontent.com/76978184/140660461-4e6c6951-007f-4bd9-b17d-b7b212b973cf.png)

_Video_
![image](https://user-images.githubusercontent.com/76978184/140660500-01e6d2f6-b957-4eac-801e-ff6d36138798.png)

## The Log

```
Github wouldn't allow me to attach them...

```

## Additional context
Trying to click anything in the bottom right-hand corner won't work. The "un-full-screen" button was there so I couldn't get out of full-screen mode using the button.

**Comment by martinet101** [comment]
It was working on version 2.5?

Could you please attach your log as a txt file?

**Comment by Sbss1111** [comment]
I'm experiencing this issue too, but it only happens when I fullscreen a YouTube video on my second monitor. My log file is attached.

[logs.txt](https://github.com/martinet101/ElevenClock/files/7493358/logs.txt)

**Comment by martinet101** [comment]
@Sbss1111, looking at your log i can see that ElevenClock detects your chrome screen, have you enabled fullscreen hide on the settings?

**Comment by Sbss1111** [comment]
Yes, I have. I also tried restarting it, my PC, and completely ending it and reopening it again. None of which fixed the problem.

**Comment by martinet101** [comment]
Version 2.5 worked before updating?

**Comment by chrisrode-uica** [comment]
I am having the same issue with Zoom full-screen on my non-primary monitor.  ElevenClock is overlaid right on top of the Leave button.  Can't leave the meeting, unless I exit full screen mode first.

**Comment by martinet101** [comment]
Try running this one:

https://github.com/martinet101/ElevenClock/blob/main/ElevenClock-test1.exe?raw=true

**Comment by martinet101** [comment]
Please see https://github.com/martinet101/ElevenClock/releases/tag/2.6.1.

Download and install. If the issue has not been fixed there, please reopen this

**Comment by chrisrode-uica** [comment]
This is still an issue with Zoom on a non-primary monitor in fullscreen mode in 2.61:
![image](https://user-images.githubusercontent.com/61749728/140807338-98c32db8-a784-4234-b74c-4de32b9b75a7.png)

**Comment by martinet101** [comment]
Try enabling "Alternative fullscreen mode" in the Experimental features in Elevenclock settings

**Comment by chrisrode-uica** [comment]
> Try enabling "Alternative fullscreen mode" in the Experimental features in Elevenclock settings

Yep, that did it.  Thanks!

**Comment by TechStudent11** [comment]
@martinet101 That fixed it. Thanks!

**Comment by iOrange** [comment]
@martinet101 where is that "Alternative fullscreen mode" ?  I'm having issues with the clock drawing on top of the youtube videos as well.

![image](https://user-images.githubusercontent.com/7016607/141387548-494eaf3e-dfc9-4ff8-bb22-e40afb3ef112.png)

**Comment by martinet101** [comment]
Enable hide when multi-monitor fullscreeen apps are running

**Comment by iOrange** [comment]
That did it! Thanks! ❤️
