### ISSUE TITLE
[BUG] Clock showing through fullscreen apps on secondary monitor.

### ISSUE THREAD

**Issue by Grenaid** [martinet101/ElevenClock#247]
**Is your feature request related to a problem? Please describe.**
Fullscreen behavior when fullscreen app is not on primary monitor.

**Describe the solution you'd like**
If I have a fullscreen app on a secondary monitor, like youtube fullscreened from a browser, eleven shows on top of the browser.

If I hide it for fullscreen apps, then it doesn't show on the secondary monitor when I game on primary.

I'd really like it to just always be on the taskbar like the windows clock (in background), but with all monitors.

Youtube on secondary with eleven clock running: 

![image](https://user-images.githubusercontent.com/441380/140671094-393ebe46-900d-41ef-9365-466231429e2f.png)

**Comment by martinet101** [comment]
Do you have enabled "hide on fullscreen apps" in the settings window?

Can you please send me your log?

**Comment by Grenaid** [comment]
Here's the log: [Grenaid eleven log.txt](https://github.com/martinet101/ElevenClock/files/7497529/Grenaid.eleven.log.txt)

re: "hide on fullscreen":

- When enabled, the clock disappears from ALL monitors when I load a game on my primary monitor.
- When disabled, the clock appears on TOP of firefox:youtube fullscreen, at least on a secondary monitor.

What I'm hoping for is a setting where it's never on top of anything, but it has the same visibility as the toolbar itself.

**Comment by martinet101** [comment]
Try running this one: https://github.com/martinet101/ElevenClock/blob/main/ElevenClock-test1.exe?raw=true

**Comment by Grenaid** [comment]
Still seems to display above youtube:

![image](https://user-images.githubusercontent.com/441380/140796663-365d3d06-caad-4cb0-bbdb-5ed2372480c6.png)

[Grenaid eleven log test exe 1.txt](https://github.com/martinet101/ElevenClock/files/7499248/Grenaid.eleven.log.test.exe.1.txt)

**Comment by martinet101** [comment]
I've now been able to reproduce your bug, now gonna try to fix it

**Comment by Grenaid** [comment]
Never sure if repro or fixing is a more satisfying feeling, myself.  😎

Glad to hear.

**Comment by martinet101** [comment]
Please see https://github.com/martinet101/ElevenClock/releases/tag/2.6.1.

Download and install. If the issue has not been fixed there, please reopen this

**Comment by Grenaid** [comment]
Hmm, issue seems to remain.  Rebooted this time to make absolutely sure.

![image](https://user-images.githubusercontent.com/441380/140805541-a2049d79-4736-4d76-a7e8-905fbbaa51c7.png)

[Grenaid eleven log 2.61.txt](https://github.com/martinet101/ElevenClock/files/7499598/Grenaid.eleven.log.2.61.txt)

**Comment by martinet101** [comment]
Sorry @Grenaid, i forgot, your issue had no relation with the whole Qt6 update failure...

**Comment by martinet101** [comment]
The thing is that 2.6 updated Qt5 to Qt6, and this has lead to issues with scaling and fullscren scaling, i'll continue to investigate yours

**Comment by Grenaid** [comment]
I guess this is a dupe of #245, may as well mention here for posterity.

**Comment by martinet101** [comment]
It might, but i'm not sure, i'd let this issue open as separate till i can find what's happening

**Comment by gril002** [comment]
Fresh installed 2.6.1 and had the same issue. Toggling "Hide the clock in fullscreen mode" Off and On seemed to fix the issue.

**Comment by Grenaid** [comment]
Hmm, toggling it didn't for me.  Tried fullscreening between toggles too.

**Comment by Celibistrial** [comment]
I am also facing this issue

**Comment by martinet101** [comment]
Toggling on settings "Hide on multi-monitor fullscreen apps" does something or not?

**Comment by Grenaid** [comment]
No, toggling does not fix it as I state here https://github.com/martinet101/ElevenClock/issues/247#issuecomment-963743907

Behavior of that setting toggled on and off remains as I describe here: https://github.com/martinet101/ElevenClock/issues/247#issuecomment-963197142

**Comment by martinet101** [comment]
@gril002, and you?

**Comment by gril002** [comment]
My issue is entirely fixed even after multiple restarts after toggling "Hide the clock in fullscreen mode", so I cannot try your suggestion sorry.

**Comment by martinet101** [comment]
@Grenaid, my suggestion might sound a little bit stupid, but can you try uninstalling, deleting everything in `C:\Users\USERNAME\.elevenclock` and installing again?

**Comment by Grenaid** [comment]
That makes sense, but no, didn't help.

1.  Uninstalled through windows, and deleted the directory you describe.
2. Grabbed latest from https://www.somepythonthings.tk/programs/elevenclock/.
3. Closed browser to make absolutely sure
4. Installed the download.  I believe it was not 2.6.1, as it almost immediately upgraded itself to 2.6.1
5. Issue persists:
![image](https://user-images.githubusercontent.com/441380/141605628-bad6da29-74d2-490e-87ae-b5d109b03cf3.png)

[eleven very clean reinstall.txt](https://github.com/martinet101/ElevenClock/files/7531401/eleven.very.clean.reinstall.txt)

**Comment by martinet101** [comment]
Can you rty this version here and send me the log?
https://1drv.ms/u/s!ApcYxgwZ8nkcgcACslyQAbO5Qntl-A?e=pKQrKE

**Comment by Grenaid** [comment]
Sure!  Doesn't fix issue, sadly.  Same steps followed, uninstalling old version and deleting C:\Users\USERNAME\.elevenclock folder.

[2.7 beta.txt](https://github.com/martinet101/ElevenClock/files/7532550/2.7.beta.txt)

**Comment by martinet101** [comment]
As far as I can see, ElevenClock reports you have disabled "Hide on fullscreen". could you check that and enable the following?
![image](https://user-images.githubusercontent.com/53119851/141655974-a9b0cc7b-58da-4051-b4f1-c0a95eaeb0ca.png)

**Comment by Grenaid** [comment]
Ok, this time unchecking and then rechecking that box worked!  Clock is now exactly as I expect!  Does not appear over a fullscreen app in its own monitor, and is still visible if a fullscreen app is running in another monitor.

**Comment by martinet101** [comment]
Nice then, closing this :)

**Comment by martinet101** [comment]
Next version will come soon
