### ISSUE TITLE
[BUG] [PowerToys] Clicking Eleven toggles "video conference mute" window instead of notifications

### ISSUE THREAD

**Issue by Grenaid** [martinet101/ElevenClock#252]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
Clicking Eleven with PowerToys installed toggles the display of the "video conference mute" window instead of notifications:

## To Reproduce
1. Grab [PowerToys](https://github.com/microsoft/PowerToys/releases/)
2. Click on 'Eleven' 
![image](https://user-images.githubusercontent.com/441380/140798500-e3a83613-0068-4180-9272-97e0c06cce5b.png)

4. Toggles:
![image](https://user-images.githubusercontent.com/441380/140798375-3d89d677-c2b4-484b-8ab8-5dc4170805ea.png)

## Expected behavior
Notifications window should appear instead.

## The Log
[Grenaid eleven log 2.5.txt](https://github.com/martinet101/ElevenClock/files/7499317/Grenaid.eleven.log.2.5.txt)

**Comment by martinet101** [comment]
That is because Win+N (shortcut for power toys) is the shortcut for the calendar/notifications.

I'm sorry, but there's no other way i can open the calendar rahter than using Win+N. You'll need to change the shortcut for mute/unmute

**Comment by Grenaid** [comment]
Amazing, so MS issue?  They double bound a key combo and PowerToys overwrites it?
