### ISSUE TITLE
Auto Update not working

### ISSUE THREAD

**Issue by hybrid2102** [martinet101/ElevenClock#259]
I installed ElevenClock  v2.5 a few days ago. I'm waiting for the **auto-update** to the latest version but it doesn't seem to happen, even with a couple of application restarts.
My settings at the moment:

- [x] Automatically check for updates
- [x] Automatically install available updates
- [ ]  Enable silent updates

**Comment by martinet101** [comment]
Hey, try instaling 2.6 and enabling "Alternative update server" on eperimental features, and it will instll 2.6.1

**Comment by hybrid2102** [comment]
2.6 version successfully updates to 2.6.1, without enabling "Alternative update server".
Thank you
