### ISSUE TITLE
[BUG] Wrong time format 

### ISSUE THREAD

**Issue by AudricSan** [martinet101/ElevenClock#260]
## Describe the bug
the time is not displayed correctly.
the "H" between minutes and hours but this displays the time in AM / PM mode.

## To Reproduce
1. Clock executor.

## Expected behavior
Let the hours and minutes be separated by an "H". Like the Windows Clock
![image](https://user-images.githubusercontent.com/29382102/141009423-0edf4cf1-b04b-4912-bce3-91934dfcba9d.png)

## Screenshots
![image](https://user-images.githubusercontent.com/29382102/141009395-d9ba1ac1-d654-46b8-bb28-9ae51275e09e.png)

## The Log
---------------------------------------------------------------------------------------------------

   ElevenClock's v2.61 log: Select all the text and hit Ctrl+C to copy it

---------------------------------------------------------------------------------------------------
fr
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
NullColor
['255,209,85', '255,182,52', '255,153,16', '81,92,107', '69,78,94', '41,47,64', '15,18,36', '239,105,80']
Starting update check
[WinError 259] Aucune donnée n’est disponible
62.18359375
<PySide2.QtGui.QScreen(0x1c374c40310, name="\\\\.\\DISPLAY2") at 0x000001C3755B8380> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x1c374c40910, name="\\\\.\\DISPLAY1") at 0x000001C3755D6440> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, -1920, 0, 96.0, 96.0)
[WinError 259] Aucune donnée n’est disponible
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-150, 1032, 150, 48)
[WinError 259] Aucune donnée n’est disponible
Full screen rect:  (-1920, 0, 0, 1080)
Restart loop: 1
<PySide2.QtGui.QScreen(0x1c374c401d0, name="\\\\.\\DISPLAY3") at 0x000001C3755D6640> PySide2.QtCore.QRect(1920, 0, 1280, 1024) (1280, 1024, 1920, 0, 96.0, 96.0)
[WinError 259] Aucune donnée n’est disponible
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(3050, 976, 150, 48)
[WinError 259] Aucune donnée n’est disponible
Full screen rect:  (1920, 0, 3200, 1024)
screenCheckThread
Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
updates not found
```

**Comment by martinet101** [comment]
I see. Let me fix that

**Comment by martinet101** [comment]
There you go. Fix will come with next release:
![image](https://user-images.githubusercontent.com/53119851/141538133-cdec196f-687c-4c73-ab82-ea1c91f469d1.png)

**Comment by AudricSan** [comment]
Tyy !
