### ISSUE TITLE
[BUG] Jumping clock position with seconds included.

### ISSUE THREAD

**Issue by ZaYACua** [martinet101/ElevenClock#262]
## Describe the bug
The position of the clock changes when the display of seconds is activated

## To Reproduce
1. Go to Setting
2. Activate "Show seconds on the clock"
3. See an error when "1" is displayed in seconds

## Expected behavior
The time position is fixed with the expectation of the widest value and does not change depending on the number of seconds.

## Screenshots
![2021-11-10_22-02-57](https://user-images.githubusercontent.com/45264833/141185323-fda7335c-8fb2-4af1-8fb7-545d4b613059.gif)

## LOG
[Log.txt](https://github.com/martinet101/ElevenClock/files/7515641/Log.txt)

## Additional context
Version 2.61 64bit
System Windows 11 Pro 10.0.22000

**Comment by martinet101** [comment]
Could you please send a picture of when is it failing?

**Comment by ZaYACua** [comment]
Time changes position
![5tprwv](https://user-images.githubusercontent.com/45264833/141199373-82298d81-d8a5-4beb-b7fe-e22448688dd9.gif)

**Comment by martinet101** [comment]
Hi @ZaYACua, that's a normal behaviour, because different digits do not have the same width. Anyway, the solution would be setting a monospace, font, what you will be able to do when i implement the change font feature #215
