### ISSUE TITLE
[FEATURE REQUEST] Brief description

### ISSUE THREAD

**Issue by sfm153** [martinet101/ElevenClock#263]
Hope you might consider adding format options including text, font, type, and color, as the AM/PM tends to blur into the numbers and leading/trailing space(s) would be helpful to set its position. T-clock, which no longer works even in compatibility mode of Win 11, was a pretty handy app in its time and had other features as well that you might be interested in adding.
Still, nice to have the seconds display and they do so nicely in the space between the windows icon and search icon on the left side.

**Comment by martinet101** [comment]
Hey, for the font type, you can follow #215, and for the font color, could you open a new Feature request? (Or use this one by changging the title).

I'm happy to see that the app is handy for you :)
