### ISSUE TITLE
[FEATURE REQUEST & BUG] Change font size

### ISSUE THREAD

**Issue by RemoUlmi** [martinet101/ElevenClock#265]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 mintues, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

## Additional context
Add any other context about the problem here
![Text has not enough space](https://user-images.githubusercontent.com/94185364/141491098-8c90c4ea-b8ce-439f-aba7-1c30de0aae04.jpg)
![Screen Settings](https://user-images.githubusercontent.com/94185364/141491138-534befcf-2491-4fc8-80cc-3931c29111a4.jpg)
.

**Comment by martinet101** [comment]
That's an issue with font size, i'm planning to add  a customization for this.

**Comment by martinet101** [comment]
Fixed, on next version you'll be able to set a smaller font size
