### ISSUE TITLE
[BUG] ElevenClock Displays On Top of Standard Clock on Taskbar in VMWare Horizon

### ISSUE THREAD

**Issue by TeejayKix** [martinet101/ElevenClock#266]
Hi there! First, I love ElevenClock and everything you've done with it so far. I've only been using ElevenClock just a few weeks since I first discovered it, and it's amazing how much it has grown and improved in just the past short few weeks I have been using it.

There is a bug or glitch with ElevenClock on my particular system that has been there since I first downloaded version 1.9. I have a triple-monitor configuration running Windows 11 that I use VMWare Horizon Client in (version 2106 build 8.3.0) for work. The taskbar on my far-right monitor in VMWare shows both the Windows 10 clock, but also ElevenClock on top of it. I've attached a screenshot for reference.

![Capture 1](https://user-images.githubusercontent.com/94186728/141497718-1008282e-fc67-4b13-be32-db47bdb1d493.PNG)

I've tried playing with all of ElevenClock's settings with disabling while in fullscreen/Citrix/RDP, but I don't think those settings work specifically for VMWare Horizon Client.

I just figured I would take a moment while I had one to send some feedback to see if maybe that can be addressed in a later release? Thanks again for all your hard work!

All the best,
 - T.J.

![Capture 2](https://user-images.githubusercontent.com/94186728/141497999-42725ab7-9d56-40d0-a677-c5acb9398dc6.png)

**Comment by martinet101** [comment]
Hi, try enabling "Hide on Multi-monitor fullscreen apps"

**Comment by martinet101** [comment]
Also try enablling hide on RDP if the previous post did not help

**Comment by martinet101** [comment]
It hides also on vmware horizon
