### ISSUE TITLE
Eleven O'clock not showing short version of day

### ISSUE THREAD

**Issue by Esium7** [martinet101/ElevenClock#267]
This has been happening for a few days now and though i would tell you about it. 

![Eleven O'clock](https://user-images.githubusercontent.com/92878165/141502500-626c9938-fe71-4fee-9035-e7214406bfd9.png)
I have the time on one line, the weekday on the next line, then for some reason on the next line it has "i12. November 12, 2021" where it should be "Fri12. November 12, 2021." The "Fri" isn't a problem because as you can see i have the day above it. I just wanted to let you know that the short "Fri" isn't showing up properly (why or why not i don't know) and this happens with the other days of the week.

So, no real problem but i did uninstall Eleven O'clock and re-install it to no avail. What do you think.

**Comment by martinet101** [comment]
Ok, i see the problem, elevenclock does not have enough width. I'll fix that

**Comment by martinet101** [comment]
Fixed, coming in next version
