### ISSUE TITLE
[BUG] Time is 24 hour when system time is set as 12 hour

### ISSUE THREAD

**Issue by ShadowBullet** [martinet101/ElevenClock#270]
As the title suggests, my time using this on my other monitors is on 24 hour time where as my system time is set as 12 hour (even checked in regional settings and re-synced my time) Looking at this now, it also appears as though my data is in UK standard instead of US standard. 

ElevenClock
![ElevenClock_Z2qXLGm4j2](https://user-images.githubusercontent.com/6118102/141606452-1c904cfd-3d0e-46e6-8839-b8f1ef4a260b.png)

Main Monitor with System
![huRzVAoNdv](https://user-images.githubusercontent.com/6118102/141606458-4c2bf69c-0d33-4763-93e5-8c496000b3d0.png)

**Comment by martinet101** [comment]
That's weird... could you please send me the log?

**Comment by ShadowBullet** [comment]
Sure thing, here is the log

---------------------------------------------------------------------------------------------------

   ElevenClock's v2.61 log: Select all the text and hit Ctrl+C to copy it

---------------------------------------------------------------------------------------------------




en
NullColor
['223,222,220', '166,165,161', '104,101,98', '76,74,72', '65,63,61', '39,37,36', '16,13,13', '16,124,16']
Starting update check
[WinError 259] No more data is available
[WinError 259] No more data is available
64.125
<PySide2.QtGui.QScreen(0x27c4bacf4a0, name="\\\\.\\DISPLAY1") at 0x0000027C4D608580> PySide2.QtCore.QRect(0, 0, 3440, 1440) (3440, 1440, 0, 0, 96.0, 96.0)
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x27c4bacf020, name="\\\\.\\DISPLAY5") at 0x0000027C4D617BC0> PySide2.QtCore.QRect(-206, -2160, 3840, 2160) (3840, 2160, -206, -2160, 120.0, 120.0)
[WinError 259] No more data is available
[WinError 259] No more data is available
[WinError 259] No more data is available
Restart loop: 1
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(3446, -60, 187, 60)
[WinError 259] No more data is available
[WinError 259] No more data is available
[WinError 259] No more data is available
[WinError 259] No more data is available
Full screen rect:  (-206, -2160, 3634, 0)
[WinError 259] No more data is available
<PySide2.QtGui.QScreen(0x27c4bacf140, name="\\\\.\\DISPLAY2") at 0x0000027C4D6106C0> PySide2.QtCore.QRect(-2560, 0, 2560, 1440) (2560, 1440, -2560, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-150, 1392, 150, 48)
[WinError 259] No more data is available
[WinError 259] No more data is available
[WinError 259] No more data is available
[WinError 259] No more data is available
Full screen rect:  (-2560, 0, 0, 1440)
[WinError 259] No more data is available
<PySide2.QtGui.QScreen(0x27c4bacf2e0, name="\\\\.\\DISPLAY3") at 0x0000027C4D620180> PySide2.QtCore.QRect(3440, 0, 2560, 1440) (2560, 1440, 3440, 0, 96.0, 96.0)
[WinError 259] No more data is available
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(5850, 1392, 150, 48)
[WinError 259] No more data is available
[WinError 259] No more data is available
[WinError 259] No more data is available
[WinError 259] No more data is available
Full screen rect:  (3440, 0, 6000, 1440)
[WinError 259] No more data is available
screenCheckThread
NullColor
['223,222,220', '166,165,161', '104,101,98', '76,74,72', '65,63,61', '39,37,36', '16,13,13', '16,124,16']
Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
updates not found

**Comment by martinet101** [comment]
Try running this one: https://1drv.ms/u/s!ApcYxgwZ8nkcgcACslyQAbO5Qntl-A?e=pKQrKE
