### ISSUE TITLE
Eleven O'clock showing two dates

### ISSUE THREAD

**Issue by Esium7** [martinet101/ElevenClock#283]
I was wondering if you could help me figure out why Eleven O'clock is showing two dates like this:
![Eleven oclock present look](https://user-images.githubusercontent.com/92878165/141832852-01d25428-c92a-4ba0-83af-bcef9bafa485.png)
Whereas Windows date is like this:
![Windows date](https://user-images.githubusercontent.com/92878165/141832926-d9f70336-5b6c-4c5e-b977-5e8490ac98c2.png)
I have the short and long date settins in the registry as "dddd MMM d, yyyy"
Windows is showing up right but not Eleven O'clock.
Where does Eleven O'clock get its settings from?
Any ideas what might be happening?
Also, putting more room on the length of the date (on the last bug i reported) worked great.

Thanks.

**Comment by martinet101** [comment]
Yes, for sure i'll take a look!

**Comment by martinet101** [comment]
Fixed, coming in 2.8 next week
![image](https://user-images.githubusercontent.com/53119851/142644396-f1dd2119-b305-4061-8fcd-041443888f58.png)
