### ISSUE TITLE
[FEATURE REQUEST] Clock position at top 

### ISSUE THREAD

**Issue by pustekuchen91** [martinet101/ElevenClock#286]
**Is your feature request related to a problem? Please describe.**
When using a multi montior setup and configuried that the windows bar is at the top, its not possible to show the clock at the top. 

**Describe the solution you'd like**
Windows 11 allows to position the bar at the bottom and top (with a registry modification). i would like to have an option to decide whether the clock is displayed in the lower or upper windows bar

**Comment by martinet101** [comment]
Yes, I'll add the switch. Could you send me the tutorial you used to change the registry to be able to know which reg keys are modified?

Thanks

**Comment by pustekuchen91** [comment]
For Single-Monitor you have to modifiy the `Settings`-Key in `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3` from `03` to `01`
![grafik](https://user-images.githubusercontent.com/7147324/141935139-3eeba7eb-2c0a-420e-bb2d-b69399b4471f.png)

For Multi-Monitor `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\MMStuckRects3`.
In this case you have to find out the correct Key for the 2nd Monitor and edit the same byte from `03` to `01`.

**Comment by martinet101** [comment]
Done, coming with 2.8
