### ISSUE TITLE
[FEATURE REQUEST] Setting to toggle adding desktop shortcut on update

### ISSUE THREAD

**Issue by jay33721** [martinet101/ElevenClock#287]
**Is your feature request related to a problem? Please describe.**
It's not a big issue, but it kind of bothers me that the app creates a new desktop shortcut that I have to delete every time it updates.

**Describe the solution you'd like**
A setting to turn off creating a desktop shortcut on update would be ideal.

**Comment by Grenaid** [comment]
Dupe of #256?  Might already be fixed, unless it's the toggle that you really want.

**Comment by jay33721** [comment]
I suppose the toggle isn't important, but it did create a shortcut just a couple days ago when updating silently, so #256 might not have been implemented yet?

**Comment by martinet101** [comment]
It should be implemente, that's why I marked this as a bug rather that a feature request

**Comment by martinet101** [comment]
It should be fixed with the next version
