### ISSUE TITLE
[ISSUE] Winget upgrade wrong version number

### ISSUE THREAD

**Issue by maxtushewski** [martinet101/ElevenClock#288]
![winget upgrade](https://user-images.githubusercontent.com/464035/141976324-918218ae-308a-447d-bbe4-9de708890b23.png)
Wrong available version number.

**Comment by martinet101** [comment]
That's because winget hasn't already updated ElevenClock. Give it some time and it will

**Comment by martinet101** [comment]
Anyway, i'll try to delete v2.61
