### ISSUE TITLE
[BUG] Clock shows when taskbar does not

### ISSUE THREAD

**Issue by ewilson** [martinet101/ElevenClock#293]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
When I use proprietory virtual desktop program (from my work) that uses my complete second monitor, the taskbar is covered by the window. The ElevenClock clock shows, and conflicts with the taskbar of the virtual desktop.

## To Reproduce
1. Open a window that covers the taskbar while the ElevenClock is running

## Expected behavior
The ElevenClock is only visible when the taskbar is visiable

## Screenshots
![image](https://user-images.githubusercontent.com/385580/142231071-488764f6-7048-468c-9bf3-0743b131eca0.png)

**Comment by martinet101** [comment]
Try enabling "Hide on multi-monitor fullscreen windows" under experimental settings

**Comment by ewilson** [comment]
All good. Thanks.
