### ISSUE TITLE
[BUG] Error "Failed to execute script" when trying to launch Elevenclock

### ISSUE THREAD

**Issue by Centazi** [martinet101/ElevenClock#294]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the latest version and the issue still happens

## Describe the bug
Every time i try to start ElevenClock or Elevenclock Settings i get the error "Failed to execute script".

## To Reproduce
1. Start Elevenclock or Elevenclock Settings.

## Expected behavior
The expected behavior is for the application to star which does not.

## Screenshots
![image](https://user-images.githubusercontent.com/54981326/142249060-2e143e02-5e8f-4bf7-840e-d83ae7bcf71f.png)

## The Log

Can't provide logs as the settings page does not launch. If there's another way to provide logs ill do so 

## Additional context
Using Windows 11 Pro. I disabled the application as i was using Startallback. When i decided to go back to stock the application did not start as stated above. Already tried to reinstall the latest version and rollback to a previous one, but the problem persisted.

**Comment by martinet101** [comment]
Try deleting the directory C:\Users\YourUserName\.elevenclock

**Comment by martinet101** [comment]
Can you try this version here and send me the log?
https://1drv.ms/u/s!ApcYxgwZ8nkcgcACslyQAbO5Qntl-A?e=pKQrKE

**Comment by Centazi** [comment]
> Try deleting the directory C:\Users\YourUserName.elevenclock

Hot diggity damn, that did the trick! Thank you very much!

**Comment by Centazi** [comment]
> Try deleting the directory C:\Users\YourUserName.elevenclock

Hot diggity damn, that did the trick! Thank you very much!
