### ISSUE TITLE
[BUG] The clock disappears when click Start on the secondary screen

### ISSUE THREAD

**Issue by DanhTran210** [martinet101/ElevenClock#295]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
The clock disappears when click Start on the secondary screen

## To Reproduce
1. Click on Start on the secondary screen using mouse 
2. See error that the clock disappears

## Expected behavior
The clock shouldn't disappear

## Screenshots
![Windows_on_secondary_screen](https://user-images.githubusercontent.com/85671217/142251713-3c7f5017-7bdb-452d-8fdd-21eb02deb30e.jpg)

**Click Start on primary screen by using mouse or keyboard seems to work normally:**
![Windows_on_primary_screen](https://user-images.githubusercontent.com/85671217/142252365-c68bf13b-192e-40a0-bb92-223560226b0f.jpg)

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.7.0 (v2.7) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------



9.5
system tray icon disabled
update checking disabled
start RDP thread
62.4453125
<PySide2.QtGui.QScreen(0x248e6f65100, name="\\\\.\\DISPLAY1") at 0x00000248E78F8140> (1920, 1080, 0, 0, 120.0, [(<PyHANDLE:131073>, <PyHANDLE:0>, (0, 0, 1920, 1080)), (<PyHANDLE:65594>, <PyHANDLE:0>, (-1920, 0, 0, 1080))])
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x248e6f01e70, name="\\\\.\\DISPLAY2") at 0x00000248E7907E80> (1920, 1080, -1920, 0, 120.0, [(<PyHANDLE:131073>, <PyHANDLE:0>, (0, 0, 1920, 1080)), (<PyHANDLE:65594>, <PyHANDLE:0>, (-1920, 0, 0, 1080))])
Regular sized taskbar
(-1920, 0, 0, 1080)
PySide2.QtCore.QRect(-1920, 0, 1920, 1080)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-1910, 1020, 250, 60)
Font families: ['Microsoft YaHei UI Light']
Font size: 9.5
Full screen rect:  (-1920, 0, 0, 1080)
Restart loop: 1
Show or hide loop started with following parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:True, ClockOn1Mon:False, NefWSMethod:False

```

**Comment by martinet101** [comment]
This is because ElevenClock and the taskbar have both the maximum y-level (show on top) level, and because when clicking start menu the taskbar gets the focus, the clock gets under it. I'm sorry but this is not fixable, there are more issues about this, if you want more info.
