### ISSUE TITLE
[BUG] "Show seconds on the clock" toggle doesn't work

### ISSUE THREAD

**Issue by Mr4erkes** [martinet101/ElevenClock#296]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
There are seconds on the clock, and turning on/off settings toggle "Show seconds on the clock" doesn't make any effect. 

## To Reproduce
1. Go to the "ElevenClock" settings.
2. Click the settings toggle "Show seconds on the clock".
3. See no effect on the secondary display.
4. Click the settings toggle "Show seconds on the clock".
5. See no effect on the secondary display.

Restarting the clock and the app still has no effect.

## Expected behavior
I expect to see the seconds when the toggle is on and not see the secconds on the toggle off.

## Screenshots
![Screenshot_2021-11-17_204953](https://user-images.githubusercontent.com/11913227/142255054-b83dab69-7c75-49b1-bc40-97b0741e2e13.png)

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.7.0 (v2.7) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------




system tray icon enabled
Starting update check
63.609375
<PySide2.QtGui.QScreen(0x2682a5cee90, name="\\\\.\\DISPLAY1") at 0x000002682AE17100> (1920, 1080, 0, 0, 120.0, [(<PyHANDLE:65598>, <PyHANDLE:0>, (0, 0, 1920, 1080)), (<PyHANDLE:131073>, <PyHANDLE:0>, (-1280, 0, 0, 1024))])
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x2682a5cfb30, name="\\\\.\\DISPLAY2") at 0x000002682AE20E40> (1280, 1024, -1280, 0, 120.0, [(<PyHANDLE:65598>, <PyHANDLE:0>, (0, 0, 1920, 1080)), (<PyHANDLE:131073>, <PyHANDLE:0>, (-1280, 0, 0, 1024))])
Regular sized taskbar
(-1280, 0, 0, 1024)
PySide2.QtCore.QRect(-1280, 0, 1280, 1024)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(-250, 964, 250, 60)
Font families: ['Segoe UI Variable Display', 'sans-serif']
Font size: 9.3
Full screen rect:  (-1280, 0, 0, 1024)
Restart loop: 1
Show or hide loop started with following parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
updates not found
```

## Additional context
Same bug was with the previous version too.

**Comment by martinet101** [comment]
Do you have seconds set in your short date locale format?

**Comment by Mr4erkes** [comment]
They are different. On my system tray I use the short format.
The short format is `HH:mm` and the full format is `HH:mm:ss`.
![image](https://user-images.githubusercontent.com/11913227/142478470-dd83ee36-e901-4b69-8077-3a60b555bb4a.png)

**Comment by martinet101** [comment]
Try this tutorial BUT follow the disable guide (Set 0 instead of 1 value to the dword)

https://winbuzzer.com/2021/03/31/how-to-show-seconds-on-the-windows-10-taskbar-clock-xcxwbt/

**Comment by Mr4erkes** [comment]
ОК. Thank you. I'll be able to check it in 1 or 2 days. I'll report the result here.

**Comment by Mr4erkes** [comment]
Thank you.
There was the value `ShowSecondsInSystemClock` in `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced` set to `1`.
Setting value `ShowSecondsInSystemClock` to `0` or deleting that value lets the `ElevenClock` make changes.
