### ISSUE TITLE
change to "Hide the clock when RDP/VMware Horizon Client or Citrix Workspace are running"

### ISSUE THREAD

**Issue by paulbraren** [martinet101/ElevenClock#297]
**Is your feature request related to a problem? Please describe.**
Suggested change to "Hide the clock when RDP/VMware Horizon Client or Citrix Workspace are running" behavior

**Describe the solution you'd like**
I use 3 monitors on my primary workstation. During workday hours, I connect via RDP to my work laptop and leave it running. When it's full screen, it takes over all 3 displays.  I often minimize this RDP window when I"m not doing workstation stuff, far more feasible the closing it, as it requires authentication every time, and the password can't be saved. At default ElevenClock settings, when I'm running RDP fullscreen, I have my ElevenClock clock showing, overlapping my work laptop's clock.

What I'm wondering is whether this feature:
"Hide the clock when RDP/VMware Horizon Client or Citrix Workspace are running"
can be changed to
"Hide the clock when RDP/VMware Horizon Client or Citrix Workspace are running Full Screen"

Any time any minimized copy of RDP is left running, my ElevenClock hides my clocks, so for me, that's all the time.

Thank you for ElevenClock, I love it, but cannot use it on a daily basis given my RDP workflow, and I'm curious whether this suggested change is even possible.

**Comment by martinet101** [comment]
The short anwser is No

The long answer is also no, but you can disable this option and enable "Hide on multi-monitor fullscreen apps"

**Comment by paulbraren** [comment]
Thank you for the prompt and definitive answer, much appreciated.

FYI, on my Windows 11 workstation, I have tried unchecking "Hide the clock when RDP/VMware Horizon Client or Citrix Workspace are running" and checking "Hide on multi-monitor fullscreen apps", but I still get two clocks seen on the fullscreen RDP (Windows 10) session.

Interesting to note that running Snagit screen capture from Windows 11 in 5 second timer mode allowed me to catch this doubled-up clock artifact (first attachment). Despite this same double-up image clearly being visible within the fullscreen Windows 10 desktop, running Snagit from there only shows the Windows 10 clock when screenshotted. I share this jsut in case its helpful.

Thank you again for the great work, I have some Windows 11 VMs (under VMware ESXi 7) that I'll be using ElevenClock for.

![2021-11-18_10-49-27](https://user-images.githubusercontent.com/11763035/142449300-73f0b682-6947-48ae-8547-41726f69ec02.jpg)
![2021-11-18_10-49-09](https://user-images.githubusercontent.com/11763035/142449301-91f461ec-88fc-49e8-876e-9ec4b7618fb7.jpg)
