### ISSUE TITLE
[FEATURE REQUEST] Hide the clock in fullscreen mode only if the fullscreen app is in the current desktop

### ISSUE THREAD

**Issue by hybrid2102** [martinet101/ElevenClock#300]
My situation:

- RDP fullscreen on Desktop 1
- "Hide the clock in fullscreen mode" is checked -> the clock is correctly hidden
- I switch to Desktop 2 (using custom mouse button)
- The clock remains hidden

**Comment by martinet101** [comment]
Enable "hide on multi-monitor fullscreen apps" under experimental features

**Comment by martinet101** [comment]
Could you please reproduce the issue and send me your log (ElevenClock Settings -> Debugging info -> Open log)

**Comment by hybrid2102** [comment]
Sure. Here is the log: https://pastebin.com/unQAnFFe

**Comment by martinet101** [comment]
I can't fix that, because you RDP client draws a fullscreen window all over both displays, and then it just pains the desktop on one of them. I'm sorry :(

**Comment by hybrid2102** [comment]
You are right: actually I instructed my RDP client to act this way to achieve a "2 monitors over 3" configuration.
Thank you for your time anyway.
