### ISSUE TITLE
[BUG] A lot of "Fatal error detected"

### ISSUE THREAD

**Issue by TechStudent11** [martinet101/ElevenClock#301]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
HOLY. I turn on my laptop, and a bunch of error windows pop out of nowhere! I did literally nothing.

## To Reproduce
Do nothing.

## Expected behavior
IDK. It just happened.

## Screenshots
![image](https://user-images.githubusercontent.com/76978184/142509228-c8de68f9-19b0-4912-ab7d-4519aa374a57.png)

_Another one. There are **A LOT** more_
![image](https://user-images.githubusercontent.com/76978184/142509632-1718cab3-80c8-4e2c-aa3e-00fbe6876b4e.png)

**Comment by martinet101** [comment]
Wow... Those are ElevenClock's?

**Comment by TechStudent11** [comment]
@martinet101 **YEAH!** I originally thought those were subprocesses, but after checking Task Manager...

![image](https://user-images.githubusercontent.com/76978184/142619086-e33fd3ad-a2f1-4cd3-b333-3a3d12290eab.png)

Most of those 189 processes/apps are ElevenClock.

**Comment by martinet101** [comment]
Does this happen with any version?

**Comment by TechStudent11** [comment]
@martinet101 I am running the latest version of ElevenClock. Should I downgrade? Because the version I am using fixed the bug that I had with fullscreen apps (#245).

**Comment by martinet101** [comment]
You could try downgrading, to see if it happens only in 2.7 or if it happens also with older versions

**Comment by TechStudent11** [comment]
@martinet101 okay. But I don't really know what caused it. I just turned on my computer and it happened.

**Comment by martinet101** [comment]
Every time you launch ElevenClock does that happen?

**Comment by TechStudent11** [comment]
@martinet101 I don't know. I'll have to test it. (but first I have to still get rid of all of the ElevenClocks. Yikes)

**Comment by martinet101** [comment]
to kill all instances, just run `taskkill /im ElevenClock.exe /f` on the run dialog (press win+r and paste the command)

**Comment by martinet101** [comment]
Ok, it might have been only a weird coincidence, because PyInstaller has been reported to do weird things like these. anyway, if the issue persists mae sure to post it here

**Comment by TechStudent11** [comment]
> Ok, it might have been only a weird coincidence, because PyInstaller has been reported to do weird things like these. anyway, if the issue persists mae sure to post it here

@martinet101 Okay.

**Comment by TechStudent11** [comment]
Also, you can remove the "needs-author-feedback" label.

**Comment by TechStudent11** [comment]
@martinet101 It happened again. I opened my computer for the first time this morning and I get this. Error windows. All in the same places as last time.

![image](https://user-images.githubusercontent.com/76978184/142761822-570c54aa-4601-445c-910c-de4bda8f56a9.png)

![image](https://user-images.githubusercontent.com/76978184/142761830-97833982-5399-40e8-ae9a-bb72499eceff.png)

![image](https://user-images.githubusercontent.com/76978184/142761847-b27224ec-24fe-470c-a717-bc15af8eaf13.png)

For context, here's File Explorer:

![image](https://user-images.githubusercontent.com/76978184/142761872-2c61e9e0-cf0b-4cbe-9d3f-7f70e7b781c8.png)

I still have about 2GB of space left. That isn't a lot, but it's definitely **NOT** none.

**Comment by TechStudent11** [comment]
So this is a space issue, not an issue with closing my lid with power going into it and having an external display connected.

**Comment by TechStudent11** [comment]
But unlike last time, ElevenClock is still running and working.

![image](https://user-images.githubusercontent.com/76978184/142762294-fec8a997-fb99-4ecc-a911-b5e532849dc0.png)

**Comment by martinet101** [comment]
> So this is a space issue, not an issue with closing my lid with power going into it and having an external display connected.

Note that windows prevents hdd writing when a really small amount of disk space is available. Could you try emptying a little bit of space and see if it still happens?

Thanks :)

**Comment by TechStudent11** [comment]
@martinet101 I have an SSD. But okay. I'll try.

**Comment by TechStudent11** [comment]
@martinet101 Alright it's working now. And yeah this is a hard one.

**Comment by TechStudent11** [comment]
Still gonna leave it open though, just in case.

**Comment by martinet101** [comment]
OK, let's leave it open for a week and see what happens

**Comment by TechStudent11** [comment]
@martinet101 Okay.

**Comment by FahimFBA** [comment]
> @martinet101 It happened again. I opened my computer for the first time this morning and I get this. Error windows. All in the same places as last time.
> 
> ![image](https://user-images.githubusercontent.com/76978184/142761822-570c54aa-4601-445c-910c-de4bda8f56a9.png)
> 
> ![image](https://user-images.githubusercontent.com/76978184/142761830-97833982-5399-40e8-ae9a-bb72499eceff.png)
> 
> ![image](https://user-images.githubusercontent.com/76978184/142761847-b27224ec-24fe-470c-a717-bc15af8eaf13.png)
> 
> For context, here's File Explorer:
> 
> ![image](https://user-images.githubusercontent.com/76978184/142761872-2c61e9e0-cf0b-4cbe-9d3f-7f70e7b781c8.png)
> 
> I still have about 2GB of space left. That isn't a lot, but it's definitely **NOT** none.

It can happen for not having DirectX, VCRedist. I would suggest you to check that again after installing all of the DirectX and VCRedist. For installing them without any hassle, you may do that using a package manager named [Chocolatey](https://chocolatey.org/install). After installing, apply the following commands.

* For installing DirectX

```
choco install -y directx
```

* For installing VCRedist

```
choco install -y vcredist-all
```

Can you let us know afterward whether that solved your problem or not? 😀

**Comment by martinet101** [comment]
I think it might be a PyInstaller issue, because it has been reported to PyInstaller to do weird things. I'll build ElevenClock 2.8 with the PyInstaller dev version.

**Comment by TechStudent11** [comment]
@FahimFBA It was a storage issue on my part. I think I have DirectX installed already. Anyways, I haven't had this bug since last time. I just have to manage my storage that's all.

**Comment by Masamune3210** [comment]
I would advise either upgrading the storage or adding another drive if your computer has a spot for it. Lack of storage space can royally mess with a lot of things that can end up hard to fix

**Comment by TechStudent11** [comment]
@Masamune3210 yeah I agree. My laptop comes with 256GB of storage and my projects folder takes up about 30GB of that.

**Comment by Masamune3210** [comment]
I know those feels, current project is taking up most of a TB

**Comment by TechStudent11** [comment]
@Masamune3210 MOST OF A TERABYTE?!?!? WHAT ARE YOU BUILDING?!?!? A REACT APP WITH AN ELECTRON APP AND SWIFT APP?!?!?

**Comment by Masamune3210** [comment]
nah, its a bunch of projects. the code itself doesn't take up a lot of space, the files they are operating on does on the other hand

**Comment by TechStudent11** [comment]
@Masamune3210 ohhhh that makes sense. kind of.

**Comment by TechStudent11** [comment]
@martinet101 Alright it's been a week and the issue hasn't occurred again. I am gonna close this now, but I'll reopen it again if the issue persists. Also, don't lock it the collaborators, just in case 😉.

**Comment by void-mian** [comment]
Same issue on 3.3.1.
There are 2725 copies of _MEIxxxxx in `%localappdata%\Temp`
<img width="112" alt="image" src="https://user-images.githubusercontent.com/36444200/158046428-7a0c3ba7-2dee-430a-a5cf-51cb4d7b62b3.png">
Each of them looks like the ElevenClock it self and takes about 110 MB.
```text
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2022/3/12     14:43                Include
d-----         2022/3/12     14:43                lang
d-----         2022/3/12     14:43                psutil
d-----         2022/3/12     14:43                PySide2
d-----         2022/3/12     14:44                resources
d-----         2022/3/12     14:43                shiboken2
d-----         2022/3/12     14:44                tcl8
-a----         2022/3/12     14:43         792701 base_library.zip
-a----         2022/3/12     14:43        4467904 d3dcompiler_47.dll
-a----         2022/3/12     14:43           1060 globals.py
-a----         2022/3/12     14:43           2211 languages.py
-a----         2022/3/12     14:43        3438840 libcrypto-1_1.dll
-a----         2022/3/12     14:43          23672 libEGL.dll
-a----         2022/3/12     14:43          32792 libffi-7.dll
-a----         2022/3/12     14:43        3368056 libGLESv2.dll
-a----         2022/3/12     14:43         698104 libssl-1_1.dll
-a----         2022/3/12     14:43        6065952 mfc140u.dll
-a----         2022/3/12     14:42         618264 MSVCP140.dll
-a----         2022/3/12     14:42          31512 MSVCP140_1.dll
-a----         2022/3/12     14:43       20923392 opengl32sw.dll
-a----         2022/3/12     14:43         204176 pyexpat.pyd
-a----         2022/3/12     14:43         150136 pyside2.abi3.dll
-a----         2022/3/12     14:43          60304 python3.dll
-a----         2022/3/12     14:43        4522384 python39.dll
-a----         2022/3/12     14:43         556544 pythoncom39.dll
-a----         2022/3/12     14:43         142336 pywintypes39.dll
-a----         2022/3/12     14:42        6031480 Qt5Core.dll
-a----         2022/3/12     14:43         445048 Qt5DBus.dll
-a----         2022/3/12     14:43        7035512 Qt5Gui.dll
-a----         2022/3/12     14:43        1352824 Qt5Network.dll
-a----         2022/3/12     14:43        4456056 Qt5Pdf.dll
-a----         2022/3/12     14:43        3761784 Qt5Qml.dll
-a----         2022/3/12     14:43         441976 Qt5QmlModels.dll
-a----         2022/3/12     14:43        4199544 Qt5Quick.dll
-a----         2022/3/12     14:43         331384 Qt5Svg.dll
-a----         2022/3/12     14:43        2116216 Qt5VirtualKeyboard.dll
-a----         2022/3/12     14:43         159352 Qt5WebSockets.dll
-a----         2022/3/12     14:43        5518456 Qt5Widgets.dll
-a----         2022/3/12     14:43         469624 Qt5WinExtras.dll
-a----         2022/3/12     14:43          29584 select.pyd
-a----         2022/3/12     14:43         147406 settings.py
-a----         2022/3/12     14:43         243320 shiboken2.abi3.dll
-a----         2022/3/12     14:43        1866480 tcl86t.dll
-a----         2022/3/12     14:43        1541872 tk86t.dll
-a----         2022/3/12     14:43          26498 tools.py
-a----         2022/3/12     14:43        1122192 unicodedata.pyd
-a----         2022/3/12     14:43          97168 VCRUNTIME140.dll
-a----         2022/3/12     14:43          44312 VCRUNTIME140_1.dll
-a----         2022/3/12     14:43          37137 welcome.py
-a----         2022/3/12     14:43         134656 win32api.pyd
-a----         2022/3/12     14:43         228864 win32gui.pyd
-a----         2022/3/12     14:43          54272 win32process.pyd
-a----         2022/3/12     14:43          22528 win32trace.pyd
-a----         2022/3/12     14:43        1428480 win32ui.pyd
-a----         2022/3/12     14:43          65936 _asyncio.pyd
-a----         2022/3/12     14:43          87440 _bz2.pyd
-a----         2022/3/12     14:43         127376 _ctypes.pyd
-a----         2022/3/12     14:43         270736 _decimal.pyd
-a----         2022/3/12     14:43         189328 _elementtree.pyd
-a----         2022/3/12     14:43          65424 _hashlib.pyd
-a----         2022/3/12     14:43         163728 _lzma.pyd
-a----         2022/3/12     14:43          31120 _multiprocessing.pyd
-a----         2022/3/12     14:43          46992 _overlapped.pyd
-a----         2022/3/12     14:43          30096 _queue.pyd
-a----         2022/3/12     14:43          80784 _socket.pyd
-a----         2022/3/12     14:43         156048 _ssl.pyd
-a----         2022/3/12     14:43          66448 _tkinter.pyd
-a----         2022/3/12     14:43          12288 _win32sysloader.pyd
-a----         2022/3/12     14:43           1268 __init__.exe.manifest
-a----         2022/3/12     14:43          72332 __init__.py
```

**Comment by martinet101** [comment]
Can you try deleting all your temp folders and see if that happens again?

**Comment by TechStudent11** [comment]
Wow that's an unusual bug. Maybe it's just a one-off. Try rebooting (which automatically clears your temp folder(s)) to see if that solves the issue.
