### ISSUE TITLE
[BUG] Era strings are not handled correctly.

### ISSUE THREAD

**Issue by CortanaJPN** [martinet101/ElevenClock#302]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the latest version and the issue still happens

## Describe the bug
Era strings are not handled correctly or at all, simply displaying placeholder text. For example, today shows as ggy年11月19日(金).

## To Reproduce
Steps to reproduce the behaviour:
1. Have your regional settings set to anything that contains an era string (e.g.: Japanese imperial calendar).
2. That's it.

## Expected behaviour
Clock should display the era and year correctly. In this case, the correct display would be 令和3年11月19日（金）.

## Screenshots
![image](https://user-images.githubusercontent.com/94655423/142516502-26d5a23b-ae0a-419d-89ff-925a53dae806.png)
↑What your app displays
![image](https://user-images.githubusercontent.com/94655423/142516522-19d4d209-46d3-4e5f-afcf-78a09e9f3933.png)
↑What should be displayed (system clock on primary monitor).

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

---------------------------------------------------------------------------------------------------

   ElevenClock's 2.7.0 (v2.7) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------




system tray icon enabled
Starting update check
64.85546875
<PySide2.QtGui.QScreen(0x1ea194aa760, name="\\\\.\\DISPLAY1") at 0x000001EA19CC8200> (1920, 1080, 0, 0, 96.0, [(<PyHANDLE:1311775321>, <PyHANDLE:0>, (0, 0, 1920, 1080)), (<PyHANDLE:1710491921>, <PyHANDLE:0>, (1920, -170, 3840, 910))])
This is primay screen and is set to be skipped
<PySide2.QtGui.QScreen(0x1ea194aa620, name="\\\\.\\DISPLAY2") at 0x000001EA19CDC180> (1920, 1080, 1920, -170, 96.0, [(<PyHANDLE:1311775321>, <PyHANDLE:0>, (0, 0, 1920, 1080)), (<PyHANDLE:1710491921>, <PyHANDLE:0>, (1920, -170, 3840, 910))])
Regular sized taskbar
(1920, -170, 3840, 910)
PySide2.QtCore.QRect(1920, -170, 1920, 1080)
taskbar at bottom
Using qt's default positioning system
Clock geometry: PySide2.QtCore.QRect(3640, 862, 200, 48)
Font families: ['Segoe UI Variable Display', 'sans-serif']
Font size: 9.3
Full screen rect:  (1920, -170, 3840, 910)
Show or hide loop started with following parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
Restart loop: 1
Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
updates not found


```

## Additional context
System and app language are set to en-GB, but regional settings and non-Unicode formats/system locale are set to ja-JP. Changing app language made no difference.

**Comment by martinet101** [comment]
I really don't know what to say about that... I'll obviously take a look, but I can't guarantee you anything...

**Comment by martinet101** [comment]
Hey, I've been testing and with the next version (2.8), which will be available soon, it works just fine:
![image](https://user-images.githubusercontent.com/53119851/143658183-a7b11415-7a69-46a4-9a0a-488cb13caecc.png)

**Comment by CortanaJPN** [comment]
I’ve updated to version 2.8, but the bug seems to remain. I don’t know if this is due to a settings file that I need to erase, or whether the code wasn’t merged into the latest update.

**Comment by martinet101** [comment]
If you modify your locale does it help?

**Comment by CortanaJPN** [comment]
I’ve tried setting the system locale to both English (United Kingdom) and to Japanese with the same effect.

On 28 Nov 2021, at 17:34, Martí Climent ***@***.***> wrote:

﻿

If you modify your locale does it help?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmartinet101%2FElevenClock%2Fissues%2F302%23issuecomment-981122838&data=04%7C01%7C%7C253bbc012e9940aa381a08d9b2954ff4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737176618174688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mspWxGTy65TfKIYbUmhl3NRfy0%2FUp%2BiB4d2Y3IKkCi4%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSFHPY4CUQMEK35V6MWXQTUOJRZZANCNFSM5IK446LQ&data=04%7C01%7C%7C253bbc012e9940aa381a08d9b2954ff4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737176618184644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZB%2Fs1Sf4h8nCRR4AxP0jnnk6szzmYof3D4JibYHg0RU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C253bbc012e9940aa381a08d9b2954ff4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737176618184644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=T9KNNCGia6pRL4eAismvXC2PrlUx34AymmqPf%2BG%2FCPw%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C253bbc012e9940aa381a08d9b2954ff4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637737176618184644%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nBSbJsYcAaYpeB948FLoA6fQuxjAeocVvLNt%2Bcj5dA4%3D&reserved=0>.

**Comment by martinet101** [comment]
Can you send me your date/time locale format?
