### ISSUE TITLE
[FEATURE REQUEST] Add new option to display the clock on primary screen

### ISSUE THREAD

**Issue by ductien1121988** [martinet101/ElevenClock#306]
I'm using windows 11 and i cant make the system clock display second.
So I'm use this app to display it but there is only 1 option that i can display it on primary screen is align it to the left.
Can you make it to display right on the system clock without select align left? Thank you!

**Comment by martinet101** [comment]
The main reason of it for being disabled is that the clock overlapps the other and it is just ilegible

**Comment by martinet101** [comment]
If disable updates and install 2.6.1 you'll be able to do that

**Comment by ductien1121988** [comment]
Ah I see, hope in the future you can take it back and make a background option for it.
Btw, thank you for this nice app :)

**Comment by martinet101** [comment]
I'm working on adding a solid background, what wouold allow to overlay default clock.
