### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by RIS2000** [martinet101/ElevenClock#307]
Not working at all ((
Windows 11 build 22000.318

---------------------------------------------------------------------------------------------------

   ElevenClock's 2.7.0 (v2.7) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "ru"

---------------------------------------------------------------------------------------------------

system tray icon enabled
Starting update check
61.69921875
<PySide2.QtGui.QScreen(0x21d27c1dab0, name="\\\\.\\DISPLAY4") at 0x0000021D285F7CC0> (2560, 1440, 0, 0, 96.0, [(<PyHANDLE:65537>, <PyHANDLE:0>, (0, 0, 2560, 1440))])
This is primay screen and is set to be skipped
Restart loop: 1
Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
updates not found
64.52734375
<PySide2.QtGui.QScreen(0x21d27c1dab0, name="\\\\.\\DISPLAY4") at 0x0000021D285F7CC0> (2560, 1440, 0, 0, 96.0, [(<PyHANDLE:65537>, <PyHANDLE:0>, (0, 0, 2560, 1440))])
This is primay screen and is set to be skipped
65.2421875
<PySide2.QtGui.QScreen(0x21d27c1dab0, name="\\\\.\\DISPLAY4") at 0x0000021D285F7CC0> (2560, 1440, 0, 0, 96.0, [(<PyHANDLE:65537>, <PyHANDLE:0>, (0, 0, 2560, 1440))])
This is primay screen and is set to be skipped
Restart loop: 2
Restart loop: 1
65.22265625
<PySide2.QtGui.QScreen(0x21d27c1dab0, name="\\\\.\\DISPLAY4") at 0x0000021D285F7CC0> (2560, 1440, 0, 0, 96.0, [(<PyHANDLE:65537>, <PyHANDLE:0>, (0, 0, 2560, 1440))])
This is primay screen and is set to be skipped
65.25
<PySide2.QtGui.QScreen(0x21d27c1dab0, name="\\\\.\\DISPLAY4") at 0x0000021D285F7CC0> (2560, 1440, 0, 0, 96.0, [(<PyHANDLE:65537>, <PyHANDLE:0>, (0, 0, 2560, 1440))])
This is primay screen and is set to be skipped
Restart loop: 2
Restart loop: 1
65.23046875
<PySide2.QtGui.QScreen(0x21d27c1dab0, name="\\\\.\\DISPLAY4") at 0x0000021D285F7CC0> (2560, 1440, 0, 0, 96.0, [(<PyHANDLE:65537>, <PyHANDLE:0>, (0, 0, 2560, 1440))])
This is primay screen and is set to be skipped
65.27734375
<PySide2.QtGui.QScreen(0x21d27c1dab0, name="\\\\.\\DISPLAY4") at 0x0000021D285F7CC0> (2560, 1440, 0, 0, 96.0, [(<PyHANDLE:65537>, <PyHANDLE:0>, (0, 0, 2560, 1440))])
This is primay screen and is set to be skipped
Restart loop: 2
Restart loop: 1

**Comment by martinet101** [comment]
You have only one display attached to your pc...
