### ISSUE TITLE
[ISSUE] Updating the README

### ISSUE THREAD

**Issue by FahimFBA** [martinet101/ElevenClock#309]
I would love to update the README file. If you would let me do that, then I need to know some info regarding that.

1. In which branch should I update now?
2. Should I also add some badges including the license, repo status, etc.?

**Comment by martinet101** [comment]
Yes, to edit it, just open a PR for the main branch.
In terms of badges, i just left those ones because they look good and they aren't too much. some time ago i had more of them and it felt ugly. I would just leave them like they are

**Comment by FahimFBA** [comment]
Thanks. I am working on it. Please assign me for the task.
