### ISSUE TITLE
[FEATURE REQUEST] starting/opening ElevenClock only when connected to external display!

### ISSUE THREAD

**Issue by yazan1107** [martinet101/ElevenClock#312]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated how much power hungry this app is, sometimes i forgot it open while not connected to external display, and it takes resources of my pc, that i could use for other programs!
**Describe the solution you'd like**
Opening ElevenCLock when connecting external display
exiting ElevenCLock only when disconnecting external Display!

**Comment by martinet101** [comment]
Well, elevenClock does only take 35mb of ram and 0% cpu...
![image](https://user-images.githubusercontent.com/53119851/142901715-9ef34015-4ba1-4736-a10e-798fb29bd91a.png)
