### ISSUE TITLE
[BUG] (The Clock of elevenclock(on secondary monitor) does not look like the default windows clock!!)

### ISSUE THREAD

**Issue by yazan1107** [martinet101/ElevenClock#313]
## Before submitting the issue
PLEASE CHECK that there are no open or close issues about the same bug before.

 ✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions
 ✅ I have checked the settings window for an option to toggle/fix what is happening
 ✅ I have installed the lastest version and the issue still happens

## Describe the bug
[BUG] (The Clock of elevenclock(on secondary monitor) does not lock the default windows clock!!)
it does not have the same font neither the same size also the shadow of the text is different!

## Expected behavior
To have the same looks as default windows clock!
## Screenshots
<img width="77" alt="image" src="https://user-images.githubusercontent.com/78726445/142898438-106724b4-4f71-4e85-8042-81b0eaa802e7.png">
<img width="50" alt="image" src="https://user-images.githubusercontent.com/78726445/142898463-d49dc6f1-f06f-49e1-8081-ee6a7dd20d50.png">

**Comment by martinet101** [comment]
For the shadow, it is a thing i've done my best, and i couldn't go further
For the size, ElevenClock adjusts so the display scale, but you can change the font size from the settings
Also, you have seconds enabled, what makes it feel wider
