### ISSUE TITLE
version change gets detected as virus

### ISSUE THREAD

**Issue by Zwangi** [martinet101/ElevenClock#318]
something in the app changed this and windows store download, is it compromised?

\/
G DATA INTERNET SECURITY has blocked malicious software from running on your system.
BEAST (behavior monitoring) identified the malicious software as follows: Generic.0F64A731

The following processes were therefore terminated by G DATA for security reasons:
	----------------------------------------------------------------
	C:\Users\user\AppData\Local\Programs\ElevenClock\ElevenClock.exe
	C:\Users\user\AppData\Local\Temp\tmpkir3i4ig\SomePythonThings-ElevenClock-Updater.exe (PID 21028)
	C:\Users\user\AppData\Local\Temp\is-4B49C.tmp\SomePythonThings-ElevenClock-Updater.tmp (PID 2456)
	----------------------------------------------------------------

G DATA has moved the following responsible programs to quarantine:
	----------------------------------------------------------------
	C:\Users\user\AppData\Local\Programs\ElevenClock\ElevenClock.exe
	C:\Users\user\AppData\Local\Temp\tmpyo2fd0pm\gen_py\dicts.dat
	C:\Users\user\.elevenclock\ElevenClockRunning1638005713.1730344
	C:\Users\user\AppData\Local\Temp\tmpyo2fd0pm\gen_py\__init__.py
	C:\Users\user\AppData\Local\Temp\tmpkir3i4ig\SomePythonThings-ElevenClock-Updater.exe
	C:\Users\user\AppData\Local\Temp\is-4B49C.tmp\SomePythonThings-ElevenClock-Updater.tmp
	C:\Users\user\AppData\Local\Temp\is-NOPER.tmp\_isetup\_setup64.tmp
	C:\Users\user\AppData\Local\Programs\ElevenClock\is-F9EAS.tmp
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\tick_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\launch_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\lang_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\settings_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\restart_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\icon.bmp
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\hide_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\experiment_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\down-arrow_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_pt.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_pl.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\appearance_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\close_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\clock_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\down-arrow_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\datetime_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\datetime_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\close_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\about_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\clock_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\bug_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_zh_CN.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_vi.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\win32gui.pyd
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_he.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\appearance_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_gd.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_sample.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_ru.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_nl.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_nb.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_ja.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_it.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_fi.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_de.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_ca.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_tr.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_es.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_pt.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_pl.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_vi.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_lt.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_ko.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\win32process.pyd
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_zh_TW.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\lang_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\experiment_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_sk.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_ru.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_it.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_nl.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_zh_CN.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_en.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\about_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_zh_TW.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\tools.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\globals.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\opengl32sw.dll
	C:\Users\user\AppData\Local\Temp\_MEI63882\pywintypes39.dll
	C:\Users\user\AppData\Local\Temp\_MEI63882\Include\pyconfig.h
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\qt.conf
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_cs.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_ca.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_es.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_en.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_ja.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_ko.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\base_library.zip
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_de.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_zh_TW.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_fi.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_de.cpython-38.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_es.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_ja.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_sr.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_nb.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_ru.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_id.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_el.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_fr.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_lt.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_ko.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_tr.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\lang_sr.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\bug_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\hide_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\icon.ico
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\restart_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\launch_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\tick_black.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\resources\settings_white.png
	C:\Users\user\AppData\Local\Temp\_MEI63882\__init__.exe.manifest
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_fi.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_fr.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_da.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_de.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\win32api.pyd
	C:\Users\user\AppData\Local\Temp\_MEI63882\settings.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\psutil\_psutil_windows.cp39-win_amd64.pyd
	C:\Users\user\AppData\Local\Temp\_MEI63882\pythoncom39.dll
	C:\Users\user\AppData\Local\Temp\_MEI63882\win32trace.pyd
	C:\Users\user\AppData\Local\Temp\_MEI63882\win32ui.pyd
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_ar.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_bg.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\_win32sysloader.pyd
	C:\Users\user\AppData\Local\Temp\_MEI63882\languages.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_fr.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_id.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_el.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_en.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_lv.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_pl.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_tr.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_uk.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\LOCALE_UPDATER.py
	C:\Users\user\AppData\Local\Temp\_MEI63882\lang\__pycache__\lang_ca.cpython-39.pyc
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_hu.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\PySide2\translations\qtbase_it.qm
	C:\Users\user\AppData\Local\Temp\_MEI63882\__init__.py
	----------------------------------------------------------------

Additional userrmation:
Ref: a6f3f961-35b4-43b8-a8e9-c94af148e815

**Comment by martinet101** [comment]
Nope, the change was intended

**Comment by martinet101** [comment]
Well, some antivirus flag ElevenClock as virus because it is unsigned, but not for being a virus
