### ISSUE TITLE
[BUG] Automatically detect primary monitor change

### ISSUE THREAD

**Issue by sefacndmr01** [martinet101/ElevenClock#319]
**Is your feature request related to a problem? Please describe.**
The clock position stays on the same monitor when I change the primary monitor for my work/gaming situations. It causes the clocks to overlap.

**Describe the solution you'd like**
For solution I need to reboot from context menu. I don't know if there is a method that can detect the primary monitor change. It will be a good experience if the workaround can be improved.

**Comment by martinet101** [comment]
I am aware of this, and it was suposed to be fixed on version 2.8 (Btw, did you update?). I'm going to mark this as a bug then and i'll investigate that

**Comment by martinet101** [comment]
Sorry, I hit the wrong button and closed this accidentally

**Comment by sefacndmr01** [comment]
@martinet101 Yes, i did. Current version is 2.8 and still not detect changes.

**Comment by martinet101** [comment]
OK, definely a bug

**Comment by martinet101** [comment]
Quick update: The screen change event is detected, but the clock does not show on correct position due a Qt5 bug that breaks things. The solucin would be upgrading to Qt6, but when I tried (Release 2.6), it just broke lots of things. I have to study this better.

**Comment by martinet101** [comment]
Since this will be automatically fixed when Qt6 is added, there's no need to have this open
