### ISSUE TITLE
Clock opens in the middle of the first screen

### ISSUE THREAD

**Issue by sudowesu** [martinet101/ElevenClock#32]
When i run the .exe file of the ElevenClock, it spawns the clock in the middle of the first screen instead of the second screen's taskbar.

![resim](https://user-images.githubusercontent.com/67051709/136611146-838b694e-0a8a-4e88-b707-53995249b766.png)

**Comment by gandafl** [comment]
Hi, 
i have the same problem.
Display Setup: 2 4k (3840*2160, 150% scale) Displays and 0-2 additional FullHD Displays (100% scale)

**Comment by martinet101** [comment]
@gandafl @0gamesbookstore, Could you please run the following elevenclock version and send me back the output on the CMD window?

https://somepythonthings.tk/misc/ElevenClock1.9-cmdwindow.exe

Thanks :)

**Comment by gandafl** [comment]
After a reboot version 1.8 works fine. Was just a problem right after installation. Thanks :)

**Comment by mrmangoz** [comment]
I have the same issue. 
Display 1: 1920x1080 175%
Display 2: 1920x1080 175% (main)
Display 3: 1920x1080 175% 

cmd output: 

[WinError 259] No more data is available
yyyy/MM/dd
h:mm tt
%#I:%M %p
%#I:%M %p
%Y/%m/%d
Starting update check
<PySide2.QtGui.QScreen(0x18ec0c6aaa0, name="\\\\.\\DISPLAY2") at 0x0000018EC1CE4440> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
This is primay screen
<PySide2.QtGui.QScreen(0x18ec0c6a560, name="\\\\.\\DISPLAY1") at 0x0000018EC1CE6E40> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
PySide2.QtCore.QRect(-108, 1032, 640, 480)
start
Full screen rect:  (1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x18ec0c6a840, name="\\\\.\\DISPLAY5") at 0x0000018EC1CE6E80> PySide2.QtCore.QRect(1920, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
PySide2.QtCore.QRect(3732, 1032, 640, 480)
start
Full screen rect:  (1920, 0, 3840, 1080)
Focus screen rect:  (837, 426, 1830, 945)
Focus screen rect:  (840, 423, 1833, 942)
Focus screen rect:  (853, 409, 1846, 928)
Focus screen rect:  (857, 403, 1850, 922)
Focus screen rect:  (864, 380, 1857, 899)
Focus screen rect:  (865, 372, 1858, 891)
Focus screen rect:  (866, 358, 1859, 877)
Focus screen rect:  (866, 354, 1859, 873)
Focus screen rect:  (863, 346, 1856, 865)
Focus screen rect:  (860, 342, 1853, 861)
Focus screen rect:  (843, 325, 1836, 844)
Focus screen rect:  (836, 320, 1829, 839)
Focus screen rect:  (819, 307, 1812, 826)
Focus screen rect:  (815, 303, 1808, 822)
Focus screen rect:  (807, 295, 1800, 814)
Focus screen rect:  (805, 292, 1798, 811)
Focus screen rect:  (795, 280, 1788, 799)
Focus screen rect:  (795, 277, 1788, 796)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
updates not found
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)
Focus screen rect:  (792, 272, 1785, 791)

**Comment by JordanIII** [comment]
I have the same problem as well, here's my setup:
Display 1: 1920 x 1080 125% (main)
Display 2: 1920 x 1080 150%

When I ran the file posted above I got the following output:
[WinError 259] No more data is available
d-M-yyyy
HH:mm
%H:%M
%H:%M
%#d-%#m-%Y
Starting update check
<PySide2.QtGui.QScreen(0x1af8ec4efa0, name="\\\\.\\DISPLAY1") at 0x000001AF8F7417C0> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 120.0, 120.0)
This is primay screen
<PySide2.QtGui.QScreen(0x1af8ec4efe0, name="\\\\.\\DISPLAY4") at 0x000001AF8F741A00> PySide2.QtCore.QRect(1920, 0, 1920, 1080) (1920, 1080, 144.0, 144.0)
PySide2.QtCore.QRect(3678, 1008, 640, 480)
start
Full screen rect:  (1920, 0, 3840, 1080)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
updates not found
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (128, 128, 1247, 775)
Focus screen rect:  (184, 158, 1303, 805)
Focus screen rect:  (419, 272, 1538, 919)
Focus screen rect:  (693, 420, 1812, 1067)
Focus screen rect:  (820, 503, 1939, 1150)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (824, 506, 1943, 1153)
Focus screen rect:  (823, 481, 1942, 1128)
Focus screen rect:  (823, 432, 1942, 1079)
Focus screen rect:  (824, 364, 1943, 1011)
Focus screen rect:  (824, 295, 1943, 942)
Focus screen rect:  (822, 181, 1941, 828)
Focus screen rect:  (820, 97, 1939, 744)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (819, 79, 1938, 726)
Focus screen rect:  (790, 74, 1909, 721)
Focus screen rect:  (682, 74, 1801, 721)
Focus screen rect:  (524, 83, 1643, 730)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)
Focus screen rect:  (503, 86, 1622, 733)

**Comment by martinet101** [comment]
I'm sorry, those commints were referred for issue #33, but i wrote a wrong name. I am still looking for a solution

**Comment by CmdrKeen4** [comment]
Not sure if this is the same issue or not, but my clock is also not showing in the correct position; the clock is in the correct position on 3 of my monitors, but the clock from my fourth monitor is in the middle of the taskbar on my second monitor...
![Screenshot 2021-10-09 230501](https://user-images.githubusercontent.com/92238042/136678716-5683f6c9-3943-4abc-8052-88eaf32271d3.png)
