### ISSUE TITLE
Replace system clock with ElevenClock

### ISSUE THREAD

**Issue by Protoncek** [martinet101/ElevenClock#321]
Hello!
I just recently found your great software and with today's update it should replace system clock on primary monitor, too, but in my case it overwrites it instead (with system clock still visible, so now i have both on same location bottom right corner). I didn't find a way to turn off original windows clock. What am i missing? 

Any advice would be welcome...

Thanks!

Best regards, Pavel

**Comment by martinet101** [comment]
You need to enable select a custom color under appearance, and click on the bottom-right corner of the screen. Let me show:
![image](https://user-images.githubusercontent.com/53119851/143763692-25598c67-c62e-4c02-865c-53489b2a120d.png)
For step 4, click anywhere on the taskbar background (next to the white square)
![image](https://user-images.githubusercontent.com/53119851/143763715-e1dfb624-4718-4e28-8c6e-4c097e1ac531.png)

**Comment by martinet101** [comment]
And there you go ![image](https://user-images.githubusercontent.com/53119851/143763769-7ad2a625-b2f3-491e-867d-fd59f94fc519.png)

**Comment by Protoncek** [comment]
Aaaaa.... nice one... sneaky, too... masking original clock with background color... many thanks!!

**Comment by richardlawley** [comment]
The custom background colour gets quite close to working, but elevenclock doesn't account for the notification icon if it is displayed, e.g.

![image](https://user-images.githubusercontent.com/1608083/143830972-a8f7d6c1-f4d8-4876-888c-ab0e61203c94.png) ElevenClock not shown on primary screen

![image](https://user-images.githubusercontent.com/1608083/143830778-19406b8f-690d-49b7-8ae4-6525af57f464.png) No custom background colour

![image](https://user-images.githubusercontent.com/1608083/143831047-113098b2-5427-4bab-a11e-dba8d74fbf67.png) With custom background colour (not quite matching, but you get the idea!)

Suggestion: Make custom background colour default to the start menu's colour

**Comment by martinet101** [comment]
Can you oopen a new isssue please ?
