### ISSUE TITLE
[BUG] "Show the clock on primary screen" doesn't account for notifications

### ISSUE THREAD

**Issue by richardlawley** [martinet101/ElevenClock#326]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the lastest version and the issue still happens<br>
</b>

## Describe the bug
Using "Show the clock on primary screen" with "Custom Background Colour" gets quite close to working, but elevenclock doesn't account for the notification icon if it is displayed, resulting in incorrect drawing.

## To Reproduce
1. Enable "Show the clock on primary screen" option
2. Get a notification in Windows (e.g. new email)
3. Observe incorrect drawing

## Expected behavior
Overlayed clock should be positioned over Windows clock.

## Screenshots
![image](https://user-images.githubusercontent.com/1608083/143830972-a8f7d6c1-f4d8-4876-888c-ab0e61203c94.png) ElevenClock not shown on primary screen

![image](https://user-images.githubusercontent.com/1608083/143830778-19406b8f-690d-49b7-8ae4-6525af57f464.png) No custom background colour

![image](https://user-images.githubusercontent.com/1608083/143831047-113098b2-5427-4bab-a11e-dba8d74fbf67.png) With custom background colour (not quite matching, but you get the idea!)

**Comment by jmlcoliveira** [comment]
Same problem happens if Focus Assist is turned on

**Comment by rigtigeEmil** [comment]
I have a related issue. If I enable week display (Date & Time Settings > Show week number on the clock), it doesn't account for the extra space the clock takes up.

With default clock:
![image](https://user-images.githubusercontent.com/70773323/145708047-b3baa602-634b-4f57-8b10-e3923b3d86ad.png)
With ElevenClock:
![image](https://user-images.githubusercontent.com/70773323/145708053-95dcd9b6-43f5-46a4-ba71-c08e6673b847.png)

**Comment by martinet101** [comment]
Hi, as you might have seen, the issue has not been fixed yet, and this is because i've found no way to detect if there are unread notifications or not. Anyway, i'm still working on it.

**Comment by martinet101** [comment]
It is closer, coming probably in the next release:

![image](https://user-images.githubusercontent.com/53119851/147579527-95a63c88-ddcf-46d1-ac47-4cd30c8937ca.png)

**Comment by martinet101** [comment]
I've added the notification counter, coming in the next release
