### ISSUE TITLE
Clock is displaying over the top of my system tray icons. How can I get it to sit beside those icons please?

### ISSUE THREAD

**Issue by thewizard-oz** [martinet101/ElevenClock#327]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the lastest version and the issue still happens<br>
</b>

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 mintues, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by thewizard-oz** [comment]
I just cannot see anywhere for a setting to choose the position of the clock in relation to any other Windows screen component.

Thanks.

**Comment by jasonkuehl** [comment]
Seeing this as well on a vertical screen

![image](https://user-images.githubusercontent.com/9578513/143916452-28eff7d0-b562-409f-9ef8-312376d15ec0.png)

**Comment by martinet101** [comment]
This is a thing i can't really modify, see https://github.com/martinet101/ElevenClock/issues/196

**Comment by martinet101** [comment]
An option is going to be added to hide the clock during 10s after being clicked. It might help with the overflow issues
![image](https://user-images.githubusercontent.com/53119851/147821562-f44ab86c-d709-419e-b822-cc91510ed30e.png)
Coming with the next version!
