### ISSUE TITLE
install\update with chocolatey

### ISSUE THREAD

**Issue by tony-asu** [martinet101/ElevenClock#334]
it'd be cool if this could be installed\updated via [chocolatey](https://chocolatey.org/).

**Comment by martinet101** [comment]
I'll take a look, but it is already published on winget and ms store, and it updates automatically

**Comment by DukeW** [comment]
+1
Chocolaty is just more mature than winget.

**Comment by BobSammers** [comment]
+1 for Chocolatey - much more widely used (at least currently).

**Comment by mikedepetris** [comment]
+1 for Chocolatey
