### ISSUE TITLE
[BUG] Show clock on primary screen overlaps main clock

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#335]
![image](https://user-images.githubusercontent.com/22828430/144244349-60fdd1e6-f207-485c-a3fe-ad3022a25d41.png)

**Comment by martinet101** [comment]
See #333

**Comment by martinet101** [comment]
You basically have to set a custom background color. To get the taskbar's background color you can open the color picker, click _Pick screen color_ and click next to the clock

**Comment by martinet101** [comment]
Anyway, i've added an alert to indicate the user that it must set a background color

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/144284732-a563b071-ba82-47c9-9afa-c9f14128d5bf.png)
