### ISSUE TITLE
[BUG] Some full screen apps overlap with clock

### ISSUE THREAD

**Issue by epizarro2** [martinet101/ElevenClock#337]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the lastest version and the issue still happens<br>
</b>

## Describe the bug
When set full screen in chrome, the clock overlap. For example, youtube in full screen can't access to button

## To Reproduce
Install
Set second screen corner
Open youtube with chrome
set full screen
cant exit with button, but esc

## Expected behavior
Cant press buttons, clock overlaps some 3rd party full screen apps

## Screenshots
![Captura de pantalla 2021-12-02 102350](https://user-images.githubusercontent.com/49302511/144430405-80c7412e-a87d-4b04-af27-fda8e9986ddd.png)

## The Log

```
All normal

```

**Comment by martinet101** [comment]
Hi @epizarro2, first of all, let me say that I really appreciate thhat you put the best video ever as a demo for the bug.

Anyway, have you enabled "hide on fullscreen" from the settings window?

**Comment by epizarro2** [comment]
Sry, my bad. Now it's OK, thanks for this piece of software.
