### ISSUE TITLE
[BUG] Duplicate instances running

### ISSUE THREAD

**Issue by ZephireNZ** [martinet101/ElevenClock#339]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the lastest version and the issue still happens<br>
</b>

## Describe the bug
In the last few days, when I check my taskbar I can see two ElevenClock icons, and Process Monitor confirms two instances are running.

## To Reproduce
Unsure

## Expected behavior
Only one instance of ElevenClock should be active.

## Screenshots
Taskbar:
![image](https://user-images.githubusercontent.com/1644496/144487478-7fd876a4-5f8c-4da3-bb20-e2e01247f9dd.png)

Process Monitor:
![image](https://user-images.githubusercontent.com/1644496/144487855-ac271176-2455-4cf1-b4d3-37abb5e1b220.png)

## The Log

First instance
```
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.8.0 (v2.8) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🟦: Information
 🟩: Task completed successfully
 🟨: Expected warning
 🟧: Unexpected warning
 🟥: Error

🟦 System tray icon enabled
🟦 Starting update check
🟨 This is primay screen and is set to be skipped
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (1920, 0, 3840, 1080)
🟦 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Restart loop: 1
🟦 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟩 Updates not found
🟥 Traceback (most recent call last):

🟥   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 260, in isElevenClockRunning

🟥 FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\brynl\\.elevenclock\\ElevenClockRunning1638441685.609692'

🟥 Note this traceback was caught by reporter and has been added to the log ([WinError 2] The system cannot find the file specified: 'C:\\Users\\brynl\\.elevenclock\\ElevenClockRunning1638441685.609692')

```

Second Instance:
```
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.8.0 (v2.8) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🟦: Information
 🟩: Task completed successfully
 🟨: Expected warning
 🟧: Unexpected warning
 🟥: Error

🟦 System tray icon enabled
🟦 Starting update check
🟨 This is primay screen and is set to be skipped
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (1920, 0, 3840, 1080)
🟦 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟦 Restart loop: 1
🟦 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟩 Updates not found
```

## Additional context
N/A

**Comment by martinet101** [comment]
This happens always?

Because there could have been a 1 in a 1000000 coincidence where both instances removed the lock file...

**Comment by ZephireNZ** [comment]
I've noticed it a few times in the last week. I've just closed down both fully, and startd up one instance. I'll let you know if/when it happens again.

**Comment by martinet101** [comment]
Try uninstalling, deleting the .elevenclock directory and installing again, and see what happens

**Comment by martinet101** [comment]
This should be fixed with the next version, coming in the following days. If it continues happening, please reopen this issue

**Comment by ZephireNZ** [comment]
I am still getting this on v3.0.0.

I am probably closing a duplicate version once a day. I had it just now - and it was actually flickering on my taskbar one with notifications and one without (presumably the two instances fighting)

**Comment by martinet101** [comment]
Could you please uninstall ElevenClock and reinstalling it? Also, can you check task manager for startup apps?

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/148428771-f73a2fcc-36e0-4320-8f85-d06ffa9f4b50.png)

**Comment by ZephireNZ** [comment]
Hi there - ElevenClock is in my Startup apps and is Enabled. There is only one, as far as I can tell. It points to `C:\Users\brynl\AppData\Local\Programs\ElevenClock\ElevenClock.exe`.

 I have just reinstalled (and from the Windows Store, not exe), we'll see if that makes a difference.

**Comment by anossovs** [comment]
![image](https://user-images.githubusercontent.com/8104628/148668114-aae11761-53d1-489a-8f6d-9ee7d9ee7953.png)
Same issue on my end

**Comment by mikedepetris** [comment]
![image](https://user-images.githubusercontent.com/19190720/148673034-14e54710-2451-43c9-ab81-52ed1bb4ae3b.png)
Some more info

**Comment by martinet101** [comment]
@mikedepetris, please try uninstalling and reinstalling from the store

**Comment by mikedepetris** [comment]
> @mikedepetris, please try uninstalling and reinstalling from the store

ok fixed here, thanks

**Comment by dktz** [comment]
I'm still having same issue with v4.1.0 running. Any fix around to mitigate this disturbing issue?

![ElevenClock v4 1 0 Issue multiple instances running](https://user-images.githubusercontent.com/2401236/232037727-51fb6979-39aa-4649-adbb-c1b3f52a1a49.png)

**Comment by marticliment** [comment]
Have you tried manually deleting the .elevenclock folder placed in your user directory?
