### ISSUE TITLE
[BUG] Hover effect not aligned properly

### ISSUE THREAD

**Issue by corwinx** [martinet101/ElevenClock#34]
App version: 1.8

Primary monitor: 2560x1440p 125% scale
Secondary monitor: 1920x1080p 100% scale

Hover effect behind clock is mis-aligned / too far left

![image](https://user-images.githubusercontent.com/44034372/136614996-f97c154b-cb73-4b32-a0d7-7ff04691ab27.png)

**Comment by Alfex4936** [comment]
same here and also is there a way to change the font scale or something? as it's not clear

App
![second](https://user-images.githubusercontent.com/2356749/136653363-b969a9d2-af83-43d6-bab5-d78858491e4e.png)
Original
![first](https://user-images.githubusercontent.com/2356749/136653393-b300a504-2ddf-4922-a6dd-cf8c9de22148.png)

Monitor setup:
![monitor](https://user-images.githubusercontent.com/2356749/136653368-7a470471-0028-4c96-907c-8579a7ca6ffe.png)
