### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by feistmann** [martinet101/ElevenClock#341]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the lastest version and the issue still happens<br>
</b>

## Describe the bug
It isn't working.  Display of time and date is the same as before I downloaded - no seconds - BUT for a brief time after I installed the app it showed time in seconds partially superimposed over the W11 time/date display.

I've tried changing settings.  No luck.

I can't reproduce it.  Sorry.

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 mintues, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by feistmann** [comment]
ElevenClock's 2.8.0 (v2.8) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🟦: Information
 🟩: Task completed successfully
 🟨: Expected warning
 🟧: Unexpected warning
 🟥: Error

🟦 System tray icon enabled
🟦 Starting update check
🟨 This is primay screen and is set to be skipped
🟦 Restart loop: 1
🟦 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟩 Updates not found

**Comment by Masamune3210** [comment]
Do you only have one monitor? By default ElevenClock is set to ignore the primary monitor unless you manually change the setting to allow it to draw on all monitors

**Comment by feistmann** [comment]
I use an external monitor through an HDMI cable, and have the PC monitor disabled.  When I click on “Show the clock in the primary scree” I get what appears to be a double image, but with seconds.  Do I need to disable the W11 clock display?  If so, how?  Thanks.

**Comment by martinet101** [comment]
See #333.
You simply need to set a custom background color (In #333 it explains how to get similar background color.)

This fearture is undocumented and i'm working on making it better

**Comment by feistmann** [comment]
I’m on Win11, and can’t find the screens shown.  Am I missing something?

An earlier response said “Do you only have one monitor? By default ElevenClock is set to ignore the primary monitor unless you manually change the setting to allow it to draw on all monitors.”  I use an external monitor, but when I set Win11 to display both monitors, nothing changes.

**Comment by feistmann** [comment]
I got it.  Thanks!
