### ISSUE TITLE
not hidden on youtube 

### ISSUE THREAD

**Issue by XtopherF** [martinet101/ElevenClock#345]
There is a problem when there is full screen, I want to remove the full screen of a video but the icon is on the time button and the button cannot be pressed, instead of it clock settings appear, this problem occurs with youtube on edge 
![image](https://user-images.githubusercontent.com/90878611/144756096-9f9f71c4-6e97-4aeb-91f7-578904b7b895.png)

**Comment by martinet101** [comment]
Go to ElevenClock Settings -> Clock settings -> Hide when an app is in fullscreen
