### ISSUE TITLE
[FEATURE REQUEST] Add the option to customize date and time format

### ISSUE THREAD

**Issue by bromelio** [martinet101/ElevenClock#350]
Hi computer genius,

very nifty and useful tool, thanks for making it!

However, when adding the weekday on the clock (which is great to have!), the clock shows 3 lines (also see attached screehshot):
hh:mm:ss
DDDD
dd.mm.yyyy

...nearly without any taskbar above and below it any more, which doesn't really look good. Can you therefore please introduce a more compact format like...

DD, hh:mm:ss
dd.mm.yyyy

for e.g.

Mon, 12:00:00
01.01.2022

Then in my view ElevenClock would be perfect!

Many thanks in advance! :-)

<img width="69" alt="weekday format" src="https://user-images.githubusercontent.com/8458358/145026478-5efa11b2-369a-4d81-a490-56af7593a7a5.png">

**Comment by martinet101** [comment]
To do this, you will need to change your regional settings. You can go to ElevenClock settings, then date & time, then open regional settings, and funnaly there you would need to set the custom strings

**Comment by martinet101** [comment]
Anyway, I had some ideas into personalizing date and time formats

**Comment by bromelio** [comment]
Thanks for the super-quick response!

**Comment by martinet101** [comment]
Check #380
