### ISSUE TITLE
[BUG] "Rellotge" isn't translated when using Spanish

### ISSUE THREAD

**Issue by Numeritxs** [martinet101/ElevenClock#351]
## Describe the bug
"Rellotge" isn't translated to Spanish.

## To Reproduce
1. Go to 'Configuración de ElevenClock'
2. Swipe down until you get to "Configuración del reloj"
3. Notice that in the forth option, "Reloj" is wroten as "Rellotge", as if chosen language was Catalan.

## Expected behavior
"Rellotge" is translated to "Reloj"

## Screenshots

![Captura de pantalla 2021-12-08 140605](https://user-images.githubusercontent.com/72006751/145213372-20cb187d-0c47-4b0d-a230-17f9db79a127.png)

## Additional context
The issue is fixed if we change lang_es.py's line 82 to show "Reloj" instead of "Rellotge".

Bones festes i bona entrada d'any!

**Comment by martinet101** [comment]
Ups, yes, didn't realise when translating😅

**Comment by martinet101** [comment]
Fixed, coming with next version
