### ISSUE TITLE
[ISSUE] Notification pane appear on primary screen only

### ISSUE THREAD

**Issue by Vayth** [martinet101/ElevenClock#353]
When I click the clock on any other screen, the notification keep appearing on my primary screen. Is there a way to work around that so the notification appears on where the clock is clicked?

**Comment by martinet101** [comment]
That has to be with windows 11, because the clock click simulates the <kbd>Win</kbd>+<kbd>N</kbd>. If MS ever happens to show the notifications pane on the screen where the mouse is present, this will be automatically fixed.
