### ISSUE TITLE
[BUG] Clicking the clock it doesn't open the Action Center

### ISSUE THREAD

**Issue by TechStudent11** [martinet101/ElevenClock#354]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
</b>

## Describe the bug
For some reason, when I click the clock, the Action Center doesn't open. Instead, some weird, Xbox-looking thing pops up. See screenshots below.

## To Reproduce
Steps to reproduce the behaviour:
1. Click the clock
2. Weird, Xbox-looking pops up.

## Expected behaviour
The Action Center opens when I click the clock.

## Screenshots

_Weird, Xbox-looking thing_

![image](https://user-images.githubusercontent.com/76978184/145289616-da2d1fff-1804-4491-9fc9-de705470e182.png)

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.8.0 (v2.8) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🟦: Information
 🟩: Task completed successfully
 🟨: Expected warning
 🟧: Unexpected warning
 🟥: Error

🟦 System tray icon enabled
🟦 Starting update check
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (0, 0, 1920, 1080)
🟦 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟦 Using bg color: 0, 0, 0, 0
🟩 Regular sized taskbar
🟦 Monitor geometry: PySide2.QtCore.QRect(-1920, 466, 1920, 1080)
🟩 Taskbar at bottom
🟨 Clock on the left
🟩 Using qt's default positioning system
🟦 Clock geometry: PySide2.QtCore.QRect(-200, 1498, 200, 48)
🟦 Font families: ['Segoe UI Variable Display', 'sans-serif']
🟦 Font size: 9.3
🟩 Using white text (dark mode)
🟦 Full screen rect:  (-1920, 466, 0, 1546)
🟦 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟦 Restart loop: 1
🟦 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟩 Updates not found

```

**Comment by martinet101** [comment]
See #353

**Comment by milantheiss** [comment]
I have encounted the same bug.
I found PowerToys Feature "Video Conference Mute" was causing the bug in my case.
After deactivating the feature I was able to access the Action Center by clicking on the clock.
I run Version 0.55.0 of PowerToys.

![Screenshot 2022-02-02 201005](https://user-images.githubusercontent.com/60037272/152222863-191aed06-28a5-4036-964a-df3abec06669.png)

**Comment by TechStudent11** [comment]
> I have encounted the same bug. I found PowerToys Feature "Video Conference Mute" was causing the bug in my case. After deactivating the feature I was able to access the Action Center by clicking on the clock. I run Version 0.55.0 of PowerToys.
> 
> ![Screenshot 2022-02-02 201005](https://user-images.githubusercontent.com/60037272/152222863-191aed06-28a5-4036-964a-df3abec06669.png)

Makes sense. Thanks!
