### ISSUE TITLE
[FEATURE REQUEST] Show Multiple Clocks

### ISSUE THREAD

**Issue by ChrisRomp** [martinet101/ElevenClock#357]
**Is your feature request related to a problem? Please describe.**
**_THANK YOU_** for building this. Saved me some time _(pun intended)_. I'll buy you a ☕.  I frequently reference time in UTC, however.

**Describe the solution you'd like**
One thing I would love is if I could have it show an additional clock/time zone (e.g., UTC) along with my local time.  I know I can click on it, and that's ok as a workaround.

**Comment by martinet101** [comment]
You mean something like #5?

**Comment by ChrisRomp** [comment]
Sort of, but showing full time, not just on hover.  Even if it was just a pair of clocks side by side, like 2 instances of however you're getting it to display, one per zone.

**Comment by martinet101** [comment]
Ok, seems a good idea. I'll take a look, but i can't grant anything

**Comment by ChrisRomp** [comment]
I wonder if there's a way someone could run two instances, and set one to another TZ?

**Comment by DanCrewger** [comment]
I would love something like this! Let me set up & name my timezones, then switch between them. I work in an international team and knowing how late it is for everyone is a big pain. Having a lightweight solution to this (other than bookmarking timeanddate.com) would be amazing!

![New Project (25)](https://user-images.githubusercontent.com/20373490/154127677-1169f62d-4cc7-47c8-9c7d-176c0743669e.png)

**Comment by martinet101** [comment]
Yes, I'm sorry guys, but I've been busy and i've not done that yet. I can't give you any ETA, but it is pending (just see that I haven't closed the issue)

**Comment by DanCrewger** [comment]
Not at all meant to push you, greatly appreciate what you do, a total life saver! And I'm a product manager myself, so I get the issue with feature requests and limited resources ;) Just thought by adding that I would like this I would confirm to you that there is need for this :) 

Thanks!

**Comment by martinet101** [comment]
Could this help (having them in the tooltip)?
![image](https://user-images.githubusercontent.com/53119851/161381456-236f09e0-8cf7-4fa4-9c7a-f64223056b1d.png)

**Comment by ChrisRomp** [comment]
I like it.

**Comment by DanCrewger** [comment]
Yes, I like it as well!

**Comment by martinet101** [comment]
Due to the inconvenients and difficulties among implementing extra clocks, since the tooltip ius already present i'm not gonna implement the extra clocks, because it is difficult and hard to do, and i don't have much free time :/

**Comment by ChrisRomp** [comment]
No worries at all, @martinet101.  Also FYI the tooltip is showing the same time for all zones, but that's a separate issue. :)

**Comment by martinet101** [comment]
yes, it is an open issue., Could you polease post there your log and export ypour elevenClock settings and post them there also?
