### ISSUE TITLE
[BUG] (ElevenClock cannot display on my 2nd screen after updated)

### ISSUE THREAD

**Issue by pwphraewa** [martinet101/ElevenClock#360]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by martinet101** [comment]
If you launch the clock again, does it work?

**Comment by martinet101** [comment]
Fixed, please reinstall
