### ISSUE TITLE
[ISSUE] Brief Description

### ISSUE THREAD

**Issue by Roystoned** [martinet101/ElevenClock#363]
Please have a less intrusive updater, it pops up and takes over the screen in the middle of games, work presentations etc...

**Comment by martinet101** [comment]
Hey @Roystoned, 

You can either:
1. Enable silent updates (Most recommended): Elevenclock will update but in the background. You won't see any changelog or nothing
2. Disable automatic update installing. You will be notified when an update is ready.
3. Disable automatic update checking (not recommended): Disable updates
