### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by gril002** [martinet101/ElevenClock#365]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
</b>

## Describe the bug
After the latest update, ElevenClock crashes on startup

## To Reproduce
Steps to reproduce the behaviour:
1. Update to version 2.9.0
2. Try to launch

## Expected behaviour
The program launches correctly

## The Log

```
                        OS: Windows
                   Release: 10
           OS Architecture: AMD64
          APP Architecture: 64bit
                   Program: ElevenClock
-----------------------------------------------------------------------------------------
ElevenClock Log:
Traceback (most recent call last):
Unable to get traceback<class 'UnicodeDecodeError'>: 'charmap' codec can't decode byte 0x98 in position 19621: character maps to <undefined>

```

## Additional context
Unable to generate the normal log as the program crashes so I am not able to generate it with the instrctions provided. This included log is from the crash report that opens the SomePythonThings Error Report on startup. I have also sent the report through that.

As the log implies that there are Unicode charracter problems, my username does include non ASCII charracters, however the user path does not.

**Comment by martinet101** [comment]
Yes, i've recieved many reports like that one. Try installing 2.9.0-rc2: https://github.com/martinet101/ElevenClock/releases/download/2.9-rc2/ElevenClock.Installer.exe

**Comment by gril002** [comment]
Yep, that fixed it, thanks!
