### ISSUE TITLE
[ISSUE] Brief Description

### ISSUE THREAD

**Issue by JohnnyC00L** [martinet101/ElevenClock#37]
Hi. If I'm watching a video in fullscreen mode on youtube for example, the clock is still visible and appears over the button for exit fullscreen video mode.
![Screenshot_1](https://user-images.githubusercontent.com/92223995/136666801-334a2c3e-2728-437d-b432-2d080a944022.png)

**Comment by urifoox** [comment]
This is a duplicate issue.

See: https://github.com/martinet101/ElevenClock/issues/33 including an exe to download in debug mode to paste results so further troubleshooting can be done/
