### ISSUE TITLE
[BUG] (Clock on Primary Display does not account for Focus Assist)

### ISSUE THREAD

**Issue by TECHSPERT50** [martinet101/ElevenClock#372]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
</b>

## Describe the bug
When focus assist is set to Priority/Alarms only mode, a moon icon appears on the taskbar, to inform you of this. This shifts where the windows 11 taskbar clock is, and elevenclock does not account for this move.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'windows 11 Control Centre'
2. Click on 'Focus assist'
3. Use either Priority/Alarms Only modes
4. See Incorrect position of elevenclock

## Screenshots
![image](https://user-images.githubusercontent.com/92092170/145798527-aba41744-373c-471a-ae2a-98521e9475ce.png)
Focus Assist Off
![image](https://user-images.githubusercontent.com/92092170/145798757-63ec42b2-0e3e-4c56-94bc-9ec5630ad962.png)
Focus Assist On With either Priority Or Alarms Only modes.
![image](https://user-images.githubusercontent.com/92092170/145799287-583d3513-2486-4bed-85d0-d5c2d47ab6f0.png)
Windows 11 Clock With Moon icon, with Eleven clock turned off.

## Potential Solutions
You could either make Eleven clock follow the taskbar clock, or to make it visually flow better,
You could make eleven clock detect when the Focus assist is on, and have it show the moon icon as part of eleven clock on the end, making sure it is big enough to cover the windows 11 clock and moon icon underneath

**Comment by TECHSPERT50** [comment]
I just noticed there is a comment on #326 which mentions this. Should I close this? They are similar issues, but are significant enough to both be separate. This also goes into more detail of this part of the issue #326

**Comment by martinet101** [comment]
Nah, I would keep this open, becayse the implementation of the solutions is different between both issues

**Comment by martinet101** [comment]
Hi, as you might have seen, the issue has not been fixed yet, and this is because i've found no way to detect if the focus assistant is open or not. Anyway, i'm still working on it.

**Comment by TECHSPERT50** [comment]
Im not to sure if this article would be helpful or not, but it talks about a way to detect the status of focus assist. https://stackoverflow.com/questions/53407374/is-there-a-way-to-detect-changes-in-focus-assist-formerly-quiet-hours-in-windo

**Comment by martinet101** [comment]
Mhmm, that looks interesting... I'll take a closer look...

**Comment by martinet101** [comment]
It's closer...
![image](https://user-images.githubusercontent.com/53119851/147503050-589f4dec-497d-4b61-8fd8-96921517e2bd.png)

It will probably come with the next release

**Comment by TECHSPERT50** [comment]
That looks awesome! I can't wait to have this on my PC.

**Comment by martinet101** [comment]
The feature has been implemented and will come with the next release. If you can't wait, you can always build your own ElevenClock version. More info here: https://github.com/martinet101/ElevenClock/wiki/source-code

The commit to clone is this one: https://github.com/martinet101/ElevenClock/tree/eabb77630d722872b4a9d9e229af521523b9d4ce
