### ISSUE TITLE
[FEATURE REQUEST] Show Date and Time On (Closed) Application Icon Hover

### ISSUE THREAD

**Issue by TurtleP** [martinet101/ElevenClock#373]
**Is your feature request related to a problem? Please describe.**
This isn't necessarily a problem, though something I've thought about recently. It would be nice to have it so that ElevenClock could show the current date and time information (like #5) when the user hovers the closed taskbar icon, like in this screenshot:

![image](https://user-images.githubusercontent.com/6239208/145859840-12668e6b-1240-4d78-93f5-844fef79ad53.png)

This should be a completely optional setting, should it be implemented. I find that it would pair nicely when using something like RoundedTB and the system tray area is hidden.

**Describe the solution you'd like**
When the Settings menu is closed and the option for this feature is enabled, ElevenClock should show the Date and Time (or perhaps just the time? Could be customized I suppose).

**Comment by martinet101** [comment]
You mean hovering the system tray icon or the _application_ icon?

**Comment by TurtleP** [comment]
The application icon, as pictured above.

**Comment by TurtleP** [comment]
I updated the Issue title, hopefully it makes more sense as well. If you need any more details, please let me know.

**Comment by martinet101** [comment]
Oh, Now I understand what you were meaning. I'm sorry, but I can't do that, since the title for the icon is taken straight away from the .exe file, which does not allow me to modify it. Anyway, I guess this can be implemented in the system tray icon
