### ISSUE TITLE
[FEATURE REQUEST] Show clock only on primary screen

### ISSUE THREAD

**Issue by wischi-chr** [martinet101/ElevenClock#378]
**Is your feature request related to a problem? Please describe.**
Yes, kind of. I only have the task bar enabled on my primary screen and I don't think there is an option (or at least I can't find it) to only show the clock on the primary screen.

**Describe the solution you'd like**
Add an option to only draw the clock on the primary screen on not on the secondary screens.

**Comment by martinet101** [comment]
Oh, I see. Let me take a look

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/146429813-e8cb0d8a-74dc-4f58-beb1-7dd7bc938b20.png)
Coming on next version, make sure to stay tuned!

**Comment by wischi-chr** [comment]
Wow that was fast. Thank you very much.

**Comment by martinet101** [comment]
Hey, you can now update and try out the feature!
