### ISSUE TITLE
[FEATURE REQUEST] Options for better alignment / formatting

### ISSUE THREAD

**Issue by wischi-chr** [martinet101/ElevenClock#379]
**Is your feature request related to a problem? Please describe.**
At the moment the size of the clock is automatically determined by the text that is displayed, the font size and so on. That makes it hard (if not impossible) to exactly overlay the original clock.

**Describe the solution you'd like**
It would be great if we could (opt-in) set the coordinates (or offsets to a screen edge) x, y, width, height and the box is fixed in place - no matter what - and the text is centered / aligned inside the box (and in edge cases where the font is to large for example) clipped at the edge of the box.

**Comment by martinet101** [comment]
I'll take a look, but that wouldn't help with overlaying the originaal clock...

**Comment by martinet101** [comment]
Ok, I understood you wrong. Now i get what you meant. And yes, this will eventually be implemented

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/149014407-3810d264-b2bc-4335-9046-f901a9610d51.png)
![image](https://user-images.githubusercontent.com/53119851/149014363-6512e3c2-7ad2-482d-8fb6-c45fa9a5fb47.png)
Coming in the next version!

**Comment by martinet101** [comment]
Sorry for it for taking that long :(

**Comment by wischi-chr** [comment]
Thank you for implementing that. No need to apologize, I'm grateful that you maintain such a nice tool.
