### ISSUE TITLE
Elevenclock doesn't change on system time change

### ISSUE THREAD

**Issue by kwiksilver3441** [martinet101/ElevenClock#383]
Read above, elevenclock doesn't react when system time changes. Clock resets correctly on app opening. To reproduce just change Window's time zone settings.

**Comment by martinet101** [comment]
Yes, i've found no way to detect this change, there's a closed issue somewhere explaining this... I would hve to make some bindings ffor the win32 events, which is a thing i have in mind, but what I think is not really possible...
