### ISSUE TITLE
[BUG] "Access denied" while updating

### ISSUE THREAD

**Issue by TechStudent11** [martinet101/ElevenClock#392]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
</b>

## Describe the bug
ElevenClock was updating when I got this error. Pressed "Try again" a couple of times but it won't work. I don't think skipping the file would help too because it copying the literal ElevenClock EXE.

## To Reproduce
Steps to reproduce the behaviour:
1. Update ElevenClock

## Expected behaviour
ElevenClock should update without any issues.

## Screenshots

_Error_

![image](https://user-images.githubusercontent.com/76978184/146652771-82708d03-ae25-4833-900c-769948c24498.png)

_ElevenClock is still running_

![image](https://user-images.githubusercontent.com/76978184/146652797-a496108e-3fc6-4d74-bf57-52e080555252.png)

## The Log

```
Can't paste the log because, well, I can't even get into ElevenClock.
```

## Additional context
I got a "Welcome to ElevenClock!" notification that does nothing when I click on it. ElevenClock is still running though.

**Comment by Masamune3210** [comment]
Probably would be smart to either warn at the start of the install to close ElevenClock or autoclose it and spawn it at the end of the update

**Comment by martinet101** [comment]
Well, when updating, the installer should kill ElevenClock... I you install an older version and let ElevenClock update does it happen always?

**Comment by martinet101** [comment]
And the "Welcome to ElevenClock" notification is actually from the latest version, because this was a new feature...

**Comment by TechStudent11** [comment]
I had to manually kill ElevenClock and afterwards, the update went fine. Thanks.
