### ISSUE TITLE
[BUG] Settings windows is resized after opening Settings again and again via context menu 

### ISSUE THREAD

**Issue by Kira-Lappo** [martinet101/ElevenClock#393]
## Reproduce steps

1. Right-click on the clock 
1. Click on "ElevenClock Settings"
1. Setting windows must appear
1. Maximize settings window
1. Close the settings window
1. Right-click on the clock 
1. Click on "ElevenClock Settings"

**Expected**: settings window is opened again without any issues
**Actual**: Settings window has a weird markup (check out screenshots). White space represents maximized window, but it displays only at quater part of it. 

## Screenshots
![after-settings-2](https://user-images.githubusercontent.com/11411852/146652867-7ee79157-014e-4718-bc0b-0da75f95f919.png)

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.9.1 (v2.91) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🔵 System tray icon enabled
🔵 Starting update check
🔵 Using bg color: 39,37,36,100.0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🔵 Using bg color: 39,37,36,100.0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3590, 1020, 250, 60)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🔵 Restart loop: 1
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found

```

## Additional context
IDK it can be because of my monitor setup. I have a laptop with a display 4k (3840x2160) but with an active resolution 1920x1080 (125% scale). 

Additional display is connected (1920x1080) (100% scale). The additional display is set as a primary display.

Windows 11 21H2 22000.376

**Comment by martinet101** [comment]
Yes, Settings window is quite glitchy and i'm aware of it. Actually, if you move the window across monitors (assuming you have more than one monitor) you'll see weird glithces and bugs. 

I'm working on it.

**Comment by martinet101** [comment]
Fixed, coming with next version
