### ISSUE TITLE
[BUG] Multiple errors preventing app start - (Error -5, Decompression Error)

### ISSUE THREAD

**Issue by kosch104** [martinet101/ElevenClock#398]
## Describe the bug
When booting up the program (via autostart, shortcut or directly) I get two error message boxes:
1. `Error -5 from inflate: (null)`
2. `Error decompressing d3dcompiler_47.dll`

## To Reproduce
Steps to reproduce the behaviour:
1. Start the program
2. See error

## Expected behaviour
The program starts, clock is shown.

## The Log
I cannot attach the log because the application does not start at all. Please tell me to log file location so I can manually search the file.

**Comment by martinet101** [comment]
Do you have free space on your disk?

**Comment by kosch104** [comment]
Yes, more than enough. Right now the issue is not reproducible anymore, however I had this happen a few times. Everything is well for a few days and then it's broken for multiple days.

**Comment by martinet101** [comment]
More than enough waht do you mean?

**Comment by martinet101** [comment]
Do you have some third-party antivirus or something?

**Comment by kosch104** [comment]
Yes, I have more than enough free space on my disk, I wanted to answer your question. I am only using windows defender, no third party anti-virus.

**Comment by martinet101** [comment]
And does Window defender mark Elevenclock as a virus/malware/PUP?

**Comment by kosch104** [comment]
No it doesn't, there are no threats found on my machine. After the latest reinstall I haven't been able to reproduce the issue in a while anymore.

**Comment by martinet101** [comment]
Ok, i guess we can keep that open for a week, and if it doesn't happen again, we close it.

**Comment by martinet101** [comment]
Did this happen again?
