### ISSUE TITLE
Clock is fuzzy

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#4]
![image](https://user-images.githubusercontent.com/22828430/136049134-73489ca8-b1de-4e70-9d74-35bd799badc1.png)

Is there anyway to make it less fuzzy/discolored? Also it says 05 but it should say 5

Here is the main taskbar one

![image](https://user-images.githubusercontent.com/22828430/136049188-0c21fd88-625e-436b-8d1b-3ee4be215a86.png)

**Comment by martinet101** [comment]
Part 1: I've fixed the extra zero.

Part 2: I've improved the look, but still not perfect:
Default: ![image](https://user-images.githubusercontent.com/53119851/136069170-11dd1953-e23e-4de0-90cc-72dc31432160.png)
ElevenClock ![image](https://user-images.githubusercontent.com/53119851/136069374-2092cd22-e146-4087-b2bd-f959cada26a0.png)

**Comment by urifoox** [comment]
Looks like if you remove the bold from the ElevenClock version it might match

**Comment by martinet101** [comment]
No, it looks in the same way, but on "light" font it is too light

**Comment by martinet101** [comment]
With regular font

![image](https://user-images.githubusercontent.com/53119851/136069952-8cb6eab5-1037-4d28-81e6-aafb417cdb81.png)

**Comment by urifoox** [comment]
Push a build, I'll test and let you know

**Comment by martinet101** [comment]
I'll build when i can, i'll try to dix the other issues before

**Comment by martinet101** [comment]
I've pushed a build, restart elevenclock and it will update

**Comment by urifoox** [comment]
Looks way better! 

Extra 0 gone from day 👍 
Cannot get it to disappear 👍 
Calendar always opens 👍 

Nice job!!

Font is still a little bit off, I don't know how you fix that. It looks like the kerning on the font is wrong or the weight? Notice the spacing

![image](https://user-images.githubusercontent.com/22828430/136072409-cb89b05a-8104-4e2d-a0aa-b1ced1d1458c.png)

**Comment by martinet101** [comment]
Happy to hear that it looks better. I'll study this smaller misalignment

**Comment by urifoox** [comment]
I think you want to use Segoe UI Light or Semilight

**Comment by martinet101** [comment]
Yes, i've tried, nope, it does not work (actually the light mode works with Segoe UI Variable Semilight). But light font is too light on dark mode, and looks awful

**Comment by martinet101** [comment]
But thank you anyway ;)

**Comment by urifoox** [comment]
I'm trying to compile locally but get
ImportError: No module named _bootlocale
Any advice here? I want to play around w/ the fonts.

**Comment by urifoox** [comment]
I downgraded python to 3.8 worked fine.

**Comment by urifoox** [comment]
self.move(w-(80*dpix), h-(48*dpiy))
self.font: QFont = QFont("Segoe UI Semilight")
self.font.setPointSizeF(8.5)

Results in this for me

![image](https://user-images.githubusercontent.com/22828430/136089341-a70238bc-dbc3-4cfd-89bc-b8b8c78b6a54.png)

Hope it helps you!

**Comment by urifoox** [comment]
I'd even say 79 instead of 80 will get you perfect pixel positioning...but I've probably fiddled with this enough lol 😄
