### ISSUE TITLE
[BUG] 3 Monitors clock in the middle of main screen v1.9

### ISSUE THREAD

**Issue by mrmangoz** [martinet101/ElevenClock#40]
With 3 monitors the clock still appears in the middle of the main monitor. Disconnecting one fixes the issue.

Console output:

[WinError 259] No more data is available
yyyy/MM/dd
h:mm tt
%#I:%M %p
%#I:%M %p
%Y/%m/%d
Starting update check
<PySide2.QtGui.QScreen(0x1f463a91ee0, name="\\\\.\\DISPLAY2") at 0x000001F464AA53C0> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
This is primay screen
<PySide2.QtGui.QScreen(0x1f463a91be0, name="\\\\.\\DISPLAY1") at 0x000001F464AA5740> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
PySide2.QtCore.QRect(-108, 1032, 640, 480)
start
Full screen rect:  (1920, 0, 0, 1080)
Focus screen rect:  (104, 104, 1097, 623)
<PySide2.QtGui.QScreen(0x1f463a91d00, name="\\\\.\\DISPLAY5") at 0x000001F464AA5840> PySide2.QtCore.QRect(1920, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
PySide2.QtCore.QRect(3732, 1032, 640, 480)
start
Full screen rect:  (1920, 0, 3840, 1080)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)
Focus screen rect:  (104, 104, 1097, 623)

**Comment by martinet101** [comment]
could you send me a screenshot of all your desktops with the clock where it shows please?

**Comment by martinet101** [comment]
like this: https://github.com/martinet101/ElevenClock/issues/32#issuecomment-939392859

**Comment by mrmangoz** [comment]
![image_2021-10-10_133812](https://user-images.githubusercontent.com/40361768/136693891-561e077d-468c-4c3d-9405-9e611eacacc7.png)

It only shows on the main monitor, in between the other two.

My setup is a laptop with 2 monitors plugged in, the main is one of the peripherals. With one disconnected it works even if the main is still one of the connected ones.

**Comment by martinet101** [comment]
https://drive.google.com/file/d/11IcdQBZOha6bABQKP3zIfKBEwW4gXECM/view?usp=sharing

Please try this file and send me the output

**Comment by mrmangoz** [comment]
> https://drive.google.com/file/d/11IcdQBZOha6bABQKP3zIfKBEwW4gXECM/view?usp=sharing
> 
> Please try this file and send me the output

[WinError 259] No more data is available
yyyy/MM/dd
h:mm tt
%#I:%M %p
%#I:%M %p
%Y/%m/%d
Starting update check
<PySide2.QtGui.QScreen(0x2340a40bf00, name="\\\\.\\DISPLAY2") at 0x000002340B472340> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
This is primay screen
<PySide2.QtGui.QScreen(0x2340a40be60, name="\\\\.\\DISPLAY1") at 0x000002340B4726C0> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
Clock geometry: PySide2.QtCore.QRect(-108, 1032, 100, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x2340a40b9e0, name="\\\\.\\DISPLAY5") at 0x000002340B4727C0> PySide2.QtCore.QRect(1920, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
Clock geometry: PySide2.QtCore.QRect(3732, 1032, 100, 48)
Full screen rect:  (1920, 0, 3840, 1080)
updates not found

**Comment by martinet101** [comment]
Disconnecting which monitor made elevenclock work?

**Comment by mrmangoz** [comment]
If I disconnect monitor three (far right) it works. If I disconnect monitor 1 (far left) it doesn't show at all

**Comment by mrmangoz** [comment]
Same issue, still in the middle. It seems from the output that the clock geometry has the correct coordinates?

WinError 259] No more data is available
yyyy/MM/dd
h:mm tt
%#I:%M %p
%#I:%M %p
%Y/%m/%d
PySide2.QtCore.QRect(0, 0, 5, 5)
Starting update check
<PySide2.QtGui.QScreen(0x1bfde7cfb50, name="\\\\.\\DISPLAY2") at 0x000001BFDF8622C0> PySide2.QtCore.QRect(0, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
This is primay screen
<PySide2.QtGui.QScreen(0x1bfde7cfaf0, name="\\\\.\\DISPLAY1") at 0x000001BFDF8626C0> PySide2.QtCore.QRect(-1920, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
Clock geometry: PySide2.QtCore.QRect(-108, 1032, 100, 48)
Full screen rect:  (-1920, 0, 0, 1080)
<PySide2.QtGui.QScreen(0x1bfde7cfb10, name="\\\\.\\DISPLAY5") at 0x000001BFDF8627C0> PySide2.QtCore.QRect(1920, 0, 1920, 1080) (1920, 1080, 96.0, 96.0)
Clock geometry: PySide2.QtCore.QRect(3732, 1032, 100, 48)
Full screen rect:  (1920, 0, 3840, 1080)
updates not found

**Comment by martinet101** [comment]
Yep, this is right. The point is that the coordinates of the clock after being moved to it's specific place are correct, but for some reason the clock doesn't actually move. I have found that all of you having this problem have multiple displays like "\\.\\\\DISPLAY1" and "\\.\\\\DISPLAY3" with the "\\.\\\\DISPLAY2" missing (because you don't have any other display connected in that port/output). Instead, on people who have all displays without having one missing, it works. I've been looking and it looks like there's a Qt bug, so now i'm gonna try moving windows with the Win32 API rather that using QWidget/QMainWindow.move(x, y). But I don't really know if i'll be able to fix that...

**Comment by mrmangoz** [comment]
It shows on Display 1 (monitor number 1 on the left) but not on monitor 3 on the right (Display 5). It doesn't show in the middle anymore

I have the 3rd monitor plugged in via a usb-C extension, could that be an issue?

**Comment by martinet101** [comment]
I don't think USB-C should be an issue... Could you send me the log of the last file i sent?

> It shows on Display 1 (monitor number 1 on the left) but not on monitor 3 on the right (Display 5). It doesn't show in the middle anymore
> 
> I have the 3rd monitor plugged in via a usb-C extension, could that be an issue?

I don't think USB-C should be an issue... Could you send me the log of that time?

**Comment by martinet101** [comment]
I think i found what could be hapening...

**Comment by mrmangoz** [comment]
Disconnecting display 1 shows on display 5

**Comment by martinet101** [comment]
Ok, i've done my best. I've added a switch. The default clock positioning behaviour will be same as before, but now there's a switch on system tray icon to enable win32 api and get at least 1 clock on one of the secondary widgets, because the other one closes itself due to a bug. 

I'll add this as version 1.9.5
