### ISSUE TITLE
[ISSUE] Slight Typo

### ISSUE THREAD

**Issue by Carterpersall** [martinet101/ElevenClock#401]
In the general settings section, in "Hide extended options from the clock right-click menu (needs a restart to be aplied)" aplied should be applied.

**Comment by martinet101** [comment]
Ok

**Comment by martinet101** [comment]
Fixed, coming in next version
![image](https://user-images.githubusercontent.com/53119851/146804947-9555f946-8410-42c9-af96-99225b71680f.png)
