### ISSUE TITLE
[FEATURE REQUEST] Czech translation

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#402]
Hi, czech translation is available, but is not used.

* https://github.com/martinet101/ElevenClock/blob/main/elevenclock/lang/lang_cs.py
* https://github.com/martinet101/ElevenClock/blob/main/elevenclock/languages.py

**Comment by panther7** [comment]
Pull request created for enable czech langauge.

**Comment by martinet101** [comment]
> Hi, czech translation is available, but is not used.
> 
> * https://github.com/martinet101/ElevenClock/blob/main/elevenclock/lang/lang_cs.py
> * https://github.com/martinet101/ElevenClock/blob/main/elevenclock/languages.py

Whops, didn't realise... Now merging your PRs

**Comment by martinet101** [comment]
Done

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/146951191-00968caf-2bb2-4ffd-b6a4-61123b9c6fda.png)

**Comment by martinet101** [comment]
Coming with new version

**Comment by panther7** [comment]
Thanks.

Btw, "System language" could be translatable string too ;-)

**Comment by martinet101** [comment]
Yes, I thought about that, but I did not translate this string (in fact, any language string) to make it accessible for someone who accidentally changed the language to one that he/she doesn't understand.
