### ISSUE TITLE
[BUG] (second monitor diff resolution + diff scale)

### ISSUE THREAD

**Issue by mooseplus** [martinet101/ElevenClock#409]
My primary monitor is 1920x1080, 125% scale. My secondary monitor is 1440x900, 100% scale. The clock on the second monitor is slightly cut-off, please see screenshot. When I change scale to be the same, the problem disappears.

At different scaling (the screenshot is not very clear, but as you can see, it cuts off on the right, the "am" and the year does not show):
![image](https://user-images.githubusercontent.com/37339338/147390462-df164d1f-78ca-4830-aba8-cf8ed6b5bd1b.png)
At similar scaling (both 125%):
![image](https://user-images.githubusercontent.com/37339338/147390475-ac1d8d48-a0df-4cc0-9d1d-fa49850853af.png)

Log:
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.9.1 (v2.91) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🔵 System tray icon enabled
🔵 Starting update check
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 9.5
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 10.5
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 11.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 11.5
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 12.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 5
🔵 Restart loop: 4
🔵 Restart loop: 3
🔵 Restart loop: 2
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 11.5
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 11.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 10.5
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 852), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Restart loop: 1
🔵 Clock geometry: PySide2.QtCore.QRect(3110, 840, 250, 60)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟡 Closing clock on {'Monitor': (1920, 0, 3360, 900), 'Work': (1920, 0, 3360, 840), 'Flags': 0, 'Device': '\\\\.\\DISPLAY4'}
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1440, 900)
🟢 Taskbar at bottom
🟡 Clock on the left
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3160, 852, 160, 38)
🔵 Font families: ['Segoe UI Emoji']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3360, 900)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1

**Comment by martinet101** [comment]
Try disabling the following checkbox (ElevenClock Settings -> Fixes and other experimental features)

![image](https://user-images.githubusercontent.com/53119851/147390948-5c064aa0-f993-4328-8882-f19391c3bb30.png)

**Comment by mooseplus** [comment]
unfortunately, if i uncheck that box, the clock becomes more buggy - it will appear on my *primary* monitor, and in the middle of the screen too.

**Comment by martinet101** [comment]
Ok... Can you please try methods 1 and 3 fom this guide? https://www.makeuseof.com/6-ways-fix-apps-that-appear-blurry-in-windows-10/

**Comment by mooseplus** [comment]
hi there, thank you so much for the article!
3) worked for me - however, under "High DPI scaling override", "Application" did not work (it created an additional bug where the clock became invisible even when i changed the text color), it was actually "System (Enhanced)" that worked. hope this is useful. and once again thank you for the app and belated merry christmas :)

**Comment by martinet101** [comment]
Well, happy to see that it worked, merry christmas (though i'm a little bit late) and happy new year :)
