### ISSUE TITLE
Getting at icons under ElevenClock

### ISSUE THREAD

**Issue by Moonwink** [martinet101/ElevenClock#415]
My WordWeb icon is hidden behind ElevenClock making it very hard to click on it.  Is there any way to force the icons in the system tray out from under ElevenClock?

**Comment by martinet101** [comment]
Check #196. A workaround could be opening the start menu, then the clock will hide

**Comment by Moonwink** [comment]
In an effort to make life easier, I use Open Shell to restore my Start button menu to something I can work with.  Clicking on the Start button and displaying the list of programs/options doesn't have any effect on the system tray.
![ElevenClock](https://user-images.githubusercontent.com/96207744/147496873-050b5247-29c0-4d7e-8f46-aca27dca0e52.jpg)

**Comment by martinet101** [comment]
An option is going to be added to hide the clock during 10s after being clicked. It might help with the overflow issues
![image](https://user-images.githubusercontent.com/53119851/147821562-f44ab86c-d709-419e-b822-cc91510ed30e.png)
Coming with the next version!
