### ISSUE TITLE
Right adjusted text causes clock to retract to right every time a '1' is displayed

### ISSUE THREAD

**Issue by TiresOfItAll** [martinet101/ElevenClock#418]
A nit.  With the latest release and moving the clock to the right of the taskbar to cover the incompetent Windows 11 clock, every time a '1' is displayed in the time the left margin of the clock contracts.  With no '1' digits the clock background partly covers the next to-the-left icon, usually the volume/speaker select.  A small font avoids partly covering the volume/speaker icon with legibility being impacted but when the '1' is in the seconds it seems to catch the eye as the display briefly contracts right and returns expanded left once the '1' passes, essentially a stutter.   When the clock is to the left the AM/PM expands/contracts indicating it is an issue whereby when on the left the clock left justifies, and when on the right it right justifies.  Suggest making time digits and AM/PM different fields so the AM/PM does not enter the justification equation.

**Comment by martinet101** [comment]
Check out #379, there is the feature request that asks for the fix
