### ISSUE TITLE
[FEATURE REQUEST] Dynamic Background Color On Primary Screen Working Well / Remove Hint In Settings 

### ISSUE THREAD

**Issue by Dypsis** [martinet101/ElevenClock#421]
Since the dynamic background color is working so well on primary screens in v2.9.2, then maybe the following settings hint for "Show the clock on the primary screen" can be removed.

**"You might need to set a custom background color for this to work. More info HERE."**

**Comment by martinet101** [comment]
I left it there for if the dynamic background wasn't working for some people, but yeah, since it works I'm gonna remove it

**Comment by martinet101** [comment]
Done
