### ISSUE TITLE
[FEATURE REQUEST] Add on hover description to clock

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#423]
(low-prio)

Add title-description on hover, like original, check screenshot. Example, "Show Desktop", "Tuesday, December 28, 2021"

Orig:  
![orig](https://user-images.githubusercontent.com/3808250/147571564-927ae435-490d-4eaf-bd2e-42f7e4011933.png) ![2021-12-28 14 37 44](https://user-images.githubusercontent.com/3808250/147571966-ed47b11f-3879-4390-b602-0b4830755207.png)

Eleven:  
![eleven](https://user-images.githubusercontent.com/3808250/147571567-b68f3ba9-aadd-45dc-b491-ca01825b407a.png)

**Comment by martinet101** [comment]
I had problems with tooltips and qt, but i'll give it a try

**Comment by martinet101** [comment]
I'm sorry, but i'd need Qt6 to do that, since Qt5's tooltips are a little bit broken and don't show. I'm sorry though :(
