### ISSUE TITLE
[FEATURE REQUEST] Sharpness font

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#424]
(low-prio)

* Line on "Show Desktop" is narrower than ElevenClock line.
* Clock font is more sharpness than ElevenClock font (see number `1`).

Orig | Eleven
![orig](https://user-images.githubusercontent.com/3808250/147572675-4e322a55-5013-408b-af89-6c929b4b60b1.png) ![eleven](https://user-images.githubusercontent.com/3808250/147572908-0ad66eec-cae4-4eb7-ac1b-47bc0249486f.png)

**Comment by martinet101** [comment]
This is because of Qt's font rendering engines. I can't really fix that
