### ISSUE TITLE
[FEATURE REQUEST] Add a notifcation badge to the clock

### ISSUE THREAD

**Issue by JohnathanN28** [martinet101/ElevenClock#429]
**Is your feature request related to a problem? Please describe.**
Windows 11 groups both the notification center and the clock, showing the notification badge with the clock.

**Describe the solution you'd like**
I would like to see ElevenClock have a notification badge integrated with the clock. 

Original WIndows 11 Picture With Example:
![image](https://user-images.githubusercontent.com/78399047/147798100-841a19ac-9d12-4a68-8675-bfaa60967afb.png)

**Comment by Masamune3210** [comment]
I'm not sure that Windows offers any way to programmatically see how many and if notifications are pending, since the only thing that consumes that data on a normal machine is explorer

**Comment by martinet101** [comment]
This issue was closed recently, and yes, it is coming in the next version

**Comment by martinet101** [comment]
I'ts actually being tested: 
![image](https://user-images.githubusercontent.com/53119851/147819771-74eb3200-eb0e-4ee3-b824-5ccbafc2e42e.png)
