### ISSUE TITLE
[BUG] Fatal Error detected when I turn my machine on from sleep

### ISSUE THREAD

**Issue by JenevanStudios** [martinet101/ElevenClock#431]
When I turn my computer and unlock my screen I keep getting an error:
"Fatal Error Detected"
Failed to execute script __init__
![elvenclock_fatal_error](https://user-images.githubusercontent.com/10820534/147833666-05d04a65-d6bf-4641-b0a7-f040f45f7b7e.png)

**Comment by martinet101** [comment]
Do you have the latest version installed?

**Comment by martinet101** [comment]
Also, the clock does still run when this happens?

**Comment by JenevanStudios** [comment]
Yes, I have the most recent version installed. And yes the clock continues to function without issue.

**Comment by martinet101** [comment]
I've extended the error reporter in a way that those errors will be reported since next version, so we can see what is going on. The nexrt version will come (hopefully) soon

**Comment by JenevanStudios** [comment]
![Screenshot 2022-01-07 195546](https://user-images.githubusercontent.com/10820534/148624842-ca1473f5-13e4-466a-9a95-01470d3ba128.png)

New error I haven't seen this before.

**Comment by Masamune3210** [comment]
Either your install is hosed or something is drastically wrong. What type of computer are you using?

**Comment by martinet101** [comment]
Can you please follow this guide and then reinstall ElevenClock? Thankyou

Guide: https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

**Comment by TechStudent11** [comment]
@martinet101 This is the exact same thing as my error for a couple of months ago (#301) and it still happens, just not on that scale.

**Comment by JenevanStudios** [comment]
> Either your install is hosed or something is drastically wrong. What type of computer are you using?

I'm running Windows 11 on an Alienware 17R5

**Comment by JenevanStudios** [comment]
> Can you please follow this guide and then reinstall ElevenClock? Thankyou
> 
> Guide: https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

Followed the steps, so far so good
