### ISSUE TITLE
[BUG] Flickering in Forza Horizon 5

### ISSUE THREAD

**Issue by AlexDeAustria** [martinet101/ElevenClock#432]
## Describe the bug
The clock causes flickering in Forza Horizon 5.

## To Reproduce
Steps to reproduce the behaviour:
1. Turn on clock
2. Play Forza Horizon 5
3. Flickering

## Expected behaviour
No flickering

## Clip
https://user-images.githubusercontent.com/55532024/147848126-ca2ee256-4877-4f6f-b63d-b8508109c005.mp4

## The Log
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.9.2 (v2.92) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "de"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟢 Loaded clocks in 1.584303855895996
🔵 System tray icon enabled
🔵 Starting update check
🟢 Loaded everything in 2.1260764598846436
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found

## Additional context
Closing ElevenClock while being in the game ended the flickering.
The bug was not there on past versions.

**Comment by martinet101** [comment]
Without the clock, Forza does not flicker? Does this affect other apps?

**Comment by AlexDeAustria** [comment]
> Without the clock, Forza does not flicker? Does this affect other apps?

I still recognized a few rare flickers like every five minutes, but most of them are gone. 
Haven't noticed that in any other app yet...

**Comment by Masamune3210** [comment]
Maybe the clock drawing on the taskbar is causing it to refresh more than normal causing it to cause issues with Exclusive Fullscreen apps? Does it flicker or stutter even in windowed mode when the taskbar is allowed to display normally?

**Comment by AlexDeAustria** [comment]
> Maybe the clock drawing on the taskbar is causing it to refresh more than normal causing it to cause issues with Exclusive Fullscreen apps? Does it flicker or stutter even in windowed mode when the taskbar is allowed to display normally?

Tried that and yes, kept flickering.

**Comment by AlexDeAustria** [comment]
My settings:

![Screenshot_1](https://user-images.githubusercontent.com/55532024/147874578-bbfc18a0-a109-4f1a-8a56-b965715489af.png)

![Screenshot_2](https://user-images.githubusercontent.com/55532024/147874579-cd8fdd06-50a0-4e9e-bcb9-f4510e543580.png)

![Screenshot_3](https://user-images.githubusercontent.com/55532024/147874580-3b92eedb-e649-4129-adb0-6cacf6e10599.png)

**Comment by martinet101** [comment]
Does this happen with other videogames?

**Comment by AlexDeAustria** [comment]
> Does this happen with other videogames?

I haven't noticed it yet. No issues in Football Manager 22, Euro Truck Simulator 2, Battlefield 4 and Call of Duty: Modern Warfare 2.
Don't know about other games.

But don't worry too much I guess. Forza Horizon 5 is a piece of broken software!
As I said, there are still some rare flickers in the game even without ElevenClock, so it just got more frequent with that running.
The strange thing is, that I hadn't had them before the ElevenClock update to 2.9.2.
Is it possible to downgrade to the previous version to see, if it's fixed then?

**Comment by AlexDeAustria** [comment]
Ok well, just tried it with version 2.9.1...the "rare flickers" are still there, but most of them are gone! Don't know where they come from and why version 2.9.2 increases them, but that's it.

Here the 2.9.1 log:

---------------------------------------------------------------------------------------------------

   ElevenClock's 2.9.1 (v2.91) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "de"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🔵 System tray icon enabled
🔵 Starting update check
🟡 This is the primary screen and is set to be skipped
🔵 Using bg color: 0, 0, 0, 0
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates found!
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates found!

**Comment by Masamune3210** [comment]
5 is indeed still very broken so I wouldn't put it past them to have some weird cases in their rendering. What card do you have, make sure that your GPU drivers are up to date

**Comment by AlexDeAustria** [comment]
> 5 is indeed still very broken so I wouldn't put it past them to have some weird cases in their rendering. What card do you have, make sure that your GPU drivers are up to date

NVIDIA GeForce RTX 2060 and of course I keep it updated. I don't know if the recent Game Ready driver 497.29 (12/20/2021) causes the flackering.

The third software update in the last two weeks was from Armoury Crate, an ASUS app for connecting, configuring and controlling the hardware.


By the way, just finished playing FH5 for a few hours. The flickering got more and more after some time so I closed ElevenClock version 2.9.1 - got a little bit better, but was still there. Way less than in the video above with version 2.9.2 activated, but still...


So there has to be some rendering bug when playing FH5 which just gets increased by ElevenClock.
Don't know if it is caused by the recent NVIDIA driver, the recent Armoury Crate update or something else.

In fact, the game developers are responsible for the bug, not you, so I won't bother you further with it.

Thanks for the help and all the best for 2022!

**Comment by martinet101** [comment]
Hope that this gets solved. I can only recommend you using an older driver 🤷‍♂️.

**Comment by Masamune3210** [comment]
I'm going to assume its an issue with the latest driver and FH5 as Nvidia isn't super well known for testing their drivers before shipping them out. Hope it gets worked out!

**Comment by AlexDeAustria** [comment]
> Hope that this gets solved. I can only recommend you trying an older driver 🤷‍♂️.

> I'm going to assume its an issue with the latest driver and FH5 as Nvidia isn't super well known for testing their drivers before shipping them out. Hope it gets worked out!

I have already tried it with an older driver....nothing has changed. I don't know what it is.
Every now and then there is a "optimizing for your PC" phase when starting the game. I'm sure that there was one before it was flackering for the first time. I don't know what and why it does that, but it surely broke it for me.

But yeah, thank you guys!

**Comment by Masamune3210** [comment]
Thats weird, the optimizing for your pc should only appear if the shader cache has been wiped, usually when changing GPU driver. When it shows that it means that its regenerating all the shaders the game needs so it doesn't stutter later on

**Comment by AlexDeAustria** [comment]
> Thats weird, the optimizing for your pc should only appear if the shader cache has been wiped, usually when changing GPU driver. When it shows that it means that its regenerating all the shaders the game needs so it doesn't stutter later on

But that would make sense then?!
New NVIDIA driver -> new optimizing for your pc in Forza -> causes errors/problems -> flickering
Or do I have a mistake in thinking?
I just wonder why it wasn't fixed then after re-installing the game...
