### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by LevandeKokbok** [martinet101/ElevenClock#433]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If ElevenClock is showing over a fullscreen window, enable "Hide on fullscreen window from the settings"
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by LevandeKokbok** [comment]
Hi, great feature especially since W11 removed seconds. I have ElevenClock running and it is good except the Windows clock still shows,
![image](https://user-images.githubusercontent.com/3142823/147884168-9b46b5c6-85c6-44d1-bad5-0e9432bc65b4.png)

Is there a way to stop this happening?
Thanks,
Richard

**Comment by martinet101** [comment]
Yes, this is due the notification counter, is going to be fixed in the next version, stay tuned!
