### ISSUE TITLE
[BUG] cursor is slow/flashes 

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#434]
Sorry I do not have a detailed report, I tried to take video but it's hard to see on it. 
Ever since installing latest version 2.9.2 the cursor as it moves around is very slow and constantly refreshes.
It makes the software unusable as the accuracy of the mouse is hindered :(
I don't know if this is helpful, just passing it along because I'd love to use it again! 

---------------------------------------------------------------------------------------------------

   ElevenClock's 2.9.2 (v2.92) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, -1088, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, -56, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, -1088, 3840, -8)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, -8, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1024, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, -8, 3840, 1072)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, -1089, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, -57, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, -1089, 1920, -9)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 1, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1033, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 1, 0, 1081)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, -1079, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, -47, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, -1079, 0, 1)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟢 Loaded clocks in 0.479691743850708
🔵 Restart loop: 1
🔵 System tray icon enabled
🟠 Update checking disabled
🟢 Loaded everything in 0.9482691287994385
🟠 Update checking disabled

**Comment by urifoox** [comment]
I do not have the issue with ElevenClock 2.8.0 so I downgraded back to that.

**Comment by martinet101** [comment]
By cursor, you mean the mouse cursor? Like the windows cursor?

**Comment by urifoox** [comment]
yeah the mouse
2.8 same issue but takes a lot longer to happen, after a few hours i have to exit the program or the whole computer gets laggy
as soon as i exit elevenclock everything works fine

**Comment by urifoox** [comment]
yeah the mouse
2.8 same issue but takes a lot longer to happen, after a few hours i have to exit the program or the whole computer gets lagg
yas soon as i exit elevenclock everything works fine
2.9.2 the lag is instant on program launch

**Comment by martinet101** [comment]
Could that be caused because of a cpu/ram leak?

**Comment by urifoox** [comment]
I upgraded to 3.0 - same problem. I clicked on Enable low cpu mode the problem went away.

just so you know this is broken:

![image](https://user-images.githubusercontent.com/22828430/148282200-92b2ae56-e12b-4ce6-b2e6-ef1d22eb6f25.png)

**Comment by martinet101** [comment]
Oh, yes, there's an open thread about the broken context menu
