### ISSUE TITLE
[FEATURE REQUEST] Allow manual toggling of clock on different displays

### ISSUE THREAD

**Issue by instantrice** [martinet101/ElevenClock#435]
**Is your feature request related to a problem? Please describe.**
I use a small monitor for system stat monitoring, as well as VMWare Horizon across two of my four displays. I'd like to disable ElevenClock on two of my four displays manually.

**Describe the solution you'd like**
I would like to see an advanced option to manually enable/disable ElevenClock per display.

**Comment by martinet101** [comment]
This will come in the next version, there's a discussion about this. You'll be able to blacklist monitors
