### ISSUE TITLE
[FEATURE REQUEST] Show clock on the left side only on one Monitor

### ISSUE THREAD

**Issue by Mayerch1** [martinet101/ElevenClock#438]
**Is your feature request related to a problem? Please describe.**
On my right (2nd) monitor I'd like to use the feature to show the clock on the left side. This way it's closer to my direct field of view.
However the option aswell moves the clock of my (3rd) left monitor to the left side aswell, moving it out of my direct field of view.

**Describe the solution you'd like**
It would be good to selectively choose the monitor(s), on which the clock is shown on the left side.
All other monitors should be able to keep the clock on the right side

#430 was opened for the same feature request, but did not bother filling out the template

**Comment by martinet101** [comment]
I'll take a look

**Comment by yazan1107** [comment]
YES PLEASE

**Comment by martinet101** [comment]
Sorry for the delay, this will come with the next version.
![image](https://user-images.githubusercontent.com/53119851/151677907-89053744-59fe-48eb-b737-6cbc0f75fe72.png)
