### ISSUE TITLE
[ISSUE] Notifications hidden

### ISSUE THREAD

**Issue by PescheHelfer** [martinet101/ElevenClock#439]
**Is your feature request related to a problem? Please describe.**
Currently, the ElevenClock box stretches over the area which shows the number of notifications, effectively hiding it.

**Describe the solution you'd like**
Make the box stretch less to the right, or manually adjustable. The custom formats mentioned in other suggestions should help making it fit into a smaller box.

Thanks a lot!

**Comment by martinet101** [comment]
Duplicate, this has already been fixed and will come with the next version
