### ISSUE TITLE
clock disappears after install

### ISSUE THREAD

**Issue by Usul420** [martinet101/ElevenClock#44]
after installation is finished clock appears on second screen then after about 5 seconds an additional setup screen appears and it looks like it install's again and then the clock disappears. the app icon is still on the desktop and task manager shows it still running but no clock on second monitor. verified it is set to launch on startup but when restarted clock does not appear 

**Screenshots**
![1](https://user-images.githubusercontent.com/49320984/136703406-cad20811-b1c8-43df-b0a2-75286ff3ca5a.jpg)
![2](https://user-images.githubusercontent.com/49320984/136703409-cf2a580e-593a-4a17-bf62-2347a84f62a9.jpg)
![3](https://user-images.githubusercontent.com/49320984/136703430-d031de41-b624-4bb6-94fb-031da146fc0f.jpg)
![4](https://user-images.githubusercontent.com/49320984/136703439-72daade8-d556-43ce-97ff-080b08e10151.jpg)
![5](https://user-images.githubusercontent.com/49320984/136703443-b4e71174-615f-41f6-afa9-7cdaada0fecf.jpg)

**Comment by martinet101** [comment]
This is because you downloaded an older version, so the older version updated itself

**Comment by martinet101** [comment]
Try opening this link in your browser:

https://www.somepythonthings.tk/versions/elevenclock.ver

what do you see?

**Comment by Usul420** [comment]
1.9
///
https://github.com/martinet101/ElevenClock/releases/download/1.9/ElevenClock.Installer.exe
///
ACD846EC20D170EA56E7AB4E12BD9FA840756CE854658B79AB00DF839AFAD3F4

**Comment by martinet101** [comment]
It does this once ot stays updating infinitely?

**Comment by Usul420** [comment]
it does not loop, after rebooting i see it now but my taskbar is at the top of the screen and clock is at the bottom

**Comment by martinet101** [comment]
The tob-bottom taskbar in windows 11 is buggy, try setting your taskbar to the top with registry and rebooting again:

https://www.howtogeek.com/759882/how-to-move-windows-11s-taskbar-to-the-top-of-the-screen/
