### ISSUE TITLE
[FEATURE REQUEST] Add translatable week number

### ISSUE THREAD

**Issue by vasilvestre** [martinet101/ElevenClock#440]
**Is your feature request related to a problem? Please describe.**
I show week of the year, what's shown is W01 despite that I'm french and we (as french) should see S01 (S = semaine = week) .

**Describe the solution you'd like**
Make this string translatable

**Comment by martinet101** [comment]
Well, in theory ElevenClock _should _adapt to your system locale. I have my pc in catalan and the week day shows in catalan.

**Comment by vasilvestre** [comment]
> Well, in theory ElevenClock _should _adapt to your system locale. I have my pc in catalan and the week day shows in catalan.

Maybe it's just not translated in french, do you know the key to use ?

**Comment by martinet101** [comment]
I actually use python libraries. Could you please send me the log? You can get it on ElevenClock settings, under debugging information

**Comment by vasilvestre** [comment]
> I actually use python libraries. Could you please send me the log? You can get it on ElevenClock settings, under debugging information

![image](https://user-images.githubusercontent.com/17164385/148073227-c158ab62-bfaa-4cc6-8f98-d08e1ba41b46.png)
This is the result, this is the log

`🔴 Traceback (most recent call last):

🔴   File "tools.py", line 100, in setSettingsValue

🔴   File "globals.py", line 11, in loadTimeFormat

🔴 NotImplementedError: loadTimeFormat function has not been defined!

🔴 Note this traceback was caught by reporter and has been added to the log (loadTimeFormat function has not been defined!)
---------------------------------------------------------------------------------------------------

   ElevenClock's 2.9.2 (v2.92) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "fr"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟢 Loaded clocks in 0.517998218536377
🔵 Restart loop: 1
🔵 System tray icon enabled
🔵 Starting update check
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:False
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟢 Default settings loaded
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟢 Loaded everything in 2.714000701904297
🔵 Restart loop: 3
🔵 Restart loop: 2
🔵 Restart loop: 1
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1346, in do_open

🔴   File "http\client.py", line 1285, in request

🔴   File "http\client.py", line 1331, in _send_request

🔴   File "http\client.py", line 1280, in endheaders

🔴   File "http\client.py", line 1040, in _send_output

🔴   File "http\client.py", line 980, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 500, in wrap_socket

🔴   File "ssl.py", line 1040, in _create

🔴   File "ssl.py", line 1309, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 106, in updateIfPossible

🔴   File "urllib\request.py", line 214, in urlopen

🔴   File "urllib\request.py", line 517, in open

🔴   File "urllib\request.py", line 534, in _open

🔴   File "urllib\request.py", line 494, in _call_chain

🔴   File "urllib\request.py", line 1389, in https_open

🔴   File "urllib\request.py", line 1349, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1928, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (1920, 0, 3840, 1080), 'Work': (1920, 0, 3840, 1032), 'Flags': 0, 'Device': '\\\\.\\DISPLAY1'}
🟡 This is the primary screen and is set to be skipped
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟢 Taskbar at bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Restart loop: 1
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1346, in do_open

🔴   File "http\client.py", line 1285, in request

🔴   File "http\client.py", line 1331, in _send_request

🔴   File "http\client.py", line 1280, in endheaders

🔴   File "http\client.py", line 1040, in _send_output

🔴   File "http\client.py", line 980, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 500, in wrap_socket

🔴   File "ssl.py", line 1040, in _create

🔴   File "ssl.py", line 1309, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 106, in updateIfPossible

🔴   File "urllib\request.py", line 214, in urlopen

🔴   File "urllib\request.py", line 517, in open

🔴   File "urllib\request.py", line 534, in _open

🔴   File "urllib\request.py", line 494, in _call_chain

🔴   File "urllib\request.py", line 1389, in https_open

🔴   File "urllib\request.py", line 1349, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Fullscreen window detected! PowerToys Runner (0, 0, 3840, 1080) Fullscreen rect: (1920, 0, 3840, 1080)
🔵 Starting update check
🔴 Traceback (most recent call last):

🔴   File "urllib\request.py", line 1346, in do_open

🔴   File "http\client.py", line 1285, in request

🔴   File "http\client.py", line 1331, in _send_request

🔴   File "http\client.py", line 1280, in endheaders

🔴   File "http\client.py", line 1040, in _send_output

🔴   File "http\client.py", line 980, in send

🔴   File "http\client.py", line 1454, in connect

🔴   File "ssl.py", line 500, in wrap_socket

🔴   File "ssl.py", line 1040, in _create

🔴   File "ssl.py", line 1309, in do_handshake

🔴 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

🔴 
During handling of the above exception, another exception occurred:


🔴 Traceback (most recent call last):

🔴   File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 106, in updateIfPossible

🔴   File "urllib\request.py", line 214, in urlopen

🔴   File "urllib\request.py", line 517, in open

🔴   File "urllib\request.py", line 534, in _open

🔴   File "urllib\request.py", line 494, in _call_chain

🔴   File "urllib\request.py", line 1389, in https_open

🔴   File "urllib\request.py", line 1349, in do_open

🔴 urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>

🔴 Note this traceback was caught by reporter and has been added to the log (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>)
🔵 Version URL: http://www.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
`

**Comment by martinet101** [comment]
Fixed, coming in the next version

**Comment by vasilvestre** [comment]
> Fixed, coming in the next version

Thank you ! Nice job :)
