### ISSUE TITLE
[BUG] 3 line clocks (ex. time, day, date) have the lowest line cut off

### ISSUE THREAD

**Issue by cev123** [martinet101/ElevenClock#443]
3 line clocks (ex. time, day and date) have the lowest line cut off. So my 1/4/2022 is only half visible.

## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If ElevenClock is showing over a fullscreen window, enable "Hide on fullscreen window from the settings"
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by cev123** [comment]
...in version 3.0

**Comment by martinet101** [comment]
Yes, I see. Let me fix that

**Comment by AbbieDoobie** [comment]
This same issue occurs with 2 line clocks, see my linked dupe with screenshot; https://github.com/martinet101/ElevenClock/issues/446

**Comment by Masamune3210** [comment]
Same thing happens for me on latest
![image](https://user-images.githubusercontent.com/1053504/148260794-0604e415-56ca-40db-9ee8-290415350b5a.png)

**Comment by martinet101** [comment]
Can you please try setting a smaller font size as a tempoary solution? Thx!

**Comment by Masamune3210** [comment]
I'm not worried about it if a fix is being worked on, i can be patient as its not super important for me, but its a nice fix for others who need it if it works

**Comment by cev123** [comment]
Thank you!

**Comment by brine-egg** [comment]
![image](https://user-images.githubusercontent.com/89018140/148308754-4d7631c1-422c-4e3d-9e90-4cb90c69cecb.png)
also happens when using two line clocks with small taskbar

**Comment by martinet101** [comment]
Fixed, coming with the next release
