### ISSUE TITLE
Mismatching fontstyle (boldness) of the display

### ISSUE THREAD

**Issue by TaminoWalter** [martinet101/ElevenClock#45]
On my (2) monitors (2560 x 1440) the clock of my secondary monitor looks bolder and kind of blurry. It would be great if the styling could be adjusted so that it looks just like the clock style of windows. (The differences are small but definitely noticeable)

Here a screenshot as comparison: (left is from ElevenClock and right is the default windows one)

![eleven_clock](https://user-images.githubusercontent.com/54551451/136703387-e48fc543-93b4-4cba-be36-ca2a307b585e.png)

**Comment by martinet101** [comment]
Yep, I know that, but this is the most accurate look i have done. (See #4)
