### ISSUE TITLE
[BUG] (Right-click menu colour)

### ISSUE THREAD

**Issue by bsavarin** [martinet101/ElevenClock#452]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If ElevenClock is showing over a fullscreen window, enable "Hide on fullscreen window from the settings"
</b>

## Describe the bug

Thanks for the update.  However, the right-click menu background colour is a very dark grey, and so you can barely see the menu options.  Unfortunately I cannot get it to show up on a screenshot.

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by Xarkam** [comment]
A picture is better than a long speech
It's the fluent design that calculates the menu background to simulate a transparency effect who bug.
![image](https://user-images.githubusercontent.com/331816/148184715-881c3e11-eff2-4a96-b855-ee66da894a74.png)
![image](https://user-images.githubusercontent.com/331816/148184825-cf3eb6d6-2c99-4b1f-8591-f9ef9f845d85.png)

**Comment by martinet101** [comment]
Please see #442, this is a duplicate, post there
