### ISSUE TITLE
[BUG] Restart string is not translated

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#454]
"Restart" string is not translated, but it is in translation file.

![Image-2022-01-05 13 27 04](https://user-images.githubusercontent.com/3808250/148219165-c005b658-179b-48bd-a914-49aaa459f4f1.png)

**Comment by martinet101** [comment]
This one has not been intended to be translatable (the string actually codes for the context menu entry) to make this part universal and accessible if you accidentally make a mess.
