### ISSUE TITLE
[BUG] Remember previous settings, if enable low-cpu mode

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#455]
Enabling "low-cpu mode" do enable "disable background color", but, after disable low-cpu mode i expect set "disable background color" to previous state ("disabled").

![Animation](https://user-images.githubusercontent.com/3808250/148219305-43c71b69-bbaf-499f-8e49-f5140c7ff9b3.gif)

**Comment by martinet101** [comment]
I'll take a look

**Comment by martinet101** [comment]
Fixed, coming with the next release
