### ISSUE TITLE
[FEATURE REQUEST] On click of Eleven Clock add additional behavior

### ISSUE THREAD

**Issue by VooDooTo** [martinet101/ElevenClock#459]
**Is your feature request related to a problem? Please describe.**
Yes it has a problem that when I click on the clock does not open the normal windows 11 calendar and does not show the week and date.

**Describe the solution you'd like**

On click of the clock now only mutes/unmutes video and audio, which is good , but I want to have other behavior like showing the calendar like the other clock was doing previously. 
So probably if you could add this functionality to the Settings window?
Can you please add such functionality ?

**Comment by martinet101** [comment]
Well, this is an issue with microsoft mapping the wrong key shortcut to PowerToys. You'll need to replace your powertoys kbd shortcut to something other like Win+Shift+N, etc
