### ISSUE TITLE
[BUG] Bad appearance when startup

### ISSUE THREAD

**Issue by javicaballero** [martinet101/ElevenClock#460]
It shows like this when windows just starts:
![elevenclock_bug](https://user-images.githubusercontent.com/6868879/148398295-2714ced5-dade-4652-b83f-25109ba04bab.gif)

It can be solved with a click, but it is annoying. Could you check please? Thanks!

**Comment by martinet101** [comment]
I can't really see the issue. Could you explain furher please?

**Comment by javicaballero** [comment]
> 
Right now I have the issue. You can notice that the system clock goes to the left. I think it's because of notifications:
![imagen](https://user-images.githubusercontent.com/6868879/148430258-234bb076-1811-43a3-a097-8ec119bd15d2.png)

**Comment by javicaballero** [comment]
This is an example of the unread notification counter. I think this brings the system clock to the left and makes it visible.
![imagen](https://user-images.githubusercontent.com/6868879/148431272-7f30a33e-df62-4f4a-a4fc-93617dba79ed.png)

**Comment by martinet101** [comment]
The last version (3.0.0) has this feature, can you please check your version?

**Comment by javicaballero** [comment]
> The last version (3.0.0) has this feature, can you please check your version?

Yes, I have that version
![imagen](https://user-images.githubusercontent.com/6868879/148453300-27dc7cd6-175c-49aa-810e-1d7c358ce133.png)

**Comment by martinet101** [comment]
Let's say you face the issue and, instead of clicking the clock you restart the clock (you only need ylto launch it again from the start menu) what is the result?

**Comment by martinet101** [comment]
Actually, can you please send me the log?
