### ISSUE TITLE
[BUG] Clock background wrong color 

### ISSUE THREAD

**Issue by Auncaughbove17** [martinet101/ElevenClock#461]
## Describe the bug
The background of the clock is wrong on 2 of my 3 displays (including main).
On 2 displays it looks like this (it's too dark)
![image](https://user-images.githubusercontent.com/26165288/148464952-1065d952-b8bd-4749-9332-3f1742659f24.png)
And weirdly on the display where it is "correct", it is changing the color to the wrong display. It always adapts to the color shown on my main display, even though it is not on my main display. Example:
With window covering main screen hotbar:
![image](https://user-images.githubusercontent.com/26165288/148465566-63618861-3cdc-413c-ab79-193323661b3b.png)
Without window covering main screen hotbar:
![image](https://user-images.githubusercontent.com/26165288/148465602-d12014b7-dc72-4552-b9e2-d1a147e358c6.png)

## To Reproduce
Steps to reproduce the behaviour:
1. activate eleven clock on secondary (and optionally main) displays
2. see wrong colors

## Expected behaviour
I expect the adaptive color to always adapt to the content currently on that screen.

## Screenshots
In the description

## The Log
too long for issue, so [bin](https://go.0xfc.de/n4g00).

**Comment by Auncaughbove17** [comment]
Today I woke up and it suddenly works fine?

**Comment by martinet101** [comment]
This might be some temp bug with window manager. Anyway, you can set a specific bg color or disable the adaptive bg color from the settings window. Let's give it some time and if the issue happens again, please report it here and I'll reopen the issue.
