### ISSUE TITLE
[BUG] Right-click menu is illegible after update to 3.0.0

### ISSUE THREAD

**Issue by dbonner** [martinet101/ElevenClock#462]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If ElevenClock is showing over a fullscreen window, enable "Hide on fullscreen window from the settings"
</b>

## Describe the bug
ElevenClock automatically updated to 3.0.0 last night.  After the update, both ElevenClock and the right-click menu became very dark and illegible.  I was able to fix ElevenClock by changing background colour.  However the right-click menu is still dark and illegible.  I have attached a screenshot.

## To Reproduce
Steps to reproduce the behaviour:
Right-click on ElevenClock

## Expected behaviour
I expected the menu to have a light background, which is much more legible, just like before the upgrade to 3.0.0.

## Screenshots
The attached partial screenshot is easier to read compared to in real life because it has been blown up in size.  I find the actual appearance on the screen to be very hard to read because it is so dark.
![E;levenClock-Illegible menu problem](https://user-images.githubusercontent.com/241474/148466862-a33f0319-5618-44a2-a8ff-fe3a417afabd.jpg)

## The Log
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.0.0 (v3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0,0,0,100.0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 3840, 2160)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3340, 2040, 500, 120)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 10.5
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟢 Loaded clocks in 0.6453380584716797
🔵 Restart loop: 1
🔵 System tray icon enabled
🔵 Starting update check
🟢 Loaded everything in 0.995917558670044
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by dbonner** [comment]
I forgot to mention a couple of thinks.  I'm not sure if they are relevant:
- I'm getting this problem on both my desktop and laptop. 
- I am running StartAllBack with mostly default settings on both computers. The only non-default settings are icon size and icon margins.  Both of these are set to "S" (small).
- Both computers have 4K screens (3840x2160)
- Both computers have Nvidia graphics cards.
All the best,
Daniel

**Comment by martinet101** [comment]
See #442
