### ISSUE TITLE
Date is cut off

### ISSUE THREAD

**Issue by fborgia** [martinet101/ElevenClock#464]
I don't know how to fix this, I tried restarting the program, adjusting my monitor, still cutting off the date.
I tried re-booting my system and re-ran the ElevenClock.  The date is still cut off unless I run the clock with the weekday feature off.
![Dateoff](https://user-images.githubusercontent.com/28830594/148529959-0a14ee56-a856-4374-a575-a9538a45e695.png)
![Weekdayoff](https://user-images.githubusercontent.com/28830594/148530878-565b463e-d1bf-4817-849d-424164607a8b.png)
.

**Comment by martinet101** [comment]
See #443
