### ISSUE TITLE
[BUG] (Enter your desc

### ISSUE THREAD

**Issue by pastordl** [martinet101/ElevenClock#466]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If ElevenClock is showing over a fullscreen window, enable "Hide on fullscreen window from the settings"
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by pastordl** [comment]
Trying to update H&R Block Premium Tax program. Will not update with elevenclock active. Ended up having to uninstall H&R Block. the make sure elevenclock off reinstall H&R Block. Then could install and update h&r prog. Once installed and checked that H&R prog runnig OK, Exited Program and ran elevenclock. then tried to start H&R prog and it hung up and crashed before fully loading. After uninstall again and leaving elevenclock off,  H&R prog runs fine cycling off and on no problem as long as elevenclock is not been on. If it is on the whole uninstall, reinstall must be done in order for the H&R prog to work.

**Comment by Masamune3210** [comment]
1. This program does nothing that would stop any other program from working, so it's an issue with the other program
2. Please write in actual sentences, it makes it much easier to read

**Comment by martinet101** [comment]
Yeah, @Masamune3210 is right. There's _no reason_ for elevenclock to modify other program's behaviour, it must have been a coincidence.

**Comment by pastordl** [comment]
Had been working with the H&R Block Prog developers on the issue. Since the update installer specified that Elevenclock be turned off for update to be completed they felt there was a conflict somewhere. A few hours after they contacted me indicating they found that the problem was with actually with Windows 11 and not Elevenclock. Their program and updates must be run as administrator in Windows 11. It somehow picks a background app as preventing the update. They say that this is not an issue in Windows 10. After several uninstall, re-install, calls and emails to them and not getting the issue dealt with and the indication from the updater that elevenclock was preventing the update, I reported the problem. It indeed is not the problem nor the cause of it. As long as H&R Block prog is run in administrator mode, no problem is reported on update and restarting the program works fine with Elevenclock running the whole time. They indicated they are working on this issue and apologized for the problem. I also apologize for the report of a bug which I now know has nothing to due with your app.

**Comment by martinet101** [comment]
Ok, all right then
