### ISSUE TITLE
[BUG] Focus Assist Icon always shows as white, regardless of taskbar theme

### ISSUE THREAD

**Issue by Ahmed-Kaid** [martinet101/ElevenClock#470]
## Describe the bug
When having focus assist turned on, the icon is always white, even though it should be black when in light mode.

## To Reproduce
Steps to reproduce the behaviour:
1. Have ElevenClock running
2. Switch to a light themed taskbar
3. Turn focus assist on (priority or alarms only)

## Expected behaviour
The icon should show up and be black.

## Screenshots
![image](https://user-images.githubusercontent.com/24940088/148754468-218ddb88-9a09-4b1e-ba5c-5992fffbf012.png)

## The Log

```
Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟢 Loaded clocks in 1.0331108570098877
🔵 Restart loop: 1
🟡 System tray icon disabled
🔵 Starting update check
🟢 Loaded everything in 1.5909843444824219
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
```

**Comment by martinet101** [comment]
Can you please try restarting ElevenClock?

**Comment by Ahmed-Kaid** [comment]
> Can you please try restarting ElevenClock?

I have restarted ElevenClock, and I also tried restarting my PC. The issue is still there (ElevenClock v3.0.0 as well).

**Comment by martinet101** [comment]
Ok, i'll take a look

**Comment by martinet101** [comment]
Fixed, coming in the next release
