### ISSUE TITLE
cannot get clock to show up on my second monitor its stuck in the center of monitor 1

### ISSUE THREAD

**Issue by rastari** [martinet101/ElevenClock#471]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If ElevenClock is showing over a fullscreen window, enable "Hide on fullscreen window from the settings"
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

## Additional context
![image](https://user-images.githubusercontent.com/97455401/148781799-563c8ea3-ed51-4623-8b58-f5137a72b32b.png)

**Comment by martinet101** [comment]
Can you please enable alternative alignment in the settings window, under optional features?

**Comment by rastari** [comment]
[image: image.png]
where? it's not on the list.

**Comment by martinet101** [comment]
Under experimental features and fixes

**Comment by rastari** [comment]
It worked. Thanks
