### ISSUE TITLE
[BUG] Bottom of the date is cut off

### ISSUE THREAD

**Issue by ronmlabelbox** [martinet101/ElevenClock#473]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If the issue is with the bottom cropped text of the clock, this has been fixed and will come with the next release

</b>

## Describe the bug
When looking at the clock with line 1 - time, line 2 - day of week line, 3 - date
the bottom have of the numbers for date are cut off.

## To Reproduce
Steps to reproduce the behaviour:

## Expected behaviour
Should not be cut off

## Screenshots
![image](https://user-images.githubusercontent.com/70235182/148843240-5ac94268-a26b-4914-ae48-8f682c9f6ab4.png)

## The Log
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.0.0 (v3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 95, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1127, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 95, 0, 1175)
🔵 Restart loop: 1
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟢 Loaded clocks in 1.0789475440979004
🔵 System tray icon enabled
🔵 Starting update check
🟢 Loaded everything in 2.319100856781006
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Closing clock on {'Monitor': (-1920, 95, 0, 1175), 'Work': (-1920, 95, 0, 1127), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 95, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1127, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 95, 0, 1175)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (-1920, 95, 0, 1175), 'Work': (-1920, 95, 0, 1127), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 95, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1127, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 95, 0, 1175)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (-1920, 95, 0, 1175), 'Work': (-1920, 95, 0, 1127), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 95, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1127, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 95, 0, 1175)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (-1920, 95, 0, 1175), 'Work': (-1920, 95, 0, 1127), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 95, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1127, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 95, 0, 1175)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (-1920, 95, 0, 1175), 'Work': (-1920, 95, 0, 1127), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 95, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1127, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 95, 0, 1175)
🔵 Restart loop: 1
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟡 Closing clock on {'Monitor': (-1920, 95, 0, 1175), 'Work': (-1920, 95, 0, 1127), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 95, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟡 Using win32 API positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1127, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 95, 0, 1175)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🟡 Closing clock on {'Monitor': (-1920, 95, 0, 1175), 'Work': (-1920, 95, 0, 1127), 'Flags': 0, 'Device': '\\\\.\\DISPLAY2'}
🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 95, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1127, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 95, 0, 1175)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:True, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Restart loop: 1
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by martinet101** [comment]
Please read the orange dots
