### ISSUE TITLE
[ISSUE] Possible bug with fullscreen behavior: Add toggle for legacy fullscreen mode

### ISSUE THREAD

**Issue by melissasage** [martinet101/ElevenClock#474]
I am putting this in this category because I am genuinely not sure if it's an issue or a bug, but I am having some issues with the interaction between fullscreen apps and the clock. Specifically, the behavior that I dislike is that on a "fullscreen" app that still shows the taskbar, such as a maximized Firefox window, ticking the "Hide the clock in fullscreen mode" option causes it to disappear. But then, if I open a game such as final fantasy xiv, this happens:

![image](https://user-images.githubusercontent.com/25471399/148992619-0ed1d2a8-60ee-48b3-9430-7b15cfc41dd2.png)

I can disable the "Hide the clock in fullscreen mode" to avoid this, but that just means i have to toggle back and forth between settings, which is annoying. Ideally I'd like to be able to specify to hide it with certain programs, or have more control over what *kind* of fullscreen apps cause the clock to be hidden--specifically, only ones that draw over the taskbar.

All of this behavior is with "show the clock when the taskbar is set to hide automatically" not ticked.

**Comment by martinet101** [comment]
Do you have the taskbar set to hide automatically?

**Comment by melissasage** [comment]
No, I prefer it to show in most cases. So in fullscreen Firefox right now, for example, I have the taskbar shown.

**Comment by martinet101** [comment]
> I prefer it to show in most cases

But you often switch this mode?

**Comment by melissasage** [comment]
Nope. I've set it and forget it and most applications where I don't want the taskbar (e.g. fullscreen video) let me configure it per-app.

**Comment by melissasage** [comment]
Speaking of, I've just tested it with fullscreen video and the same thing occurs.

**Comment by melissasage** [comment]
Certain programs provide their own settings for drawing over the taskbar, and if I ever want an app to go true fullscreen I use such settings, like fullscreen video, fullscreen video games, the F11 shortcut in the firefox browser, etc. I do not ever touch the Windows setting.

**Comment by Evaldash** [comment]
Same issue here! When Youtube is in fullscreen, the clock overlay is still present..
![Screenshot 2022-01-12 032210](https://user-images.githubusercontent.com/61429051/149047206-16e1cc86-2fb5-4413-8ea2-47b03d648ef9.png)
.

**Comment by martinet101** [comment]
@Evaldash, @melissasage, can you please send your logs?

**Comment by Evaldash** [comment]
Here's the log:
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.0.0 (v3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "lt"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-200, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Restart loop: 1
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True
🟢 Loaded clocks in 1.6740045547485352
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🔵 System tray icon enabled
🔵 Starting update check
🟢 Loaded everything in 3.482003688812256
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! `Tomuks - Discord (-1928, -8, 8, 1088) Fullscreen rect: (-1920, 0, 0, 1080)
🟡 Fullscreen window detected! Downloads (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
🟡 Fullscreen window detected! *C:\Users\evkax\Desktop\new 2.txt - Notepad++ (1912, -8, 3848, 1088) Fullscreen rect: (1920, 0, 3840, 1080)
0 1
PySide2.QtCore.QRect(48, 16, 16, 16)
PySide2.QtCore.QRect(48, 16, 16, 16)
PySide2.QtCore.QRect(77, 16, 16, 16)
0 1
PySide2.QtCore.QRect(48, 16, 16, 16)
PySide2.QtCore.QRect(48, 16, 16, 16)
PySide2.QtCore.QRect(77, 16, 16, 16)
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found

**Comment by martinet101** [comment]
> HideonFS:False

But you have "Hide on fullscreen disabled". You can enable it on the settings window

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/149152452-20692788-149e-49f8-b3fc-e678029608ce.png)

**Comment by Evaldash** [comment]
I apologise, I didn't notice that. It would be great if this setting would be on by default, I'm sure I'm not the only one who was confused. Thank you! :)

**Comment by martinet101** [comment]
> I apologize, didn't notice that. It would be great if this setting was on by default, I'm sure I'm not the only one who was confused. Thank you! :)

It actually is, but only on the three latest versions. If you installed an older one (most likely from a web where it's outdated, this might happen)

**Comment by Evaldash** [comment]
> 

That is indeed what happened, it's been quite a while since I installed it. Thanks for the help! :)

**Comment by melissasage** [comment]
While poking around I think I've figured out the actual problem, which is that when this setting is ticked, if a fullscreen app is present, even if that app is currently not in focus, elevenclock disables itself. Here's my logs.

[logs.txt](https://github.com/martinet101/ElevenClock/files/7857128/logs.txt)

**Comment by TechStudent11** [comment]
> Certain programs provide their own settings for drawing over the taskbar, and if I ever want an app to go true fullscreen I use such settings, like fullscreen video, fullscreen video games, the F11 shortcut in the firefox browser, etc. I do not ever touch the Windows setting.

Configuring on a per-app basis would prove useful.
Also, this is kinda similar to #472.

**Comment by martinet101** [comment]
> While poking around I think I've figured out the actual problem, which is that when this setting is ticked, if a fullscreen app is present, even if that app is currently not in focus, elevenclock disables itself. Here's my logs.
> 
> [logs.txt](https://github.com/martinet101/ElevenClock/files/7857128/logs.txt)

Yes, this is true, it works like this

**Comment by melissasage** [comment]
That makes sense then. Would it be possible in the future for the app to detect if a fullscreen app is currently in focus? Or, like @TechStudent11 mentioned, potentially just configuring it on a per-app basis? Either of those would be more desirable behavior, at least for me.

**Comment by martinet101** [comment]
> That makes sense then. Would it be possible in the future for the app to detect if a fullscreen app is currently in focus? Or, like @TechStudent11 mentioned, potentially just configuring it on a per-app basis? Either of those would be more desirable behavior, at least for me.

The per-app basis, despite is a good idea, it wouldn't be efficient, because it would need to check every fullsceen/maximized window's process, what takes lots of cpu (see the old RDP/citrix workspace behaviour, was buggy and sketchy). For the focus ones, let's suppose you have  a fullscrene youtube window on a display, and then you open whatsapp/mail/telegram/ony other thing on the other side, the clock wound show, and it is annoying. Actually, the first versions to introduce fullscreen hide used this method, but people complained 🤷‍♂️

**Comment by TechStudent11** [comment]
Maybe make that a setting

**Comment by martinet101** [comment]
That could be an actual solution...
