### ISSUE TITLE
[FEATURE REQUEST] Hide the notification counter

### ISSUE THREAD

**Issue by justinkruit** [martinet101/ElevenClock#475]
In a recent update, the notification counter got added (#429).
Could an option be added to hide this counter? Personally I'm fine with having it only on my main monitor, and would like to hide it on the others.

**Comment by martinet101** [comment]
If you enable Low-CPU mode it willget disabled. But you'll lose automatic background too. 

I should add a switch

**Comment by martinet101** [comment]
fixed, coming with next version
