### ISSUE TITLE
[BUG] ElevenClock suddenly consuming a large amount of CPU, even in "lowCPU" mode

### ISSUE THREAD

**Issue by masnider** [martinet101/ElevenClock#476]
## Describe the bug

Elevenclock is consistently consuming ~9-13% of my CPU.
  
![image](https://user-images.githubusercontent.com/10968331/149399529-29f191a1-e8de-4d93-a8ce-bb1ccd51254b.png)

This persists even if the clock is restarted, or if low-cpu mode is turned on. I only have two total monitors, and am not currently RDPd into anything. No errors or anything interesting in the logs.

Current version afaik, silent auto updates are enabled
![image](https://user-images.githubusercontent.com/10968331/149401079-ec0efc1d-162b-49a9-acdd-3efbad1fcb0c.png)

## To Reproduce
Steps to reproduce the behaviour:
1. Start or restart ElevenClock
2. Observe CPU consumption in Taskmgr

## Expected behaviour
I would not expect ElevenClock to consume so much CPU, I do not believe it did previously

## The Log
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.0.0 (v3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Expected warning
 🟠: Unexpected warning
 🔴: Error

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1440, 2560)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1240, 2512, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Restart loop: 1
🔵 Full screen rect:  (0, 0, 1440, 2560)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🔵 Initializing clock 1...
🟡 Not using taskbar background color
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1440, 336, 1080, 1920)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2320, 2208, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1440, 336, 2520, 2256)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True
🟢 Loaded clocks in 4.8812255859375
🟡 System tray icon disabled
🔵 Starting update check
🟢 Loaded everything in 7.865937948226929
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found

**Comment by martinet101** [comment]
3.1.1 should have that fixed

**Comment by masnider** [comment]
Apologies for not replying sooner, for some reason these notifications landed in my spam. I have forwarded you the dumps that I had collected earlier. I also deleted the directory that you indicated and relaunched the clock, no effect. 

ElevenClock is currently at version 3.2.0 and this issue is still occurring, and I've tried some of the same workarounds as above. Please let me know if we should reopen this or if you would prefer I open another. 

![image](https://user-images.githubusercontent.com/10968331/153315224-5b71ceec-ee4f-4232-9deb-cca2b6084a92.png)

![image](https://user-images.githubusercontent.com/10968331/153315342-e9959de6-cf43-4ea5-b5a2-f21b1c3c4885.png)
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.0 (v3.2) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------
 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1440, 2560)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1240, 2512, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Restart loop: 1
🔵 Full screen rect:  (0, 0, 1440, 2560)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🟡 Not using taskbar background color
🔵 Using bg color: 0, 0, 0, 0
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(1440, 336, 1080, 1920)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(2320, 2208, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1440, 336, 2520, 2256)
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 4.772693634033203
🟢 Cached text input host hwnd: 131968
🟡 System tray icon disabled
🔵 Starting update check
🔵 Low cpu mode is set to True. DisableNotifications is set to False
🟢 Loaded everything in 14.748774290084839
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/we-are-on-twitter.webp
🔵 Saving log...
🟡 log save cancelled!
🔵 Copying log to the clipboard...

**Comment by martinet101** [comment]
Have you tried resetting elevenClock? (deleting the .elevenclock folder in your user diurectory?)

**Comment by masnider** [comment]
Yes, tried deleting the folder already, no impact. 

> Apologies for not replying sooner, for some reason these notifications landed in my spam. I have forwarded you the dumps that I had collected earlier. I also deleted the directory that you indicated and relaunched the clock, no effect.

I will disable the notification badge and see if that helps.
