### ISSUE TITLE
[BUG] black text on black background(in options overflow context menu)

### ISSUE THREAD

**Issue by yazan1107** [martinet101/ElevenClock#478]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
</b>

## Describe the bug
right clicking the tray icon the menu is black text on black background, so it is hardly readable, please fix this asap(i attached photo?)
## To Reproduce
Steps to reproduce the behaviour:
1. Go to corner overflow
2. Right Click on elevenclock app
3. settings shown is black text on black background
4. See error: hardly readable(see photo)
![image](https://user-images.githubusercontent.com/78726445/149499923-9b4a6c1c-cb5a-4623-9c4c-c9c61292395e.png)

## Expected behaviour
contrast thing between text and background
## Screenshots
![image](https://user-images.githubusercontent.com/78726445/149499924-92d84ce8-d5de-40b9-a8b9-990deb00b17d.png)

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by martinet101** [comment]
This issue has been fixed and will come with the next release
