### ISSUE TITLE
[BUG] Overflow problem on second monitor

### ISSUE THREAD

**Issue by akiftnrvrd** [martinet101/ElevenClock#484]
**Is your feature request related to a problem? Please describe.**
(Turkish)
Evet. İkinci monitörde tarih ve saatle birlikte günü göster dediğim zaman ekran görüntüsündeki sorunu yaşıyorum

(English - Google Translate)
Yeah. I have the problem with the screenshot when I say show the day with date and time on the second monitor

**Describe the solution you'd like**
(Turkish)
Bu ayarlar yan yana da kullanılabilmeli. Üst üste konunca sorun oluyor.

(English - Google Translate)
These settings should also be available side by side. It's a problem when you put them on top of each other.

![3 Ekran görüntüsü 2022-01-14 224633](https://user-images.githubusercontent.com/86967730/149576070-43be3220-ff38-4add-8b6b-534c63f1c025.png)

**Comment by martinet101** [comment]
Ok, i see. I'll fix that

**Comment by martinet101** [comment]
Fixed, coming in the next release
