### ISSUE TITLE
Avast antivirus identifes ElevenClock as malware

### ISSUE THREAD

**Issue by Warzdin** [martinet101/ElevenClock#489]
this issue can be worked around by setting avast to not scan the file with ElevenClock.exe in it.

**Comment by martinet101** [comment]
I've sent a false positive report to avast

**Comment by maxgill** [comment]
Here is the result from virus total. Avast and AVG flag it as Win64:Trojan-gen.
https://www.virustotal.com/gui/file/f6f0e06ca0ce4db2d3d57de9cff616d55db53de59db55b417bb10a92ff0f5d69/detection

**Comment by martinet101** [comment]
This is basically because the app was built with PyInstaller

**Comment by Warzdin** [comment]
I thought the Bat files caused it but ok

**Comment by martinet101** [comment]
> I thought the Bat files caused it but ok

There aren't bat files in my program...

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/149753606-59ea640a-94fd-4c15-ac11-e47469a74231.png)

**Comment by Strasser-Pablo** [comment]
I got ElevenClock installation removed by bitdefender. I also tried to reinstall it but got the installer removed before it could be installed. As I saw that the virus total test before contain bitdefender I just reply to this issue and didn't open another one.
I reported the issue to bitdefender by sending them a link to the installer in the release.

**Comment by martinet101** [comment]
Ok, thanks

**Comment by danielslinger** [comment]
BitDefender Total Security flaggeda and quarantined as malware.  I received three notifications today.

"The file %userprofile%\AppData\Local\Programs\ElevenClock\ElevenClock.exe is infected with Trojan.GenericKDZ.82303 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean."

"The file %AppData%\Microsoft\Windows\Start Menu\Programs\ElevenClock Settings.lnk is infected with Trojan.GenericKDZ.82303 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean."

"The file %AppData%\Microsoft\Windows\Start Menu\Programs\ElevenClock.lnk is infected with Trojan.GenericKDZ.82303 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean."

**Comment by maxgill** [comment]
> Here is the result from virus total. Avast, AVG and Antiy-AVL flag it as Win64:Trojan-gen. https://www.virustotal.com/gui/file/f6f0e06ca0ce4db2d3d57de9cff616d55db53de59db55b417bb10a92ff0f5d69/detection

Now 10 security vendors flagged it as malicious...

**Comment by Dardrai** [comment]
At least avast got "resolved" but yeah 9/66 virus scanner recoginze that as a virus

**Comment by martinet101** [comment]
Updates have been paused. install version 3.0 and i'll fix this asap.

**Comment by martinet101** [comment]
See status:https://twitter.com/ElevenClockProj/status/1483351974259142657

**Comment by martinet101** [comment]
Check version 3.1.1. 
It is not flagged anymore

**Comment by tetralovania** [comment]
Opening this up again because Avast has "ww25.somepythonthings.tk" (which ElevenClock tries to access) on their blacklist and therefore flags ElevenClock

**Comment by marticliment** [comment]
Please update to latest ElevenClock version manually. That domain got lost a long time ago
