### ISSUE TITLE
[BUG] Time not on taskbar at top of screen

### ISSUE THREAD

**Issue by CmdrKeen4** [martinet101/ElevenClock#49]
in v1.8 the time was on the taskbar at the top of my screen, though 1 of my screens had the time showing on a different location as per the screenshot i posted in issue#32.

Now in v1.9 the time is in the same location on my 2nd 3rd and 4th monitors, but that location is the bottom right instead of the top right...i know windows no longer supports top taskbars officially so i hope this is not the issue, since it seemed to mostly be working in the previous version.
This has remained through restarting the program, restarting windows, and uninstalling the program and reinstalling it.
![Screenshot 2021-10-10 174957](https://user-images.githubusercontent.com/92238042/136712712-f58ba1a7-b52e-4650-b0dc-b38f5c3e20a0.png)

**Comment by martinet101** [comment]
Fixed, will be present on next update
