### ISSUE TITLE
[BUG] "Blue" title background

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#490]
(low-prio), v3.1.0

Native window with settings ("Nastavení") have title background is correct.

Settings window of ElevenClock have title background is "blue" .

![2022-01-16 15 40 35](https://user-images.githubusercontent.com/3808250/149664709-f9963d40-e9e0-48ce-a380-11ab69a36f1a.png)

System color settings:
![2022-01-16 15 42 04](https://user-images.githubusercontent.com/3808250/149664759-0d43eb21-6188-4c80-b7e0-975c757afa6e.png)

**Comment by martinet101** [comment]
Yes, this is a windows issue. 

In this window, mica is enabled through an undocumented api. Since this api has been made public on the latest windows 11 preview, I expect microsoft to eventually fix that.
