### ISSUE TITLE
[ISSUE] Eleven clock is reported as a malware

### ISSUE THREAD

**Issue by redace0001** [martinet101/ElevenClock#492]
Hello,

Today when I started my computer, eleven clock tried to update to the last version but my antivirus stopped him and reported a malware.
Reported as Win64:Trojan-gen by "Avast!".

I tried to install it manually but it also failed because it thinks it's a malware.

I've reported a false positive but maybe you changed something that antiviruses don't like ?

It was working fin until then

**Comment by martinet101** [comment]
Yes, see https://github.com/martinet101/ElevenClock/issues/489. Already have reported that to avast

**Comment by redace0001** [comment]
Ok I didn't see it because the issue was closed. Sorry for the time lost responding.
You should left one "pending" so people don't open more issues until it is resolved.

**Comment by martinet101** [comment]
Yes, good idea!
