### ISSUE TITLE
[BUG] ElevenClock clock has a gray background where there should be the taskbar background

### ISSUE THREAD

**Issue by SamJoex** [martinet101/ElevenClock#496]
## Bug Description
When I upgraded from 3.0.0 to 3.1.0, the clock gained a gray, translucent background. This occurs even when "Use a custom background color" is disabled.

## To Reproduce:
1. Install ElevenClock 3.1.0 or upgrade to it from a previous version.
2. See error

## Expected behaviour
The taskbar background should show instead.

## Screenshots
Version 3.1.0 behavior:
![ElevenClock 3 1 0 bug](https://user-images.githubusercontent.com/88250307/149677517-c67e1298-8aa7-4544-9afb-2703afb313dd.png)

Version 3.0.0 behavior:
![ElevenClock 3 0 0 behavior](https://user-images.githubusercontent.com/88250307/149677525-9a400507-0f0e-49ab-840a-d80ef009b541.png)

## The Log

---------------------------------------------------------------------------------------------------

   ElevenClock's 3.1.0 (v3.1) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True
🟢 Loaded clocks in 0.9329979419708252
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.4024531841278076
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/we-are-on-twitter.webp
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/we-are-on-twitter.webp

## Additional context
As a sidenote, all the Clock Appearance options are unchecked. I am also using Windows 11 Dev Build 22533.1001. The error is somewhat mitigated upon adding an extra icon like Discord in the system tray, but it's still possible to discern a slight translucent background that shouldn't be there. The background also reacts with the "Taskbar corner overflow" arrow.

**Comment by martinet101** [comment]
Can you please, under clock position, on the settings, enable custom height and adjust it till the clock looks normal? Thanks

**Comment by martinet101** [comment]
It is still a bug

**Comment by IAmVisco** [comment]
I think I have something to add up to this issue. I use different backgrounds on my 2 monitors, but by default the app seems like to sample color of the main screen and paste it on other screens. Compare main screen 
![image](https://user-images.githubusercontent.com/18630605/150098165-457df210-f016-4ef4-ab12-388b35238e86.png)
and 2nd screen colors. 
![image](https://user-images.githubusercontent.com/18630605/150098197-555fd9da-f357-4d60-bdf9-32b6955eb865.png)
If I check "Disable block taskbar background color," 2nd monitor has correct colors (because it's transparent?), while main screen has... this.
![image](https://user-images.githubusercontent.com/18630605/150098310-50783331-1f2a-47a5-9176-6844123c2051.png)

**Comment by martinet101** [comment]
Ok, i see. I guess there's an issue with the automated color picker

**Comment by martinet101** [comment]
It should be now fixed. Anyway, i'm gonna test in on some dev channel builds

**Comment by martinet101** [comment]
Yes, tested and it works now
