### ISSUE TITLE
Error:  DeleteFile failed: code 5

### ISSUE THREAD

**Issue by wpcoe** [martinet101/ElevenClock#497]
This just started today.  Coincidentally, I also upgrade Win 11 Home to Win 11 Pro, so not sure if that's related?
![elevenclock](https://user-images.githubusercontent.com/92417196/149679605-e4a72ea9-824e-4354-8741-7dd8d84ef1b5.gif)

I'm not (re-)installing, so I'm assuming ElevenClock is trying to update itself?

**Comment by dinokath** [comment]
I am having the same issue as well. Noticed the clocks were gone. Went to do a reinstall and am now getting this error. Disabled my antivirus and still the same issue. Using Bitdefender.

**Comment by martinet101** [comment]
Try not disabling the antivirus but whitelisting the installer

**Comment by wpcoe** [comment]
Yesterday, I got the code-5 error a few more times, then one time it apparently worked as I got a pop-up saying ElevenClock had been updated and gave a changelog.  Go figure.

FWIW, my clocks never disappeared.

**Comment by martinet101** [comment]
Ok. then should I close this?
