### ISSUE TITLE
[FEATURE REQUEST] Hovering over clock does not provide more info

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#5]
If you hover over original clock you get this - not on clocks made by program

![image](https://user-images.githubusercontent.com/22828430/136049556-add93088-a943-4454-a9d0-a426242c18ee.png)

**Comment by SmartManoj** [comment]
> I'm sorry, but i can't implement this because windows registry clocks 1 and 2 use a timezone method not compatible with python's, and i've found no way to convert them. I'm sorry though :(

You can use [this](https://github.com/regebro/tzlocal/blob/master/tzlocal/windows_tz.py)

**Comment by martinet101** [comment]
Mhmm, that looks promising...

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/161381429-08485252-6dda-4146-aca7-eee239b2518e.png)
Coming in the next release!

**Comment by myfairsyer** [comment]
Now that you can convert the timezone formats, can you also make %z and %Z work in custom date formats?

(I assume the different timezone format is why `%z` and `%Z` do not work for me. If there is another reason or it should even normally work and only does not work for me or if implementing this is rather complicated, or you wish so for any other reason, I'd open a separate issue for this.)

Currently `%z` and `%Z` just stay empty on my machine:
![image](https://user-images.githubusercontent.com/13559472/164158484-6226b64f-a8db-490b-bd8f-6e431c07e21b.png)

**Comment by myfairsyer** [comment]
@martinet101 As you almost immediately reacted to my other comment from the same day, I guess you might have missed this one and I allow myself to _ping_ :)

**Comment by martinet101** [comment]
Oh yes, missed it. I think this is already an open issue, isn't it? If not, can you open it please? Thx!
