### ISSUE TITLE
[BUG] (eleven clock not showing on my secondary monitor!)

### ISSUE THREAD

**Issue by yazan1107** [martinet101/ElevenClock#500]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If the issue is with the bottom cropped text of the clock, this has been fixed and will come with the next release

</b>

## Describe the bug
eleven clock not showing on my secondary monitor!
## To Reproduce
Steps to reproduce the behaviour:
enable eleven clock
not showing on secondary monitor

## Expected behaviour
to show clock on secondary monitor
## Screenshots
<img width="78" alt="image" src="https://user-images.githubusercontent.com/78726445/149724345-5b89abe6-3a0d-43bb-87c0-9cc87c936314.png">

## The Log
[log.txt](https://github.com/martinet101/ElevenClock/files/7879763/log.txt)

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by martinet101** [comment]
Can you please share yout log

**Comment by yazan1107** [comment]
I shared it you see the log.txt file? It is my log file

**Comment by martinet101** [comment]
Can you please send me a screenshot of your display arrangement? something llike this:
![image](https://user-images.githubusercontent.com/53119851/150634731-1ad303ea-cce2-4fe5-b298-1ba43f479e74.png)
Both screens 1920x1080p at 100% scaling

**Comment by corwinx** [comment]
I've been having this issue for a couple of days, couldn't get to the bottom of it. Reinstalling the app didn't help.

What did work was uninstalling ElevenClock, deleting c:\users\<user>\.elevenclock\ and then reinstalling.

**Comment by Japultra** [comment]
> 
That worked! Thank you
