### ISSUE TITLE
[BUG] Enabling week number hides battery icon

### ISSUE THREAD

**Issue by GameBurrow** [martinet101/ElevenClock#502]
## Describe the bug
Enabling week days will hide the last icon of 3-icon section, maybe allow to move it to third line?

## To Reproduce
Steps to reproduce the behaviour:
1. Enable the week numbers

## Screenshots
See the gif below
![https://i.imgur.com/cwv5PDG.gif](https://i.imgur.com/cwv5PDG.gif)

## The Log
Log was too long to paste here.
https://gist.github.com/GameBurrow/3b8949dde5664735f09ef30cef947f7d

## Additional context
Could be that the issue comes with StartAllBack installed (even though I disabled it's taskbar, keeping the default Win 11 taskbar) - EDIT: Nope, even without that, issue occurs.

**Comment by martinet101** [comment]
No, that's because the clock text gets wider. This can't really be changed, you can only set a smaller font size

**Comment by myfairsyer** [comment]
Would you mind adding this to your wiki's known issues section? @martinet101 
https://github.com/martinet101/ElevenClock/wiki#known-issues

**Comment by martinet101** [comment]
Yes, this could be a thing in there!
