### ISSUE TITLE
[FEATURE REQUEST] Confirmation window before auto update

### ISSUE THREAD

**Issue by Seeloewen** [martinet101/ElevenClock#51]
**Is your feature request related to a problem? Please describe.**
It's sometimes really annoying when the auto update starts automatically, especially if you are in a fullscreen game as it tabs you out.

**Describe the solution you'd like**
It would be great if a window could pop up which asks you if you want to update the software. The window also **_shouldn't_** tab you out of your current window, but rather stay in the background. A windows notification could also be a good solution.

**Comment by martinet101** [comment]
Coming in release 2.0
