### ISSUE TITLE
[FEATURE REQUEST] Automatic/recurring reload

### ISSUE THREAD

**Issue by barbatron** [martinet101/ElevenClock#512]
**Is your feature request related to a problem? Please describe.**
As display set changes e.g. TV or monitors turn on/off, the clock often gets misaligned. 

**Describe the solution you'd like**
Either detect changes to the set of displays, or allow the clock to self-reload every minute or so, if possible.

**Comment by martinet101** [comment]
This is an issue related with Qt5. You'll need to right-click the clock ->  Restart ElevenClock
