### ISSUE TITLE
Dark stripe on the background of the clock on the 2nd monitor.

### ISSUE THREAD

**Issue by vladimir-kordas** [martinet101/ElevenClock#514]
Hello, I am writing with a technical question. It is about the background hiding feature on the 2nd monitor. I use Elevenclock on both monitors. Because of the primary monitor I have to have the background on (then the original windows clock can be seen). However, when I have the background on, there is a dark bar under the clock on the second monitor (you can see it in the attached picture). My question is if there would be a possibility of having the background on only on the primary monitor and having the option off on the 2nd one, since I don't have to cover any clock there.

![Untitled](https://user-images.githubusercontent.com/81954797/150103229-f5bd457d-a21c-47b9-a488-586c96e0f374.png)

**Comment by martinet101** [comment]
Yes, it is a glithch related to transparent backgrounds (and it is actually intended.) If the background was fully transparent, the clock wouldn't respond to mouse hover/click
