### ISSUE TITLE
[FEATURE REQUEST] Interop with rounded TB

### ISSUE THREAD

**Issue by trajano** [martinet101/ElevenClock#522]
**Is your feature request related to a problem? Please describe.**
RoundedTB makes the non-allocated areas of the taskbar fully transparent.  But It also means that the Eleven Clock area is also transparent on the other monitors. 

**Describe the solution you'd like**
Provide an option (do not remove existing show transparent settings) to read the color value for the taskbar from Windows and set that as the background.

**Comment by martinet101** [comment]
You can set a custom background color, and on the color chooser, there's a button to pick a on-screen color

**Comment by trajano** [comment]
Yes but I was wondering if it can be done automatically without having to eyedrop it.

**Comment by martinet101** [comment]
Yes, this could definely be a feature... Idk, i'll take a look

**Comment by trajano** [comment]
I saw this https://stackoverflow.com/questions/50840395/c-sharp-console-get-windows-10-accent-color it may help

**Comment by martinet101** [comment]
Fixed, cmoing with the next version
