### ISSUE TITLE
[BUG] UI fonts for Simplified Chinese should use Microsoft YaHei UI instead of Microsoft JhengHei UI

### ISSUE THREAD

**Issue by Hill-98** [martinet101/ElevenClock#524]
`Microsoft JhengHei UI` It is a font created for Traditional Chinese, it is not the best for displaying Simplified Chinese, you should use `Microsoft YaHei UI`, which is a font created for Simplified Chinese.

Note: If setting the clock font to `Microsoft YaHei UI` would be less than pretty, I suggest reserving the use of `Segoe UI Variable` for Simplified Chinese environments to make it similar to the native display. (I'm not sure exactly what the native clock font is)

**Comment by martinet101** [comment]
Fixed, coming in the next release
