### ISSUE TITLE
[ISSUE] Two of them will be activated at the same time

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [martinet101/ElevenClock#526]
Two of them will be activated at the same time.
You can work around this by closing one of them manually, but this problem started to occur after the timing of the update to v3.1.1.

![image](https://user-images.githubusercontent.com/11265280/151467031-63602d45-c4cb-4ee4-8f97-6b57307a4a73.png)
![image](https://user-images.githubusercontent.com/11265280/151467050-fa41a395-7f3c-4af2-b47b-29d3da2ff171.png)
![image](https://user-images.githubusercontent.com/11265280/151467314-84696a9d-ce90-47be-becc-06d973642302.png)

**Comment by martinet101** [comment]
can you please send me your log?
