### ISSUE TITLE
[FEATURE REQUEST] Change Current Lineup

### ISSUE THREAD

**Issue by MuhammetEminCakir** [martinet101/ElevenClock#530]
This is current lineup for ElevenClock:
Time(23:58:20)
Weekday(Cumartesi)
Date(29.01.2022)
![Ekran görüntüsü 2022-01-29 235851](https://user-images.githubusercontent.com/64583157/151677407-47ae5682-3a13-4869-bc28-000106a3296a.png)

I want to change this like
Time(23:58:20)
Date(29.01.2022)
Weekday(Cumartesi)

Can you add a feature for this?

**Comment by martinet101** [comment]
This will be implemented in #380
