### ISSUE TITLE
[FEATURE REQUEST] Show detailed date info as tooltip on hover

### ISSUE THREAD

**Issue by sinusinu** [martinet101/ElevenClock#531]
Windows' clock shows detailed date info as tooltip when user hovers mouse over the clock.
I sometimes use this feature to check weekday, and ElevenClock's clock missing the tooltip itches me occasionally.
ElevenClock's "Show weekday on the clock" makes the clock text 3 lines, which I do not prefer aesthetically...
so having a tooltip like this would be appreciated.
![1](https://user-images.githubusercontent.com/1446561/151687095-64a13b02-012a-4970-bd28-542902677054.png)

**Comment by martinet101** [comment]
I had tried it, but tooltips somehow are broken. Anyway, i'll take a look
