### ISSUE TITLE
[BUG] Confusing label at disabled state

### ISSUE THREAD

**Issue by Kira-Lappo** [martinet101/ElevenClock#535]
### Version
3.2.0 , branch **main** (d97755be1dfbc477e59)

### Repro steps
1. Open settings 
2. Open **Clock Appearance** section
2. Enable option **Use a custom background option**
3. Check tooltip of disabled option **Use system accent color as background color**

Expected: it says "**Use a custom background option** needs to be disabled to change this setting"
Actuall: it says "**Use system accent color as background color** needs to be disabled to change this setting"

![image](https://user-images.githubusercontent.com/11411852/151714759-003ff871-5336-4bb5-bb1b-f74d56835df2.png)

**Comment by martinet101** [comment]
Yeah, you're right. I just messed up the strings. It is fixed now. Thx for noticing!
