### ISSUE TITLE
[BUG] I keep getting errors about things not being compatible with Windows.

### ISSUE THREAD

**Issue by dredshep** [martinet101/ElevenClock#539]
I just turned on my screen and saw the following:

![image](https://user-images.githubusercontent.com/78047001/151815848-e29b10f4-a192-42cf-a03e-7f847be3f3e2.png)

I've seen different errors with different dialogs, saying things like "this python thing" or "that other thing" is not compatible with Windows, or with my version of Windows, etc. If I have more of these I can bring them.

edit: new one

![image](https://user-images.githubusercontent.com/78047001/151818790-91f3820e-652a-48da-8fc3-39e83667f3c5.png)

![image](https://user-images.githubusercontent.com/78047001/151818887-fa62b83e-abcb-43e9-bac8-84abc4a1a871.png)

**Comment by Masamune3210** [comment]
You have a corrupted Windows install, or something has gone seriously wrong

**Comment by dredshep** [comment]
Hmm, I'm not sure that's the case but it's possible. I've never had an error like this on this laptop, and I have installed and used quite a few programs, including dozens of games and random apps. This is the first time I've seen an error like this on this computer.

**Comment by martinet101** [comment]
@Masamune3210 is right, you might have a corrupted copy of windows. Can you please try this guide? https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

**Comment by martinet101** [comment]
> Hmm, I'm not sure that's the case but it's possible. I've never had an error like this on this laptop, and I have installed and used quite a few programs, including dozens of games and random apps. This is the first time I've seen an error like this on this computer. How could I tell if my Windows install is corrupted?

Yes, the answer might feel weird, but some people reporthed this and they happened to have corrupt installations
