### ISSUE TITLE
[ISSUE] Antivirus Removed Elevenclock

### ISSUE THREAD

**Issue by verrucktschmidt** [martinet101/ElevenClock#540]
G'day,
Absolutely love Elevencclock. I have been using it for weeks with plenty of antivirus scans but I have woken up this morning to my screen covered in "Suspicious software blocked" and "All Threats Resolved"

Am I safe to add the software to the exception list or has the software been compromised?
![Elevenclock Threat Suspicious 2](https://user-images.githubusercontent.com/97493745/151878271-cda9f7f4-6957-4c1c-b959-cea9393e4987.jpg)

**Comment by TechStudent11** [comment]
First of all, welcome to GitHub :)

And second, this is probably a false-positive from PyInstaller. When converting Python apps to executables, antiviruses tend to not like it. As you can see from the window, it appears that some image/temp file is causing some false positive. You should be good to add the program to your exception list.

**Comment by verrucktschmidt** [comment]
Thanks was hoping that was the case.
I'm more used to false positives in nursing haha
