### ISSUE TITLE
Unfortunately, I can't display the clock on the right, it always appears on the left, even though the left display is turned off.[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by laszlodrgero** [martinet101/ElevenClock#543]
[##]([url]([url](url))) Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If the issue is with the bottom cropped text of the clock, this has been fixed and will come with the next release

</b>

## Describe the bug
Unfortunately, I can't view the clock on the right, it always appears on the left, even though the left view is turned off.

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

## Additional context
![2022-02-01_064026](https://user-images.githubusercontent.com/70061393/151919748-8afebb19-87fa-414e-a525-ace699bad4ac.jpg)
![2022-02-01_064223](https://user-images.githubusercontent.com/70061393/151919753-e127e674-297d-412c-a6a1-25f327252978.jpg)

**Comment by martinet101** [comment]
Can you please delete the  .elevenclock folder placed in your user directory?

**Comment by laszlodrgero** [comment]
> 

Thanks! problem solved!

![2022-02-01_134713](https://user-images.githubusercontent.com/70061393/151971153-f8a21846-53af-4784-84f9-c766289748b0.jpg)
