### ISSUE TITLE
[FEATURE REQUEST] Left Side Clock?

### ISSUE THREAD

**Issue by C0NFR0NTATI0N** [martinet101/ElevenClock#544]
With my setup I have dual monitors with my mic in front of both in the middle.  I'm using Windows 11 with Start Menu in the middle of the screen on both monitors.  I would prefer to have a clock in the taskbar on the left side of the screen, could this be done?  Essentially a clock on the left on the left monitor and a clock on right on right monitor.

**Comment by martinet101** [comment]
Yes, right-click the clock you want to move to the left -> monitor tools -> move this clock to the left
