### ISSUE TITLE
[FEATURE REQUEST] Chime every hour

### ISSUE THREAD

**Issue by ShinyRP** [martinet101/ElevenClock#548]
Thank you for this. In Tclock you can set it so you receive a small chime every hour. Is this possible to implement?

**Comment by martinet101** [comment]
I could try, but i can't guarantee nothing...

**Comment by martinet101** [comment]
Hi, due to package sizes and module incompatibiity, seeing the few range of people that this improvement could benefit has made me think of not implementing 
. However, i'll keep this in mind for a possible (but not near) future.

Sorry for taking this long :(
