### ISSUE TITLE
[ISSUE] WIndows 11 with Classic Shell: ElevenClock's background is transparent showing the original Windows clock behind

### ISSUE THREAD

**Issue by aholzinger** [martinet101/ElevenClock#549]
Running Windows 11 and Classic Shell (for me it works, knowing that it's abandoned) the EöevenClock tray clock is shown above the Windows 11 tray clock, because the background of ElevenClock seems to be transparent.

Is there a way to make the background of the ElevenClock tray clock solid so that the Windows 11 tray clock will not be visible anymore?

**Comment by Masamune3210** [comment]
Its in the settings

**Comment by aholzinger** [comment]
Thank you. Just two minutes ago I found the background settings.

I have a feature request though: A colour picker would be perfect.

**Comment by martinet101** [comment]
Yes, it is actually present

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/152020145-f952c553-7630-478e-80ac-8fd01269dbfb.png)

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/152020168-5919804d-34e7-4d53-80c2-9f7f440aad05.png)

**Comment by martinet101** [comment]
If you update to the latest version, you can enable an automatic background color by disablihg the following checkbox:
![image](https://user-images.githubusercontent.com/53119851/152020356-6b026803-c273-4be8-815e-39d4d1930667.png)

**Comment by aholzinger** [comment]
Perfect!

Thank you very much
