### ISSUE TITLE
[BUG] Initial icon size on HiDPI monitors is too small + width bug on dev build

### ISSUE THREAD

**Issue by Kira-Lappo** [martinet101/ElevenClock#551]
1. Use HiDPI monitor (working resolution 3840x2160 with 250%(recommended) scaling)
2. Open Settings
3. Icons of settings groups are too small. Opening/collapsing setting group resizes icons to appropriate value.

![image](https://user-images.githubusercontent.com/11411852/152046810-1c8c6d21-4c2b-4afe-8968-bf8e9e752cfc.png)

**Comment by martinet101** [comment]
Can you please send me the log?

**Comment by Kira-Lappo** [comment]
@Kira-Lappo Todo [2022/02/03 KL] Add logs here

**Comment by Kira-Lappo** [comment]
```shell
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.0 (v3.2) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "ru"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 26,44,75,100
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3340, 2040, 500, 120)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 0.42226719856262207
🔵 Restart loop: 1
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.2201857566833496
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/we-are-on-twitter.webp
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

```

**Comment by Kira-Lappo** [comment]
today I noticed that settings windows is opened with a correct icon size, but some seconds later they are scaled down

**Comment by martinet101** [comment]
Mhmm.. weird...

**Comment by Kira-Lappo** [comment]
@martinet101

https://user-images.githubusercontent.com/11411852/152412200-9c35d3ea-c016-45ea-aed6-cfa3a8290fee.mp4

**Comment by Kira-Lappo** [comment]
idk may be it is a Qt issue

**Comment by martinet101** [comment]
> idk may be it is a Qt issue

Honestly, i don't think so, since I had to implement the icon scaling mechanism. Idk, i'll take a lookj

**Comment by Kira-Lappo** [comment]
@martinet101 I don't think it's a "high" priority, it doesn't break the app in the end))
you have more important issues than that)

**Comment by martinet101** [comment]
> @martinet101 I don't think it's a "high" priority, it doesn't break the app in the end)) you have more important issues than that)

Yes, but it is going to probably bve a simple thing where i forgot to add the scale, and, not gonna lie, it looks disappointing

**Comment by martinet101** [comment]
The issue has been fixed (in theory). The fix will come with the next release

**Comment by Kira-Lappo** [comment]
ok, I tested it on 0d60779b3c2688 and icon size is of appropriate size
ps Idk why settings are so narrow, I believe, I build it incorrectly :) will check on a release build
![image](https://user-images.githubusercontent.com/11411852/153256794-3ea97b90-8c8a-4500-a93e-7f21586ab1c4.png)
