### ISSUE TITLE
[BUG] Wrong color with "Use system color"

### ISSUE THREAD

**Issue by Kira-Lappo** [martinet101/ElevenClock#552]
**Version**
latest release, 3.2.0

With "Use system color as a background" option enabled, it takes a brighter color than one that is used in a system theme.
You can see that on the screenshot attached here

![image](https://user-images.githubusercontent.com/11411852/152048206-49e69104-b8a3-4703-85a9-211d6f41dd16.png)

**Comment by nicholasz2510** [comment]
Similar issue here! 
![image](https://user-images.githubusercontent.com/20385225/152069838-1f67aaef-5de0-4c14-8ffa-c53bfc59bc46.png)

**Comment by martinet101** [comment]
Yes thst one I was not sure of which accent color to get, since Windows provides 8 of them (see pic). The clock uses color 1, do you thing it should use color 2?
![image](https://user-images.githubusercontent.com/53119851/152195220-22ee2930-b833-4034-946a-9c65c7b30f99.png)

**Comment by Kira-Lappo** [comment]
> Yes thst one I was not sure of which accent color to get, since Windows provides 8 of them (see pic). The clock uses color 1, do you thing it should use color 2? ![image](https://user-images.githubusercontent.com/53119851/152195220-22ee2930-b833-4034-946a-9c65c7b30f99.png)

I think yes, the second, darker one. If it is possible to change in code and check it,  I can do that, just tell me where pick-color code is placed

**Comment by Kira-Lappo** [comment]
> Similar issue here! ![image](https://user-images.githubusercontent.com/20385225/152069838-1f67aaef-5de0-4c14-8ffa-c53bfc59bc46.png)
> 
> Edit: I actually don't have "Use system color as a background" enabled. This seems to be a bug with having clocks on other windows displayed on a different color background.

Update to 3.2.0, the feature appeared in the latest release.

**Comment by martinet101** [comment]
> Similar issue here! ![image](https://user-images.githubusercontent.com/20385225/152069838-1f67aaef-5de0-4c14-8ffa-c53bfc59bc46.png)
> 
> Edit: I actually don't have "Use system color as a background" enabled. This seems to be a bug with having clocks on other windows displayed on a different color background.

What I think is hapening to you is that, since your taskbar is modified and has a transparent margin, ElevenClock is taking your background image color as background color. You can setting a Y offset or a specific height from the settings window, under Clock position and size

**Comment by Kira-Lappo** [comment]
@martinet101 I used you algorithm that gets colors from registry to get my color pallete
here it goes
![image](https://user-images.githubusercontent.com/11411852/152418574-b7020cab-c8c7-44a0-ad5d-a2aaedf564d8.png)

the color order as in you initial colors array

**Comment by martinet101** [comment]
Ok, this is color [5] (from index 0-7), and the current picked color is [4]. gotta change that

**Comment by Kira-Lappo** [comment]
tested on 0d60779b3c2688fb9, worked like a charm
