### ISSUE TITLE
[BUG] Day of week and week number with Russian language

### ISSUE THREAD

**Issue by Kira-Lappo** [martinet101/ElevenClock#555]
Version: latest release 3.2.0
I use the English language as a system language and have English region formats in the system.
But I use ElevenClock with Russian translation (yep, I am a weirdo).
For some reason, day of week and week number are not displayed with such a combination of parameters.
English or Polish translations do have DOW and D#. With Polish translation it shows English names of days.

![image](https://user-images.githubusercontent.com/11411852/152052679-0c3f5ee6-6899-423b-9db4-044cf2a84b4d.png)

```shell
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.0 (v3.2) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "ru"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🟡 Not using taskbar background color
🔵 Using bg color: 19,33,56,100.0
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 3840, 2160)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3340, 2040, 500, 120)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 3840, 2160)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:False, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 Restart loop: 1
🟢 Loaded clocks in 1.93558931350708
🟢 Cached text input host hwnd: 131836
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to True. DisableNotifications is set to False
🟢 Loaded everything in 2.718893051147461
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/we-are-on-twitter.webp
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Copying log to the clipboard...
```

**Comment by martinet101** [comment]
Yes, this happens because the locales are taken from the system. The only thong that is loaded from ElevenClock is the "W" that codes for week.

**Comment by martinet101** [comment]
In fact, I tried converting from ttf to odf, and those are the results:
Converted vs original:  ![image](https://user-images.githubusercontent.com/53119851/152196690-e83f380d-5a19-4bd0-a2ae-cddaecab76ee.png)![image](https://user-images.githubusercontent.com/53119851/152196758-c6163bf9-d709-48bb-b224-b048eec53d9a.png)

It just looks broken

**Comment by Kira-Lappo** [comment]
> Yes, this happens because the locales are taken from the system. The only thong that is loaded from ElevenClock is the "W" that codes for week.

Right, but days of week and week number are not displayed at all in Russian. And at the same time with Polish language in the app, they are displayed as in system locale.

**Comment by martinet101** [comment]
> > Yes, this happens because the locales are taken from the system. The only thong that is loaded from ElevenClock is the "W" that codes for week.
> 
> Right, but days of week and week number are not displayed at all in Russian. And at the same time with Polish language in the app, they are displayed as in system locale.

Yes, because your system locale format is english

**Comment by Kira-Lappo** [comment]
> Yes, because your system locale format is english

Right, but why does it work for Polish translation?) It should just pull system locale and show week days in English (in my case)
![image](https://user-images.githubusercontent.com/11411852/152412836-0249c5ea-0c6d-4301-95fa-6a8d387bb815.png)
After switching from Polish to Russian the clock is completely gone
![image](https://user-images.githubusercontent.com/11411852/152412926-57576f53-f1d7-44d1-bb00-5653ee22e895.png)

**Comment by martinet101** [comment]
Huh, tha's weird... Can you please send me the log after the clock gets empty?

**Comment by martinet101** [comment]
Ok, there you go

**Comment by martinet101** [comment]
Could you please run the latest commit and send me again the log? Thx!

**Comment by Kira-Lappo** [comment]
@martinet101 
```bash
ElevenClock on  main [?] via 🐍 v3.10.2 took 52s
❯ python .\elevenclock\__init__.py
Exception in thread Main: Locale string loader:
Traceback (most recent call last):
  File "C:\Users\kiril\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "D:\workspace\github.com\ElevenClock\elevenclock\tools.py", line 159, in settrace_and_run
    self._run()
  File "C:\Users\kiril\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "D:\workspace\github.com\ElevenClock\elevenclock\__init__.py", line 417, in timeStrThread
    nTimeStr = datetime.datetime.now().strftime(dateTimeFormat)
UnicodeEncodeError: 'locale' codec can't encode character '\u041d' in position 18: encoding error
```

What I did was:
* started eleven clock
* switched to polish
* set clock to print dow and week number
* switched to russian
* restarted

Now the clock is just blank
![image](https://user-images.githubusercontent.com/11411852/153247781-8fcef26c-8aae-424b-bcd5-3dcf05af3fab.png)

Commit 0d60779b3c26

**Comment by Kira-Lappo** [comment]
@martinet101 it does not support cyrillic Н 
https://unicode-table.com/en/041D/
It comes from translation file 
![image](https://user-images.githubusercontent.com/11411852/153252570-e74f5810-9a3e-45a8-a368-8712f2fa19d0.png)

**Comment by Kira-Lappo** [comment]
just a minor update: now it does show Weekday in English
but there is that problem with week number, that is described above

**Comment by martinet101** [comment]
The question might seem dumb, I don't know russian and say no if the answer is no, but could the H be replaced by a standard H?

If not, do you think that a solution could be adding a placeholder character and then replacing it after the strftime() function?

**Comment by Kira-Lappo** [comment]
@martinet101 what do you think about this https://github.com/martinet101/ElevenClock/issues/555?
Using Latin H was my first thought as well, but it could be any other non-ASCII symbol from any other language

**Comment by martinet101** [comment]
> Using Latin H was my first thought as well, but it could be any other non-ASCII symbol from any other language

Yeah, that's actually true. 



> @martinet101 what do you think about this #555?

If it works it is good then

**Comment by Kira-Lappo** [comment]
https://github.com/martinet101/ElevenClock/pull/572
it works locally) I found the solution here:
https://bugs.python.org/issue8304

**Comment by martinet101** [comment]
Yes, the code looks good and the source seems legit.

Thank you for the fix!

This issue can then be closed?

**Comment by Kira-Lappo** [comment]
why not
