### ISSUE TITLE
Can the width be based on the longest possible time string for the font used?

### ISSUE THREAD

**Issue by Hypersapien** [martinet101/ElevenClock#559]
Right now, as the time changes, the width of the overlay changes with the width of the characters used in the time, causing shifting with the date. When ElevenClock starts up, or when the font is changed, could the app figure out the widest numbers used in every position in the time string, and base the width on that?

I noticed that there was a slider to override the height of the clock, but not the width.

**Comment by martinet101** [comment]
See #519
