### ISSUE TITLE
[ISSUE] Brief Description

### ISSUE THREAD

**Issue by madalinn** [martinet101/ElevenClock#565]
Hello,

I blacklisted one of my two secondary monitors, so now the clock is displayed only on one secondary monitor. But I need it back. How can this monitor be removed from the blacklist? I looked everywhere in the settings area but couldn't find any option for this.

Thanks
Madalin

**Comment by martinet101** [comment]
You can reset the blacklisting status from the settings window:
![image](https://user-images.githubusercontent.com/53119851/152675837-65bfa093-aab3-4cfb-baed-e1b25240a9a9.png)
