### ISSUE TITLE
[BUG] Elevenclock messes with norton or vice versa

### ISSUE THREAD

**Issue by XboxBedrock** [martinet101/ElevenClock#569]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the FAQ on README.md for solutions<br>
✅ I have checked the settings window for an option to toggle/fix what is happening<br>
✅ I have installed the latest version and the issue still happens<br>
  
  
### 🟠🟠 If the issue is with the bottom cropped text of the clock, this has been fixed and will come with the next release

</b>

## To Reproduce
Steps to reproduce the behaviour:
1. Have a machine with Norton Antivirus installed
2. Click on the clock
3.  The norton video blocker and mic panel shows up instead the windows wiget menu thing

## Expected behaviour
The windows menu that opens without elevenclock should open

![image](https://user-images.githubusercontent.com/68715625/153104712-294d1e1a-d836-43e7-a734-5df0e855c567.png)

**Comment by martinet101** [comment]
This is not Norton's fault, but rather Microsoft having assigned the samw shortcut for power toys as for the notifications pane. You might need to change the power toys shortcut to ctrl+shifr+n, or something like this
