### ISSUE TITLE
[FEATURE REQUEST] Add an option to have a clock on the header of the calendar widget/flyout

### ISSUE THREAD

**Issue by edox** [martinet101/ElevenClock#576]
Hello,
Currently you can add an alternate clock to the top of the calendar widget when you click on the time in the task bar. That lacks font size and font selection options currently and the seconds do not move at all. Maybe this is too much for this type of addition to the UI. If so feel free to ignore. Love what you have done with this! Thanks!

**Comment by martinet101** [comment]
No, that wouldn't be possible, because of how the calendar is made. I'm sorry :(

**Comment by edox** [comment]
No worries. Thanks for the response.
