### ISSUE TITLE
Clock won't hide with fullscreen programs/games

### ISSUE THREAD

**Issue by Damienb2022** [martinet101/ElevenClock#577]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 
</b>

## Describe the bug
When running a game/program, ElevenClock still appears on top of program when they are in fullscreen mode. Have to quit ElevenClock. This is on the main screen. 

## Screenshots
Uploaded.

## The Log

---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.0 (v3.2) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Initializing clock 1...
🔵 Using taskbar background color
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1920, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (-1920, 0, 0, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 2...
🔵 Using taskbar background color
🔵 Monitor geometry: PyQt5.QtCore.QRect(1920, 0, 1920, 1080)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(3640, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 Full screen rect:  (1920, 0, 3840, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:False, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 0.7400214672088623
🟢 Cached text input host hwnd: 66644
🔵 Restart loop: 1
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.1778502464294434
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/we-are-on-twitter.webp
🔵 Copying log to the clipboard...

```

## Additional context
Add any other context about the problem here.
![elevenclockerror](https://user-images.githubusercontent.com/99514170/153681835-6d894a3b-66a9-4594-a868-74469603d591.png)

**Comment by Kira-Lappo** [comment]
do you have these options enabled?
![image](https://user-images.githubusercontent.com/11411852/153709639-7459b137-65f1-4f90-901a-9e2d8651b5b0.png)

**Comment by martinet101** [comment]
> ~do you have these options enabled?~ seems like no, according to your settings:
> 
> ```
> HideonFS:False, NotHideOnTB:False, 
> ```
> 
> try enable these options in settings and check how it works

@Kira-Lappo is right, you haven't those options enabled

**Comment by Damienb2022** [comment]
I checked settings and the Hide on Full Screen was unticked. Have ticked this now. Interestingly, this hasn't occurred until most recent update. Was it normally ticked by default? And recent update changed it's state to unticked now?

**Comment by martinet101** [comment]
> Was it normally ticked by default? And recent update changed it's state to unticked now?

It wasn't until 2.9.1 (not exactly sure but more or less) that the checkbox was ticked
