### ISSUE TITLE
[ISSUE] Week count format in language file isn't i18n friendly

### ISSUE THREAD

**Issue by mmis1000** [martinet101/ElevenClock#580]
The week count was expected to be a prefix like `W12`.
However, this doesn't really apply to all languages.

In chinese, the format of week count is `第{0}周`  or `{0}周` depends on context. 
It requires a suffix and optionally a prefix.

`周1` means  something totally different. It means `Monday`. 
Which is not the original intention at all.

This seems require a format change in translation file to be translated properly

**Comment by martinet101** [comment]
Ok, I see

**Comment by martinet101** [comment]
So, in chinese instead of `W{0}` would need to be `{0}W` (being W replaced by the chinese character)

**Comment by mmis1000** [comment]
> So, in chinese instead of `W{0}` would need to be `{0}W`? (being W replaced by the chinese character)

The `first` in chinese is `第1`, `second` is `第2`, `third` is `第3` and so on.
Order in chinese is a number prefixed by `第`.

And we exclusively prefix it to a noun, so it is always like

```txt
[第 1]  [週]
First   week
```
(The `第` is something ignored if we know you are talking about orders instead of quantities based on context.)

So, yes. At least post-fix is required. prefix is probably optional (since put quantities here is pointless)

Take the calendar from government for example 
![圖片](https://user-images.githubusercontent.com/2993977/156294528-1deef941-d76e-4951-83f2-0a74d965a985.png)
https://www.tms.org.tw/tw/modules/piCal/?cid=0&smode=Weekly&caldate=2022-1-30

**Comment by martinet101** [comment]
Ok

**Comment by martinet101** [comment]
The issue should now have been fixed

**Comment by martinet101** [comment]
Could you please test it and tell me if it is the appropiate format now?

**Comment by mmis1000** [comment]
![圖片](https://user-images.githubusercontent.com/2993977/156880945-f04a7f67-e552-4be7-a85d-0a29c0a49656.png)

For some reason, that didn't work in debug mode. So I am not really to check it.
And I think `09周` is still weird, `第09周` or even `第9周` is probably how people pronounce it daily.

**Comment by martinet101** [comment]
> For some reason, that didn't work in debug mode. So I am not really able to check it.

But running the source code did?

**Comment by mmis1000** [comment]
> > For some reason, that didn't work in debug mode. So I am not really able to check it.
> 
> But running the source code did?

Did you mean run it like `python elevenclock\__init__.py` ? That don;t work either.

Actually, it also didn't work with the `build.bat`.
I am thinking whether my environment has been messed up by windows update now.

**Comment by martinet101** [comment]
Ok, gonna add then the 第 before the week number. Also, does this apply to simplified chinese?

**Comment by martinet101** [comment]
This should be now fixed
