### ISSUE TITLE
Info: Microsoft re-add clock to second monitor

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#581]
Release date: first half March.

> We added the clock and date to the taskbars of other monitors when you connect other monitors to your device.

Source: https://blogs.windows.com/windows-insider/2022/02/10/releasing-windows-11-build-22000-526-to-beta-and-release-preview-channels/

**Comment by Kira-Lappo** [comment]
it's been a loooooooooooong time...

**Comment by martinet101** [comment]
I see. Do you guys think that an option could be moving the clock x pixels to the right (like have an enormous padding?)

**Comment by martinet101** [comment]
> Release date: first half March.
> 
> > We added the clock and date to the taskbars of other monitors when you connect other monitors to your device.
> 
> Source: https://blogs.windows.com/windows-insider/2022/02/10/releasing-windows-11-build-22000-526-to-beta-and-release-preview-channels/

Yes, I recieved the update yesterday and (not gonna lie) the clock actually s*cks... I mean, it isn't even clickable...

**Comment by martinet101** [comment]
Just for you to know, ElevenClock will still be maintained

**Comment by Kira-Lappo** [comment]
> > Release date: first half March.
> > > We added the clock and date to the taskbars of other monitors when you connect other monitors to your device.
> > 
> > 
> > Source: https://blogs.windows.com/windows-insider/2022/02/10/releasing-windows-11-build-22000-526-to-beta-and-release-preview-channels/
> 
> Yes, I recieved the update yesterday and (not gonna lie) the clock actually s*cks... I mean, it isn't even clickable...

did they added option to show/not to show clock on a particular/all monitors?

**Comment by martinet101** [comment]
No, it is like a watermark, can't interact with it, and either remove it.

**Comment by tyler274** [comment]
Might be worthwhile to pool our feedback on what still needs to be added.

**Comment by martinet101** [comment]
yeah, i agree, the clock is in a really premature state
