### ISSUE TITLE
[BUG] Custom Font and Size are not applied

### ISSUE THREAD

**Issue by Kira-Lappo** [martinet101/ElevenClock#582]
## Version
Latest release 3.2.0

## To Reproduce

1. Go to clock settings
2. Set **Use custom font** option
3. Use any other non-default font
4. Unset **Use custom font** option
5. Set **Use custom font** option 

## Expected behaviour
Custom font is applied to clock

## Actual
Default font is used
Same for size option (and may be for other options)

![image](https://user-images.githubusercontent.com/11411852/153729934-8a3fa20f-ca18-4dd2-9ac2-a7d211803c4d.png)

**Comment by martinet101** [comment]
Yes, this was meant like this, because the file that stores the values is deletehd when those are disabled. Anyway, i'll take a look

**Comment by martinet101** [comment]
Fixed, coming with the next release
