### ISSUE TITLE
[FEATURE REQUEST] Notifications & Calendar on correct Screen

### ISSUE THREAD

**Issue by hofq** [martinet101/ElevenClock#585]
**Is your feature request related to a problem? Please describe.**

Hi Martí, it would be cool if the Popup of the Notifications and the Calender would show up on Secondary screens if you click the Clock + Date there.

**Describe the solution you'd like**
if the Same Popup 1:1 would show up on the Screen i clicked the clock. As long Windows allows that.
If someone created an Request about that i am sorry.

**Comment by martinet101** [comment]
Yes, this is a thing that i can't reallu modify, since it is built into Windows Shell. This is microsoft's job, actually
