### ISSUE TITLE
[BUG] Font corruption in korean language

### ISSUE THREAD

**Issue by hoony0203** [martinet101/ElevenClock#586]
ver 3.2.1 update after font corruption occured.

![image](https://user-images.githubusercontent.com/52574960/153939443-71973810-e67d-4ad2-b61e-d71607525c3e.png)

**Comment by mario31274** [comment]
Can confirm this is also happening on my Chinese system.
![圖片](https://user-images.githubusercontent.com/26250287/153943610-80503d0b-a4b3-4878-85cd-b80978b7c69f.png)

**Comment by martinet101** [comment]
Ok, plese post #590

**Comment by martinet101** [comment]
Please post it there
