### ISSUE TITLE
Option to prevent display on primary monitor

### ISSUE THREAD

**Issue by markny2** [martinet101/ElevenClock#588]
Perhaps I missed something, but as of today's update, I can no longer prevent the display on my primary monitor. For me this is crucial because Elevenclock now blocks a handful of apps in the tray. 

Why in the world was this feature removed?

Thanks.

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/153944719-fc695e8a-ef2f-4a8a-aa6b-b51419ad036b.png)

**Comment by martinet101** [comment]
It should be there, at least for me it is

**Comment by markny2** [comment]
Yeah, you’re right. I found it shortly after I sent the note.

 

Thanks.

 

Mark Kramer

 ***@***.***> ***@***.***

 

914 238-8061 Home

917 796-9567 Mobile
