### ISSUE TITLE
Bad characters for the Czech language.

### ISSUE THREAD

**Issue by vladimir-kordas** [martinet101/ElevenClock#589]
After the last update there is a problem with the characters for the Czech language. I did not have this problem in any previous version.[Untitled](https://user-images.githubusercontent.com/81954797/153943713-ed213c13-2470-409d-b84b-84b1feda7571.png)

**Comment by martinet101** [comment]
Ok, plese post #590

**Comment by martinet101** [comment]
Please post it there
