### ISSUE TITLE
[BUG] (Cyrilic no longer displayed correctly after update to v.3.2.1 )

### ISSUE THREAD

**Issue by vdexoto** [martinet101/ElevenClock#594]
Hi,
Just got the update to v.3.2.1 and when the clock loaded it no longer shows the day of the week correctly in cyrilic.
See first screenshot
 
![image](https://user-images.githubusercontent.com/99691055/153947245-d68268e4-0da1-40a1-8be8-73d904f2dcfb.png)

I have configured it as seen here and until the previous version it was working great.
![image](https://user-images.githubusercontent.com/99691055/153947479-261c38e9-2cae-4477-9fc4-e33c73f2f45d.png)

Could you please check the encoding and fix it.
Thank you
Viktor

**Comment by martinet101** [comment]
Please post on #590
