### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by yugonji** [martinet101/ElevenClock#598]
## Before submitting the issue
![image](https://user-images.githubusercontent.com/98372589/153982130-b317b8c8-8315-4b87-ac61-2ffd80407ff6.png)

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 
# for issues related with font corruption see #590
 
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by martinet101** [comment]
> for issues related with font corruption see #590
