### ISSUE TITLE
[BUG] (Enter your description here)한글버그

### ISSUE THREAD

**Issue by Ryzen89** [martinet101/ElevenClock#599]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 
# for issues related with font corruption see #590
 
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

## Additional context
![제목 없음](https://user-images.githubusercontent.com/99708423/153995193-bc70b7f8-b26e-4d3a-bbcb-d90fc0c5aada.png)

**Comment by martinet101** [comment]
> # for issues related with font corruption see #590
