### ISSUE TITLE
Clock appears/disappears 

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#6]
![image](https://user-images.githubusercontent.com/22828430/136049662-07feeac1-e420-4183-b2e7-6abdeb5f550f.png)

![image](https://user-images.githubusercontent.com/22828430/136049675-dcfa20c9-22fa-4eb9-858c-c8d1c7c9cffe.png)

Goes in and out

**Comment by martinet101** [comment]
Fixed! It is a timing issue
