### ISSUE TITLE
[BUG] Issues with Win+N

### ISSUE THREAD

**Issue by Ryzen89** [martinet101/ElevenClock#600]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 
# for issues related with font corruption see #590
 
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

## Additional context
[log.txt](https://github.com/martinet101/ElevenClock/files/8066023/log.txt)

**Comment by portgasdpetch** [comment]
Sometimes, I can not click the clock to show the calendar(the calendar and notification will not show up). Always happen when I use 'find function (ctrl+F)' on a web browser in my language(only in Thai language, not English), also happen by other causes. I have to use 'windows search(windows + s)' or find function on a web browser in English to make the clock work(to be clicked and show the calendar) again. Also the clock font is weird, like it is not in English language(you can see the Tue back to normal form while I was using windows search in the first VDO).
ps. I pressed enter every time I used 'find function' on the web browser

https://user-images.githubusercontent.com/23282812/153995451-85b7a632-8b60-4619-b000-810d5fc60447.mp4


https://user-images.githubusercontent.com/23282812/153995459-aa494741-2161-4176-aaa8-8d813a8502c5.mp4

**Comment by portgasdpetch** [comment]
look likes the problem occurs only when my keyboard input language is not English.

**Comment by martinet101** [comment]
What is youk keyboard shortcut to open the calendar? The default is Win+N, but yors could be changing

**Comment by portgasdpetch** [comment]
> What is youk keyboard shortcut to open the calendar? The default is Win+N, but yors could be changing

There is no problem using hotkey (win+n) no matter the language. Only direct clicking has it.

**Comment by martinet101** [comment]
So, when it fals, pressing Win+N works?

**Comment by martinet101** [comment]
*fails

**Comment by portgasdpetch** [comment]
> So, when it fals, pressing Win+N works?

It fails only when I directly click on the date/time while my keyboard input language is 'Thai' (I guess other languages also fail, it only works when my keyboard input language is English).
Yes, the hotkey (win + n) always works even when I am using Thai language.

**Comment by martinet101** [comment]
Mhmm, it looks like it is related to this: https://www.reddit.com/r/learnpython/comments/l4pfp1/having_issue_with_pynput_type_language_other_than/

I'll take a look

**Comment by portgasdpetch** [comment]
Thank you so much.

**Comment by martinet101** [comment]
The issue has been fixed and the fix will come with the next update
