### ISSUE TITLE
[ISSUE] Unable to Install the software

### ISSUE THREAD

**Issue by MR-DERP-YT** [martinet101/ElevenClock#602]
I am unable to install the software.
When I run the "ElevenClock.Installer.exe" with or without my anitvirus on, it says this:
![image](https://user-images.githubusercontent.com/74773615/154006913-58e9f2c9-e729-4b3d-bcf0-2ed348646ee2.png)

I have ran the Installer with Administrator (right click).
First time I ran the Installer (Antivirus was on), It showed a message at the end of installation saying "This file is potential Virus".
I am the Admin (like the owner), yet it doesn't work.
I have McAfee Antivirus, I turned it off, yet it doesn't work. 

I have seen the place where the files are getting created, and it seems that when the .tmp files are created they are instantly deleted (even when the antivirus is off).

Any Help would be helpful

**Comment by martinet101** [comment]
Instead of diabling the antivirus, can you try creating an exception for ElevenClock?

**Comment by martinet101** [comment]
And do you have Windows Defender enabled?

**Comment by MR-DERP-YT** [comment]
I have sent an email for the False Positive report to McAfee. Now it is time to wait
*Waits*

**Comment by martinet101** [comment]
Ok, let's see what they say. 

\*waits*
