### ISSUE TITLE
[BUG] Update can't complete while ElevenClock is running

### ISSUE THREAD

**Issue by scarez** [martinet101/ElevenClock#607]
When an update is released for ElevenClock they always fail because the application is currently running.  This is standard behavior within Windows where the majority of application files cannot be modified while the application is running.  What the update process should do is shutdown ElevenClock so the update can complete and then restart the application when finished.  I think the restart is happening, but users must manually shutdown the application.

**Comment by martinet101** [comment]
The installer should kill the process, and (at leasrt for me) it does. Do you have any kind of protection versus process management or something?

**Comment by scarez** [comment]
Windows Defender supplementing Malwarebytes Premium is what I am running. I am also in an Insider chain for a Windows 11. Outside of that I am not running anything that I know of that would be preventing the process shutdown. All other apps present a dialog usually if they need to stop a process to update.

Scott Carez
________________________________

**Comment by martinet101** [comment]
If you run the command `taskkill /im elevenclock.exe /f`, elevenclock gets killed or not?
