### ISSUE TITLE
[BUG] Incorrect hover background size

### ISSUE THREAD

**Issue by JUMBUZI** [martinet101/ElevenClock#608]
## Describe the bug
The hover animations size is incorrect, see screenshot

## To Reproduce
Happens to me always immediately at startup.

## Expected behaviour
The hover animation is supposed to cover all of the text

## Screenshots
![image](https://user-images.githubusercontent.com/50639201/154138375-7a477be2-cd94-4913-a3a2-4bcff5ea8682.png)

## The Log
The log is empty, another bug maybe?

**Comment by martinet101** [comment]
Do you have a small taskbar, right?

**Comment by JUMBUZI** [comment]
yes

**Comment by martinet101** [comment]
Ok, gonna fix that

**Comment by martinet101** [comment]
The issue has been fixed and will come in the next release
