### ISSUE TITLE
[ISSUE] What is this dot?

### ISSUE THREAD

**Issue by yoppy25378** [martinet101/ElevenClock#609]
A dot is displayed next to the seconds.
It appears only when seconds are displayed.
![画像_2022-02-16_051033](https://user-images.githubusercontent.com/80618645/154141079-79bd8042-04ad-4193-9b26-139852573460.png)

It has been appearing since ver. 3.2.2.

**Comment by martinet101** [comment]
Mhmm, this dot shouldn't appear...

Can you send me your log plz?

**Comment by yoppy25378** [comment]
I don't know why, but nothing is recorded in the log (I've reloaded it many times).
Is there something I need to change in my settings?

**Comment by martinet101** [comment]
No, my fault. I'm sorry.

**Comment by martinet101** [comment]
Forgot to switch some stuff.

**Comment by yoppy25378** [comment]
Okay, I'm waiting for the update.

**Comment by martinet101** [comment]
Give it 5 or 6 days, i think the dot issue is not a _urgent_ update... I mean, i'll fix it asap but not gonna make a specific release for it...

**Comment by yoppy25378** [comment]
To be honest, I don't really care about the dot problem, so I'll wait patiently. Thanks.

**Comment by martinet101** [comment]
The latest update should has a potential fix, could you check it?

**Comment by yoppy25378** [comment]
Doesn't look like it's been fixed yet...
I've attached the logs
[elevenclock_log.txt](https://github.com/martinet101/ElevenClock/files/8081841/elevenclock_log.txt)
.

**Comment by martinet101** [comment]
Ok

**Comment by martinet101** [comment]
Fixed, coming in the next release
