### ISSUE TITLE
[BUG] (Enter your description here)  3.2.2 does the same thing 3.2.1 did.  ElevenOclock loads and displays for about 5 seconds and then crashes.  Reverting back to 3.2.0 is the only fix for me.

### ISSUE THREAD

**Issue by jbinedina** [martinet101/ElevenClock#611]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>
 
# for issues related with font corruption see #590
 
</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log). 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)

```

**Comment by MartinJSoles** [comment]
In the Windows Event Log Viewer, I see an error associated with version 3.2.2. The faulting module is Qt5Core.dll. Was something odd being done in the application compilation? Or, is the installer adding a dependency that can't be resolved?

**Comment by kslifter** [comment]
How do you revert back a version?

**Comment by MartinJSoles** [comment]
I uninstalled the latest version and then downloaded the 3.2.0 release from here. Since I had automatic updating turned on, I then disabled my internet connections so that it couldn't find an update after installing. Next, I opened the settings from the Start menu and disabled the option to automatically install updates.

**Comment by sefodopo** [comment]
I have the same issue with the new Windows Update KB5010414 which adds the crappy clock to the second display. Using 3.2.0 works just fine.

**Comment by martinet101** [comment]
The issue was spotted by @sinusinu, it was a thread updating a QLabel without using a Qsignal. It has been fixed and an update will come asap

**Comment by martinet101** [comment]
The update is live now
