### ISSUE TITLE
[BUG] Silent Update is taking away focus

### ISSUE THREAD

**Issue by AlexeyOplachko** [martinet101/ElevenClock#617]
## Before submitting the issue

<b>
✅ I have checked that the bug is not a duplicate or, if it is, it needs to be reopened; and I've checked the [FAQ](https://github.com/martinet101/ElevenClock/wiki/Troubleshooting) for solutions<br>
✅ I have installed the latest version and the issue still happens<br>

</b>

## Describe the bug
Even a with "Really silent update" it took away focus from the app.

## To Reproduce
Steps to reproduce the behaviour:
1. Enable really silent updates
2. Start getting an update
3. Do something else, like type in a document or w/e
4. Lose focus from said document

## Expected behaviour
I'd expect it to be completely in background. And turning off auto-updates doesn't sound like a good idea.

**Comment by martinet101** [comment]
Thst's an actual issue with Inno Setup, which takes the focus for a sec when launched, even if it's on /verysilent.
