### ISSUE TITLE
[FEATURE REQUEST] Add text outline feature

### ISSUE THREAD

**Issue by probablypablito** [martinet101/ElevenClock#620]
**Is your feature request related to a problem? Please describe.**
Having the clock take up a square of the bottom of your screen is quite annoying. The box is necessary though as without it (transparent background), the clock can be hard to read.

**Describe the solution you'd like**
I would like for there to be an option to add an outline around the text of the clock. This would allow for the clock to be legible no matter the background (or lack there of)

**Comment by martinet101** [comment]
I don't know if that would be possible, but i''lll take a look

**Comment by martinet101** [comment]
Hi @probablypablito, couldn't find a way to implement this. I'm sorry :(

**Comment by martinet101** [comment]
Hi @probablypablito, couldn't find a way to implement this. I'm sorry :(

**Comment by probablypablito** [comment]
ok! idk if having 2 texts with 1 slightly bigger than the other would work, but in any case I'll survive. thanks!
