### ISSUE TITLE
Font size in custom fonts

### ISSUE THREAD

**Issue by Draskic** [martinet101/ElevenClock#624]
Please increase Custom font sizes! The last size is 10.5, which is too little because I use your clock as a replacement for the Atomic Alarm Clock that doesn't work on Windows 11 (TrayClockWClass not found). I simply overlap with your clock the Microsoft system clock in a taskbar and I want the time digits to be much higher (from 11 to say 20).
Thanks and Regards!
Drasko, Croatia

**Comment by martinet101** [comment]
If you scroll down you'll find up to 16pt. Anyway, i could add more of them

**Comment by Draskic** [comment]
> If you scroll down you'll find up to 16pt. Anyway, i could add more of them
Incredibly! But true! Like you said I scrolled further and found 16! I don’t know how I overlooked that! Much better 16. 18-20 would be the maximum.
Thanks and Regards!
Drasko, Croatia

**Comment by Draskic** [comment]
Incredibly! But true! Like you said I scrolled further and found 16! I don’t know how I overlooked that! Much better 16. 18-20 would be the maximum.
Thanks and Regards!
Drasko, Croatia
👍
