### ISSUE TITLE
[BUG] (Tuesday not written Properly)

### ISSUE THREAD

**Issue by ErassyJR** [martinet101/ElevenClock#625]
## Describe the bug:
Letter "T and U" in Tuesday appear as if attached together.

## Screenshots:
![Screenshot (24)](https://user-images.githubusercontent.com/79103807/155040273-40b2618d-88f0-44bb-9c6c-3f1a345b272a.jpg)

## The Log:

---------------------------------------------------------------------------------------------------

   ElevenClock's 3.2.3 (v3.23) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1366, 768)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1166, 720, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: ddd: d/MM/yyyy
🔵 tTimeMode: HH:mm tt
🔵 Loaded date time format: %H:%M:%S· %p
%a: %#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 Restart loop: 1
🟢 Loaded clocks in 1.1652734279632568
🟣 Expected AttributeError on backgroundLoop thread
🟢 Cached text input host hwnd: 65952
🟣 Expected AttributeError on backgroundLoop thread
🟡 System tray icon disabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.6254613399505615
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Image URL: https://www.somepythonthings.tk/resources/rose.webp
🟡 Closing clock on {'Monitor': (0, 0, 1366, 768), 'Work': (0, 0, 1366, 720), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1366, 768)
🟡 Taskbar at bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1166, 720, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: ddd: d/MM/yyyy
🔵 tTimeMode: HH:mm tt
🔵 Loaded date time format: %H:%M:%S· %p
%a: %#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: ddd: d/MM/yyyy
🔵 tTimeMode: HH:mm tt
🔵 Loaded date time format: %H:%M:%S· %p
%a: %#d/%m/%Y
🟢 Cached text input host hwnd: 65952
🔵 Restart loop: 1
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/rose.webp
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

**Comment by martinet101** [comment]
That's an issue with qt font rendering, and i can0t do much about it. You can catually change your font to fix that
