### ISSUE TITLE
Week number overlap battery icon W11

### ISSUE THREAD

**Issue by scattozzi** [martinet101/ElevenClock#627]
When option "week number" is active, ElevenClock overlap the battery/power system icon.

option disabled
![image](https://user-images.githubusercontent.com/100275548/155287631-45f9b990-8af1-4926-9202-4b0290702de2.png)

option enabled
![image](https://user-images.githubusercontent.com/100275548/155287742-1f8e1793-7c16-474c-9e20-268c840cda55.png)

BTW: great tool!! Must be include in standard W11 package.

**Comment by martinet101** [comment]
Yes, Best you can do is to set a smaller font. This can't be fixed since the clock is an overlay on the taskbar

In a near future a custom format editor will be implemented and fixes to this will be available.

**Comment by myfairsyer** [comment]
See #502
