### ISSUE TITLE
[FEATURE REQUEST] Ability to move/clone system tray from primary to secondary monitor

### ISSUE THREAD

**Issue by DjVolume** [martinet101/ElevenClock#638]
**Is your feature request related to a problem? Please describe.**

With KB5010414 being released to the public, this otherwise great app sadly lost its primary functionality to me (i.e., showing clock on my second monitor). It still however could be useful, if it only offered the ability to move or clone system tray (icons near the clock) from primary to secondary monitor.
Windows 10 had such functionality - all you had to do was to unlock the primary taskbar , and then drag and drop it to the other monitor. Windows 11 made it impossible for some reason.
The obvious workaround is to change your primary monitor of course, but sadly it creates few problems - for example, fullscreen games being shown on the wrong monitor (and as far as I can tell, it's impossible to move them). I would really like to be able to monitor my apps on the second monitor, while I use fullscreen application on my primary one (e.g. watch Discord mute/unmute status etc.).

**Describe the solution you'd like**

Please consider adding option to move or clone system tray (and/or move the whole taskbar with system tray) to other monitor(s).

**Comment by Masamune3210** [comment]
I believe this has been talked about before, and it was decided that this is either impossible or way more work than it sounds if not since the taskbar changes almost constantly and is handled by a different process entirely

**Comment by martinet101** [comment]
@Masamune3210 is actually right (more or less). By the time this was discussed, i knew no way to implement that. But, since the implementation of the notification counter, there's a possible potential way of implementing it. Anyway, it would represent a lot of work and it's not going to be imlemented anytime soon, if it is ever implemented.
