### ISSUE TITLE
[BUG/ISSUE] Keeps showing on Primary Screen even when setting turned off.

### ISSUE THREAD

**Issue by Baxmann** [martinet101/ElevenClock#645]
## Describe the bug
Whenever there's an update, even when the clock setting "Show the clock on the primary screen" is off, the clock will display on the primary screen. I have to reopen the settings, click and unclick the settings to fix the problem.

**Comment by martinet101** [comment]
Weird... Gotta fix that

**Comment by martinet101** [comment]
Fixed, the next update won't do that anymore

**Comment by frischeDaten** [comment]
thanks, I did not check on issues fixed but not released, sorry. For future reference: fixed with [Issue](https://github.com/martinet101/ElevenClock/commit/44b33e9021528cb26591e96d0f2c51098591b305) https://github.com/martinet101/ElevenClock/issues/645
