### ISSUE TITLE
[BUG/ISSUE] (ElevenClock keeps opening two instances (i see two instances in menu overflow), when i hover the mouse over one instance it exits))

### ISSUE THREAD

**Issue by yazan1107** [martinet101/ElevenClock#648]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ ] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
[BUG/ISSUE] (ElevenClock keeps opening two instances (i see two instances in menu overflow), when i hover the mouse over one instance it exits))
## To Reproduce
Steps to reproduce the behaviour:
1. at random times
2. eleven clock opens another instance, while it is open!
3. Scroll down to menu overflow, there is two instances(when hovering over one of them by my mouse it exits!)

## The Log
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.3.0 (v3.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(2880, 80, 2049, 1536)
🟢 Clock on the bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(2892, 1544, 300, 72)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: H:mm
🔵 Loaded date time format: %#H:%M:%S 
%d/%m/%Y
🔵 Full screen rect:  (2880, 80, 4929, 1616)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:False, NefWSMethod:True, DisableNotifications:False, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
🔵 Long date string: dddd, d MMMM yyyy
🟢 Loaded clocks in 0.7039992809295654
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to True
🟢 Loaded everything in 1.8699989318847656
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Copying log to the clipboard...

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log
[log.txt](https://github.com/martinet101/ElevenClock/files/8163897/log.txt)
. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Yes, that's because of the update. When an app quits, the sustem tray doesn't get updated (idk why) and when you hover on it, the taskbar refreshes the icon and closes it since it is not running anymore. This is microsoft's issue, because this is a  thing of the taskbar
