### ISSUE TITLE
[BUG/ISSUE/Feature-Request] Tooltip Blank -> Hide ToolTip

### ISSUE THREAD

**Issue by Dypsis** [martinet101/ElevenClock#654]
The tooltip that has just been implemented in ElevenClock v3.3.0 is blank.

Also, could we possibly have an option to turn it off?
I don't see the point of it, as unlike the Windows clock, ElevenClock already provides the full date and time details and it's a bit obtrusive. It also pops up when checking notifications or viewing the calendar.

![ElevenClock Tooltip Blank](https://user-images.githubusercontent.com/34975400/156281876-5e5e76e7-a17f-4ab3-ac1f-2e53c4725a32.png)

**Comment by Dypsis** [comment]
I am using Windows 11 Version 21H2 (22000.527).
The log is attached
[ElevenClock_Log.zip](https://github.com/martinet101/ElevenClock/files/8172863/ElevenClock_Log.zip)
.

**Comment by martinet101** [comment]
Ok, i'll add an option to hidde that

**Comment by martinet101** [comment]
The option to hide the tooltip has been added and will come with then ext version
