### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by Biskupator** [martinet101/ElevenClock#658]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug

On primary display. If opening context menu of pinned icon tray icons overlaps with clock and date area then that area adopts background color of the menu. Clock area is also always on top.

## To Reproduce
Steps to reproduce the behaviour:
1. Select any pinned icon you want with context menu big enough to overlap. (By pinned I mean those dragged from icon tray to the taskbar, always visible, just making sure, but you probably know what I mean.. aaaaaaanyway.)
2. Click RMB on it.

## Expected behaviour

I expected it to no adopt background color of a menu. And to prioritize displaying menu rather than clock

## Screenshots
![image](https://user-images.githubusercontent.com/25778084/156397227-c0617650-6ce0-4ad8-9778-37348421b4b0.png)

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Yes, that's related with the background color picker, which picks the background color from the top-left corner of the clock. You can always specify a custom color. For the overlaying of the menus, much can't be done. I'm sorry :(
