### ISSUE TITLE
[BUG/ISSUE] Not possible to use Segoe UI Bold as the font?

### ISSUE THREAD

**Issue by Skyyblaze** [martinet101/ElevenClock#659]
## Describe the bug
Segoe UI Bold is not listed as a possible font

## To Reproduce
Steps to reproduce the behaviour:
1. Go to "Use Custom Font"
2. Click on the font list
3. Segoe UI Bold isn't listed

## Expected behaviour
Segoe UI fonts should be offered in the bold variants.

Is there a reason why it's not possible to select Segoe UI Bold as a font? The dropdown-menu only offers the Semibold, Semilight and Black variants.

**Comment by Skyyblaze** [comment]
Yes I tried that too, for some reason the font-picker wont list any Bold variant of the Segoe UI family and it's subfamilies:

![grafik](https://user-images.githubusercontent.com/22203339/156438397-825472c5-e774-47c2-ac3e-bef91109951f.png)

The fonts are correctly installed and are listed in other programs just fine so the issue is isolated to ElevenClock on my end. Black and Bold are different fonts as you can see here:

![grafik](https://user-images.githubusercontent.com/22203339/156438665-1f7a76f8-d7df-42e1-b16c-b68547ea5f65.png)

![grafik](https://user-images.githubusercontent.com/22203339/156438723-c114cfce-98da-4afc-98e6-6ed5d5db9824.png)

Black = Schwarz
Bold = Fett

in my locale.

**Comment by martinet101** [comment]
I don't really know what is heppening and i'll take a look, but I don't really think this is ElevenClock's faults but Qt or Windows

**Comment by Skyyblaze** [comment]
Alright, regardless if you can solve it or not thank you for your time and thanks for the great work with ElevenClock, it's a great little tool! :)

**Comment by martinet101** [comment]
Hi, i've not found the reason for bold fonts not to show, i actually made a new, elevenclock-independent app qith qt and bold fonts didn't show neither. But I realised that semibold, for whatever the reason renders the same way as bold fonts (when assigned from stylesheet.)

I'm sorry this couldn't be fixed, but i can't see any solution for an issue that seems to be Qt's fault
