### ISSUE TITLE
[BUG/ISSUE] ElevenClock background changes based on screen contents on third display

### ISSUE THREAD

**Issue by wardyorgason** [martinet101/ElevenClock#662]
## Before submitting the issue

- [ x ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ x ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ x ] **I have checked that I am running the latest version of ElevenClock**
- [ x ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ x ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
On my third monitor the background color of the ElevenClock overlay changes based on the contents of the screen.

## To Reproduce

I am currently using ElevenClock on a 3-display work computer. Note that on the first two displays, everything works like it should. However, on my third display, the background color of the ElevenClock overlay seems to periodically change.

After some use I realized it was changing rapidly while I watched a Youtube video. After some experimentation I realized that it's background is matching the color of a pixel somewhere around the center of that screen.

## Expected behaviour
I'm expecting it to match the color of my start menu on all three screens, but on one of the screens it doesn't.

## Screenshots
Here is my normal desktop:
![screenshot1](https://user-images.githubusercontent.com/3272503/156469286-28a31ca3-05f2-4330-99e2-b40c10a25ad4.png)

Here it is where it's matching a specific color from the center of my screen:
![screenshot2](https://user-images.githubusercontent.com/3272503/156469692-5097ceae-7863-4c59-8fe0-9d60b11a6ed1.png)

## The Log

---------------------------------------------------------------------------------------------------

   ElevenClock's 3.3.0 (v3.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1680, 1050)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1480, 1002, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 1680, 1050)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-1680, 0, 1680, 1050)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-200, 1002, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (-1680, 0, 0, 1050)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Initializing clock 2...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(-4240, 226, 1280, 720)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(-3160, 898, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (-4240, 226, -2960, 946)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: dddd, MMMM d, yyyy
🟢 Loaded clocks in 0.24499988555908203
🟢 Cached text input host hwnd: 6620502
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 0.8040008544921875
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Fullscreen window detected! Greenshot capture form (-4240, 0, 1680, 1666) Fullscreen rect: (0, 0, 1680, 1050)
🟡 Fullscreen window detected! Greenshot capture form (-4240, 0, 1680, 1666) Fullscreen rect: (0, 0, 1680, 1050)
🔵 Showing hover
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

**Comment by RantMaster** [comment]
I am seeing this issue as well

**Comment by martinet101** [comment]
Can you please try increasing a litle bit the clock's y offset?

**Comment by martinet101** [comment]
Yes, that's not doing any good... 
Have you been able to found from where does the color come from? I mean, is there a specific place where you could a window and the clock would change its color?

**Comment by wardyorgason** [comment]
@martinet101 Yes, mostly. It seems to be the center of the screen not counting the start menu. 

Here is where I think the source pixel is:
![image](https://user-images.githubusercontent.com/3272503/156627058-6971f33f-07c0-4be5-8715-464a5c07be1b.png)

I don't know a lot about the implementation but I'm wondering if it's some sort of memory leak or a bad pointer or something. The fact that it's pretty much the center of the screen makes me think it's a side-effect from something else.

**Comment by martinet101** [comment]
Yes, I see. I theory, it was supposed to pick this color from the top-left corner of the clock, but it doesn't look to really work...

**Comment by martinet101** [comment]
The issue has been fixed and the fix will come with the next release.

After all, it was an issue with microsoft's high PPP _fixing_ software. Ironically, the _fixing_ software _broke_ this.
