### ISSUE TITLE
[BUG] Clock flicker after show thumbnail on taskbar

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#668]
Clock flicker after show thumbnail on taskbar

https://user-images.githubusercontent.com/3808250/156745700-1dcbf3d5-4778-41c7-8075-ba45965e8d9b.mp4

v3.3.0

**Comment by martinet101** [comment]
Please see known issues section in the  [wiki](https://github.com/martinet101/ElevenClock/wiki)
