### ISSUE TITLE
[FEATURE REQUEST] Brief description

### ISSUE THREAD

**Issue by SmileyStyles** [martinet101/ElevenClock#670]
**Is your feature request related to a problem? Please describe.**

I Play eve online. EVE Server Time or EVE Time refers to the in-game server time, It is identical to real-world Coordinated Universal Time. I would like the ability to have a second clock so that I may keep track of time in game. Maybe the ability to change the color. Great app, thanks for being a genius.

**Describe the solution you'd like**

**Comment by martinet101** [comment]
Could this be related to #357?
