### ISSUE TITLE
When a notification is received, a deliberately hidden icon is revealed.

### ISSUE THREAD

**Issue by vladimir-kordas** [martinet101/ElevenClock#673]
Hello, I am writing with an aesthetic request. My point is that I have a deliberately hidden sound icon. However, the problem is that when I get a notification, a bit of it is revealed. It's nothing serious, just aesthetic. If you could advise me if there is any way to eliminate this, I would be very happy 😊

![Untitled](https://user-images.githubusercontent.com/81954797/156931674-edecfa55-faca-4b4b-bdcf-ffe8584373f0.png)

**Comment by martinet101** [comment]
You can specify a minimum width on the clock, that should fix it. If not, you can also set a negative x offset
