### ISSUE TITLE
[BUG/ISSUE]無法使用時鐘

### ISSUE THREAD

**Issue by RyanCDC** [martinet101/ElevenClock#674]
![1](https://user-images.githubusercontent.com/101058786/156932610-307b6a65-f141-4808-9cdc-9d6be8c9bd1b.jpg)

Why??????

**Comment by RyanCDC** [comment]
[1.txt](https://github.com/martinet101/ElevenClock/files/8193044/1.txt)


---------------------------------------------------------------------------------------------------

   ElevenClock's 3.3.0 (v3.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "zh_TW"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['Microsoft JhengHei UI', 'Segoe UI Variable', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🟢 Loaded clocks in 0.5796675682067871
🟣 Expected NameError on timeStrThread
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟢 Cached text input host hwnd: 262380
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.7423136234283447
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Saving log...
🟢 log saved successfully
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

**Comment by RyanCDC** [comment]
[Log legend.txt](https://github.com/martinet101/ElevenClock/files/8193055/Log.legend.txt)


---------------------------------------------------------------------------------------------------

   ElevenClock's 3.3.0 (v3.3) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "zh_TW"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['Microsoft JhengHei UI', 'Segoe UI Variable', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🟢 Loaded clocks in 0.5796675682067871
🟣 Expected NameError on timeStrThread
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟢 Cached text input host hwnd: 262380
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.7423136234283447
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Saving log...
🟢 log saved successfully
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing hover
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File "settings.py", line 2502, in loadAnnouncements

🔴   File "urllib\request.py", line 214, in urlopen

🔴   File "urllib\request.py", line 523, in open

🔴   File "urllib\request.py", line 632, in http_response

🔴   File "urllib\request.py", line 561, in error

🔴   File "urllib\request.py", line 494, in _call_chain

🔴   File "urllib\request.py", line 641, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 500: Internal Server Error

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 500: Internal Server Error)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['Microsoft JhengHei UI', 'Segoe UI Variable', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['Microsoft JhengHei UI', 'Segoe UI Variable', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Restart loop: 2
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['Microsoft JhengHei UI']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟢 Cached text input host hwnd: 262380
🔵 Restart loop: 2
🔵 Restart loop: 1
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['Microsoft JhengHei UI']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟢 Cached text input host hwnd: 262380
🔵 Restart loop: 1
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['微軟正黑體']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟢 Cached text input host hwnd: 262380
🔵 Restart loop: 1
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['微軟正黑體']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['微軟正黑體']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['微軟正黑體']
🔵 Font size: 9.0
🟢 Using black text (light mode)
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟢 Cached text input host hwnd: 262380
🔵 Restart loop: 3
🔵 Restart loop: 2
🔵 Restart loop: 1
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['微軟正黑體']
🔵 Font size: 9.0
🟡 Using custom text color: 
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['微軟正黑體']
🔵 Font size: 9.0
🟡 Using custom text color: 
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['微軟正黑體']
🔵 Font size: 9.0
🟡 Using custom text color: 0,0,0
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟢 Cached text input host hwnd: 262380
🔵 Restart loop: 3
🔵 Restart loop: 2
🔵 Restart loop: 1
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟡 Closing clock on {'Monitor': (0, 0, 1920, 1080), 'Work': (0, 0, 1920, 1020), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PyQt5.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PyQt5.QtCore.QRect(1670, 1020, 250, 60)
🔵 Font families: ['微軟正黑體']
🔵 Font size: 9.0
🟡 Using custom text color: 255,0,0
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 Full screen rect:  (0, 0, 1920, 1080)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🟢 Cached text input host hwnd: 262380
🔵 Restart loop: 1
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
%Y/%#m/%#d/%A
🔵 tDateMode: yyyy/M/d/dddd
🔵 tTimeMode: tt HH:mm:ss
🔵 Loaded date time format: %p %H:%M:%S 
(周%W) %Y/%#m/%#d/%A
🔵 Showing hover
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Saving log...
🟢 log saved successfully
🔵 Saving log...
🟢 log saved successfully
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Saving log...

**Comment by martinet101** [comment]
This is broken but will be fixed in the next release

**Comment by martinet101** [comment]
See pinned issue

**Comment by RyanCDC** [comment]
Thank you！I Love it！I need Sec.
