### ISSUE TITLE
right click menu disappearing when moving the mouse away from the taskbar

### ISSUE THREAD

**Issue by AmikadM** [martinet101/ElevenClock#687]
the right click menu disappear when my mouse isn't on the taskbar (without clicking anywhere)

https://user-images.githubusercontent.com/77983171/158031637-c0576f06-de40-47ef-99a2-f093cb76d5b2.mp4

**Comment by martinet101** [comment]
Can you try opening the ElevenClock settings (from the start menu), recreating the issue and sending me the log?

**Comment by martinet101** [comment]
(please make sure to first open settings and then recreate)

**Comment by AmikadM** [comment]
i got some news, first here is the log :

---------------------------------------------------------------------------------------------------

   ElevenClock's 3.3.1 (v3.31) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "fr"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1366, 768)
🟡 ElevenClock set to hide with the taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟡 Y offset being used!
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1165, 721, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using black text (light mode)
🔵 Restart loop: 1
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M:%S 
%d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
🟡 Desktop button enabled
🟣 Expected AttributeError on backgroundLoop thread
🟢 Loaded clocks in 7.890939474105835
🟢 Cached text input host hwnd: 131870
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 9.447745323181152
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: dddd d MMMM yyyy
🔵 Copying log to the clipboard...

i also figured out that it works only when the settings page (of eleven clock) is the active window, it also doesn't work when there is no active windows

**Comment by AmikadM** [comment]
if you need details on my windows version :
windows 11 pro insider canal dev build 22572.100

**Comment by martinet101** [comment]
Thank you, i think I see what is happening...

**Comment by AmikadM** [comment]
so ?

**Comment by martinet101** [comment]
I guess that since the clock is hiding the menu does also. I wound need to prevent the clock from hiding whet the context menu is visible for the user

**Comment by AmikadM** [comment]
yes, it works when the taskbar is always visible but only after a restart (it doesn't detect the mode of the taskbar even after a restart of the app) but that's not what i want.

**Comment by martinet101** [comment]
The issue has been fixed and will come with the next release
