### ISSUE TITLE
It's now a feature

### ISSUE THREAD

**Issue by witalihirsch** [martinet101/ElevenClock#688]
Please, could you make PySide2 window with Mica as a template?
This could be very helphul for everyone

**Comment by martinet101** [comment]
Check out https://github.com/martinet101/win32mica, is that what you mean?

**Comment by witalihirsch** [comment]
Yes, but so that you can apply a Mica for the entire window like template, as in your application ElevenClock (btw cool app).
This would be very helpful for other developers who want to design like in Windows 11. 😊

**Comment by witalihirsch** [comment]
that's what i got 
![image](https://user-images.githubusercontent.com/73841541/158130771-12f32257-e383-4c8c-8e5b-e6d2e8efbdcb.png)
![image](https://user-images.githubusercontent.com/73841541/158130875-5e0fdd78-52db-4966-9283-33cf8cbda839.png)

**Comment by witalihirsch** [comment]
Sorry, I was inattentive, corrected the error.
If anyone else needs
![image](https://user-images.githubusercontent.com/73841541/158132295-fec98163-4180-408d-9e73-4401386db34f.png)
![image](https://user-images.githubusercontent.com/73841541/158132355-a2c0fc70-ed19-4b41-8550-cdef7d675eda.png)

**Comment by martinet101** [comment]
Yes, i should make this more visible.
