### ISSUE TITLE
[FEATURE REQUEST] Oulined fonts

### ISSUE THREAD

**Issue by Draskic** [martinet101/ElevenClock#691]
Hi
Please can you add the so-called "outlined" fonts?
Sometimes certain font colors don’t look good, especially bright fonts on white surfaces!
Thanks for the larger fonts!
Drasko, Croatia

**Comment by martinet101** [comment]
Hi @Draskic,

Font outlining was a feature that was already requested but because of the incompatibility of Qt with this type of font and the inefficiency and unstability of the manual implementation it was decided not to include this feature

**Comment by Draskic** [comment]
Hi
I understand thid!
Thanks!
Drasko
