### ISSUE TITLE
[BUG/ISSUE]Tooltip is not showing on hidden system icon

### ISSUE THREAD

**Issue by Draskic** [martinet101/ElevenClock#692]
Hi
When the mouse hovers over the icon in the system tray (hidden icons) there is no tooltip, and all other applications show something.
It would be nice if nothing else named "ElevenClock"!
Greeting!
Drasko, Croatia

**Comment by Draskic** [comment]
😛👍
O. K.
In the next update!
Best Regards.!
Drasko

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/158585435-1a8d84af-bc87-463a-b0a3-429a5db210dd.png)
Coming in the next version!

**Comment by Draskic** [comment]
Hi
Thanks! 😛👍🐺
Drasko
