### ISSUE TITLE
[BUG/ISSUE] "Showing Hiding Icons" tip bubble affects background color of ElevenClock

### ISSUE THREAD

**Issue by layahcn** [martinet101/ElevenClock#693]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
"Showing Hiding Icons" tip bubble affects background color of ElevenClock

## To Reproduce
Steps to reproduce the behaviour:
1. Move mouse to system tray "^" icon
2. "Showing Hiding Icons" tip bubble showing
3. tip bubble above the Clock

## Expected behaviour
the Clock background color no glitch

## Screenshots
![微信截图_20220315155711](https://user-images.githubusercontent.com/5712054/158334505-fbedbef7-368e-4dd9-88f0-1d4afbe46fa9.png)

## The Log

```
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.3.1 (v3.31) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "zh_CN"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟡 X offset being used!
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1717, 1032, 200, 48)
🔵 Font families: ['Microsoft YaHei']
🔵 Font size: 10.0
🟢 Using white text (dark mode)
🟡 Custom loaded date time format: %#H:%M:%S
%Y.%#m.%#d
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 1.0512399673461914
🟢 Cached text input host hwnd: 131706
宋体
🔵 Restart loop: 1
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.4691436290740967
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/peace.webp
🔵 Showing tooltip
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Showing tooltip
🔵 Long date string: yyyy'年'M'月'd'日'
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
```

**Comment by martinet101** [comment]
This is because of the tooltip showing on the point from where elevenClock picks the background color. 

To prevent this, you can set a custom static background color from the settings window, and then select the desired background color with the "pick screen color" button.
