### ISSUE TITLE
[BUG/ISSUE] (App forgets setting after update to not show on primary screen)

### ISSUE THREAD

**Issue by frischeDaten** [martinet101/ElevenClock#694]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
After an update of the app (many updates since I started using the app months ago), it "forgets" my setting to NOT "Show the clock on the primary screen".
As a result, the setting is activated and the clock shows on my primary screen.

## To Reproduce
Steps to reproduce the behaviour:
1. Deselect the option "Show the clock on the primary screen" in Clock Settings
2. Update the App
3. Got to Clock Settings
4. See that the option "Show the clock on the primary screen" is selected again

## Expected behaviour
The option remains deselected after an app update. (or selected, keep the state)

## Screenshots
Don't think it is necessary to understand.

## The Log

```
It does appear that the app logs are not transcending version updates.
```

## Additional context
I have two monitors on Windows 11 and need the clock only on the second monitor.

**Comment by martinet101** [comment]
Yes, this issue had been repored and has been fixed. The next update shouldn't do that
