### ISSUE TITLE
Thanks for your support!

### ISSUE THREAD

**Issue by iOrange** [martinet101/ElevenClock#697]
OMG you just made me cry. I just opened settings for ElevenClock on mt PC and saw that banner on top.
Thanks so much for your support, you should know - we truly appreciate that!

**Comment by CryptoSiD** [comment]
I would like to also thank you for creating this awesome app/software.

I was missing the seconds in the clock!

**Comment by martinet101** [comment]
Thank you guys :)

Your support is much appreciated ;)
