### ISSUE TITLE
[FEATURE REQUEST] Better compute RAM size

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#698]
34.2817955584 -> 32,GB

![2022-03-17 08 46 31](https://user-images.githubusercontent.com/3808250/158761310-f509ae43-485e-45e7-a531-8289884b7057.png)

**Comment by martinet101** [comment]
Huh, weird, i guess it calculates RAM using microsoft's 1024 bytes in one kb. I'll take a look

**Comment by panther7** [comment]
```
3428179555,8 / 1024 / 1024 / 1024 = 31,927 (GB)

Math.round(31,927) => 32 (GB)
```
