### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by Unknown16161** [martinet101/ElevenClock#701]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by lfechio12** [comment]
Hello, every time a notification appears in the notification bar, the clock is duplicated, as shown in the image
![Relógio duplicado](https://user-images.githubusercontent.com/74553990/159011765-81925248-4c96-4ea2-9638-4541f8d11347.jpg)
.

**Comment by martinet101** [comment]
Are you running version 3.3.1?

**Comment by martinet101** [comment]
Also, have you tried reseting ElevenClock?

**Comment by lfechio12** [comment]
> Are you running version 3.3.1?

Yes

**Comment by lfechio12** [comment]
> Also, have you tried reseting ElevenClock?

yes and still continues

**Comment by martinet101** [comment]
Can you please send me your log?

**Comment by lfechio12** [comment]
> Can you please send me your log?

Yesm shur
[elevenclock log LF.txt](https://github.com/martinet101/ElevenClock/files/8309799/elevenclock.log.LF.txt)
e

**Comment by martinet101** [comment]
Hi @lfechio12, looking at your log I saw that you might have this checkbox enabled:
![image](https://user-images.githubusercontent.com/53119851/159135319-09213f88-549f-4297-b2f1-2a2ce57e7afb.png)
Is this true?

**Comment by lfechio12** [comment]
> Hi @lfechio12, looking at your log I saw that you might have this checkbox enabled:

Yes it's true. All I need is to disable option: Disable the notification badge?

**Comment by martinet101** [comment]
Yes, with this checkbox disabled you should now see the counter. Is this true?

**Comment by lfechio12** [comment]
> Yes, with this checkbox disabled you should now see the counter. Is this true?

Yes, I'm seeing the counter now, thank you very much!
