### ISSUE TITLE
[FEATURE REQUEST] Sync with atomic clock

### ISSUE THREAD

**Issue by laszlodrgero** [martinet101/ElevenClock#704]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I would like new features. 

1. To be able to synchronise the system clock to any atomic clock on the internet at any time.

2. Be able to change the font size in the settings.

Thank you!

**Comment by martinet101** [comment]
For the font size, this is an actual thing. You can change that. For the time servers, this could be a good idea

**Comment by martinet101** [comment]
On the next version you'll be able to sync the time from apis like http://worldclockapi.com/ or http://worldtimeapi.org/
