### ISSUE TITLE
Calender week in overview

### ISSUE THREAD

**Issue by jiks23** [martinet101/ElevenClock#711]
Hi, awseome app that I just recently discovered!

I´d love to be able to see the calender week as well in the little calender overview, after clicking the calender/clock in the tray. Any solution for this?

Here is a corresponding image showing the same question, already once mentioned directly within the microsoft requests:
https://filestore.community.support.microsoft.com/api/images/3a1c8a2d-c404-4336-8c2a-f4804d6bdccd?upload=true

Huge thanks!

**Comment by martinet101** [comment]
Hi @jiks23, I don't think this is possible due to new modification restrictions
