### ISSUE TITLE
Permanent white border around the hidden icon.

### ISSUE THREAD

**Issue by Draskic** [martinet101/ElevenClock#714]
A permanent white border is around the hidden 11 Clock icon when the hidden menu is called up!
The Tooltip appears.
😷

**Comment by Draskic** [comment]
Now I actually realized that it is a feature of Windows 11 (Build 22581) to round the first top left icon in a white box but which disappears right after hovering through the menu!

**Comment by Draskic** [comment]
It actually looks like this
![image](https://user-images.githubusercontent.com/24246539/160280652-130042a0-4f40-480d-afea-e747383ba7f6.png)

**Comment by martinet101** [comment]
Yes, just remember that build 22581 is still in beta state...
