### ISSUE TITLE
[FEATURE REQUEST] Disable and/or change hotkey action when clicking on clock

### ISSUE THREAD

**Issue by Seaweed-Seal** [martinet101/ElevenClock#716]
**Is your feature request related to a problem? Please describe.**
Currently clicking on the clock invokes win+n and makes the calendar appear. I don't intend on ever using this feature, and it just gets in the way when I click on the clock to hide it for 10 seconds (I only use ElevenClock on my 2nd monitor).

**Describe the solution you'd like**
Add an option to disable or change the action that clicking on the clock performs.

**Comment by martinet101** [comment]
Yes, i guess i'll add that

**Comment by martinet101** [comment]
Fixed, coming in thge next release
