### ISSUE TITLE
Sun Valley 2 (dev/beta builds) tablet mode issues

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [martinet101/ElevenClock#720]
An option to hide the clock in the new tablet mode in Sun Valley 2 (beta/dev builds) would be great! The taskbar shrinks in the new mode, but the clock remains there and looks very strange; simply hiding it would be good for now (although when the taskbar is expanded it is in the wrong place, but that can be dealt with in the future).

![image](https://user-images.githubusercontent.com/49895442/161369852-f5611fba-ad5e-4ee8-89b3-e345ab1ee004.png)

**Comment by martinet101** [comment]
Yes, that's true. Btw, i'm in the process  of fixing elevenClock on the beta build

**Comment by SubjunctiveQuaver** [comment]
Thanks that sounds great!! I'm sure you've noticed that the line along the top of the taskbar now extends across the whole taskbar instead of ending, so I had to manually adjust the position of the clock to have it not poke out

**Comment by martinet101** [comment]
Yes, this is a thing that will be fixed in the next version, bu thanks for letting know ;)

**Comment by martinet101** [comment]
Hi, i can't implement this feature (as dumb as it can seem) because i have found no way to enable tablet mode on my pc. I'll still research, but not much can be done at the moment.

I'm sorry :(
