### ISSUE TITLE
[BUG/ISSUE] Win11 Build 22581: Minor graphical bug with default clock height

### ISSUE THREAD

**Issue by SamJoex** [martinet101/ElevenClock#722]
## Description
On Windows 11 Dev/Beta Build 22581.200, the new 1-pixel line in the top of the taskbar finally extends all the way to the right. As a result, since ElevenClock's default height is the full 48 pixels of the taskbar's height, it obscures this line and makes it look like it ends prematurely again.

## To Reproduce
Steps to reproduce the behaviour:
1. Install ElevenClock on Windows 11 Build 22581.200
2. See minor error

## Expected behaviour
The clock does not obscure the line on top of the taskbar at default clock height.

## Screenshots
The minor bug in action:
![ElevenClock 3 3 2 bug](https://user-images.githubusercontent.com/88250307/161409468-25bfc52b-4cd4-48a0-85ac-bce1008d0119.png)

Ideal Result (achieved with Override clock default height & Adjust vertical clock position):
![ElevenClock 3 3 2 bug (ideal)](https://user-images.githubusercontent.com/88250307/161409491-7b43122c-88c7-48c0-a0b2-2b3173a4babb.png)

## The Log

Win32mica: Failed to DwmExtendFrameIntoClientArea -2147024809
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.3.2 (v3.32) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1720, 1032, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy-MM-dd
🔵 tTimeMode: HH:mm:ss
🔵 Loaded date time format: %H:%M:%S 
%Y-%m-%d
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(1920, 52, 1280, 1024)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(3000, 1028, 200, 48)
🔵 Font families: ['Segoe UI Variable Display', 'sans-serif']
🔵 Font size: 9.3
🟢 Using white text (dark mode)
🔵 tDateMode: yyyy-MM-dd
🔵 tTimeMode: HH:mm:ss
🔵 Loaded date time format: %H:%M:%S 
%Y-%m-%d
🔵 Full screen rect:  (1920, 52, 3200, 1076)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
🟢 Loaded clocks in 0.6597995758056641
🔵 Restart loop: 1
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🟣 Expected AttributeError on backgroundLoop thread
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.6733777523040771
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/customize.webp
Win32mica: Failed to SetWindowCompositionAttribute 1
Win32mica: Failed to SetWindowCompositionAttribute (dark mode) 1
🔵 Copying log to the clipboard...

**Comment by martinet101** [comment]
Yes, this is going to be fixed in the next release
