### ISSUE TITLE
Highlighting clock when notification centre is shown (build 22581+)

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [martinet101/ElevenClock#723]
How ElevenClock looks when the notification area is shown:

![image](https://user-images.githubusercontent.com/49895442/161413489-d7e16814-c528-4122-97c9-8be1887064ac.png)

When ElevenClock is off, and notification centre is shown, the clock remains highlighted ("pressed"). This is consistent with action centre, language picker, pen button, etc.

![image](https://user-images.githubusercontent.com/49895442/161413504-afd137d1-aa54-47f8-a035-8191c8df18cf.png)

**Comment by martinet101** [comment]
Yes, this is a thing I coudn't manage to do, since i found nowhere to check wether the calendar is opened or not
