### ISSUE TITLE
ElevenClock Started Crashing Today

### ISSUE THREAD

**Issue by KhalidAlotaibiSA** [martinet101/ElevenClock#725]
OS: Windows
                   Version: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 3.4.0
          APP Version Code: 3.4
                   Program: ElevenClock

-----------------------------------------------------------------------------------------

ElevenClock Log:

Traceback (most recent call last):
  File \\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py, line 1450, in <module>
  File .\settings.py, line 172, in __init__

ValueError: '' is not in list<class 'ValueError'>: '' is not in list

**Comment by martinet101** [comment]
Yes, the latesu update if failing. i'm fixing this rn

**Comment by RDols** [comment]
Same here.

**Comment by martinet101** [comment]
Please reinstall again please

**Comment by RDols** [comment]
It's working again at my setup. Thanks for the quick action.

**Comment by KhalidAlotaibiSA** [comment]
Bug has been fixed, i just reinstall the program and worked like a charm, amazing work martinet101 👌🔥
