### ISSUE TITLE
BUG - App wont open

### ISSUE THREAD

**Issue by willbert03** [martinet101/ElevenClock#726]
## Describe the bug
I tried to update the app (by restarting and allowing it to update) and it couldn't. It then didn't reopen. 

## To Reproduce
Try opening app after restarting it

## Expected behaviour
Open the app...

## The Log
Traceback (most recent call last):
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1450, in <module>
  File ".\settings.py", line 172, in __init__

ValueError: '' is not in list<class 'ValueError'>: '' is not in list

**Comment by martinet101** [comment]
please try installing now again

**Comment by willbert03** [comment]
It works!
