### ISSUE TITLE
[BUG] Hide ElevenClock no way to get it back

### ISSUE THREAD

**Issue by urifoox** [martinet101/ElevenClock#74]
**Describe the bug**
If you hide ElevenClock from the settings menu and do not have the window in the system tray it is gone forever and there's no way to get it back unless you terminate the app.

**To Reproduce**
1. In the settings menu hide it from the tray
2. Right click on the clock
3. Select hide clock

**Expected behavior**
Should not let you hide the clock if there's no way to get it back or it should enable the system tray icon so you can re-enable it

**Screenshots**
![image](https://user-images.githubusercontent.com/22828430/136986264-91bf74db-30ec-4c39-8445-37eee49510a2.png)

**Comment by urifoox** [comment]
I recommend not letting the user configure the software into a state that makes no sense. This is one example, another is to uncheck show clock and show date - what's the point?

**Comment by martinet101** [comment]
Added start menu shortcut to settings. will ship in v2.1
