### ISSUE TITLE
[BUG] Clock is not hiding with the taskbar

### ISSUE THREAD

**Issue by ottozumkeller** [martinet101/ElevenClock#749]
My suggestion would be, if the taskbar is set to hide automatically, that ElevenClock detects this and the clock adapts to the hide animation and also hides or moves below the bottom of the screen. At the moment, when the taskbar is hidden, the clock is still displayed which doesn't look very nice. Of course this will be difficult to implement, but it would be a real improvement if this would work.

**Comment by martinet101** [comment]
> the clock is still displayed

You mean temporarily or permanently? Because ElevenClock _should_ hide and show, but without animation.

**Comment by martinet101** [comment]
That's then a bug, because it should hide automatically. Can you please send me your log?

**Comment by ottozumkeller** [comment]
Here's the log:
[log.txt](https://github.com/martinet101/ElevenClock/files/8495691/log.txt)

**Comment by martinet101** [comment]
Can you please try resetting ElevenClock?

**Comment by ottozumkeller** [comment]
Thank you, now it works. 👍
