### ISSUE TITLE
[ISSUE] High CPU usage

### ISSUE THREAD

**Issue by dada051** [martinet101/ElevenClock#75]
ElevenClock 2.0 (don't know for previous verisons) use 25% on my CPU (4 cores/8 threads). An app that only show time and date should not use so much CPU

**Comment by martinet101** [comment]
Try killing and then restarting the app. 

On my old pc the behaviuor is normal:
![image](https://user-images.githubusercontent.com/53119851/136987387-bddd3f75-0c72-4e77-9cb1-a30e0a607432.png)

**Comment by dada051** [comment]
I tried the seconds settings too. That's probably where the issue is.

**Comment by TTTTHD** [comment]
![grafik](https://user-images.githubusercontent.com/48693275/136996168-b4e4a133-299f-4ca9-bc83-717fcfc3feba.png)
with a 8700 - not ideal

**Comment by martinet101** [comment]
Ok, i have found that threads are not being removed when clocks are restarted, so they accumulate, and because when changing settings clocks reload. they finish overloading the cpu
