### ISSUE TITLE
[BUG/ISSUE] Letters overlapping

### ISSUE THREAD

**Issue by SmartManoj** [martinet101/ElevenClock#751]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
Tu are overlapping
## To Reproduce
Steps to reproduce the behaviour:

## Screenshots
![image](https://user-images.githubusercontent.com/7231077/162859951-02a96d6c-5058-450a-970d-06aef4490096.png)

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
This is on the https://github.com/martinet101/ElevenClock/wiki#known-issues section on the wiki
