### ISSUE TITLE
Increase date font in Tooltip.

### ISSUE THREAD

**Issue by Draskic** [martinet101/ElevenClock#752]
It’s a little too small a date at 11clock when touched with a mouse!
Even in Windows 11 it's bigger.
If possible, of course!
Greeting
![Date tooltip](https://user-images.githubusercontent.com/24246539/163026321-b414bec8-22c7-4c5e-91f7-e50ed5402720.jpg)
!

**Comment by martinet101** [comment]
Oh, the font is the Windows 11's default, but i can link it to the clock's font size (it would make more sense)

**Comment by Draskic** [comment]
I understand.
I use the font size for "11 Clock" 24.
Maybe it will be too big?
It is best to set the date font size as on the clock from Windows (in
the task bar).
Will the font size change in the tooltips of settings as well?
Greeting!
Drasko

**Comment by martinet101** [comment]
> Will the font size change in the tooltips of settings as well?

No, it shouldn't



> Maybe it will be too big?

Yes, I should add a specific option to customize the tooltip maybe...

**Comment by Draskic** [comment]
That would be best.
If you have nerves!
Greeting!
Drasko

**Comment by martinet101** [comment]
In the next version the user will have the ability to customize the tooltip

**Comment by Draskic** [comment]
Very good!
I can't wait for this improvement too!
These details further enhance an already great clock for Windows!
Greeting!
Drasko!
