### ISSUE TITLE
[BUG/ISSUE] Additional Clock show current timezone, not set timezone

### ISSUE THREAD

**Issue by CJTC70** [martinet101/ElevenClock#754]
## Describe the bug
Using the Windows "Additional clocks" feature, the clocks show up with the proper labels when mousing over the clock, but the time is the current timezone, not the set timezone.

## To Reproduce
- Setting additional clocks in windows with different time zones:
 >> Open Settings.
 >> Click on Time & language.
 >> Click the Date & time page on the right side.
 >> Under the "Related links" section, click the Additional clocks setting.
 >>Click the Show this clock option. 
 >>In the "Enter a display name" settings, confirm the name for the clock — for example, Home.
 >>Click the Apply button.
 >>Click the OK button.
      Note: A link to the directions I used to set the additional clocks:
      [https://www.windowscentral.com/how-set-multiple-clocks-windows-11]
- Show the clocks:
 >>Mouse over the clock

## Expected behavior
Each additional clock shows the correct time for its setting(but instead shows the current timezone time)

Note: if clicking on the time to show the calendar, the timezone times show correctly

## Screenshots
![elevenclock_issue](https://user-images.githubusercontent.com/51372753/163434541-2239a386-1fd6-45fa-9ed2-6d59ccb2183e.png)

## The Log
 - Log too long to include in ticket.

## Additional context
None

**Comment by martinet101** [comment]
Yes, this is a buh that has been fixed and will be available in the next update

**Comment by martinet101** [comment]
Yes, this will be fixed in the next update
