### ISSUE TITLE
[FEATURE REQUEST] How install ElevenClock for all users?

### ISSUE THREAD

**Issue by redbob365** [martinet101/ElevenClock#758]
I installed ElevenClock in a computer running Windows 11. It works! Congrats...
But... I switch a user in this computer (We have AD submitting all computers) and it's not even installed.

I saw that ElevenClock is installed in %appdata%, so will I have to install it again for every new user that will log on this machine?
What about to  copy ElevenClock to Default User folder (c:\users\default)? Will it work?

**Comment by martinet101** [comment]
No, ElevenClock gets installed on a per-user basis, and each user will need to install it. An easy way to install it is from the MS store, since it is onyl one click and you are ready to go.

Idk if moving ElevenClock to Default User folder will work, you can for sure give it a try :)
