### ISSUE TITLE
[FEATURE REQUEST] Add Double Click action

### ISSUE THREAD

**Issue by Riajyuu** [martinet101/ElevenClock#759]
**Describe the solution you'd like**
Already we have single click action override. But with double click action we can add more action without overriding the default one.
Despite that, in the action menu, I would like to see "clear recycle bin" as an action option.

**Comment by martinet101** [comment]
Yes, that could definitely be a thing


> clear recycle bin

I don't know up to what point this will be possible, but i'll try.

**Comment by Riajyuu** [comment]
>I don't know up to what point this will be possible

You need winshell: https://github.com/tjguk/winshell

e.g.:

````
import winshell
winshell.recycle_bin().empty(confirm=False, show_progress=False, sound=False)
````

**Comment by martinet101** [comment]
The feature will come with the next version
