### ISSUE TITLE
[FEATURE REQUEST] Support Chinese Lunar Calendar

### ISSUE THREAD

**Issue by Riajyuu** [martinet101/ElevenClock#760]
**Describe the solution you'd like**
If you don't know how to, here is sth for you:
https://github.com/6tail/lunar-python/blob/master/README_EN.md

Our national standard, GB/T 33661-2017 (Chinese only), can be [viewed online](http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=E107EA4DE9725EDF819F33C60A44B296).

Also you seem required to add a special format string to the custom date-time setting area to display output above.

Another plausible approach is to allow user customize tooltip into date time string.

I'm pretty sure both the [library developer](mailto:6tail@6tail.cn) and I would be very glad to help you on this

**Comment by martinet101** [comment]
I understand the request, but i don't understand in which part of the tooltip should this be included.

It would be awesome if you could provide more details :)

**Comment by Riajyuu** [comment]
![image](https://user-images.githubusercontent.com/16912240/164894920-3d77a14a-ce5a-4629-afc7-3c6315f12676.png)

This is the part I wanna customize. Here is the result I expect (quick draft made with PPT):
![image](https://user-images.githubusercontent.com/16912240/164895360-3ccb102e-bf3e-4f00-8234-62cb6ccdc7f0.png)

====

Desipte that, in this part: 
![image](https://user-images.githubusercontent.com/16912240/164895186-10861ecf-ef8b-4cbb-ab4b-3238b0deb27b.png)

I would like to see the possibility to use lunar format. Maybe sth like %lunarYr or %solarTerm

**Comment by martinet101** [comment]
Hi, I've been trying to figure out this but I don't have the chinese knowledge to make that. If you manage to make a python function that returns a string with the current day, year, etc. from the lunar calendar then open a PR and i'll try again, but I really can't do this myself
