### ISSUE TITLE
[FEATURE REQUEST] Show all icons in sys tray

### ISSUE THREAD

**Issue by venustoise** [martinet101/ElevenClock#762]
Hi, I've install 11clock immediately after upgrading to Win11, and I've resolved 1 of 2 bullshit of the last Windows OS: show seconds.
The other big problem is that the option to see ALL icons in the sys tray is impossibile to enable. Of course, it's possible exec
"explorer shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9}" and then check "Always show all icons..." and it works! Or at least until next boot. I hate this, and I think I'm not the only one: if I want to see all system tray icons, or clock seconds, I've the right to choose!!
It's possible to add an option for this? THANKS!!!

**Comment by Masamune3210** [comment]
It's a lot more complicated to completely replace the tray menus than it is to draw over a clock that you painted over with a square, that's the issue

**Comment by venustoise** [comment]
> It's a lot more complicated to completely replace the tray menus than it is to draw over a clock that you painted over with a square, that's the issue

I think it's not need a full tray menu replacement, but just running, on start-up, 2 commands (the explorer shell above and, this may be more difficult if GUI only, selecting the native option for showing all icons in tray) that will force Windows to show all icons in the tray menu, as it should be.

**Comment by martinet101** [comment]
Hi @venustoise, what @Masamune3210 said is right. The implementation is difficult (even with the shell command run), and it is not really related to the application.

Regarding what you want to achieve, in m pc I have the native, _windows 11-like_ option to do it. Under taskbar settings, i have a drop-down whch allows me to show or hide system tray icons. Wouldn't that help with your issue?
![image](https://user-images.githubusercontent.com/53119851/164892032-ddaa151e-bfe7-44a4-8a28-00acbe4c0a52.png)

**Comment by Masamune3210** [comment]
The annoying thing is that Microsoft decided to remove the option to never hide anything in the overflow menu, and instead makes you either drag the icon out of the overflow menu into the tray or go into that menu to change the setting, both of which will do the same thing. Unfortunately not much way around it though
