### ISSUE TITLE
On Sun Valley 2, default horizontal clock position slightly off

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [martinet101/ElevenClock#763]
On v3.4.1, there is like a 1 pixel offset for the default horizontal clock position, as seen when opening the notification centre (you see a few pixels of the underlying button).

Default horizontal clock position (with notification centre open):
![image](https://user-images.githubusercontent.com/49895442/164890091-f1b00baa-f61b-4ea3-af79-d2dfaeaf6abe.png)

Manually adjusted horizontal clock position (with notification centre open):
![image](https://user-images.githubusercontent.com/49895442/164890068-9fce9a2d-4775-482e-9b86-6ed002539344.png)

**Comment by martinet101** [comment]
Oh, I see

**Comment by SubjunctiveQuaver** [comment]
Yes, literally unusable 😂

**Comment by martinet101** [comment]
Fixed!
