### ISSUE TITLE
Gitlab releases downloads button

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#764]
Update downloads button link to https://github.com/martinet101/ElevenClock/releases/download/3.4.1/ElevenClock.Installer.exe or disable link, because now linking to https://github.com/martinet101/ElevenClock/blob/3.4.1 which does not works.

Link: https://github.com/martinet101/ElevenClock/releases/tag/3.4.1

![2022-04-27 17 06 21](https://user-images.githubusercontent.com/3808250/165550449-9309372d-8504-41f0-ac86-924d6c6fc53b.png)

**Comment by martinet101** [comment]
Done!
