### ISSUE TITLE
[BUG/ISSUE] Showing seconds will overlay the battery icon

### ISSUE THREAD

**Issue by nnhthuan** [martinet101/ElevenClock#770]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [X] **I have checked that I am running the latest version of ElevenClock**
- [X] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [X] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
Showing seconds will overlay the battery icon

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'settings'
2. Check to show seconds on clock

## Expected behaviour
The clock should not overlay the battery icon

## Screenshots
The clock overlays the battery icon. See screenshot.
<img width="168" alt="Screenshot 2022-05-01 231157" src="https://user-images.githubusercontent.com/300141/166147533-bf27f3e4-45f0-4348-bbdc-ff97b58a71e1.png">

## The Log
[elevenclock_logs.txt](https://github.com/martinet101/ElevenClock/files/8598972/elevenclock_logs.txt)

## Additional context
N/A

**Comment by martinet101** [comment]
The issue is described in the known issues section

**Comment by martinet101** [comment]
>  ElevenClock overlays the battery/volume icon in the taskbar
The best solution here is to set a smaller font size, since ElevenClock is a simple overlay and can't interact with other taskbar elements.
