### ISSUE TITLE
Multiple ElevenClock system tray icons

### ISSUE THREAD

**Issue by HydroTRI** [martinet101/ElevenClock#784]
I'm not sure if this occurs after my screen sleeps or just over time but after a while when I look at my system tray icons, I'll have 3-5 ElevenClock apps running.

**Comment by martinet101** [comment]
If you hover your mouse over them, do they get closed?

**Comment by HydroTRI** [comment]
No, however it seems to happen less as of late. Every now and then there are 2 instances, so I just right click and quit one. Not sure what changed.

**Comment by martinet101** [comment]
Can you please try uninstalling ElevenClock, removing a folder called  .elevenclock placed in your home directory and then reinstalling ElevenClock?

**Comment by HydroTRI** [comment]
Okay I will give it a shot.
