### ISSUE TITLE
[BUG] Crash almost every night

### ISSUE THREAD

**Issue by SkateScout** [martinet101/ElevenClock#788]
In the error Submit Window i get this information:

                        OS: Windows
                   Version: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: Unknown
          APP Version Code: Unknown
                   Program: ElevenClock

-----------------------------------------------------------------------------------------

ElevenClock Log:

Traceback (most recent call last):
  File \\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py, line 41, in <module>
  File C:\Users\Besitzer\AppData\Local\Temp\embedded._67ysxps.zip\shibokensupport\__feature__.py, line 142, in _import
  File PyInstaller\loader\pyimod03_importers.py, line 495, in exec_module
  File .\external\FramelessWindow.py, line 25, in <module>
  File C:\Users\Besitzer\AppData\Local\Temp\embedded._67ysxps.zip\shibokensupport\__feature__.py, line 142, in _import

ImportError: DLL load failed while importing QtWinExtras: %1 ist keine zulässige Win32-Anwendung.<class 'ImportError'>: DLL load failed while importing QtWinExtras: %1 ist keine zulässige Win32-Anwendung.

**Comment by martinet101** [comment]
Can you please try reiinstalling? IF it does not work, can you please try doing a healt check? https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

**Comment by SkateScout** [comment]
Hi, i am running on Windows 11 and since the hab is using Local\Temp i do not really like to reinstall Windows. Since it is the only program that have any issues.

**Comment by martinet101** [comment]
No, i meant reinstalling ElevenClock

**Comment by martinet101** [comment]
From the microsoft store

**Comment by SkateScout** [comment]
Hi did an uninstall an installed it fresh from microsoft store.

**Comment by martinet101** [comment]
Did it help?
