### ISSUE TITLE
[BUG] 3rd monitor clock appears in white when on light theme

### ISSUE THREAD

**Issue by doug-cannon** [martinet101/ElevenClock#79]
I have an **Auto Dark Mode** app that I use to switch from **light mode** to **dark mode**. When in light mode _(or light theme),_ The clock on my left monitor is fine with black text on white background. But my right monitor shows white text on white background.

![left+right_monitor_10 12 2021](https://user-images.githubusercontent.com/47096124/136994100-b7371ce2-353d-4ee5-898f-7629f0b5b372.jpg)

**Comment by martinet101** [comment]
Fixed, releasing in 2.1
