### ISSUE TITLE
[BUG/ISSUE] Getting tons of errors after opening computer with low space

### ISSUE THREAD

**Issue by TechStudent11** [martinet101/ElevenClock#791]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ ] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
When I woke my computer from sleep (or just opened the lid) this morning, I was greeted with tens of error windows originating from ElevenClock.

## To Reproduce
Steps to reproduce the behaviour:
1. Have low space
2. Close then open laptop lid.

## Expected behaviour
There should be no error windows.

## Screenshots
![image](https://user-images.githubusercontent.com/76978184/170828277-11bc7be9-1fa7-42f1-bed7-a642d3aa7198.png)

## The Log

```
Can't open. I get another error window.
```

## Additional context
I know I have low space, but it's already installed. So it should continue to work, right?

**Comment by martinet101** [comment]
Yes, I think it was discussed about ElevenClock crasing with low disk space.

My friend, there's nothing I can't do about this, since those are Qt's errors when Windows restricts disk usage (due to low space). Said that, the best thing I can encourage you is to free up space. 

I'm sorry I can't help more :(

**Comment by TechStudent11** [comment]
> I'm sorry I can't help more :(

It's fine, I understand.
