### ISSUE TITLE
[FEATURE REQUEST] Sync with system color mode

### ISSUE THREAD

**Issue by azumukupoe** [martinet101/ElevenClock#798]
**Is your feature request related to a problem? Please describe.**
I'm using https://github.com/AutoDarkMode/Windows-Auto-Night-Mode and when it switches system color mode ElevenClock doesn't change its color so I have to restart ElevenClock to have it displayed correctly

**Describe the solution you'd like**
Sync with current color mode of WIndows

**Comment by martinet101** [comment]
Mhmm, it _should_ change, let me check that...

**Comment by martinet101** [comment]
Are you running the latest version (3.5.0) ?

Do you have any custom background color set?

**Comment by azumukupoe** [comment]
Yes, I'm on 3.5.0
No, I haven't touched any appearance settings

**Comment by martinet101** [comment]
Have you tried Resetting ElevenClock?

**Comment by azumukupoe** [comment]
I tried but it's the same

**Comment by martinet101** [comment]
I suppose that if you change your color scheme from the settings window it fails also. 

Can you please send me your log and record your screen while changing the system theme?
