### ISSUE TITLE
BUG: Bold Not Working.

### ISSUE THREAD

**Issue by RandyJae** [martinet101/ElevenClock#809]
v3.6.0 Added Font Style Bold. When selected, does not bold (no change in visual at all. Tried with several fonts including Times New Roman and Arial (Neither worked). 

Custom Font Size 26 selected. (Should not make a difference, just large enough to evaluate font thickness)

Italic, Strikeout, Underline, changing fonts work. Bold does not

Below Image is a screen shot: top line is regular, bottom line is bold

![ElevenClock](https://user-images.githubusercontent.com/102175494/173621489-2db15635-a3d1-4790-aa37-db388efbb86a.png)

**Comment by martinet101** [comment]
Bold fonts are a bug in Qt. I have found No way to get them to work.  Neither with QFonts, QSS or special font files, i couldn't get any bold font to work. 

Best i can say is to set a semib font, if available.
