### ISSUE TITLE
pin clock to desktop?

### ISSUE THREAD

**Issue by adammo94** [martinet101/ElevenClock#813]
Is it possible to pin the  clock to desktop? So it wouldn't overlap apps (I have it in right top position)? Couldn't find such option.

**Comment by martinet101** [comment]
Mhmm, i see, some kind of stay on bottom option...

Yes, this could definitely be a thing

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/176890312-e5ba35b4-cfca-4fed-8374-bc917eced719.png)
It will come with the next version
