### ISSUE TITLE
[BUG/ISSUE] Elevenclock dumps 69 GB data in temp and creates 2277 processes with Fatal Error messages

### ISSUE THREAD

**Issue by Qaatloz** [martinet101/ElevenClock#818]
## Before submitting the issue

- [ X ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- There have been previous tickets, but do not entirely cover issues reported here
- [ X] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ X ] **I have checked that I am running the latest version of ElevenClock**
- Version 3.6.0
- [ X ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- not yet, but i didn't deviate far from defaults and the issue shouldn't really occur whichever settings you choose
- [ X ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
Login after lunchbreak shows a desktop with loaded with fatal error windows from elevenclock. Some mentioning failure to decompress files, some mentioning lack of disk space. Task manager shows more than 2000 elevenclock processes. Appdata\local\Temp folder contains 2277 folders starting with _MExxxx taking up about 67 GB of space all generated within the 30 minute period. It has locked up windows explorer.exe and crashed multiple drivers (bluetooth etc.)

## To Reproduce
Steps to reproduce the behaviour:
Unknown. It seems like auto-update behaviour. but auto-update is disabled in the settings.

## Expected behaviour
Normal functioning. Not eating 67 GB of space and crashing critical windows subsystems.

## Screenshots
Unfortunately i was unable to create screenshots because of the caused issues for windows

## The Log
Unfortunately not able to retrieve log. Is it saved somewhere as separate file?

**Comment by martinet101** [comment]
See #790 

I thas been fixed and the fix will come with the next version

**Comment by martinet101** [comment]
If you have low disk space, PyInstaller is known to crash (see #791).

In what represents the 69GB of data, the issue has been fixed and the fix will come with the next version (see #790 )

**Comment by Qaatloz** [comment]
I'm happy to see that you have a fix already, but in my case my laptop was not low on space before the issue. I will check out the new version when its there en report back if it occurs again.

**Comment by martinet101** [comment]
Then make sure to post here if the issue persists!

**Comment by martinet101** [comment]
You can now update
