### ISSUE TITLE
[PRIVACY] Title of full-screen window shouldn't be logged

### ISSUE THREAD

**Issue by kkm000** [martinet101/ElevenClock#820]
## Before submitting the issue

- [X] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [X] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [X] **I have checked that I am running the latest version of ElevenClock**
- n/a **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [X] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

## Describe the bug

In Settings/Debugging information/Open ElevenClock log, lines like the following are logged:

> 🟡 Fullscreen window detected! (10) HOW an **(... REDACTED ...)** - YouTube — Firefox Developer Edition (0, 0, 3072, 1920) Fullscreen rect: (0, 0, 3072, 1920)

Since PII is logged, the program must include privacy policy, describing what and where is logged, how long the information is retained, is it sent home automatically, how it's used if it is, etc. etc. Given that this particular information has no apparent diagnostic value, it would be better to simply omit the window title than go through these compliance hoops. It's hard to believe that the title contents may help with diagnosing problems.

A process name seems as good to me, if not better—you can tell Zoom from GoToMeeting, for example. I would not care if the log recorded that zoom.exe was running full-screen, but I *do* care a humongous lot whether the meeting title is logged, as probably anyone working form home does. "firefox.exe" is OK, but sharing what video from which site I watch may not always be.

On a lesser point, logging the same message again and again into a log containing no timestamps looks excessive. I see 2366 of these messages logged during a ~24 minute long video. Should a log need to be shared in a ticket to diagnose even an unrelated problem, it would be a lot of work to redact it.

## To Reproduce

1. Enable ElevenClock to display in full-screen mode.
2. Open a YouTube video, and press `f` to go full-screen.
3. Play it for some time, and check the log.
4. Observe the above message logged about 1-2 times a second.

## Expected behaviour
PII of dubious utility isn't logged.

## The Log

> Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

**No way!!!** 😃

**Comment by martinet101** [comment]
Oh, i see. 

Just for you to know, those logs don't get stored or sent nowhere. But yes, the process name would be better

**Comment by martinet101** [comment]
Fixed, coming with the next version
