### ISSUE TITLE
[FEATURE REQUEST] Have secondary monitors show calendar pop up when clicked

### ISSUE THREAD

**Issue by JoeBush266** [martinet101/ElevenClock#822]
Right now when you click on the calendar of a secondary monitor it only shows the calendar on the primary monitor.
When doing screens shares it is sometimes desirable to discuss upcoming meetings, etc. and it is needed to show the calendar of the screen you may be sharing. Having the calendar pop up on that screen would be very valuable as the presenter has to switch to another app to show it.

**Comment by martinet101** [comment]
This is impossible, since the calendar is fixed on the primary display. You should then blame microsoft. 

See https://github.com/martinet101/ElevenClock/wiki#known-issues
