### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by albiek1976** [martinet101/ElevenClock#828]
## Before submitting the issue

- [x ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x ] **I have checked that I am running the latest version of ElevenClock**
- [x ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
A clear and concise description of what the bug is. Whenever the computer comes out of sleep, the clock crashes. Right now please refer to screen + snip. I also have three monitors with all drivers up to date

## To Reproduce
Steps to reproduce the behaviour:

## Screenshots
<img width="1877" alt="Screenshot 2022-07-10 074445" src="https://user-images.githubusercontent.com/92185158/178143462-ab9ba212-421c-471b-b750-4ad693b6b00d.png">

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

## Additional context
right now, only my main monitor has returned the clock to normal position and working but still has what is running in the screen snip. The other two monitors do not have the clock running after the crash and I believe that the 2 portions of the clock in the screen snip are the clocks that should be on the lower right of each monitor.

This has also happened last week and I reinstalled right away

**Comment by martinet101** [comment]
Follow this guide and set "App" instead of "system".
https://www.addictivetips.com/windows-tips/disable-scaling-in-apps-on-windows-10/#:~:text=To%20disable%20scaling%20for,option%2C%20and%20click%20OK.
If you open the URL with chrome the section you need to do will be highlighted
