### ISSUE TITLE
Hover Outline Glitch

### ISSUE THREAD

**Issue by neoOpus** [martinet101/ElevenClock#829]
## Before submitting the issue
- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
The clock outline that shows when it is hovered miss the top part and there is some margin on the bottom, nothing in the setting fixed this, so I am considering it a bug

## To Reproduce
Steps to reproduce the behaviour:
Mouse over the clock.

## Expected behaviour
The outline must show all around but it would be better to have it removed so it just mimic Windows 11 style or let everyone decide how to style this part too just like the other customizable visual features.

## Screenshots
![image](https://user-images.githubusercontent.com/1388336/178166529-5226afcb-e7f5-4462-892d-a2bda7d0a925.png)

**Comment by neoOpus** [comment]
How it should look like

![image](https://user-images.githubusercontent.com/1388336/178166589-32a618d1-a295-46fc-abca-a3ed71c3dbeb.png)

**Comment by martinet101** [comment]
Can you please send me your log?

**Comment by neoOpus** [comment]
Sure here it is

It took 0.0009915828704833984 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.6.3 (v3.63) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1716, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using black text (light mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d/%m/%Y
🔵 Full screen rect:  (0, 0, 1920, 1080)
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟢 Loaded clocks in 0.9918873310089111
🟢 Cached text input host hwnd: 131890
🔵 Restart loop: 1
None
🟣 Expected AttributeError on backgroundLoop thread
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟡 System tray icon disabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 2.9962680339813232
🔵 (worldtimeapi.org) Time offset set to -0.016902685165405273
🟢 Green lignt to rease temp dirs
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: HH:mm
🔵 TZ 1 is tzfile('US/Pacific')
🔵 Long date string: HH:mm
🔵 TZ 2 is tzfile('Europe/Paris')
🔵 Long date string: dddd, d MMMM yyyy
🔵 Showing tooltip
🔵 Long date string: HH:mm
🔵 TZ 1 is tzfile('US/Pacific')
🔵 Long date string: HH:mm
🔵 TZ 2 is tzfile('Europe/Paris')
🔵 Long date string: dddd, d MMMM yyyy
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://upload.wikimedia.org/wikipedia/commons/d/db/Google_Translate_Icon.png
🔵 Saving log...
🔵 Starting update check

**Comment by neoOpus** [comment]
Yes it looks great now, Thanks.
