### ISSUE TITLE
[BUG] Clock shows over rdp window when using all monitors in RDP

### ISSUE THREAD

**Issue by The1CABAL** [martinet101/ElevenClock#83]
**Describe the bug**
ElevenClock displays over the RDP session when using all available monitors for the session when the clock is expected to be hidden

**To Reproduce**
1. Open Remote Desktop Connection
2. Navigate through More Options -> Display
3. Check "Use all my monitors for the remote session"
4. Connect to RDP session
5. Observe Clock displaying over RDP

**Expected behavior**
The Win 11 clock hides while the RDP session is open

**Screenshots**
![image](https://user-images.githubusercontent.com/37129528/137023858-21fe88f2-dee7-4183-968f-8ff63fd1fd0b.png)

**Comment by AnagogBestagog** [comment]
It is set to 100% on both monitors.
