### ISSUE TITLE
Releases improvements in github (v3.6.4)

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#830]
Releases improvements:
* Available Languages: link into readme, with autogenerated list of translations: https://github.com/martinet101/ElevenClock#currently-supported-languages
* [v3.6.4](https://github.com/martinet101/ElevenClock/releases/tag/3.6.4) wrong downloads banner to 3.6.3

@martinet101

**Comment by martinet101** [comment]
About the autogenerated languages, keep in mind that while they keep updated regularly, the languages on each version are frozen, so linking to the readme wouldn't be the best

**Comment by panther7** [comment]
#832 this is only for copy&paste to github release page.
