### ISSUE TITLE
[BUG]: Won't install from Microsoft Store

### ISSUE THREAD

**Issue by ManfredLange** [martinet101/ElevenClock#833]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [x] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
ElevenClock installation from Microsoft Store fails with error "Code: 0x8D050004". The complete message is:

> Couldn't install app
> 
> Something happened and we couldn't install the app. Wait a bit then try again.
>
> Code: 0xD050004

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Micosoft Store'
2. Click on 'Install'

Clicking "Retry" in the Microsoft Store results in the same error, even if waiting several minutes.

## Expected behaviour
Installation should be successful

## Screenshots

![2022-07-14_08-27-37-store-install-failure](https://user-images.githubusercontent.com/1130812/178830455-c7509264-77b2-4fc3-a3d4-f0328e36fee1.png)

## The Log

Does the app produce a log during installation?

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

## Additional context

I tried other apps from the Microsoft Store and they install without issue.

System:
- Windows 11 Pro, 64 bit, version 21H2, build 22000.795
- "Experience": Windows Feature Experience Pack 1000.22000.795.0
- Ryzen 9
- 64 GB RAM
- Nvidia RTX 3070 Ti

According to Microsoft the OS is up-to-date. I also rebooted the computer.

I also tried the "Windows Store Apps" troubleshooter. That didn't detect anything either.

**Comment by martinet101** [comment]
What if you try opening the "visit support website" button?

**Comment by martinet101** [comment]
Honestly, I have no clue of what is happening. I just uploaded the installer as always do, and it has always worked.

Anyway, can you please share me the error code?

**Comment by martinet101** [comment]
I saw what is happening now, MS "antivirus" crap thinks ElevenClock is a virus. Anyway, this will be fixed soon. Meanwhile, install from Github
