### ISSUE TITLE
[BUG] (crashed after external monitor disconnected after computer sleep/hibernate )

### ISSUE THREAD

**Issue by acezzz** [martinet101/ElevenClock#834]
## Describe the bug
crashed after external screen disconnected during computer sleep

## To Reproduce
Steps to reproduce the behaviour:
1. Connect at least 1 external monitors
2. Put computer into sleep or hibernate
3. Disconnect the external monitor
4. put computer out of sleep, will see crash report

```

**Comment by martinet101** [comment]
Can you please send a screenshot of the error please?

Also, try enabling this and relaunching elevenClock:
![image](https://user-images.githubusercontent.com/53119851/178991752-859d4c5b-755d-42f8-932d-d7184ab9efdb.png)

**Comment by acezzz** [comment]
You are likely right. It is about a "file not found" error.
The error message box :

---------------------------
Fatal error detected
---------------------------
Error loading Python DLL 'C:\Users\abc\AppData\Local\Temp\_MEI250842\python310.dll'.
LoadLibrary: The specified module could not be found.


-----------------------------------------------------------------------------------------
                        OS: Windows
                   Version: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: Unknown
          APP Version Code: Unknown
                   Program: ElevenClock

-----------------------------------------------------------------------------------------
ElevenClock Log:

Traceback (most recent call last):
  File \\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py, line 4, in <module>
  File PyInstaller\loader\pyimod03_importers.py, line 495, in exec_module
  File ctypes\__init__.py, line 8, in <module>

ImportError: DLL load failed while importing _ctypes: The specified module could not be found.<class 'ImportError'>: DLL load failed while importing _ctypes: The specified module could not be found.

**Comment by acezzz** [comment]
I will try the setting and let you know if  it works.
