### ISSUE TITLE
[BUG/ISSUE] (Enter your description here)

### ISSUE THREAD

**Issue by MadCabbit** [martinet101/ElevenClock#836]
## Describe the bug
Day of the week in mouseover is not displayed correctly.  First and second character are not spaced properly and are jumbled together.  I seem to recall this going away and coming back repeatedly over the course of the months I've used ElevenClock. 

## To Reproduce
Steps to reproduce the behaviour:
Mouse over the date and time on the second monitor.

## Expected behaviour
Font should be spaced properly like on mouseover of primary monitor's date and time.

## Screenshots
![image](https://user-images.githubusercontent.com/2042561/179815789-8e31b237-852b-46dc-9b1a-77002eff886f.png)

## The Log

It took 0.0 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.6.4 (v3.64) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 2560, 1440)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(2356, 1394, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (0, 0, 2560, 1440)
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 Initializing clock 1...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(-1920, 357, 1920, 1080)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(-204, 1391, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: M/d/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M %p
%#m/%#d/%Y
🔵 Full screen rect:  (-1920, 357, 0, 1437)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟢 Loaded clocks in 0.7070000171661377
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Restart loop: 1
None
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.4620039463043213
🟢 Green lignt to rease temp dirs
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Showing tooltip
🔵 Long date string: dddd, MMMM d, yyyy
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://upload.wikimedia.org/wikipedia/commons/d/db/Google_Translate_Icon.png
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🟡 Fullscreen window detected! (0, 0, 2560, 1440) Fullscreen rect: (0, 0, 2560, 1440)
🔵 Copying log to the clipboard...

**Comment by martinet101** [comment]
Please read the known issues in the wiki.
