### ISSUE TITLE
[BUG/ISSUE] I try to install elevenclock in microsoft store but...

### ISSUE THREAD

**Issue by MatiLol251** [martinet101/ElevenClock#837]
Well... i try to install elevenclock in microsoft store, but it says an error:
"No se pudo instalar la aplicación
Hubo un problema y no pudimos instalar esta aplicación. Espera un poco e inténtalo de nuevo.
Código: 0x8D050004"
</b>

I don't know exactly why the bug is. i uninstalled the legacy edition but nothing different happened.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'Microsoft Store'
2. Click on 'The download Button'
3. See error

## Expected behaviour
I thinked the app uninstalled the legacy edition and installed it's edition

## Screenshots
![image](https://user-images.githubusercontent.com/106706551/179840291-867462c9-bfe9-469e-b113-ee7424d97553.png)

## The Log
Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🟡 This is the primary screen and is set to be skipped
🟢 Loaded clocks in 1.5050573348999023
🔵 Restart loop: 1
None
None
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 3.2616450786590576
🟢 Green lignt to rease temp dirs
🔴 Traceback (most recent call last):

🔴   File ".\tools.py", line 248, in clearTmpDir

🔴   File "shutil.py", line 749, in rmtree

🔴   File "shutil.py", line 619, in _rmtree_unsafe

🔴   File "shutil.py", line 617, in _rmtree_unsafe

🔴 PermissionError: [WinError 5] Acceso denegado: 'C:\\Users\\Matias\\AppData\\Local\\Temp\\_MEI155802\\libcrypto-1_1.dll'

🔴 Note this traceback was caught by reporter and has been added to the log ([WinError 5] Acceso denegado: 'C:\\Users\\Matias\\AppData\\Local\\Temp\\_MEI155802\\libcrypto-1_1.dll')
🔵 (worldtimeapi.org) Time offset set to 1.4967265129089355
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Announcement URL: http://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://upload.wikimedia.org/wikipedia/commons/d/db/Google_Translate_Icon.png
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

## 🙂

**Comment by martinet101** [comment]
The microsoft store version and the legacy version are actually the same, so no need to install ms store version.

About the error, something happened and it won't install anywhere. I'm trying to get this fixed, i just need to wait for MS to validate my new submission
