### ISSUE TITLE
[BUG] Issue with clock on second screen if both screens doesn't have same resolution

### ISSUE THREAD

**Issue by tygore587** [martinet101/ElevenClock#84]
**Describe the bug**
I use a 4k display with 125% scaling and a 2k second screen with 100% scaling. I configured the second screen to be in the middle of the main screen (see screenshot 2). The problem is, the clock will move to the place, where the second display ends in the settings.

**To Reproduce**
1. Go to settings -> display (don't know what is called in english)
2. Move second display to another position other than the first display
3. Apply settings
4. The clock should move to another position

**Expected behavior**
Clock should stay in the bottom in taskbar

**Screenshots**
![image](https://user-images.githubusercontent.com/12038641/137023847-e31f850d-ffcb-44e1-9661-ace7451df36b.png)

![image](https://user-images.githubusercontent.com/12038641/137024045-1b6bd942-c4d2-4b4e-b517-15144eb4d0aa.png)

**Comment by martinet101** [comment]
Then closing
