### ISSUE TITLE
[BUG/ISSUE] (ElevenClock does not hide the default clock)

### ISSUE THREAD

**Issue by Dhyfer1** [martinet101/ElevenClock#843]
</b>

## Describe the bug
When I activate the option "Show the clock at the left of the screen", the main clock on the right side of the taskbar is still visible.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'ElevenClock Settings'
2. Scroll down to 'Clock position and size' section
3. Click on 'Show the clock at the left of the screen' 

## Expected behaviour
I was expecting the main clock to be hidden when the ElevenClock clock is placed on the left side of the taskbar

## Screenshots
![image_1](https://user-images.githubusercontent.com/50301201/180627007-481f2f24-abc3-4b86-8b41-a2e2454acd9c.png)

## The Log

It took 0.054601430892944336 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.6.4 (v3.64) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1366, 768)
🟢 Clock on the bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(4, 722, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🔵 Restart loop: 1
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟣 Expected AttributeError on backgroundLoop thread
can't parse ""
🟢 Loaded clocks in 114.46285033226013
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟢 Cached text input host hwnd: 131522
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
None
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🟣 Expected AttributeError on backgroundLoop thread
🔵 System tray icon enabled
🔵 Starting update check
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 148.82485365867615
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🔵 Starting update check
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2922, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 308: Permanent Redirect)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟡 Closing clock on {'Monitor': (0, 0, 1366, 768), 'Work': (0, 0, 1366, 720), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1366, 768)
🟢 Clock on the bottom
🟢 Clock on the right
🔵 Restart loop: 1
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1162, 722, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟢 Cached text input host hwnd: 131522
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟡 Closing clock on {'Monitor': (0, 0, 1366, 768), 'Work': (0, 0, 1366, 720), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1366, 768)
🟢 Clock on the bottom
🔵 Restart loop: 1
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(4, 722, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟢 Cached text input host hwnd: 131522
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟡 Closing clock on {'Monitor': (0, 0, 1366, 768), 'Work': (0, 0, 1366, 720), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1366, 768)
🟢 Clock on the bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(4, 722, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🔵 Restart loop: 1
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟢 Cached text input host hwnd: 131522
🔵 Showing tooltip
🔵 Long date string: dddd, d 'de' MMMM 'de' yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d 'de' MMMM 'de' yyyy
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟡 Closing clock on {'Monitor': (0, 0, 1366, 768), 'Work': (0, 0, 1366, 720), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1366, 768)
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1162, 722, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🔵 Restart loop: 1
🟢 Cached text input host hwnd: 131522
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟡 Closing clock on {'Monitor': (0, 0, 1366, 768), 'Work': (0, 0, 1366, 720), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1366, 768)
🔵 Restart loop: 1
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(1162, 722, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟢 Cached text input host hwnd: 131522
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2922, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 308: Permanent Redirect)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟡 Closing clock on {'Monitor': (0, 0, 1366, 768), 'Work': (0, 0, 1366, 720), 'Flags': 1, 'Device': '\\\\.\\DISPLAY1'}
🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🔵 Monitor geometry: PySide2.QtCore.QRect(0, 0, 1366, 768)
🟢 Clock on the bottom
🟡 Clock on the left
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide2.QtCore.QRect(4, 722, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: -1.0
🟢 Using white text (dark mode)
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🔵 Full screen rect:  (0, 0, 1366, 768)
🔵 Restart loop: 1
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🔵 tDateMode: d/MM/yyyy
🔵 tTimeMode: h:mm tt
🔵 Loaded date time format: %#I:%M:%S  %p
%#d/%m/%Y
🟢 Cached text input host hwnd: 131522
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🔵 Showing tooltip
🔵 Long date string: dddd, d 'de' MMMM 'de' yyyy
🔵 Showing tooltip
🔵 Long date string: dddd, d 'de' MMMM 'de' yyyy
🟡 Fullscreen window detected! (0, 0, 1366, 768) Fullscreen rect: (0, 0, 1366, 768)
🟠 Unable to retrieve latest announcement
🔴 Traceback (most recent call last):

🔴   File ".\settings.py", line 2922, in loadAnnouncements

🔴   File "urllib\request.py", line 216, in urlopen

🔴   File "urllib\request.py", line 525, in open

🔴   File "urllib\request.py", line 634, in http_response

🔴   File "urllib\request.py", line 563, in error

🔴   File "urllib\request.py", line 496, in _call_chain

🔴   File "urllib\request.py", line 643, in http_error_default

🔴 urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

🔴 Note this traceback was caught by reporter and has been added to the log (HTTP Error 308: Permanent Redirect)
🔵 Copying log to the clipboard...
🟢 Log copied to the clipboard successfully!
🔵 Copying log to the clipboard...

## Additional context
I would just like to be able to hide the main clock to place it on the left of the taskbar, as shown in this screen shot

![image_2](https://user-images.githubusercontent.com/50301201/180627134-c1dc56a7-1f3a-40bc-bb8f-ad608e4e0b05.png)

**Comment by panther7** [comment]
I think, that this issue is the feature, because ElevenClock is new layer with custom clock and default Windows clock can not be "hide" or "moved".

**Comment by Dhyfer1** [comment]
> I think, that this issue is the feature, because ElevenClock is new layer with custom clock and default Windows clock can not be "hide" or "moved".
> 
True, it is a feature of ElevenClock, only ElevenClock does not replace the main clock, it just hides it under its layer. Also the main clock can be hidden, but not the date.

**Comment by martinet101** [comment]
> Screenshot is probably from secondary monitor.

So true, I forgot about that

**Comment by martinet101** [comment]
I'll update the screenshots asap, and apologizes for the confusion

**Comment by martinet101** [comment]
Although now I am thinking that a clock that hid (kind of) the defailkt clock could be an option. It would be just using the same overlay elevenclock uses now but without text on it

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/182189924-7a70ba49-34fa-4ef4-afdf-b391bb3e80e7.png)


It does now.

The fix will be released in the next version

**Comment by Dhyfer1** [comment]
> Although now I am thinking that a clock that hid (kind of) the defailkt clock could be an option. It would be just using the same overlay elevenclock uses now but without text on it

It seems to be a good idea. That means that in the next version Elevenclock could add one more layer to the taskbar to hide the main clock? Sounds good.

I hope the next version comes soon

**Comment by martinet101** [comment]
Check out version 3.7.0!
