### ISSUE TITLE
时钟区闪烁

### ISSUE THREAD

**Issue by Duguwochou** [martinet101/ElevenClock#848]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ *] **I have checked that I am running the latest version of ElevenClock**
- [* ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
当鼠标放在任务栏图标上时，时钟闪烁。我使用的是Windows11 Dev 25163版。
## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Please post in english so we all can understand

**Comment by Kira-Lappo** [comment]
The clock blinks when the mouse is over the taskbar icon. I am using Windows11 Dev version 25163
(c) Google Translate

**Comment by martinet101** [comment]
Hi @Kira-Lappo, I appreciate that you translated it, but translating is not the point. This is a community that includes people around the globe, and if everyone had to translate everyother messages this would be a mess. Being the case that this person does not know how to speak english (which is not a problem, I am actually in process of learning it), if you know how to use github you know how to use google translate. 

I'm sorry, but this thread should continue in english.

**Comment by mozushixin** [comment]
@martinet101 Maybe he didn't kwon how to accurately translate this issue

**Comment by martinet101** [comment]
OK.

@Duguwochou, could you please provide more details?

When did this start, how does it happen, etc.?
