### ISSUE TITLE
[BUG] Netflix fullscreen doesnt remove clock

### ISSUE THREAD

**Issue by tygore587** [martinet101/ElevenClock#85]
**Describe the bug**
If I go full screen on netflix, the clock isn't hiding.

**To Reproduce**
1. Go to netflix
2. Start a video
3. Go to fullscreen

**Expected behavior**
Clock will hide on fullscreen

**Screenshots**
![image](https://user-images.githubusercontent.com/12038641/137028144-4d3128cb-8eb9-405d-96cd-57cc39b70003.png)

**Comment by aisgbnok** [comment]
Same issue with YouTube. 

![image](https://user-images.githubusercontent.com/10838153/137052418-43558959-7013-4333-a5f5-f004c21bfea0.png)

**Comment by martinet101** [comment]
Because v2 gave a improvement to fullscreen support
