### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by aholzinger** [martinet101/ElevenClock#850]
Error message is (German version):
Ankündigungen konnten nicht geladen werden. Bitte versuche es später erneut
HTTP Error 308: Permanent Redirect

Remains the same since update to 3.6.4

**Comment by ShintakuNobuhiro** [comment]
This is a duplicate of the following items.
https://github.com/martinet101/ElevenClock/issues/847#issue-1320323982

**Comment by martinet101** [comment]
Dupe
