### ISSUE TITLE
The new feature that hides to computer's clock makes the ElevenClock blink rapidly nonstop. Turning the new feature off fixes the problem.

### ISSUE THREAD

**Issue by Barbarossa1974** [martinet101/ElevenClock#853]
## Before submitting the issue

- [ ] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ ] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ ] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Ok

**Comment by martinet101** [comment]
Can you please send your log?

**Comment by Barbarossa1974** [comment]
How do I do that?

-----Original Message-----

**Comment by prom00** [comment]
I've had the same issue:
![image](https://user-images.githubusercontent.com/46184489/182303333-d467ca98-ac0f-4f8c-b93f-6ba91136f536.png)


I'm running a single (wide) monitor where I want the clock left and right in the task bar.
The right is original Windows so I can open de calendar.
Left is ElevenClock

Now I get this on the right:
![image](https://user-images.githubusercontent.com/46184489/182303559-79f0bfb5-bbef-4462-8f77-d5b4c49c32af.png)


Toggling this activates the clock again:
![image](https://user-images.githubusercontent.com/46184489/182303480-99043d17-b3a6-4c65-a811-c14965ed5859.png)

I think it would be better to keep the original functionality, as everyone might already be using it that way. If you want to hide it in the original position, then let the user enable that?

**Comment by martinet101** [comment]
> I've had the same issue: ![image](https://user-images.githubusercontent.com/46184489/182303333-d467ca98-ac0f-4f8c-b93f-6ba91136f536.png)
> 
> I'm running a single (wide) monitor where I want the clock left and right in the task bar. The right is original Windows so I can open de calendar. Left is ElevenClock
> 
> Now I get this on the right: ![image](https://user-images.githubusercontent.com/46184489/182303559-79f0bfb5-bbef-4462-8f77-d5b4c49c32af.png)
> 
> Toggling this activates the clock again: ![image](https://user-images.githubusercontent.com/46184489/182303480-99043d17-b3a6-4c65-a811-c14965ed5859.png)
> 
> I think it would be better to keep the original functionality, as everyone might already be using it that way. If you want to hide it in the original position, then let the user enable that?
> 
> Logs

Maybe yes, it would be better

**Comment by Skyyblaze** [comment]
I have the same issue, if I can help anyhow to resolve this let me know. I'm running Windows 11 Build 22621.232 and also run the customization tool RoundedTB and TranslucentTB.

**Comment by prom00** [comment]
> I have the same issue, if I can help anyhow to resolve this let me know. I'm running Windows 11 Build 22621.232 and also run the customization tool RoundedTB and TranslucentTB.

Have you tried the 'Disable hiding the default windows clock'?

**Comment by Dhyfer1** [comment]
> I have the same issue, if I can help anyhow to resolve this let me know. I'm running Windows 11 Build 22621.232 and also run the customization tool RoundedTB and TranslucentTB.

![image_1](https://user-images.githubusercontent.com/50301201/182366849-14964ac4-9108-4659-8a39-0f148071caec.png)

In my case it works fine. I also use roundedtb and translucenttb (the blur effect with translucenttb is not applied well). Back to the topic and as you can see in the image Elevenclock hides well my main clock and leaves it on the left, but if you could just remove the empty space left by the main clock, let the other icons (volume, wifi etc ) move automatically to the right to occupy that empty space would be fine.

It is a pity that Microsoft has removed the registry key that served to hide the date and time and that only works in Windows 10.

**Comment by Skyyblaze** [comment]
> > I have the same issue, if I can help anyhow to resolve this let me know. I'm running Windows 11 Build 22621.232 and also run the customization tool RoundedTB and TranslucentTB.
> 
> Have you tried the 'Disable hiding the default windows clock'?

Yeah that fixes the issue of course but ideally I would like to see the new feature working properly.



> > I have the same issue, if I can help anyhow to resolve this let me know. I'm running Windows 11 Build 22621.232 and also run the customization tool RoundedTB and TranslucentTB.
> 
> ![image_1](https://user-images.githubusercontent.com/50301201/182366849-14964ac4-9108-4659-8a39-0f148071caec.png)
> 
> In my case it works fine. I also use roundedtb and translucenttb (the blur effect with translucenttb is not applied well). Back to the topic and as you can see in the image Elevenclock hides well my main clock and leaves it on the left, but if you could just remove the empty space left by the main clock, let the other icons (volume, wifi etc ) move automatically to the right to occupy that empty space would be fine.
> 
> It is a pity that Microsoft has removed the registry key that served to hide the date and time and that only works in Windows 10.

Hmm alright interesting, I wonder what causes it for some then and not for other people.

**Comment by martinet101** [comment]
> Yeah that fixes the issue of course but ideally I would like to see the new feature working properly.
> 
> > >

Of course this behaviour will be fixed



> , let the other icons (volume, wifi etc ) move automatically to the right to occupy that empty space would be fine.

I'm sorry, but this is impossible. The clock is actuallt there, but it has been covered with a tinted window so it can't be seen

**Comment by Dhyfer1** [comment]
> I'm sorry, but this is impossible. The clock is actuallt there, but it has been covered with a tinted window so it can't be seen

I understand, I know you can't do anything about it. This is Microsoft's problem for removing many useful features from the taskbar that are in Windows 10 and are no longer in Win 11, anyway thanks for the update.

Now I'm seeing how to have the clock on the right and the date on the left, and that both are centered.

**Comment by martinet101** [comment]
Fixed, the issue should now no longer happen
