### ISSUE TITLE
Area where clock was moved from has a blanking patch over it.

### ISSUE THREAD

**Issue by DO1955** [martinet101/ElevenClock#859]
I have moved the taskbar to the top of the primary screen. I am using ElevenClock to put a Clock on the lower right corner of each screen. I turned off Windows Eleven Clock.

## Describe the bug:

Issue appeared with 3.7.0. The location on the upper right corner of the screen where ElevenClock wants to put the Clock (this is the right end of the taskbar on the primary screen) is replaced with a grey rectangle when the clock is moved to the bottom corner. This square covers over the window sizing buttons of the windows on the screens that do not have a taskbar.

## Expected behaviour:

I have the taskbar on the top of the primary screen which is in the lower left since it is most easily accessible from all screens. I move the clocks to the lower corner so I can access the window sizing buttons.

## Screenshots
![image](https://user-images.githubusercontent.com/110496246/182471683-8ff25602-5781-428c-9861-7b4b10d28f44.png)

## The Log:

[ElevenClock log.txt](https://github.com/martinet101/ElevenClock/files/9245559/ElevenClock.log.txt)

Thanks!

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/182473801-f2f5fb63-8feb-45e8-84be-83542ebe68c9.png)


Follow the instructions on the announcement. 

The issue is being discussed in #853
