### ISSUE TITLE
[BUG/ISSUE] Left Click and Double Click Always Shows Calendar

### ISSUE THREAD

**Issue by wilburlikesmith** [martinet101/ElevenClock#865]
Settings doesn't save. Wait double checked, so left click doesn't change it always shows Calendar even if double click, it briefly shows calendar before Desktop or opening Task Manager.

**Comment by da-KITT** [comment]
My installation won't allow me to set the calender to open on single oder double-click. It always opens a new quick note no matther what I set.

**Comment by martinet101** [comment]
@da-KITT ,have you set win+n to your notes quick shortcut?

**Comment by da-KITT** [comment]
apparently, yes

**Comment by martinet101** [comment]
Then that's the cause. The notifications pane is invoked via the Win+N shortcut

**Comment by martinet101** [comment]
@wilburlikesmith , can you please change those settings two or three times and then send me your log?

**Comment by da-KITT** [comment]
> Then that's the cause. The notifications pane is invoked via the Win+N shortcut

hmm, I cannot find the setting though. It should be win + alt + N for a new quick note, not just win + N ...

**Comment by martinet101** [comment]
I'm sorry @da-KITT, but i can't help much here. You can try resetting your notes app preferences, but this issue is not related with ElevenClock.

**Comment by wilburlikesmith** [comment]
> 

Not sure if you found it, but perhaps you used PowerToys?

**Comment by wilburlikesmith** [comment]
> @wilburlikesmith , can you please change those settings two or three times and then send me your log?

Hi, so sorry for belated reply. I've probably since then reinstalled my Windows probably twice... It seems to work, although there's a myriad of other issues depending on how you look at it or how / when it's caused. I think if that 10 secs disappear settings is on, then clicking or double click the clock does the old actions, which makes sense as the new one is hidden. From user experience it's either confusing or at the least jarring. 

Then there's a display issue, where miraculously your 022 sits snug next to my 2 of the 2022/12/14. Which is ok unless I change my date format to include more stuff then it actually overlaps my system tray icons like battery and volume...

**Comment by martinet101** [comment]
> Then there's a display issue, where miraculously your 022 sits snug next to my 2 of the 2022/12/14. Which is ok unless I change my date format to include more stuff then it actually overlaps my system tray icons like battery and volume...

This can't t be fixed, you can see the known issues list on the wiki for more info

**Comment by martinet101** [comment]
For the issue above, please see #1062
