### ISSUE TITLE
[BUG] Bug page is pointing to latest release 3.4.0, but It's actually 3.7.1 causing this crash report...

### ISSUE THREAD

**Issue by saetre** [martinet101/ElevenClock#866]
https://www.somepythonthings.tk/error-report/?appName=ElevenClock&errorBody={s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}OS:{s}Windows{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Version:{s}(%2710%27,{s}%2710.0.22000%27,{s}%27SP0%27,{s}%27Multiprocessor{s}Free%27){l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}OS{s}Architecture:{s}AMD64{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Architecture:{s}64bit{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Version:{s}3.7.1{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}APP{s}Version{s}Code:{s}3.71{l}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}{s}Program:{s}ElevenClock{l}{l}-----------------------------------------------------------------------------------------{l}{l}{l}{l}ElevenClock%20Log:{l}{l}{l}{l}{l}Traceback{s}(most{s}recent{s}call{s}last):{l}{s}{s}File{s}%22\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py%22,{s}line{s}38,{s}in{s}%3Cmodule%3E{l}{l}ModuleNotFoundError:{s}No{s}module{s}named{s}%27PySide2.QtGui%27%3Cclass{s}%27ModuleNotFoundError%27%3E:{s}No{s}module{s}named{s}%27PySide2.QtGui%27

## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [x] **I have checked that I am running the latest version of ElevenClock**
- [ ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ ] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

**Comment by martinet101** [comment]
Fixed!
