### ISSUE TITLE
New clock doesn't share the same look as native clock.

### ISSUE THREAD

**Issue by B-Wilhelm** [martinet101/ElevenClock#87]
I've noticed that the clock on my second monitor looks thicker (potentially blurrier? or bold?) than it should, or at least is thicker than it looks when I set the monitor to my main for windows to draw a clock natively.

Clock drawn Natively:
![image](https://user-images.githubusercontent.com/12756875/137035665-06c314f2-93e4-4fde-912b-9589bae7ac14.png)

Clock drawn by ElevenClock:
![image](https://user-images.githubusercontent.com/12756875/137035119-76d82b37-e671-4dbb-a6ae-947385a43bc5.png)

I'm not sure if this is intended, if additional information is helpful here I'm using a Primary monitor @ 2560x1440 and this secondary monitor @ 1920x1080.

Ideally I would like to be able to make them both look the same for consistency's sake.

**Comment by martinet101** [comment]
Duplicate. Check out closed issues, there's one explaining the reason of this (clock is fuzzy)
