### ISSUE TITLE
[FEATURE REQUEST] Please create a function that ignores mouse clicks.

### ISSUE THREAD

**Issue by godnao** [martinet101/ElevenClock#871]
**Is your feature request related to a problem? Please describe.**
If you click on the clock while playing the game, you lose control of the game.

**Describe the solution you'd like**
Please create a function to ignore mouse clicks.
ex) ontopreplica.exe -> click-through

**Comment by martinet101** [comment]
That might be a good thing to do, though itmight also be difficult

**Comment by Farkie** [comment]
I don't think it should be in front of the game; rather than adding a feature to ignore mouse clicks. I've seen it myself and it's been infuriating being mid-game and clicking it, and it is losing focus of the game.

**Comment by martinet101** [comment]
> I don't think it should be in front of the game

You can hide ElevenClock when an app goes fullscreen

**Comment by Farkie** [comment]
> > I don't think it should be in front of the game
> 
> You can hide ElevenClock when an app goes fullscreen

Yea that's set but sometimes it doesn't hide. I think I had to fullscreen back and forth to get it to work properly. This might be a separate issue, it just felt related.

**Comment by martinet101** [comment]
Done!
