### ISSUE TITLE
[FEATURE REQUEST] Translatable announcements

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#872]
![2022-08-17 11 22 36](https://user-images.githubusercontent.com/3808250/185099344-5395b8ce-70d5-4e74-a1b7-a4a3f766b880.png)

Actual url: https://www.somepythonthings.tk/resources/elevenclock.announcement

```
New url: https://www.somepythonthings.tk/resources/elevenclock.announcement?lang=<lang>
Example: https://www.somepythonthings.tk/resources/elevenclock.announcement?lang=cs
Default: lang=en
```

BE (on https://www.somepythonthings.tk) with cron to downloads from https://app.tolgee.io/projects/688 (like `download_translations.py`).

**Comment by martinet101** [comment]
I'm not sure if it could work with URL params, but some kind of translation should be possible. I'll take a look

**Comment by martinet101** [comment]
This will come with #929

**Comment by martinet101** [comment]
Done!

**Comment by panther7** [comment]
Good job, but i think, thats "block" as `<p>` and `</p>` over two strings are potencialy brokable (if translator did some wrong - missing).

Link as ´linkId?translate´ is potenciale hackable (like custom link).

**Comment by panther7** [comment]
Better HTML is:
```html
<h1>
We are searching for translators
</h1>
<p>
The latest version of ElevenClock has now been downloaded 50k times.
<br>
This is why we want you to help us translating ElevenClock. Before, it was a complicated process, but now it has been simplified<br>and can be done without any programming knowledge. More info on how to become a translator <a style="color:linkColor" href="linkId?translate">HERE</a>
</p>////https://upload.wikimedia.org/wikipedia/commons/d/db/Google_Translate_Icon.png
```

Translatable strings:
```
* We are searching for translators
* The latest version of ElevenClock has now been downloaded 50k times.
* This is why we want you to help us translating ElevenClock. Before, it was a complicated process, but now it has been simplified<br>and can be done without any programming knowledge. More info on how to become a translator <a style="color:linkColor" href="linkId?translate">HERE</a>
```

**Comment by martinet101** [comment]
> linkId?translate

Nope, because any url will be invalidated by the funcion that loads the announcements. 

1. The http(s) urls are invalidated
2. The linkId?translate are converted to the proper url

**Comment by martinet101** [comment]
> Better HTML is:
> 
> ```
> <h1>
> We are searching for translators
> </h1>
> <p>
> The latest version of ElevenClock has now been downloaded 50k times.
> <br>
> This is why we want you to help us translating ElevenClock. Before, it was a complicated process, but now it has been simplified<br>and can be done without any programming knowledge. More info on how to become a translator <a style="color:linkColor" href="linkId?translate">HERE</a>
> </p>////https://upload.wikimedia.org/wikipedia/commons/d/db/Google_Translate_Icon.png
> ```
> 
> Translatable strings:
> 
> ```
> * We are searching for translators
> * The latest version of ElevenClock has now been downloaded 50k times.
> * This is why we want you to help us translating ElevenClock. Before, it was a complicated process, but now it has been simplified and can be done without any programming knowledge. More info on how to become a translator <a style="color:linkColor" href="linkId?translate">HERE</a>
> ```

This is consequence of the old announcement file that was not intended to be split in lines, and will be fixed in a future
