### ISSUE TITLE
[BUG/ISSUE] Change VPN-Time/ Local Time after first Setup 

### ISSUE THREAD

**Issue by Mirko1984** [martinet101/ElevenClock#875]
I recently installed ElevenClock on my Windows 11. At the very first setup the app was asking me if I wanna use VPN-Time or the time on my local machine and I set it wrong. Now ElevenClock is showing me VPN-Server Time although I`d like to see local time. 

I already uninstalled ElevenClock completely and reinstalled it but the dialog just doesn`t show up anymore :( I`m not sure if I missed to delete something after deinstallation so it could show up again or if I can somehow change it any other way?

Help is highly appreciated, thank you so much for the tool!

**Comment by martinet101** [comment]
Hi @Mirko1984, you can still open ElevenClock Settings -> internet time and date -> enable/disable internet time sync.

Additionally, you can specify a fixed url to get your location's date and time.
