### ISSUE TITLE
[FEATURE REQUEST] Brief description

### ISSUE THREAD

**Issue by RogYaeger** [martinet101/ElevenClock#876]
Not sure if a bug / or a feature request...

Installed ElevenClock today, on Windows 11, current and up to date. 

I have changed the time format to HH:mm:ss, and the font to "Comic Sans", and the font to 10pt, and keeping the date otherwise unchanged. When these changes are made, the "block" that the date/time uses now covers the "ICON" area to the left, partially covering the "Sound" icon. Larger fonts will also cover the "Network" icon too. 

Is there a fix to the problem? 

Thank you,
![ElevenClock Problem 01](https://user-images.githubusercontent.com/111669349/185773152-d7e8daf3-8ae7-4cff-9889-8670cddbcbb7.png)

Roger Yaeger

**Comment by martinet101** [comment]
Hi,

You can specify a specific clock horizontal position from the settings window

![image](https://user-images.githubusercontent.com/53119851/185803286-f73f6af4-fbf6-445b-9d0a-dc926b187df9.png)
