### ISSUE TITLE
[ISSUE] Some text is displayed in English instead of Japanese

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [martinet101/ElevenClock#892]
## Describe the bug
Custom formatting rule descriptions are not translated correctly in Japanese viewing environments.
A long time ago I used Tolgee to do some Japanese translation work.

## To Reproduce
Steps to reproduce the behaviour:
1. Go to 'ElevenClock Settings'
2. Click on 'Date & Time Settings'
3. Check on 'Set a custom date and time format'
4. See issue

## Expected behaviour
It should be displayed as "ここには任意のテキストを配置できます。日付や時刻などを配置するには、1989 C Standard の形式を使用してください。詳細は次のリンクをご参照ください", just like the translated text in Tolgee.

## Screenshots
![image](https://user-images.githubusercontent.com/11265280/187851425-b161cdfd-2149-4e7c-9578-5fd11b488d49.png)

**Comment by martinet101** [comment]
Mhmm, I see. It appears as translated, there might be some issue with the key.

**Comment by martinet101** [comment]
Fixed!

**Comment by ShintakuNobuhiro** [comment]
Not fixed in version 3.7.3.

**Comment by martinet101** [comment]
True, the translations must have got overriden by something...

Because I swear i also faced this issue, i fixed it and it worked for me and now it fails again...

**Comment by martinet101** [comment]
Fixed!

**Comment by ShintakuNobuhiro** [comment]
Confirmed fixed. Thank you very much.
