### ISSUE TITLE
Crowdstrike MaliciousNetworkActivity detection.

### ISSUE THREAD

**Issue by Jagsta2121** [martinet101/ElevenClock#893]
\Device\HarddiskVolume5\Users\johnathan\AppData\Local\Programs\ElevenClock\ElevenClock.exe

A process engaged in network activity with a remote destination known for malicious activity. Investigate events around the remote connection.

**Comment by martinet101** [comment]
Can you please share the URL where ElevenClock is connecting to?
There are three possibilities:
 - http://www.somepythonthings.tk/versions/elevenclock.ver (alternative update server)
 - https://versions.somepythonthings.tk/versions/elevenclock.ver (main update server)
 - https://www.somepythonthings.tk/resources/elevenclock.annoucement (announcements repo).

It should not connect anywhere else

**Comment by martinet101** [comment]
Please note that .tk domains are generally flagged as insecure because anyone can register one of them, and they have been used for malicious activities iun the past.

**Comment by Jagsta2121** [comment]
Destination IP: 34.149.204.188

DNS Request: versions.somepythonthings.tk

**Comment by Masamune3210** [comment]
Sounds like Crowdstrike is just being a bit overjumpy then
