### ISSUE TITLE
Correction Date

### ISSUE THREAD

**Issue by 171252** [martinet101/ElevenClock#894]
Hello,
would it be possible to integrate a space between the month and the year and ideally also between the day and the month - thank you very much!

**Comment by martinet101** [comment]
Yes!

You will need to specify a custom date and time format:

![image](https://user-images.githubusercontent.com/53119851/188153523-f6c124cb-739e-42ca-914e-b8c19b86ef77.png)

You can find a cheatsheet here: https://strftime.org/
