### ISSUE TITLE
[BUG] ElevenClock pinned my CPU usage at 100%

### ISSUE THREAD

**Issue by BluePlastics** [martinet101/ElevenClock#90]
**Describe the bug**
Was playing Final Fantasy 14, had Discord, and Steam running, and suddenly my computer started to respond slowly, at first I thought it was Steam downloading something, but after closing steam, the lag continued! Opened task manager and saw ElevenClock at the top of CPU usage at 100%, closed it and everything returned to normal.

**To Reproduce**
I guess run FFXIV, Steam, and Discord at the same time?

**Expected behavior**
ElevenClock NOT pinning my CPU at 100%?

**Screenshots**
Didn't grab any screenshots at the time, was too busy getting ready for a raid.

**Comment by martinet101** [comment]
Duplicate
