### ISSUE TITLE
Time not correct

### ISSUE THREAD

**Issue by Dturner618** [martinet101/ElevenClock#904]
Updated to latest version and found that Eleven Clock time is 1 hour off. I have tried syncing with different time servers, checked the setting on my PC which are correct time zone etc. Rebooted, restarted app. Will not sync time correctly always showing 1 hour earlier than it is.

**Comment by martinet101** [comment]
Could your issue be related to #894?

**Comment by Dturner618** [comment]
Hi,

 

Thank you for the response. Whatever the issue it seems to have resolved. Not sure what actually fixed it but it is working again.

Thanks!
