### ISSUE TITLE
[BUG] Seconds are display after AM/PM

### ISSUE THREAD

**Issue by vulpasin** [martinet101/ElevenClock#91]
**Describe the bug**
Seconds are display after AM/PM

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Show seconds on the clock'
3. Restart

The clock will show "7:30 AM:30"
![image](https://user-images.githubusercontent.com/17246066/137067528-ac6857d2-83cd-4e98-aa03-1d890de696e0.png)

**Comment by martinet101** [comment]
Duplicate
