### ISSUE TITLE
[BUG/ISSUE] ElevenClock not showing

### ISSUE THREAD

**Issue by DrMicahStone** [martinet101/ElevenClock#927]
## Before submitting the issue

- [ x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [ x] **I have checked that this issue is not present in the [Known Issues](https://github.com/martinet101/ElevenClock/wiki#known-issues) section on the wiki.**
- [ x] **I have checked that I am running the latest version of ElevenClock**
- [x ] **I have tried resetting and reinstalling ElevenClock and the issue persisted or happened again**
- [ x] **I have checked the [Common Problems](https://github.com/martinet101/ElevenClock/wiki#common-problems) section on the wiki for solutions**

</b>

## Describe the bug
When Win11 updates, particularly ,Net updates, ElevenClock no longer displays the clock on the task bar, but the icon for EC does display and all it's functions work.
In the past when that happened, I had to uninstall EC, find an old 2.x version, install that and let it up date to the current version.  But even that no longer works to get EC clock on the Task Bar

# To Reproduce
Steps to reproduce the behaviour:

## The Log

```
Please paste here the log (Go to ElevenClock Settings -> Scroll to the bottom -> Open ElevenClock Log. 

If the issue can be reproduced (As an example: After waiting 5 minutes, the clock shows a wrong format), please 
send the log AFTER reproducing the issue (1. Launch ElevenClock, 2. Reproduce the issue, 3. Paste the log)
```

## Additional context
[ELEVENCLOCK-LOG.txt](https://github.com/martinet101/ElevenClock/files/9578905/ELEVENCLOCK-LOG.txt)

**Comment by DrMicahStone** [comment]
I also tied quitting ElevenClock - making certain it is no longer listed in Task Manager - then tried to delete the .elevenclock folder in my user profile. It would NOT delete because it's "open in another program" ???!!!

**Comment by martinet101** [comment]
Hi, 

I don't know why it says the folder is opened, because it shouldn't. 

To make sure that ElevenClock is killed and is not running as a second-plane process please run this in the task manager: `taskkill /im elevenclock.exe /f`. 

Then, delete the .ElevenClock folder and empty the %temp% folder also. 

Finally install version 3.8.X. 

Does this work?

**Comment by DrMicahStone** [comment]
Marti,
I quit EC from the task icon then ran the taskkill command from an admin cmd prompt. The .elevenclock folder could then be deleted. (NOTE: even though the folder was  "running" in another process, it's contents could still be deleted.)   I installed the current 3.8.2 version and the clock did appear on the task bar.
I'll see if it still works after the next windows 11 update with a .NET update !!!
Many thanks for your work on ElevenClock.  Those thousands (millions?) of us who were used to the AtomicAlarmClock TrayClock on previous windows versions really needed something for Win 11--and you have  great solution !
 
 
DrMicahStone
***@***.***
 
 
-----Original Message-----

**Comment by martinet101** [comment]
Let's see if it works then!

**Comment by martinet101** [comment]
Has this issue been solved?
