### ISSUE TITLE
FullScreen display error

### ISSUE THREAD

**Issue by mozushixin** [martinet101/ElevenClock#933]
![image](https://user-images.githubusercontent.com/49932627/190944816-8d6897df-cbd0-41fc-824d-cbde7ec22044.png)
It's displaying toTop when i play video with fullscreen.

**Comment by martinet101** [comment]
Do you have hide on full-screen enabled in the settings window?

**Comment by mozushixin** [comment]
> Do you have hide on full-screen enabled in the settings window?

yeah
![image](https://user-images.githubusercontent.com/49932627/191399336-cf5bb5c2-614f-4af9-8665-c04e9e53bb3d.png)

**Comment by mozushixin** [comment]
> Do you have hide on full-screen enabled in the settings window?

I  play video with cmd of ffmpeg.

**Comment by martinet101** [comment]
Can you please share your log? (Debugging info -> open log)

Also, what happens if you run ffmpeg with the `-window_title` argument?

**Comment by mozushixin** [comment]
> Can you please share your log? (Debugging info -> open log)
> 
> Also, what happens if you run ffmpeg with the `-window_title` argument?

Now it works fine when I  restart system.
Yesterday I only enable it.
