### ISSUE TITLE
[FEATURE REQUEST]Always on top on one monitor, while on the other to hide

### ISSUE THREAD

**Issue by res88ro** [martinet101/ElevenClock#941]
Hi, i just found out this clock and its amazing, i wasn't to make it be always on top on my secondary monitor, while in my primary monitor to make it disappear when something is fullscreen

I ask for this cause one monitor is for work/browsing while the other is for gaming/videos

Is something like this possible?

**Comment by martinet101** [comment]
For the moment it is not quite possible. 

However, in the next updates there will be the ability to add a second clock to every display, and if in your secondary displays you
1. Set your 2nd clocks to hide on fs
2. Set them to not sow in 1st mon
3. Set primary clock to not show in the sec monitors

It should work for you

**Comment by martinet101** [comment]
So this issue depends on the extra clocks.

**Comment by res88ro** [comment]
Thank you a lot, i will wait for the updates
