### ISSUE TITLE
[FEATURE REQUEST] Copy the time/date by clicking the clock

### ISSUE THREAD

**Issue by ppvnf** [martinet101/ElevenClock#943]
Hello @martinet101, thanks to your amazing software I am almost migrating definitely to Windows 11. I've some complaints against Micro$oft, but I must admit that a reason I didn't migrate to the new OS is because I am so used to T-Clock Redux in Windows 10. 

I've seen that your app interface is vastly superior and the functionalities that I usually use from T-Clock are pretty similar, except for one: the ability to copy the time/date by clicking the clock.

![Captura de tela 2022-09-22 201821](https://user-images.githubusercontent.com/73800734/191878138-6b31738a-3a31-4afd-a463-29d94a331b75.png)

While in ElevenClock it is possible to select a lot of actions for clicking the clock, it's missing the ability to copy the time and date that I used so much in T-Clock Redux.

![Captura de tela 2022-09-22 223516](https://user-images.githubusercontent.com/73800734/191878148-5abc6c22-ecb4-41a3-9391-887f6c842546.png)

If you add this option, I think it would be useful to allow the selection of time format like in T-Clock Redux.

Of course I am not expecting you to address this issue if you think it is irrelevant for most users. Thanks a lot nonetheless!

**Comment by martinet101** [comment]
Yes, i suppose this could be a thing

**Comment by martinet101** [comment]
Saw your pr, finished the code

**Comment by ppvnf** [comment]
[panther7](https://github.com/panther7) and [martinet101](https://github.com/martinet101), thank you very much!
