### ISSUE TITLE
[BUG/ISSUE] Wrong icon color light scheme

### ISSUE THREAD

**Issue by panther7** [martinet101/ElevenClock#944]
Wrong icon color light scheme.

* Win 11 22H2
* 3.8.2

![2022-09-23 10 43 22](https://user-images.githubusercontent.com/3808250/191923817-d9ecfd2b-ad56-46c8-bec7-0c7f50e16b2e.png)

**Comment by martinet101** [comment]
Does this happen always or it gets fixed with an app restart?

**Comment by panther7** [comment]
Fix after app restart, but not, if app running...

**Comment by martinet101** [comment]
Fixed!
