### ISSUE TITLE
[FEATURE REQUEST] Allow setting line height

### ISSUE THREAD

**Issue by dhilgarth** [martinet101/ElevenClock#949]
**Is your feature request related to a problem? Please describe.**
I would like to display three lines in my clock. Together with an increased font size to easily read it on a big screen, this makes the Clock too high.

**Describe the solution you'd like**
In T-Clock, I was able to set the line height, allowing me to reduce the whitespace between them

**Comment by martinet101** [comment]
I don't know if that can be achieven in Qt, but it is worth giving it a try

**Comment by dhilgarth** [comment]
Thanks for the prompt reply! If I understand the code correctly, you are using QLabel? According to [SO](https://stackoverflow.com/questions/2749612/qlabel-interlinea-linespacing-in-wordwrap-mode), it's only possible when using HTML. But I think you already do that?

**Comment by martinet101** [comment]
Done!
