### ISSUE TITLE
[BUG] The setting menu did not handle hidpi correctly

### ISSUE THREAD

**Issue by mmis1000** [martinet101/ElevenClock#95]
**Describe the bug**
The setting menu crams all together under hidpi

**To Reproduce**
1. Go to windows setting
2. Set display scale to 200%
3. Open the setting menu
4. See the broken setting menu

**Expected behavior**
A normal, usable setting menu.

**Screenshots**
![圖片](https://user-images.githubusercontent.com/2993977/137144629-ece40ff2-99ce-43b6-a4b2-eb185a8e185f.png)

**Additional context**
Windows 11 build 22000
Two 4K screen @ 200% display scale

**Comment by martinet101** [comment]
Duplicate, already fixed and coming with 2.1
