### ISSUE TITLE
[FEATURE REQUEST] Middle-click action

### ISSUE THREAD

**Issue by ppvnf** [martinet101/ElevenClock#958]
**Is your feature request related to a problem? Please describe.**

Currently there are only 2 options of customizable mouse action. A 3rd one would be even better.

**Describe the solution you'd like**

Add the option  "Change the action done when the clock is middle-clicked" below "Change the action done when the clock is double-clicked"

![](https://user-images.githubusercontent.com/73800734/191878138-6b31738a-3a31-4afd-a463-29d94a331b75.png)

**Comment by martinet101** [comment]
This feature has been added and will come with the next release
