### ISSUE TITLE
[FEATURE REQUEST] Ability to centre the clock text and position on the Windows taskbar

### ISSUE THREAD

**Issue by TheFifthHour** [martinet101/ElevenClock#967]
The text is not centred on the taskbar, and on Wednesdays, moved a few pixels to the left. The text would move to the right on Thursdays until the following Wednesday. This meant I had to adjust the horizontal clock position twice a week, which was a bit annoying, possibly given the vertical taskbar.

Hence, the ability to centre the text on the clock itself, which is then centred on the taskbar would be greatly appreciated.

![Screenshot 2022-09-29 000224](https://user-images.githubusercontent.com/65485629/193455304-daf79455-37c7-4e64-b2a9-e92a4beb17a5.png)
![Screenshot 2022-09-28 235245](https://user-images.githubusercontent.com/65485629/193455307-411fc3fe-020f-4285-b4f9-1c791053eda2.png)

**Comment by martinet101** [comment]
This is an issue where qt won't poroperlyt center fonts. My best recommendation is to mess a little with the x/y offset to get this to work

**Comment by martinet101** [comment]
Also, you can disable the notification counter and focus assistant icons from the settings window (though it seems like you already did that)

**Comment by martinet101** [comment]
Did this fix the issue?

**Comment by TheFifthHour** [comment]
1. If that means adjusting the horizontal and vertical clock positions, I've already done that, to my heart's content (except on Wednesdays of course when I have to change it).

2. No, I don't see that as an issue right now (though I just did turn Focus Assist back on).

**Comment by martinet101** [comment]
Then, as I said, there are issues with Qt's font kerning and alignments on newer variable fonts, and this can't be really fixed. I'm sorry though.
