### ISSUE TITLE
Update FAiled, New Install Failed

### ISSUE THREAD

**Issue by TJKB2TQU** [martinet101/ElevenClock#974]
I received an update notice. ElevenClock downloaded it and it generated the error. I downloaded the install file and tried that and received the same error. Here is the Error Report. 

Love the app. Please help!

alamirat@optonline.net

OS: Windows
                   Version: ('10', '10.0.22000', 'SP0', 'Multiprocessor Free')
           OS Architecture: AMD64
          APP Architecture: 64bit
               APP Version: 3.9.0
          APP Version Code: 3.9
                   Program: ElevenClock

-----------------------------------------------------------------------------------------

ElevenClock Log:

Traceback (most recent call last):
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1854, in <module>
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 250, in loadClocks
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1137, in __init__
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 677, in __init__
  File "\\samba-server\SPTPrograms\ElevenClock\elevenclock\__init__.py", line 1546, in close

AttributeError: 'Clock' object has no attribute 'rightFast'<class 'AttributeError'>: 'Clock' object has no attribute 'rightFast'

**Comment by martinet101** [comment]
Please install version 3.9.1

**Comment by martinet101** [comment]
Does it work?

**Comment by TJKB2TQU** [comment]
Yes, it did. I did the download of the new version as the error message suggested but got the same error. Then the software in the link you sent me worked. Thank you for your support!!!
