### ISSUE TITLE
Overflow of the clock to the second panel when adjusting the horizontal position.

### ISSUE THREAD

**Issue by vladimir-kordas** [martinet101/ElevenClock#982]
Dobrý den, rád bych se zeptal, jestli lze nějak opravit to, že jakmile si upravím horizontální pozici trochu více doleva, tak panel přeteče na druhý monitor. 

Vidět to jde tehdy, když mám na druhém monitoru puštěné například video přes celou obrazovku.

Díky.
![Snímek obrazovky 2022-10-12 144320](https://user-images.githubusercontent.com/81954797/195346015-b9689dca-b89d-4a8e-abf5-ce8314293b20.jpg)

**Comment by martinet101** [comment]
Could you please post in english so we all can understand?  Thanks ;)

**Comment by vladimir-kordas** [comment]
> 

Oh sorry :D 

I would like to ask if there is any way to fix the fact that as soon as I adjust the horizontal position a bit more to the right, the panel overflows to the second monitor.

I can see it when I have, for example, a full screen video playing on the second monitor.

Thanks.

**Comment by martinet101** [comment]
No, there's not really any kind of fix. 

However, you could set a font a little bit smaller, achieving a shorter clock in terms of width, so you don't need to move the clock to the right

**Comment by vladimir-kordas** [comment]
> No, there's not really any kind of fix.
> 
> However, you could set a font a little bit smaller, achieving a shorter clock in terms of width, so you don't need to move the clock to the right

Ok, thanks.
