### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by jlbrkntr** [martinet101/ElevenClock#986]
Clicking on ElevenClock doesn't open the calender, even after choosing "show calendar" for the option "Change the action done when the clock is clicked". Windows 11. Latest version of ElevenClock from Microsoft Store.

**Comment by martinet101** [comment]
could it be the same issue as #923?

**Comment by jlbrkntr** [comment]
Appears to be the same issue with the calendar not showing but in my case it doesn't work, like ever. It used to work in older versions a while back. Now the calendar option doesn't do anything only shows the tooltip.

**Comment by martinet101** [comment]
Which is the latest version that worked?

**Comment by jlbrkntr** [comment]
I have no idea but it was before it was available in the Microsoft Store I think (it was downloadable as a setup file). Is it possible that they changed something with the taskbar in one of the Windows updates?

**Comment by martinet101** [comment]
Ok, it was before the change...

**Comment by martinet101** [comment]
Can ypu please post on #923 so we can close this one ad duplicate and discuss the issue there?

**Comment by jlbrkntr** [comment]
I'll follow the other thread for any updates 👍

**Comment by martinet101** [comment]
Could you please try this release?
https://github.com/martinet101/ElevenClock/releases/tag/3.9.3-r2

Make sure to enable the toggle listed in the release's description!

**Comment by jlbrkntr** [comment]
It's been working fine for me after installing Windows on a new PC. Enabling the toggle (for me at least) opens both the start menu and the calendar when clicking on the clock which I don't believe is supposed to happen. There's also an issue with the clock closing shortly after Windows starts up even though Eleven Clock is running in the task manager. Only seems to happen when installing manually from a setup file. Doesn't happen when installing from the Microsoft Store.

**Comment by jlbrkntr** [comment]
In my case the issue with the clock disappearing might be related to StartAllBack which I use to change the taskbar to Windows 10 style in order to get ungrouped taskbar buttons. After uninstalling StartAllBack the Eleven Clock didn't disappear anymore. When installed the clock disappears even with older versions. On the other hand though, this started happening quite recently and I've been using StartAllBack for at least a month. Someone else reported the clock issue ten days ago (#1017) so could be some other underlying reason, maybe one of the Windows updates?

**Comment by martinet101** [comment]
With start all back and ElevenClock 3.9.1 does this still happen?

**Comment by jlbrkntr** [comment]
Yeah it does, noticed something interesting in the log though. After the line "Loaded everything in 0.7441775798797607" it says "Fullscreen window detected! (0, 0, 1920, 1080) Fullscreen rect: [0, 0, 1920, 1080]" and this line repeats itself 529 (yes five hundred twenty nine!) times in a row so something (possibly StartAllBack) is making Eleven Clock think there is a fullscreen app running and hence making it hide itself. If I turn off the option "Hide the clock in fullscreen mode" it doesn't happen.

**Comment by martinet101** [comment]
Hi,

could you please try this release (it is a new version)?

https://github.com/martinet101/ElevenClock/releases/tag/3.9.4-beta2

**Comment by jlbrkntr** [comment]
Same thing. I've been doing some troubleshooting where I've been disabling startup apps (including services) one by one to see if any of them could be causing it. Only thing that has solved it for me is uninstalling StartAllBack so something about StartAllBack is causing Eleven Clock to detect a fullscreen app and hence making it hide itself. I've managed to reproduce this by closing explorer.exe in task manager and then running it again which has the same effect. After uninstalling StartAllBack the log no longer shows any instances of "Fullscreen window detected" when the desktop loads.

**Comment by martinet101** [comment]
Hi,

Could you please test this release and send your log?

https://github.com/martinet101/ElevenClock/releases/tag/3.9.4-beta3

**Comment by jlbrkntr** [comment]
Works flawlessly, even after tweaking the settings to my liking.

Here's the log with default settings after initial installation:

🟢 Using cached lang file
🟡 Using bundled lang file (forced=True)
It took 0.0019958019256591797 to load all language files
---------------------------------------------------------------------------------------------------

   ElevenClock's 3.9.4-beta (v3.939) log: Select all the text and hit Ctrl+C to copy it
   All modules loaded successfully and sys.stdout patched correctly, starting main script
   Translator function set language to "en"

---------------------------------------------------------------------------------------------------

 Log legend:
 🔵: Verbose
 🟢: Information
 🟡: Warning
 🟠: Handled unexpected exception
 🔴: Unhandled unexpected exception
 🟣: Handled expected exception

🔵 Initializing clock 0...
🔵 Using taskbar background color
🟢 Regular sized taskbar
🟢 Clock on the bottom
🟢 Clock on the right
🟢 Using qt's default positioning system
🔵 Clock geometry: PySide6.QtCore.QRect(1720, 1034, 200, 46)
🔵 Font families   : ['Segoe UI Variable Display', 'sans-serif']
🔵 Custom font     : 
🔵 Font size: 9.0
🟢 Using white text (dark mode)
🔵 tDateMode: dd/MM/yyyy
🔵 tTimeMode: HH:mm
🔵 Loaded date time format: %H:%M
%d/%m/%Y
🟣 Expected AttributteError on resizeEvent
🟣 Expected AttributteError on resizeEvent
🔵 Full screen rect:  (0, 0, 1920, 1080)
can't parse ""
🔵 Show/hide loop started with parameters: HideonFS:True, NotHideOnTB:False, HideOnRDP:False, ClockOn1Mon:True, NefWSMethod:True, DisableNotifications:True, legacyFullScreenMethod:False
🟡 Desktop button enabled
🟢 Loaded clocks in 0.27686476707458496
🔵 Restart loop: 1
🟣 Expected AttributeError on checkAndUpdateBackground
{'System language': 'default', 'Arabic - عربي\u200e (62%)': 'ar', 'Bosnian - Bosanski (6%)': 'bs', 'Bulgarian - български (18%)': 'bg', 'Catalan - Català': 'ca', 'Czech - Čeština': 'cs', 'Danish - Dansk (99%)': 'da', 'German - Deutsch (99%)': 'de', 'Greek - Ελληνικά (18%)': 'el', 'English - English': 'en', 'Spanish - Español (99%)': 'es', 'Estonian - eesti (92%)': 'et', 'Persian - فارسی\u200e (5%)': 'fa', 'Finnish - Suomi (63%)': 'fi', 'French - Français': 'fr', 'Hebrew - עִבְרִית\u200e (92%)': 'he', 'Croatian - Hrvatski (11%)': 'hr', 'Hungarian - Magyar': 'hu', 'Indonesian - Bahasa Indonesia (92%)': 'id', 'Italian - Italiano (65%)': 'it', 'Japanese - 日本語 (93%)': 'ja', 'Korean - 한국어': 'ko', 'Lithuanian - Lietuvių (22%)': 'lt', 'Latvian - Latviski (61%)': 'lv', 'Norwegian (bokmål) (92%)': 'nb', 'Dutch - Nederlands (91%)': 'nl', 'Norwegian (nynorsk) (67%)': 'nn', 'Polish - Polski (98%)': 'pl', 'Portuguese (Brazil)': 'pt_BR', 'Portuguese (Portugal)': 'pt_PT', 'Romanian - Română (92%)': 'ro', 'Russian - Русский (92%)': 'ru', 'Sinhala - සිංහල': 'si', 'Slovak - Slovenčina (30%)': 'sk', 'Serbian - Srpski (22%)': 'sr', 'Swedish - Svenska (78%)': 'sv', 'Thai - ภาษาไทย (82%)': 'th', 'Turkish - Türkçe (99%)': 'tr', 'Ukranian - Yкраї́нська': 'ua', 'Vietnamese - Tiếng Việt (38%)': 'vi', 'Simplified Chinese (China)': 'zh_CN', 'Traditional Chinese (Taiwan)': 'zh_TW'}
🔵 Language file up-to-date
🟣 Expected AttributeError on checkAndUpdateBackground
🔵 System tray icon enabled
🔵 Starting update check
b'\x00\x00\x00\x00'
🔵 Low cpu mode is set to False. DisableNotifications is set to False
🟢 Loaded everything in 1.1174113750457764
b'\x00\x00\x00\x00'
🔵 Version URL: https://versions.somepythonthings.tk/versions/elevenclock.ver
🟢 Updates not found
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
🟡 Verifying unverified hwnd 66564
🟡 Fullscreen window detected! (0, 0, 1920, 1080) Fullscreen rect: [0, 0, 1920, 1080]
🟡 Verifying unverified hwnd 328446
🟡 Fullscreen window detected! (0, 0, 1920, 1080) Fullscreen rect: [0, 0, 1920, 1080]
🟡 Blacklisted hwnd 66564 under title Windows Input Experience (Process name is c:\windows\systemapps\microsoftwindows.client.cbs_cw5n1h2txyewy\textinputhost.exe)
🟡 Blacklisted hwnd 328446 under title Windows Input Experience (Process name is c:\windows\systemapps\microsoftwindows.client.cbs_cw5n1h2txyewy\textinputhost.exe)
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
🔵 Announcement URL: https://www.somepythonthings.tk/resources/elevenclock.announcement
🔵 Image URL: https://www.somepythonthings.tk/resources/translate.png
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'
b'\x00\x00\x00\x00'

**Comment by martinet101** [comment]
Perfect!
