### ISSUE TITLE
[FEATURE REQUEST] Adding times with timezone shifts

### ISSUE THREAD

**Issue by TheAlienDrew** [martinet101/ElevenClock#989]
Want to be able to use more than one time zone in the custom date and time format settings.
E.g. wanting to be able to set the clock to look like so:

**8:00 AM PST
11:00 AM Local**

**Comment by martinet101** [comment]
That will be hard, since all the localisation stuff is done through Python libraries, which don't support that.

**Comment by TheAlienDrew** [comment]
I mean, as long as you can get it to UTC, you should be golden on being able to convert it to any TZ time.

**Comment by martinet101** [comment]
Yeah, but this would mean while time function remake, unless the python function datetime.strtftime can support different time zones via custom format

**Comment by andrew-flatters-bliss** [comment]
Semi-related but the hover over timezones when you add additional clocks seems to be wrong adjusted with day light savings in UK is saying the same time as UTC at the moment where we are +1hrs compared to UTC at moment.

**Comment by TheAlienDrew** [comment]
> Semi-related but the hover over timezones when you add additional clocks seems to be wrong adjusted with day light savings in UK is saying the same time as UTC at the moment where we are +1hrs compared to UTC at moment.

You're taking about a bug, which someone else already made an issue about. This is a **feature request**.

**Comment by martinet101** [comment]
Could you please try this release?
https://github.com/martinet101/ElevenClock/releases/tag/3.9.3-r2

**Comment by martinet101** [comment]
The issue with timezones in the tooltip is being worked on.

This feature request won't be worked on because of the same reason as #1018

**Comment by TheAlienDrew** [comment]
I think you're thinking a little too hard on it, see https://docs.python.org/3.6/library/datetime.html#datetime.datetime.astimezone

**Comment by martinet101** [comment]
> I think you're thinking a little too hard on it, see https://docs.python.org/3.6/library/datetime.html#datetime.datetime.astimezone

It literally does not work. I know that the documentation seems easy and without further complications, but for whatever the reason it does not work.

**Comment by TheAlienDrew** [comment]
> > I think you're thinking a little too hard on it, see https://docs.python.org/3.6/library/datetime.html#datetime.datetime.astimezone
> 
> It literally does not work. I know that the documentation seems easy and without further complications, but for whatever the reason it does not work.

Link me to the file in the code with the issue, and I'll try some testing of my own at home today.

**Comment by martinet101** [comment]
I have tested the following:
1. Loading the timezone by using the %z and %Z parameters, which returns empty strings.
2. Using the tzname() function, which ends up returning empty strings
3. Loading the current timezone from Windows Registry, parsing it and loading into a tzinfo object, which works, but, again, no matter the way I try to extract the name it just returns empty strings or None objects.
4. IO also tested other libraries like dateutil and tzinfo, appart from datetime, and none of them worked.

I don't have the code, i didn't save it, but trust me, it was a mess.

**Comment by TheAlienDrew** [comment]
@martinet101 Related to my working timezone code here: https://github.com/martinet101/ElevenClock/issues/1018#issuecomment-1330063502

Timezones can be displayed as the abbreviated versions with the following edits to my code, but you would need to install and import `pytz`, or otherwise, worry about the pain staking process of setting up abbreviations on your own:

If using pytz, you'll need to clarify further for locations that either had their abbreviations removed because of duplicates or didn't have one at all because not as significant to get their own code
- For example `Amazon, Brazil` and `Armenia, Asia` both had used **AMT** in the past, but it was changed to use the short form offset (`UTC-04` and `UTC+04` respectively) per IANA standards

```python3
import datetime
import dateutil.tz as tz 
import pytz # $ pip install pytz
from tzlocal import get_localzone # $ pip install tzlocal

# pytz is the only one that will display timezone abbreviations or short versions of the timezone offset

# see https://stackoverflow.com/a/39079819/7312536
LOCAL_TIMEZONE = datetime.datetime.now(datetime.timezone.utc).astimezone().tzname()

dateTimeFormat = "%I:%M %p %Z (%z)"

# timezones
localDateutilTZ = tz.gettz(LOCAL_TIMEZONE)
localPytz = get_localzone() # tzlocal uses pytz timezone objects
egyptDateutilTZ = tz.gettz('Egypt Standard Time') # or Africa/Cairo, or EET
egyptPytz = pytz.timezone('EET') # only can use abbr. or CONTINENT/COUNTRY
amazonasDateutilTZ = tz.gettz('UTC-04') # ditches AMT abbr.
amazonasPytz = pytz.timezone('America/Manaus')
armeniaDateutilTZ = tz.gettz('UTC+04') # also ditches AMT abbr.
armeniaPytz = pytz.timezone('Etc/GMT-4') # doesn't have its own CONTINENT/COUNTRY

# allows showing of TZ info via `%z` and `%Z`
nowUTC = datetime.datetime.now(datetime.timezone.utc)
nowLocal = nowUTC.astimezone()
nowLocalDateutilTZ = nowUTC.astimezone(localDateutilTZ)
nowLocalPytz = nowUTC.astimezone(localPytz)
nowEgyptDateutilTZ = nowUTC.astimezone(egyptDateutilTZ)
nowEgyptPytz = nowUTC.astimezone(egyptPytz)
nowAmazonasDateutilTZ = nowUTC.astimezone(amazonasDateutilTZ)
nowAmazonasPytz = nowUTC.astimezone(amazonasPytz)
nowArmeniaDateutilTZ = nowUTC.astimezone(armeniaDateutilTZ)
nowArmeniaPytz = nowUTC.astimezone(armeniaPytz)

# now use strftime to format times
timeUTC = nowUTC.strftime(dateTimeFormat)
timeLocal = nowLocal.strftime(dateTimeFormat)
timeLocalDateutilTZ = nowLocalDateutilTZ.strftime(dateTimeFormat)
timeLocalPytz = nowLocalPytz.strftime(dateTimeFormat)
timeEgyptDateutilTZ = nowEgyptDateutilTZ.strftime(dateTimeFormat)
timeEgyptPytz = nowEgyptPytz.strftime(dateTimeFormat)
timeAmazonasDateutilTZ = nowAmazonasDateutilTZ.strftime(dateTimeFormat)
timeAmazonasPytz = nowAmazonasPytz.strftime(dateTimeFormat)
timeArmeniaDateutilTZ = nowArmeniaDateutilTZ.strftime(dateTimeFormat)
timeArmeniaPytz = nowArmeniaPytz.strftime(dateTimeFormat)

print("Results formated as =>",dateTimeFormat,"\n")
print("In UTC -------------------------->",timeUTC)
print("Local timezone ------------------>",timeLocal)
print("Local timezone (dateutil.tz) ---->",timeLocalDateutilTZ)
print("Local timezone (pytz) ----------->",timeLocalPytz)
print("Egypt, Africa (dateutil.tz) ----->",timeEgyptDateutilTZ)
print("Egypt, Africa (pytz) ------------>",timeEgyptPytz)
print("Amazonias, Brazil (dateutil.tz) ->",timeAmazonasDateutilTZ)
print("Amazonias, Brazil (pytz) -------->",timeAmazonasPytz)
print("Armenia, Asia (dateutil.tz) ----->",timeArmeniaDateutilTZ)
print("Armenia, Asia (pytz) ------------>",timeArmeniaPytz)
```

**Comment by TheAlienDrew** [comment]
Here's an example of the output I get after running my test script:

```
Results formated as => %I:%M %p %Z (%z)

In UTC --------------------------> 06:41 AM UTC (+0000)
Local timezone ------------------> 10:41 PM Pacific Standard Time (-0800)
Local timezone (dateutil.tz) ----> 10:41 PM Pacific Standard Time (-0800)
Local timezone (pytz) -----------> 10:41 PM PST (-0800)
Egypt, Africa (dateutil.tz) -----> 08:41 AM Egypt Standard Time (+0200)
Egypt, Africa (pytz) ------------> 08:41 AM EET (+0200)
Amazonias, Brazil (dateutil.tz) -> 02:41 AM UTC (-0400)
Amazonias, Brazil (pytz) --------> 02:41 AM -04 (-0400)
Armenia, Asia (dateutil.tz) -----> 10:41 AM UTC (+0400)
Armenia, Asia (pytz) ------------> 10:41 AM +04 (+0400)
```

**Comment by TheAlienDrew** [comment]
Most up-to-date information I've found, and implemented a working test for is at https://github.com/martinet101/ElevenClock/issues/1039#issuecomment-1330448194
