### ISSUE TITLE
[FEATURE REQUEST] Change text color dynamically with background.

### ISSUE THREAD

**Issue by BuhoSolitario** [martinet101/ElevenClock#992]
**Is your feature request related to a problem? Please describe.**
When dynamic background or transparent clock is active text color doesn't change.
If background color is similar to text color sometimes the clock cannot be seen.

**Describe the solution you'd like**
1) Get the dynamic color HSB code and invert its brightness if text brightness is near background brightness. 
2) The quantity of similarity could be a new numeric setting/slider.
3) Also, just in case, add an option to opt-in/opt-out this feature, because there would be people happy if clock "disappears", typically on very dark/light background colors.

**Comment by martinet101** [comment]
Done!
https://user-images.githubusercontent.com/53119851/202849106-aa23e9f7-8ea2-4b74-a913-fa266cff0212.mp4
