### ISSUE TITLE
An option should be added for ElevenClock to be INSTEAD of the Windows 11 clock!

### ISSUE THREAD

**Issue by Draskic** [martinet101/ElevenClock#997]
Hi
I have one suggestion after using ElevenClock for a long time:
An option should be added for ElevenClock to be INSTEAD of the Windows 11 clock with the same shape given in ElevenClock's setup. This is currently not possible or is very clumsy, and it also interferes with the "Show Desktop" function.
Greeting!

**Comment by martinet101** [comment]
Hi @Draskic,

Regarding the desktop button, you can enable one from the settings window.

About replaing the window clock, this can't be done, annd this is why ElevenClock shows on top of the windows clock. This is actually the main _feature_ of ElevenClock, that allows windows 11 compatibility

**Comment by Draskic** [comment]
Regarding the desktop button, you can enable one from the settings window.
I tried but I didn't see that button!
Regards!
Drasko

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/196996095-df7b7009-a259-4c26-a1ce-1f9499aecd7e.png)

**Comment by Draskic** [comment]
Yes I know for that but ... maybe because I use the black background?

**Comment by martinet101** [comment]
If you have sey any x or y offset(s), the button might be misplaced. If not, it should show like this:
![image](https://user-images.githubusercontent.com/53119851/197003661-665a5821-a03d-45da-9fc1-117c16da458c.png)

**Comment by Draskic** [comment]
O,K.
I will check!
And how do I replace the Windows 11 clock?
When I move it with shift x, it slowly disappears under the Taskbar!

**Comment by martinet101** [comment]
What do you mean? Could you please send a video?

**Comment by Draskic** [comment]
[image: Elevenclock blocked.jpg]

**Comment by martinet101** [comment]
Can't see the pictures

**Comment by martinet101** [comment]
Can't see the pictures

**Comment by Draskic** [comment]
Attached now

**Comment by martinet101** [comment]
Github doesn't allow sending images through email, you'll need to upload them directly from thge github thread or throuhg a google dtive/imgur url.

**Comment by martinet101** [comment]
It still doesn't work. Please attach a imgur url

**Comment by martinet101** [comment]
![image](https://user-images.githubusercontent.com/53119851/197021671-cdc5a670-edf5-4ab7-a469-a4ea6445f2f6.png)

**Comment by martinet101** [comment]
Do you have your clock pinned to the desktop? If so disable it.
![image](https://user-images.githubusercontent.com/53119851/197025814-49d3dcf8-55cc-463f-ae73-b9067722542b.png)

**Comment by Draskic** [comment]
Yes!
I will!

**Comment by Draskic** [comment]
I made it!
But still ther is no buttons for destop!
Fortunately I narroved the 11clock and see the original Windows 11 place for "Show Desktop"
Thanks!
